instructure/canvas-ios

CanvasCore/CanvasCore/Quizzes/Model/QuizSubmission.swift

refs: MBL-14217
release note: Fixed bug on quizzes so extra time will be shown.

Fix parsing of quiz submission response so extra time on quiz shows up

---

CanvasCore/CanvasCore/PDF/CanvadocView.swift
CanvasCore/CanvasCore/PDF/PSPDFView.swift
rn/Teacher/src/modules/assignment-details/map-state-to-props.js
rn/Teacher/src/modules/assignments/assignment-entities-reducer.js
rn/Teacher/src/modules/courses/courses-reducer.js
rn/Teacher/src/modules/discussions/reducer.js
rn/Teacher/src/modules/groups/GroupList.js
rn/Teacher/src/modules/inbox/reducer.js
rn/Teacher/src/modules/quizzes/reducer.js
rn/Teacher/src/modules/submissions/list/submission-entities-reducer.js
rn/Teacher/src/redux/actions/async-tracker.js

refs: MBL-14179
release note: Fixed a crash in speedgrader

Fixes top crashes in Teacher

---

Core/Core/Pages/PageList/PageListViewController.storyboard
Core/Core/Pages/PageList/PageListViewController.swift

Fix the page selection

---

Core/Core/Planner/APIPlannable.swift

refs: MBL-14217
release note: Fixed bug on completed todos in new calendar

Fix decoding of plannable override, sometimes assignment id is null

---

Core/Core/Pages/GetPage.swift
Core/CoreTests/Pages/GetPageTests.swift

refs: MBL-14254
release note: Fixed an issue with a cached course home page

Reset outdated isFrontPage before saving new front page

---

Parent/Parent/Conversations/ConversationDetailCell.swift
Parent/Parent/Conversations/ConversationDetailViewController.storyboard

Detect links in inbox messages, copy and select text

---

package.json
scripts/build_automation/automateVersioning.sh
scripts/generate-release-notes.js
yarn.lock

Fix release note generation

---

Core/Core/AppEnvironment/ExperimentalFeature.swift
Student/Student/CanvasAppDelegate.swift
Student/Student/RootViewController.swift
rn/Teacher/src/canvas-api/apis/users.js
rn/Teacher/src/common/ExperimentalFeature.js
rn/Teacher/src/modules/courses/CourseNavigation.js
rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
rn/Teacher/src/modules/courses/__tests__/__snapshots__/CourseNavigation.test.js.snap

refs: MBL-14182
release note: Added Student View
Test plan:
* Install App Store version of Student app
* Install this build of Teacher app
* In teacher app, log in as narmstrong.instructure.com > t
* Use an existing test student:
- Dashboard > CS 1400 > Student View > Should be logged in as Test Student
* In teacher app, log in as narmstrong.instructure.com > t2
* Create a new test student:
- Dashboard > Modules course > Student View > Should be logged in as Test Student
* The Inbox tab should be hidden from test students

Use API to get-or-create test student

---

scripts/build_automation/bitrise_workflows/parent.yml
scripts/build_automation/bitrise_workflows/student.yml
scripts/build_automation/bitrise_workflows/teacher.yml
scripts/build_automation/bitrise_workflows/tests.yml

use carthage head

---

Core/Core/Conferences/APIConference.swift
Core/Core/Conferences/ConferenceDetailsViewController.storyboard
Core/Core/Conferences/ConferenceListViewController.swift
Core/CoreUITests/Courses/CourseNavigation.swift
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Conferences/ConferenceDetails.swift
Student/StudentE2ETests/Conferences/ConferencesE2ETests.swift
Student/StudentE2ETests/Conferences/ConferencesList.swift
Student/StudentUITests/Conferences/ConferencesUITests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/Element/ElementWrapper.swift
TestsFoundation/TestsFoundation/Fixtures/API/APITabFixture.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCanvasState.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCourse.swift
TestsFoundation/TestsFoundation/UITests/MiniCanvasUITestCase.swift

refs: MBL-14189
affects: none
[run-nightly]

Add UI/E2E tests for conferences

---

Core/CoreUITests/Discussions/DiscussionEditTests.swift
Core/CoreUITests/Discussions/DiscussionReplyTests.swift
Core/CoreUITests/Inbox/InboxTests.swift

fix nightly tests that use AttachmentView

---

Core/CoreTests/Login/LoginWebViewControllerTests.swift

Fix testPreloaded

---

Canvas.xcworkspace/contents.xcworkspacedata
package.json
scripts/generate-release-notes.js
scripts/update-jira-issues.js
yarn.lock

Add scripts to tag fixVersion & label released tickets

---

Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Planner/APIPlannable.swift
Core/Core/Planner/Plannable.swift

refs: MBL-14249
affects: parent, student
release note: Fixed a bug that could cause an error in the calendar
Test plan: Masquerade as [this user](https://mdca.instructure.com/accounts/1/users/421)
and view the calendar. It should load without error.

Ignore plannable context_image to fix error

---

scripts/build_automation/bitrise_workflows/parent.yml
scripts/build_automation/bitrise_workflows/student.yml
scripts/build_automation/bitrise_workflows/teacher.yml

Generate release notes after tagging

---

Podfile
Podfile.lock
rn/Teacher/package.json
rn/Teacher/test/scripts/jestSetup.js
rn/Teacher/yarn.lock

no for realz this time.
refs: none
affects: none

Remove last use of UIWebView

---

Core/Core/Use Cases/UploadMedia.swift
Core/CoreUITests/Profile/UserFilesTests.swift
Student/Student.xcodeproj/project.pbxproj
Student/StudentUITests/Assignments/IPadAssignmentsTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/AudioVideo/AudioRecorder.swift
TestsFoundation/TestsFoundation/Extensions/XCUIElementExtensions.swift
TestsFoundation/TestsFoundation/Extensions/XCUIElementQueryExtensions.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGrader.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderCommentUITests.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderQuizUITests.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderUITests.swift
rn/Teacher/src/canvas-api/apis/media-comments.js
rn/Teacher/src/common/components/AudioRecorder.js
rn/Teacher/src/common/components/__tests__/AudioRecorder.test.js
rn/Teacher/src/common/components/__tests__/__snapshots__/AudioRecorder.test.js.snap
rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/GradeTab.test.js.snap
rn/Teacher/src/modules/speedgrader/comments/ChatBubble.js
rn/Teacher/src/modules/speedgrader/comments/CommentInput.js
rn/Teacher/src/modules/speedgrader/comments/CommentRow.js
rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentInput.test.js
rn/Teacher/src/modules/speedgrader/comments/__tests__/__snapshots__/CommentInput.test.js.snap

refs: mbl-14014
affects: none
[run-nightly]

Add UI tests for speedgrader comments

---

Core/Core/ActAsUser/ActAsUserWindow.swift
rn/Teacher/src/modules/courses/CourseNavigation.js

refs: MBL-14344, MBL-14315
Test plan: Launch Student View and see that the text changes are correct.

Update Student View text

---

rn/Teacher/i18n/locales/index.js

refs: MBL-14265
release note: Added support for Catalan language

Add Catalan language to RN

---

Core/Core/Conferences/Conference.swift
Core/CoreTests/Conferences/ConferenceDetailsViewControllerTests.swift

refs: MBL-14337
release note: Fixed launching some conferences

Fix launching conferences with statistics

---

Core/Core/Profile/Settings/APIPairingCode.swift
Core/CoreTests/Profile/Settings/APIPairingCodeTests.swift

Add account terms of service api request

---

CanvasCore/CanvasCore/Helm/Extensions/HelmSplitViewControllerExtensions.swift
CanvasCore/CanvasCore/Helm/Helm.swift
CanvasCore/CanvasCore/Inbox/inboxTab.swift
Core/Core/Conversations/ConversationListViewController.swift
Core/Core/Views/HorizontalMenuViewController.swift

Fix route to RN conversation details in Teacher

---

Core/Core/AppEnvironment/ExperimentalFeature.swift
Core/Core/Profile/Settings/PairWithObserverViewController.storyboard
Core/Core/Profile/Settings/PairWithObserverViewController.swift
Core/Core/Router/Route.swift
Parent/Parent/Routes.swift

refs: MBL-14197
Testing:
1. enable flag `student_qr_code_pairing` 
2. Settings > Pair with observer
3. should show qr code 
4. disable same flag
5. make sure old pairing code flow shows up

Add Student qr code for creating parent account

---

Core/Core/Conversations/ComposeReplyViewController.swift
Core/Core/Conversations/ComposeViewController.swift
Core/Core/Conversations/EditComposeRecipientsViewController.swift
Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Discussions/DiscussionEntry.swift
Core/Core/Discussions/DiscussionTopic.swift
Core/Core/Discussions/GetDiscussions.swift
Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Planner/CalendarDaysViewController.swift
Core/Core/Store/Store.swift
Core/Core/en.lproj/Localizable.stringsdict
Core/CoreTests/Discussions/DiscussionEntryTests.swift
Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift

Added ratings to html discussion details

---

CanvasCore/CanvasCore/Quizzes/Taking a Quiz/SubmissionViewController.swift

refs: MBL-14370
Test plan: See ticket

Fix a11y on multiple answer quiz questions

---

Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift
Core/Core/Modules/ModuleList/ModuleItemCell.swift
Core/CoreTests/Modules/ModuleItems/ModuleItemDetailsViewControllerTests.swift
Core/CoreTests/Modules/ModuleListViewControllerTests.swift

refs: MBL-14385
release note: Fixed viewing quizzes from Modules

Fix locked quizzes in teacher app

---

Core/Core/Login/LoginWebViewController.swift
Core/CoreTests/Login/LoginWebViewControllerTests.swift

refs: MBL-14356
release note: Fixed bug with user locale on login

Locale was not getting set on login.

---

rn/Teacher/src/modules/inbox/CourseSelect.js
rn/Teacher/src/modules/inbox/__tests__/CourseSelect.test.js

refs: MBL-14333
release note: Fixed a bug that caused concluded courses to show when composing a message in the Inbox

Only show available courses in Inbox Compose

---

rn/Teacher/src/common/components/AttachmentView.js
rn/Teacher/src/common/components/__tests__/AttachmentView.test.js

refs: MBL-14336
release note: Fixed displaying heic images in some areas of the app

Support HEIC images in RN AttachmentView

---

Core/Core/Discussions/DiscussionDetailsViewController.swift

fix discussion icon sizes

---

TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift

[run-nightly]
refs: none
affects: none

Fix Nightly again

---

rn/Teacher/src/canvas-api/apis/courses.js

refs: MBL-14397
release note: Fixed viewing unpublished courses in Student View

Allow concluded courses in Student View

---

Core/Core/RichContentEditor/RichContentToolbarView.xib

refs: MBL-14414
release note: Fixed changing the text color in text assignment submission

Fix text color in Text Submissions

---

Core/Core/Pages/PageDetails/PageDetailsViewController.storyboard
Core/Core/Pages/PageDetails/PageDetailsViewController.swift

refs: MBL-14362
release note: Fixed images in beta and test environments
Test plan:
- Masquerade as the teacher in the ticket, make sure you are on beta
- View the page in the ticket
- The image should load

Fix images in beta rich content

---

rn/Teacher/src/modules/files/ViewFile.js
rn/Teacher/src/modules/files/__tests__/ViewFile.test.js

refs: MBL-14336
release note: Fixed viewing heic course files
Test plan:
- narmstrong > t > CS 1400 > Files > IMG_0011.HEIC
- Image should load

Fix viewing heic course files

---

Parent/Parent/Create Account/CreateAccountViewController.storyboard
Parent/Parent/Create Account/CreateAccountViewController.swift

Refine attributed string texts

---

Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Discussions/DiscussionReplyViewController.swift
Core/Core/Discussions/DiscussionTopic.swift
Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift

Load child group topic if needed

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Use Cases/GetGroup.swift
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
Core/CoreTests/Use Cases/GetGroupTests.swift

Show group topic children to teachers

---

Student/Student/Routes.swift
Student/StudentUITests/Submissions/TextSubmission/TextSubmissionTests.swift
rn/Teacher/ios/Teacher/AppDelegate+Routes.swift

[run-nightly]
refs: MBL-14421
affects: teacher, student

Fix missing attachment button on discussion reply

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Pages/APIPage.swift
Core/Core/Pages/PageDetails/PageDetailsViewController.swift
Core/Core/Pages/PageList/PageListViewController.swift
Core/CoreE2ETests/Course Files/CourseFileE2ETests.swift
Core/CoreE2ETests/Dashboard/DashboardE2ETests.swift
Core/CoreE2ETests/Deep Links/DeepLinkE2ETests.swift
Core/CoreE2ETests/Pages/PageE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Pages/PageDetails.swift
TestsFoundation/TestsFoundation/CoreUIElements/Pages/PageEdit.swift
TestsFoundation/TestsFoundation/CoreUIElements/Pages/PageList.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCourse.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherUITests/Pages/PagesUITests.swift
rn/Teacher/src/redux/middleware/error-handler.js

refs: MBL-13991
affects: none
[run-nightly]

Add teacher UI test cases

---

Parent/Parent/Create Account/CreateAccountViewController.storyboard
Parent/Parent/Create Account/CreateAccountViewController.swift

Refinements to create account screen

---

Core/Core/Discussions/DiscussionDetailsViewController.storyboard
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift

Automatically mark read visible entries 1 second after scrolling ends

---

Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionEntry.swift
Core/Core/Discussions/DiscussionReplyViewController.swift
Core/Core/Discussions/GetDiscussions.swift
Core/CoreTests/Discussions/APIDiscussionTests.swift
Core/CoreTests/Discussions/DiscussionReplyViewControllerTests.swift
Core/CoreTests/Discussions/GetDiscussionsTests.swift

refs: MBL-14431
affects: Student/Teacher

Fix edit discussion reply

---

rn/Teacher/src/common/login-verify.js

refs: MBL-14429
release note: Fixed a bug with launching Student View
Test plan:
- Install both Student and Teacher apps
- Launch the Student app and log in as a student, background the app
- Open teacher app and launch Student View from course details
- Student View should work as expected
- You should still be logged in as the teacher in the Teacher app

Fixed a bug in Student View

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/API/APIRequestable.swift
Core/Core/Files/APIFile.swift
Core/Core/UITestHelpers/MockDistantURLSession.swift
Core/CoreE2ETests/Login/LoginE2ETests.swift
Core/CoreTests/Files/APIFileTests.swift
Core/CoreUITests/Profile/UserFilesTests.swift
Core/CoreUITests/Profile/ViewFile.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Filles/FileEditItem.swift
TestsFoundation/TestsFoundation/Fixtures/API/APIFileFixture.swift
TestsFoundation/TestsFoundation/MiniCanvas/Extensions/HttpResponseExtensions.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCanvasState.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCourse.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniFile.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniFolder.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherUITests/Files/FilesUITests.swift
rn/Teacher/src/common/components/rows/RowWithTextInput.js
rn/Teacher/src/common/components/rows/__tests__/__snapshots__/RowWithTextInput.test.js.snap
rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDetailsEdit.test.js.snap
rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap

Course file UI tests for Teacher

---

Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionDetailsViewController.storyboard
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Discussions/DiscussionTopic.swift
Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift

Add sections list to discussion details

---

rn/Teacher/src/modules/announcements/list/AnnouncementsList.js
rn/Teacher/src/modules/announcements/list/__tests__/AnnouncementsList.test.js

refs: MBL-14445
release note: Fixed announcement details incorrectly displaying "Discussion Details"

Fix announcement details header

---

rn/Teacher/src/modules/inbox/components/ConversationMessageRow.js
rn/Teacher/src/modules/inbox/components/__tests__/ConversationMessageRow.test.js

refs: MBL-14449
release note: Fixed an issue with course context used to view conversation participant's details

Try to match the conversation context when viewing user details

---

Core/Core/Discussions/DiscussionDetailsViewController.swift

Fix done button missing on details

---

Core/Core/Discussions/DiscussionReplyViewController.swift
Core/CoreTests/Discussions/DiscussionReplyViewControllerTests.swift

Allow previewing attachments added to discussion replies

---

TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift

add mock to fix all UI tests

---

Core/Core/Quizzes/APIQuiz.swift
Core/CoreTests/Dashboard/AccountNotifications/APIAccountNotificationTests.swift
Core/CoreTests/Quizzes/APIQuizTests.swift
Student/StudentUITests/Quizzes/QuizzesTests.swift
scripts/coverage/config.json

Some API requests defined were never used.
refs: none
affects: none

Fix coverage for APIQuiz & account notification

---

Core/Core/Views/BottomSheetPickerViewController.swift

Fix editing discussion topic

---

Core/Core/ActAsUser/ActAsUserWindow.swift

Make sure the end act button is very last element

---

Parent/Parent/Routes.swift
Parent/ParentUnitTests/RoutesTests.swift

refs: MBL-13897
release note: Fixed display of course files

Route more file paths to the file controller

---

Student/StudentUITests/Course/Syllabus/SyllabusTests.swift

Fix syllabus tests

---

Core/Core/Pages/PageDetails/PageDetailsViewController.swift

refs: MBL-14323
release note: Support window.ENV.COURSE.id on course pages

Add course id to course page web view

---

TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
rn/Teacher/ios/TeacherUITests/Files/FilesUITests.swift
rn/Teacher/src/modules/files/EditItem.js

Fix Files UI Tests

---

Core/Core/API/API.swift
Core/Core/AppEnvironment/ExperimentalFeature.swift
Core/Core/Login/LoginManualOAuthViewController.storyboard
Core/Core/Login/LoginSession.swift
Core/CoreTests/API/APITests.swift
rn/Teacher/src/common/ExperimentalFeature.js

extra: set expiresAt when refreshing in case we decide to check that
refs: MBL-11480
release note: Improved support for short-lived access tokens

Remove refresh token flag

---

Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Views/BottomSheetPickerViewController.swift
Student/StudentUITests/Submissions/TextSubmission/TextSubmissionTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Discussions/DiscussionDetails.swift
TestsFoundation/TestsFoundation/Element/Element.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasServer.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCanvasState.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCourse.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniDiscussion.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherUITests/Discussions/DiscussionsUITests.swift
rn/Teacher/src/modules/discussions/edit/DiscussionEdit.js

Teacher discussion UI tests

---

Core/Core/Assignments/APIAssignment.swift
Core/Core/Assignments/Assignment.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Assignments/AssignmentTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsSectionContainerView.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift
Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift

refs: MBL-14304
release note: Added the number of attempts available for an assignment when limited.

Add attempts to assignment details

---

Core/Core/Extensions/UIViewControllerExtensions.swift
Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.swift
Core/CoreTests/Modules/ModuleItems/ModuleItemSequenceViewControllerTests.swift

refs: MBL-14513
release note: Fixed full screen option on iPads

Fix displayModeButton on module item details

---

Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Pages/PageDetails/PageDetailsViewController.swift

extra: Set the proper baseURL for pages.
refs: MBL-14508
release note: Fixed an issue with discussion options

Disable topic options when there aren't any

---

Core/Core/Modules/APIModule.swift
Core/Core/Modules/CompletionRequirement.swift
Student/StudentUITests/Modules/ModulesTests.swift

Fix testUnlockModuleItemWithPrerequisiteModule

---

Core/Core/Files/FilePicker/FilePickerViewController.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
TestsFoundation/TestsFoundation/Router/TestRouter.swift

uses router functions to make the tests more reliable
refs: MBL-14516
affects: none

Reenable SubmissionButtonPresenterTests

---

rn/Teacher/src/modules/submissions/list/SubmissionList.js

refs: none
release note: Fixed an issue with sorting grouped submissions

Fix bad comparison in SubmissionList

---

Core/Core/Discussions/DiscussionDetailsViewController.swift
rn/Teacher/src/modules/discussions/edit/DiscussionEdit.js

refs: MBL-14509
release note: Fixed discussion details not showing recent edits to the topic

Refresh discussion details when edited

---

Core/Core/DocViewer/Comments/CommentListViewController.storyboard
Core/Core/DocViewer/Comments/CommentListViewController.swift
Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.storyboard
Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift

refs: MBL-14512
release note: Fixed poor coloring around the submission comment field in some cases

Fix styling of comment reply field

---

CanvasCore/CanvasCore/React Native Modules/NativeNotificationCenter.m
rn/Teacher/src/modules/files/EditItem.js
rn/Teacher/src/modules/files/FilesList.js

refs: MBL-14496
release note: Fixed files list to auto update after a file is edited or deleted

Update files list when a file is edited or deleted

---

Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/AppDelegate.swift

Fix bloat analytics tracking

---

TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCanvasState.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherUITests/Todo/TodoUITests.swift

refs: MBL-13996
affects: none
[run-nightly]

Add UI test for teacher todo list

---

Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift

refs: MBL-14525
release note: Fixed loading discussions for users not in a group

Fix group discussions for students not in a group

---

Core/Core/Assignments/Assignment.swift
Core/CoreTests/Assignments/AssignmentTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift

Fixed unsubmitted submission attempt count

---

CanvasCore/CanvasCore/React Native Modules/NativeNotificationCenter.m
Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Discussions/GetDiscussions.swift
Core/Core/Router/Router.swift
Core/CoreTests/Discussions/GetDiscussionsTests.swift
rn/Teacher/src/modules/discussions/list/DiscussionsList.js

Delete response wasn't the correct struct,
router.dismiss didn't work for non-modals,
Discussion list didn't refresh
refs: MBL-14552
release note: Fixed an issue with deleting discussion topics

Fix discussion delete

---

rn/Teacher/ios/TeacherUITests/Todo/TodoUITests.swift
rn/Teacher/src/modules/to-do/list/ToDoListItem.js
rn/Teacher/src/modules/to-do/list/__tests__/__snapshots__/ToDoListItem.test.js.snap

Add commas to todo cells

---

Core/Core/Views/TitleSubtitleView.xib

refs: MBL-14534
release note: Fixed an issue with adding discussion attachments in courses with long names

Make titles more compressible

---

Core/Core/DocViewer/DocViewerViewController.swift
Core/CoreTests/DocViewer/DocViewerViewControllerTests.swift

refs: MBL-14520
release note: Fixed a bug with post-submission annotations

Disable annotations in long-press menu in Student

---

rn/Teacher/ios/TeacherUITests/Discussions/DiscussionsUITests.swift

It's failed nightly a few too many times now. Re-enable ticket: MBL-14583

Disable flaky testEditTopic

---

CanvasCore/CanvasCore/WhizzyWig/CanvasWebView.swift
Core/Core/Views/CoreWebView.swift

Improve escaping of some URL fragments

---

CanvasCore/CanvasCore.xcodeproj/project.pbxproj
Parent/Parent.xcodeproj/project.pbxproj
Student/Student.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
scripts/build_automation/bitrise_workflows/parent.yml
scripts/build_automation/bitrise_workflows/student.yml
scripts/build_automation/bitrise_workflows/teacher.yml

[run-nightly]
refs: none
affects: none

Update project files for Xcode 11.6

---

Core/Core/AppEnvironment/LocalizationManager.swift
Core/CoreTests/AppEnvironment/LocalizationManagerTests.swift

refs: MBL-14502
release note: Fixed an issue with QR Login

Make QR Login with new locale smoother

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Extensions/FontExtensions.swift

Add Font extensions

---

Core/Core/Discussions/DiscussionHTML.swift
Core/Core/UIViews/CoreWebView.swift
Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift

refs: MBL-14591
release note: Fixed LTI tools in discussions
Test plan:
- See ticket for Kaltura in a discussion
- Make sure Launch External Tool button still shows up elsewhere as well
- twilson > Arc course > Pages > Page - with Arc Video

Fix LTI tools in discussions

---

TestsFoundation/TestsFoundation/Fixtures/GraphQL/SubmissionListFixture.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniAssignment.swift
rn/Teacher/src/canvas-api-v2/__templates__/assignment.js
rn/Teacher/src/canvas-api-v2/queries/SubmissionList.js
rn/Teacher/src/modules/quizzes/submissions/QuizSubmissionList.js
rn/Teacher/src/modules/quizzes/submissions/__tests__/map-state-to-props.test.js
rn/Teacher/src/modules/quizzes/submissions/map-state-to-props.js
rn/Teacher/src/modules/submissions/list/SubmissionList.js
rn/Teacher/src/modules/submissions/list/__tests__/SubmissionList.test.js
rn/Teacher/src/modules/submissions/list/__tests__/map-state-to-props.test.js
rn/Teacher/src/modules/submissions/list/map-state-to-props.js
rn/Teacher/src/modules/submissions/list/submission-prop-types.js

refs: MBL-14634
release note: Fixed an error when viewing submissions

Remove muted from GraphQL query

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/AppEnvironment/AppEnvironment.swift
Core/Core/Courses/CourseListView.swift
Core/Core/SwiftUIViews/CoreHostingController.swift
Core/Core/UIViews/EmptyView.swift
Core/Core/ViewModifiers/TestIdentifier.swift
Core/CoreTests/Courses/CourseListViewTests.swift
Core/CoreTests/ViewModifiers/AvoidKeyboardAreaTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/Extensions/TestTreeExtensions.swift
TestsFoundation/TestsFoundation/Helpers/TestEnvironment.swift

~Proof of concept only. Way too reliant on alphabetized strings.~
A testing framework for SwiftUI.
refs: MBL-14613
affects: none

SwiftUI testing

---

rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/TeacherTests/RoutesTests.swift

refs: MBL-14639
release note: Fixed a crash in certain links

Fix /wiki links in Teacher

---

Parent/Parent/Routes.swift
Parent/ParentUnitTests/RoutesTests.swift
Student/Student/Routes.swift
Student/StudentUnitTests/RoutesTests.swift
rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/TeacherTests/RoutesTests.swift
rn/Teacher/src/routing/register-screens.js

refs: MBL-14634
release note: Fixed file links in new RCE
Test plan:
- narmstrong > CS 1400 > Assignments > File Upload 3 > tap file links
- Files should open in all 3 apps

Handle new RCE file links

---

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift

refs: MBL-14643
release note: Fixed viewing submissions
Test plan:
- Submit to an assignment for the first time
- View the submission from Assignment details "Submission & Rubric"
- The first attempt should show up

Fix showing first submission

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Planner/APICalendarEvent.swift
Core/Core/Planner/CalendarEvent.swift

refs: MBL-14568
release note: Fix viewing of section specific calendar event details
test plan: see ticket for an event

Fix section specific calendar event details

---

Core/Core/Pages/PageEditor/PageEditorView.swift
Core/Core/RichContentEditor/RichContentEditor.js
Core/Core/RichContentEditor/RichContentEditor.swift
Core/Core/UIViews/CoreWebView.swift
Core/Core/UIViews/ItemPickerViewController.swift
TestsFoundation/TestsFoundation/CoreUIElements/RichContentEditor/RichContentEditor.swift

use ItemPicker for who can edit
fix scrollbar weirdness in rce
refs: MBL-14652

Polish PageEditor

---

Core/Core/DocViewer/Comments/CommentListViewController.swift
Core/Core/DocViewer/DocViewerAnnotationProvider.swift
Core/Core/DocViewer/DocViewerCommentReplyAnnotation.swift
Core/Core/DocViewer/PSPDFAnnotationExtension.swift
Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift

refs: MBL-11429
release note: Added an icon to annotations on submissions when there are comments attached

Add an icon to annotations when they have comments

---

.gitcommit
setup.sh

You can set it with:
```git config commit.template .gitcommit```

Add git commit template

---

rn/Teacher/ios/TeacherE2ETests/ContextCardE2ETests.swift

Disable a broken test until November

---

scripts/build_automation/bitrise_workflows/common.yml

refs: none
test plan:
Install Teacher app, view a pdf submission. should not crash.

Fix loading PSPDFKit in Teacher

---

Core/Core/DocViewer/DocViewerAnnotationProvider.swift

refs: MBL-14723
release note: Fixed a crash when adding annotations
test plan:
- Add some annotations to a document
- Add some comments to an annotation
- Should not crash

Fix crash in DocViewer

---

scripts/build_automation/bitrise_workflows/common.yml

refs: none
affects: none
Archive first, then upload dsyms, then deploy to itunesconnect.
This build was done with these changes and it worked: https://app.bitrise.io/build/4d6ba7ef8a6911f7#?tab=log

Fix App Store workflows

---

Core/Core/DocViewer/DocViewerAnnotationProvider.swift
Core/Core/DocViewer/DocViewerViewController.swift
Core/Core/DocViewer/PSPDFAnnotationExtension.swift
Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift

refs: MBL-14699
release note: Fixed an issue that could prevent annotations from showing on submissions

Fix annotations when pdf has been rotated

---

Core/Core/Discussions/DiscussionHTML.swift

refs: MBL-14713
release note: Fixed custom js in discussions

Execute custom js in discussions

---

Core/Core/Modules/ModuleItem.swift
Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift
Core/CoreTests/Modules/ModuleItemTests.swift
Core/CoreTests/Modules/ModuleItems/ModuleItemDetailsViewControllerTests.swift

refs: MBL-14715
release note: Fixed viewing details of locked discussion and quiz module items

Allow viewing of locked discussions and quizzes

---

Core/Core/Planner/GetPlannables.swift

refs: MBL-14728
release note: Hide announcements on calendar to match web

Don't save announcement plannables

---

README.md

Add react-native-cli to readme

---

scripts/blame.json
scripts/build_automation/bitrise_workflows/common.yml

Get rid of most references to myself

---

Core/Core/Profile/Settings/PairWithObserverViewController.swift

refs: MBL-14752
test plan: You would need to have an Android device to test this. I have
one and tested it locally. I will test with the ad-hoc build as well.

Include account ID in pairing QR code

---

Parent/Parent/Dashboard/DashboardViewController.swift
Parent/Parent/Routes.swift
Parent/Parent/Students/AddStudentController.swift
Parent/Parent/Students/StudentListViewController.swift
Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
Parent/ParentUnitTests/Students/AddStudentControllerTests.swift
Parent/ParentUnitTests/Students/StudentListViewControllerTests.swift

refs: MBL-14744
test plan:
- Add a student using QR code from dashboard
- Add a student using QR code from Settings > Manage Students > +

Support pairing with QR from Manage Students

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Core.xcodeproj/project.pbxproj
Parent/Parent.xcodeproj/project.pbxproj
Podfile
Podfile.lock
Student/Student.xcodeproj/project.pbxproj
Student/Student.xcodeproj/xcshareddata/xcschemes/CITests.xcscheme
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj

Move PSPDFKit & Lottie to SPM

---

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
rn/Teacher/src/modules/speedgrader/SubmissionViewer.js
rn/Teacher/src/modules/speedgrader/__tests__/SubmissionViewer.test.js

refs: MBL-14762
release note: Fixed displaying ppt, xls, and csv submissions

Fixed display of ppt, xls, csv, and a few others

---

rn/Teacher/src/modules/assignment-due-dates/AssignmentDueDates.js
rn/Teacher/src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js
rn/Teacher/src/modules/assignment-due-dates/__tests__/map-state-to-props.test.js
rn/Teacher/src/modules/assignment-due-dates/map-state-to-props.js

refs: MBL-14753
release note: Fixed a crash when viewing due dates for graded discussions

Fix assignment due dates for graded discussions

---

Core/Core/Extensions/WKWebViewExtensions.swift
Core/Core/UIViews/CoreWebView.swift
Core/Core/UIViews/CoreWebViewController.swift

refs: MBL-14544
release note: Fixed certain links not opening in pages

Implement WKUIDelegate methods to handle popups & prompts

---

Core/Core/ObservedStudents/GetObservedStudents.swift
Core/CoreTests/API/APITests.swift
Core/CoreTests/AudioVideo/UploadMediaCommentTests.swift
Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
Student/Student/Routes.swift
Student/StudentUnitTests/RoutesTests.swift
rn/Teacher/ios/TeacherTests/Attendance/AttendanceStatusControllerTests.swift
rn/Teacher/ios/TeacherTests/Attendance/AttendanceViewControllerTests.swift
rn/Teacher/ios/TeacherTests/Attendance/RollCallSessionTests.swift

refs: MBL-14754
release note: Fixed an issue with missing observed students

Fix loading cross-trust observer enrollments

---

Student/Student/StudentAppDelegate.swift

refs: MBL-14767
release note: Fixed an error when launching from Student View in Teacher app

Fix error when starting Student View

---

Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Discussions/DiscussionReplyViewController.swift

refs: MBL-14740
release note: Fixed file preview window in some cases

Make file attachments modal

---

Parent/Parent.xcodeproj/project.pbxproj
Student/Student.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj

https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/
refs: none
affects: none

Fix library not loaded when running on device

---

Core/Core/AppEnvironment/BackgroundVideoPlayer.swift
Core/Core/Files/FileDetails/FileDetailsViewController.swift
Core/Core/UIViews/PagesViewController.swift
Core/CoreTests/AppEnvironment/BackgroundVideoPlayerTests.swift
Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift

refs: MBL-14729
release note: Fixed a layout issue in module items when reopening the app

Fix module items offset when resuming the app

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Core.xcodeproj/project.pbxproj
Parent/Parent.xcodeproj/project.pbxproj
Podfile
Podfile.lock
Student/Student.xcodeproj/project.pbxproj
Student/Student.xcodeproj/xcshareddata/xcschemes/CITests.xcscheme
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj

refs: none
test plan: builds should pass

Use CocoaPods for PSPDFKit :(

---

Core/Core/Contexts/TabVisibility.swift

refs: MBL-14796
release note: Fixed a bug that could prevent modules from loading

Fix loading modules

---

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
Student/Student/Submissions/SubmissionDetails/Views/Drawer.swift

refs: MBL-14794
release note: Open drawer in submission details

Start drawer in middle position

---

Core/Core/AppEnvironment/SessionDefaults.swift
Core/Core/Modules/ModuleList/ModuleListViewController.swift

refs: MBL-14557
release note: Remember module toggle state across app launches

Store collapseIDs in userDefatults

---

Core/Core/UIViews/KeyboardTransitioning.swift

refs: refs: MBL-14802
release note: Fix extra space above keyboard when replying to discussion

Remove keyboardspace

---

CanvasCore/CanvasCore/Helm/Helm.swift
CanvasCore/CanvasCore/Helm/HelmViewController.swift
Core/Core/People/PeopleListViewController.storyboard
Core/Core/People/PeopleListViewController.swift
Core/Core/Router/Router.swift
Core/Core/UIViews/FilterHeaderView.swift
Parent/Parent/Routes.swift
Student/Student/Routes.swift
Student/StudentUnitTests/RoutesTests.swift
rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.storyboard
rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
rn/Teacher/ios/TeacherTests/RoutesTests.swift
rn/Teacher/src/modules/courses/CourseNavigation.js
rn/Teacher/src/routing/register-screens.js

extra: Allows the FilterHeaderView to be auto sized & have up to 2 lines in the title
refs: MBL-14799

Align Student & Teacher routing

---

Core/Core/Contexts/TabVisibility.swift

refs: MBL-14820
release note: Fixed loading modules

Support users tab visibility

---

Core/Core/Contexts/ContextColor.swift
Core/Core/Courses/Course.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Groups/Group.swift
Core/CoreTests/Courses/CourseTests.swift
Core/CoreTests/Groups/GroupTests.swift
TestsFoundation/TestsFoundation/Fixtures/Model/ContextColorFixture.swift

refs: MBL-14810
release note: Fixed a crash that could occur when the app was launched from a notification
test plan: Course and group colors should be correct.

Make context color a relationship

---

Student/Student/Notifications/ActivityStreamViewController.swift

refs: MBL-14824
release note: Fix notification navigation in group view

Fix notification navbar style in case of groups

---

README.md

Add note about redux-logger to readme

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher/SpeedGrader/Drawer.swift
rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderView.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
scripts/coverage/config.json

Add drawer to native speedgrader with placeholder content

---

Core/CoreTests/Profile/Settings/PairWithObserverViewControllerTests.swift

Bump QR code coverage

---

Core/Core/Files/FileList/FileListViewController.swift
Core/CoreTests/Files/FileList/FileListViewControllerTests.swift

refs: MBL-14800
release note: Add ability to delete files from files screen
test plan:
* open files screen, swipe left on any file/folder
*delete should be visible if file can be deleted by user
* empty folder can be deleted
* teacher can delete files from course
* files visible as search results can also be deleted

Add ability to delete files from FileList

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/AppEnvironment/AppEnvironment.swift
Core/Core/Extensions/TransactionExtensions.swift
Core/Core/SwiftUIViews/Pages.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher/SpeedGrader/CommentsTab.swift
rn/Teacher/ios/Teacher/SpeedGrader/Drawer.swift
rn/Teacher/ios/Teacher/SpeedGrader/FilesTab.swift
rn/Teacher/ios/Teacher/SpeedGrader/GradesTab.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift

Improve animations & add attempt picking

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Files/File.swift
Core/Core/Submissions/APISubmission.swift
Core/Core/Submissions/Submission.swift
Core/Core/SwiftUIViews/Pages.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher/SpeedGrader/SimilarityScore.swift
rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderView.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift

Also disable page panning while picking an attempt
refs: MBL-14816

Add SimilarityScore for native speedgrader

---

Core/Core/Files/FilePicker/FilePickerCell.swift
Core/Core/Files/FilePicker/FilePickerViewController.storyboard
Core/Core/Files/FilePicker/FilePickerViewController.swift
Core/Core/UIViews/EmptyView.swift
Core/CoreTests/Files/FilePicker/FilePickerViewControllerTests.swift

refs: MBL-14835
release note: Add ability to remove files from staged file upload submission
test plan:
* upload files for a submission
* gray X should be visible in each file's row
* click X to remove those files
* after confirmation files should be removed

Add ability to remove files from staged file upload submission

---

Core/Core/DocViewer/DocViewerViewController.swift
Core/Core/UIViews/CoreWebView.swift
Core/CoreTests/UIViews/CoreWebViewTests.swift

refs: MBL-14866
release note: Various bug fixes

Fix a crash when opening a new web view window

---

Core/Core/AudioVideo/UploadMediaComment.swift
Core/Core/Extensions/NSPersistentContainerExtensions.swift
Core/Core/Logger/Logger.swift
Core/Core/Store/UseCase.swift
Core/Core/Submissions/CreateTextComment.swift
Core/Core/Submissions/SubmissionBreakdownViewController.swift
Core/Core/Todos/TodoList/TodoListViewController.swift
Core/CoreTests/Submissions/SubmissionBreakdownViewControllerTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
TestsFoundation/TestsFoundation/Database/TestPersistence.swift
rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift
rn/Teacher/src/modules/assignment-details/AssignmentDetails.js
rn/Teacher/src/modules/assignment-details/__tests__/AssignmentDetails.test.js

also fix submission breakdown dials routing correctly to native submission list
refs: none

Fix merge conflicts causing errors in SubmissionList

---

Core/Core/Modules/ModuleItem.swift
Core/Core/Modules/ModuleList/ModuleItemCell.swift
Core/CoreTests/Modules/ModuleItemTests.swift
Core/CoreTests/Modules/ModuleListViewControllerTests.swift

refs: MBL-14897
release note: Fixed access to locked content from modules
test plan:
- student app > ssadler.instructure.com
- username: narmstrong
- course > modules > all items should be tappable

Fix accessing locked content from modules

---

Core/Core/AudioVideo/UploadMediaComment.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Submissions/SubmissionComment.swift
Student/Student/Submissions/SubmissionComments/SubmissionCommentVideoCell.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentListCell.swift

no notes since this is a feature flag bug
refs: MBL-14888

Keep local media url for a while

---

Core/Core/UIViews/CoreWebView.swift

refs: MBL-14882
release note: Fixed an issue with video on Pages

Fix iframe replacement bug

---

Core/Core/Files/FileList/FileListViewController.swift

refs: MBL-14800
release note: Fix translation
test plan: Open files, try to delete one, check for alert title

fix translation

---

Core/Core/AudioVideo/APIMediaComment.swift
Core/Core/AudioVideo/MediaComment.swift
Core/Core/Files/UploadManager.swift
Core/Core/Submissions/APISubmission.swift
Core/Core/Submissions/GetSubmissions.swift
Core/Core/Submissions/Submission.swift
Core/CoreTests/AudioVideo/MediaCommentTests.swift

refs: MBL-14895
release note: Fixed loading grades and submissions

Fix json decoding errors on grades and submissions

---

Core/Core/Profile/GetAccountHelpLinks.swift
Core/CoreTests/Profile/GetAccountHelpLinksTests.swift

refs: MBL-14928
affects: parent, teacher, student
release note: Fixed help link visibility across apps

Fix helplink scope

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Assignments/APIRubric.swift
Core/Core/Assignments/Assignment.swift
Core/Core/Assignments/Rubric.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Extensions/SwiftUIExtensions.swift
Core/Core/Grades/GradeFormatter.swift
Core/Core/Submissions/APISubmission.swift
Core/Core/Submissions/GradeSubmission.swift
Core/Core/SwiftUIViews/EditorForm.swift
Core/Core/SwiftUIViews/FlowStack.swift
Core/Core/SwiftUIViews/RemoteImage.swift
Core/Core/UIViews/AlertAction.swift
Core/Core/en.lproj/Localizable.stringsdict
Core/CoreTests/Assignments/GetAssignmentsTests.swift
Core/CoreTests/Assignments/RubricTests.swift
Core/CoreTests/Submissions/APISubmissionTests.swift
Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
Student/StudentUnitTests/Submissions/SubmissionRubric/RubricViewControllerTests.swift
TestsFoundation/TestsFoundation/Fixtures/Model/RubricFixture.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift
rn/Teacher/ios/Teacher/SpeedGrader/Drawer.swift
rn/Teacher/ios/Teacher/SpeedGrader/RubricAssessor.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentList.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift

Also fixed some iOS 13 issues in native speedgrader
refs: MBL-14905

Add grading to native speedgrader

---

Core/Core/Extensions/URLComponentsExtensions.swift
Student/Student/Routes.swift
Student/StudentUnitTests/RoutesTests.swift
rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/TeacherTests/RoutesTests.swift
rn/Teacher/src/modules/dashboard/GlobalAnnouncementRow.js
rn/Teacher/src/modules/dashboard/__tests__/GlobalAnnouncementRow.test.js
rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/GlobalAnnouncementRow.test.js.snap

refs: MBL-14931
release note: Fixed viewing files linked in global announcements

Show files from global announcements in a web view

---

Core/Core/Modules/ModuleList/ModuleListViewController.swift
Core/CoreTests/Modules/ModuleListViewControllerTests.swift

refs: MBL-14961
release note: Fixed module scrolling in special cases
test plan: see ticket, make sure that cache is cleared

fix scroll to module

---

Parent/Parent/ParentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-14977
affects: Parent, Teacher
test plan:
- Compile parent and teacher app.
- No Firebase deprecation warnings should be raised.

Fix Firebase deprecation warnings

---

Core/Core/Assignments/APIRubric.swift

refs: MBL-14987
release note: Fix grades list not loading in specific cases.
test plan:
- See ticket.

Make APIRubric property optional

---

rn/Teacher/ios/TeacherUITests/Discussions/DiscussionsUITests.swift

affects: none
test plan:
- Discussions UI tests should pass

Fix discussions UI test expectation.

---

Core/Core/Submissions/SubmissionBreakdown.swift
TestsFoundation/TestsFoundation/CoreUIElements/Assignments/Assignments.swift
rn/Teacher/ios/TeacherE2ETests/ContextCardE2ETests.swift

Fix graded circle not getting tapped by UI test. Remove unused code.
test plan:
- Context card E2E test should pass

Fix context card E2E test

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Login/LoginWebViewController.swift
Core/Core/Submissions/APISubmission.swift
Core/CoreTests/Dashboard/DashboardCardTests.swift
Core/CoreTests/Extensions/TransactionExtensionTests.swift
Core/CoreTests/Submissions/GradeSubmissionTests.swift
Core/CoreTests/Submissions/SubmissionSummaryTests.swift
TestsFoundation/TestsFoundation/Fixtures/Model/SubmissionFixture.swift

Don't ever animate backtracking, and animate out opacity when complete.
refs: none
release note: Polished progress bar while logging in

Smooth out login web view progress bar

---

Core/Core/DocViewer/DocViewerViewController.swift

refs: MBL-14966
release note: Fixed annotations not saving in some cases
test plan: easiest is to use balintbartok.instructure.com -> teacher,  Test Course, Assignements, Annotation
This is a multilayered document, annotations should save, they should be on top of the pages. Any changes happening should also be visible in the student app and on web.

Fix annotation saving and layers

---

TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderCommentUITests.swift

Fix simulator permission override method, disable failing test

---

Core/Core.xcodeproj/project.pbxproj
Core/CoreTests/Extensions/SwiftUIExtensionsTests.swift
Core/CoreTests/Submissions/GetSubmissionSummaryTests.swift

affects: none
test plan:
- Test coverage warnings shouldn't be visible during pull request.

Increase test coverage

---

Core/Core/ViewModifiers/AvoidKeyboardArea.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasServer.swift
TestsFoundation/TestsFoundation/MiniCanvas/State/MiniCourse.swift
rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderCommentUITests.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderRubricUITests.swift
rn/Teacher/ios/TeacherUITests/Todo/TodoUITests.swift

test plan:
- Keyboard shouldn't overlap content during SpeedGrader comment composing on iOS 14.3.
- UI tests shouldn't fail.

UI test fixes

---

Student/StudentUITests/Inbox/InboxTests.swift

refs: MBL-15073
affects: none
test plan:
- InboxTests shouldn't fail.

Align message sending test to latest changes.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Extensions/NSPredicateExtensions.swift
Core/Core/Grades/GetAssignmentsByGroup.swift
Core/Core/Grades/GradeListViewController.swift
Core/CoreTests/Extensions/NSPredicateExtensionsTests.swift
Core/CoreTests/Grades/GetAssignmentsByGroupTests.swift

refs: MBL-15017
release note: Hide grades of not graded assignments
test plan: see ticket, make sure to test with an empty cache

Don't show not graded assignments

---

Core/Core/API/API.swift
Core/Core/Extensions/URLResponseExtensions.swift
Core/Core/Modules/GetModules.swift
Core/CoreTests/API/APITests.swift
Core/CoreTests/Extensions/URLResponseExtensionsTests.swift

refs: MBL-14953
release note: Fix module mixup and disappearence

Fix modules not getting downloaded

---

Core/Core/Extensions/URLComponentsExtensions.swift
Core/Core/Files/FileDetails/FileDetailsViewController.swift
Student/Student/Routes.swift
Student/StudentUnitTests/RoutesTests.swift
rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/TeacherTests/RoutesTests.swift

refs: MBL-15056
release note: Fix user files not opening in app
test plan: addition to the ticket, files should be open from
*global announcements ( MBL-14931 )
*discussions( MBL-15056)
*anywhere (?)

Open user files in webview

---

Core/Core/Profile/Settings/ProfileSettingsViewController.swift
Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift

refs: MBL-15183
test plan: Open settings/privacy policy -> should open ../canvas/privacy

Change privacy policy URL to new one

---

Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/GetDiscussions.swift
Student/Widgets/AnnouncementsWidget/Controller/AnnouncementsProvider.swift
Student/Widgets/AnnouncementsWidget/Model/AnnouncementItem.swift

Make announcements widget use APIDiscussion entity to avoid CoreData conflict with other UseCases

---

rn/Teacher/src/routing/register-screens.js

refs: MBL-14812
test plan: check if syllabus can be opened from student

Fix student syllabus navigation

---

Core/Core/Discussions/DiscussionEditorView.swift
Student/StudentUITests/Discussions/DiscussionEditorTests.swift

refs: MBL-15210
release note: Update Empty announcement error message

Show alert for announcements without description

---

Core/Core/UIViews/HorizontalMenuViewController.swift

refs: MBL-15101
release note: Improve VoiceOver support on Syllabus page.
test plan:
- Go to the Syllabus of a course
- Enable VoiceOver and navigate to the Summary Tab
- Double tap to activate the Summary Tab
- Swipe right on the screen
- Notice that it sends you back to the Syllabus Tab instead of moving to the content of the Summary Tab

Fix syllabus content scroll being reset after VoiceOver focus moves to content.

---

Student/Student/StudentTabBarController.swift

refs: MBL-15217
release note: Fix Todo badge icon
test plan: open student application with a user, that has unread todo items, make sure the badge is visible on initial load

refresh todoController, when needed

---

Core/Core/Dashboard/DashboardCard.swift
Core/Core/Dashboard/DashboardCardView.swift
Core/Core/Dashboard/GroupCard.swift
Core/Core/Todos/Todo.swift

refs: MBL-15216
test plan: make sure tests are running, nothing breaks

Remove possible cycles

---

Student/Student.xcodeproj/xcshareddata/xcschemes/IPadTests.xcscheme
Student/StudentUITests/SpringBoard/SpringBoardTests.swift
rn/Teacher/ios/TeacherUITests/SpeedGrader/IPadSpeedGraderTests.swift
scripts/build_automation/bitrise_workflows/tests.yml

refs: MBL-15031
affects: none
test plan:
- No nightly test should fail

Fix Nightly-A UI test runner

---

Core/Core/People/PeopleListViewController.swift
scripts/build_automation/bitrise_workflows/tests.yml

refs: MBL-15079
test plan:
- Apply a filter on the people list inside a course
- VoiceOver focus should remain on the filter button and not jump back to the top of the page

Restore accessibility focus after filtering.

---

Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift

refs: MBL-15103
test plan: check rubric a11y labels

Pass double into string formatter

---

CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift

refs: MBL-14984
test plan: see accessibility label of expand button

Change expand button accessibility label

---

CanvasCore/CanvasCore/Helm/Helm.swift

Change secondary back button accessibility label

---

Core/Core/SwiftUIViews/EditorForm.swift

hide a11y label for editor section header

---

Core/Core/Todos/TodoListViewController.swift
Core/CoreTests/Todos/TodoListViewControllerTests.swift

refs: MBL-15234
release note: Fixed To-Do badge not counting non-graded submissions.

Include not graded submissions in To-Do badge count.

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Todos/Todo.swift
TestsFoundation/TestsFoundation/Fixtures/Model/TodoFixture.swift

refs: MBL-15231
release note: Fix todo list chronological order
test plan: see ticket, compare with web

Use due date for sorting

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/People/APIUser.swift
Core/CoreTests/People/APIUserRequestableTests.swift
Core/CoreTests/People/APIUserTests.swift
rn/Teacher/ios/TeacherUITests/Todo/TodoUITests.swift

refs: MBL-15236
release note: Fixed SpeedGrader not loading submissions from some users.
test plan:
See ticket.

Handle empty string avatar_url while decoding APIUser.

---

Core/Core/Dashboard/DashboardCardView.swift
Student/Student/StudentTabBarController.swift
rn/Teacher/ios/Teacher/TeacherTabBarController.swift

refs: MBL-15254
test plan:
See ticket.

Remove group list from teacher dashboard

---

Core/Core/Grades/GradeListViewController.swift
Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift
rn/Teacher/src/modules/assignments/AssignmentList.js
rn/Teacher/src/modules/assignments/__tests__/AssignmentList.test.js

Amend assignment list title.
refs: MBL-15203
release note: Update assignment list title
test plan:
- Open the assignments page
- Observe title

Change the asignments list screen's title

---

Core/Core/People/ContextCard/Course/ContextCardViewModel.swift
Core/Core/People/ContextCard/Group/GroupContextCardViewModel.swift

refs: MBL-15280
release note: Fixed messaging from people list.
test plan: try to send messages from the people list
* opened from a course
* opened from groups

Fix context ID for messages

---

Core/Core/People/ContextCard/Course/ContextCardViewModel.swift
Core/CoreTests/People/ContextCard/Course/ContextCardTests.swift

refs: MBL-15249
release note: Fixed students' grades in people list

Use gradingPeriod for enrollments

---

rn/Teacher/ios/Teacher/SpeedGrader/RubricAssessor.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift

refs: MBL-15261
release note: Fixed rubric rating description not displaying correctly.
test plan: See ticket. Also added long description of the rating.

Fix rubric tooltip going under submission view. Add rubric long description to bubble.

---

Core/Core/Courses/Course.swift
Core/CoreTests/Courses/CourseTests.swift

refs: MBL-15259
release note: Fixed course grades in specific cases.

Use current grading scores, even in case of totals enabled

---

Core/Core/Extensions/DateExtensions.swift
Core/Core/Todos/Todo.swift
Core/Core/Todos/TodoListViewController.storyboard
Core/CoreTests/Todos/TodoTests.swift

refs: MBL-15251
release note: Added day of week to to-do list items' due date.
test plan: To-do list should display the day of week as part of the due date.

Add day of week to to-do list cell. Make date field on to-do item cell to shrink text if it's too long.

---

Core/Core/Dashboard/DashboardCard.swift
Core/Core/Dashboard/DashboardCardView.swift
Core/CoreTests/Dashboard/DashboardCardTests.swift
Student/Student/StudentTabBarController.swift
rn/Teacher/ios/Teacher/TeacherTabBarController.swift

refs: MBL-15277
release note: Fixed Teachers seeing their student enrollments on dashboard

Filter Coursecards for Teachers

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/People/PeopleListViewController.swift
Core/Core/People/User.swift
Core/CoreTests/People/PeopleListViewControllerTests.swift
Core/CoreTests/People/UserTests.swift

refs: MBL-15321
release note: Fixed roles disappearing from peoplelist.

Change user-enrollment datamodel connection

---

Core/Core/Extensions/URLComponentsExtensions.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/Student/Routes.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
Student/StudentUnitTests/RoutesTests.swift

refs: MBL-15268
release note: Fixed assignment files not auto-populating course and assignment fields while sharing in some cases.

Fixed files opened from assignment details description opening the file as part of the module sequence.

---

Parent/Parent/Info.plist
Student/Student/Info.plist
rn/Teacher/ios/Teacher/Info.plist

refs: MBL-15241
release note: Non-secure http connections are now disallowed.

Disable http protocol usage

---

rn/Teacher/ios/Teacher/SpeedGrader/GradeSlider.swift

refs: MBL-15126
test plan:
*check a submission with a grade slider and use voiceover

Add a11y identifier for the grade slider

---

Core/Core/Extensions/UITextViewExtensions.swift
Core/Core/Planner/CreateTodoViewController.storyboard
Core/Core/Planner/CreateTodoViewController.swift
Core/Core/UIViews/DynamicTextField.swift
Core/CoreTests/Planner/CreateTodoViewControllerTests.swift

refs: MBL-15107
test plan:
in the calendar add a new to do item, and test the view for a11y

Fix a11y for new todo item screen

---

CanvasCore/CanvasCore/ReactNativeModules/RichContentEditorManager.m
CanvasCore/CanvasCore/ReactNativeModules/RichContentEditorWrapper.swift
Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift
Core/Core/Discussions/DiscussionEditorView.swift
Core/Core/Discussions/DiscussionReplyViewController.swift
Core/Core/ErrorReports/ErrorReportViewController.swift
Core/Core/Files/FileEditor/FileEditorView.swift
Core/Core/Files/FileList/FileListViewController.swift
Core/Core/Login/LoginFindSchoolViewController.swift
Core/Core/Pages/PageEditor/PageEditorView.swift
Core/Core/RichContentEditor/RichContentEditor.swift
Core/Core/RichContentEditor/RichContentEditorViewController.swift
Core/Core/SwiftUIViews/EditorForm.swift
Core/Core/Syllabus/SyllabusEditorView.swift
Student/Student/Submissions/TextSubmission/TextSubmissionViewController.swift
Student/Student/Submissions/urlSubmission/UrlSubmissionViewController.swift
rn/Teacher/ios/Teacher/SpeedGrader/RubricAssessor.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift
rn/Teacher/ios/Teacher/Submissions/SubmissionFilterPickerViewController.swift
rn/Teacher/src/common/components/rows/RowWithTextInput.js
rn/Teacher/src/modules/courses/settings/CourseSettings.js
rn/Teacher/src/modules/courses/settings/__tests__/__snapshots__/CourseSettings.test.js.snap
rn/Teacher/src/modules/inbox/Compose.js
rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Compose.test.js.snap
rn/Teacher/src/modules/quizzes/edit/QuizEdit.js
rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap

refs: MBL-15089
test plan:
see ticket, check all inputs based on changed files

Add A11y labels for text inputs

---

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift

Fix assignment details scroll content getting behind submit button.

---

Core/Core/Dashboard/DashboardCard.swift
Core/CoreTests/Dashboard/DashboardCardTests.swift

refs: MBL-15277
release note: Fixed course cards for TAs
test plan:
Enroll a user as a TA on a course. Check if the course is visible on the dashboard from the teacher app. Student app is not affected.

Fix TA enrollment dashboard

---

Core/Core/Pages/PageEditor/PageEditorView.swift
Core/CoreTests/Pages/PageEditor/PageEditorViewTests.swift

refs: MBL-15209
release note: Fixed page editor not showing title
test plan:
see ticket (add a page from groups)

Fix add page for groups

---

Core/Core/API/APIURL.swift
Core/Core/Extensions/StringExtensions.swift
Core/CoreTests/API/APIURLTests.swift
Core/CoreTests/Extensions/StringExtensionTests.swift

Remove xml escaping while parsing a url from JSON.

---

Core/Core/Submissions/GetSubmissions.swift
Core/Core/Submissions/Submission.swift
Core/CoreTests/Submissions/GetSubmissionsTests.swift

refs: MBL-15318
release note: Fixed excused student submissions listing.

Fix submission needs grading for excused students

---

Core/Core/Grades/GradeFormatter.swift
Core/CoreTests/Grades/GradeFormatterTests.swift

refs: MBL-15220
release note: Fixed rounding for grades
test plan: see ticket, Grade should be 40 instead of 39.99

Fix grade rounding

---

Core/Core/Constants/UserAgent.swift
Core/Core/SwiftUIViews/WebView.swift
Core/Core/UIViews/CoreWebView.swift
Core/CoreTests/Constants/UserAgentTests.swift
Core/CoreTests/UIViews/CoreWebViewTests.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift

refs: MBL-15278
release note: Fixed google authentication for LTI tools
test plan: see ticket (use canvas login)

Change webview User Agent name for LTI tools

---

Podfile
Podfile.lock

refs: MBL-15125
release note: Update PSPDFKit to version 10.3.0

Update PSPDFKit to version 10.3.0

---

Core/Core/Submissions/GetSubmissions.swift
Core/CoreTests/Submissions/GetSubmissionsTests.swift

refs: MBL-15360
release note: Fix inactive students visible is speedgrader while swiping.

Inactive students are listed in not submitted tab when swiping

---

Core/Core/Profile/SideMenu/SideMenuBottomSection.swift
Student/StudentUITests/SideMenu/SideMenuUITests.swift
rn/Teacher/ios/TeacherUITests/SideMenu/SideMenuUITests.swift

refs: MBL-15270
release note:  none

Fix Sidebar Menu logout crash, fix UI tests.

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/Pages/PageDetails/PageDetailsViewController.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/Student/Quizzes/QuizDetails/QuizDetailsViewController.swift

Reset voiceover focus to the top of the page after a screen is loaded as a module sequence item

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Extensions/ProcessInfoExtensions.swift
Core/Core/Files/FileSubmissionsStatus.swift
Core/Core/Files/UploadManager.swift
Core/Core/Profile/SideMenu/SideMenuBottomSection.swift
Core/CoreTests/Files/UploadManagerTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift

refs: MBL-15296
release note: Fixed assignment details screen indicating a successful submission while the assignment is still not submitted.

Fix file upload state inconsistency

---

Core/Core/People/ContextCard/Course/ContextCardGradesView.swift

refs: MBL-15383
release note: Fix total grades with decimal values.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/117681933-e0dff200-b1b2-11eb-85de-a40b57093e3d.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/117681944-e2a9b580-b1b2-11eb-8980-a1448ebd58a1.png"></td>
</tr>
</table>

Student total grade is rounded down

---

Core/Core/Todos/Todo.swift
Core/Core/Todos/TodoListViewController.swift
Core/CoreTests/Todos/TodoTests.swift

refs: MBL-15322
release note: Hide TA role todos.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/117790635-d7559900-b249-11eb-8aa3-0cd6fdc66cd0.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/117790654-db81b680-b249-11eb-94ed-1af9d1b68c3d.png"></td>
</tr>
</table>

Students can see items needing grading in Todo if they have TA roles in other courses

---

rn/Teacher/ios/TeacherUITests/Discussions/DiscussionsUITests.swift

Re-enable discussionsUITests testEditTopic

---

Core/Core/Todos/TodoListViewController.storyboard
Core/Core/Todos/TodoListViewController.swift

refs: MBL-14907
release note: Improved accessibility features.

Add voiceover status updates.

---

rn/Teacher/ios/TeacherE2ETests/ContextCardE2ETests.swift

Fix contextCardE2ETests Teacher

---

Core/Core/Assignments/APIAssignment.swift
Core/Core/Assignments/Assignment.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Assignments/AssignmentTests.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift

refs: MBL-7529
release note: Fixed anonymous survey submissions.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/118104511-8675aa00-b3db-11eb-9051-d165b04c7c2b.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/118104520-88d80400-b3db-11eb-8472-97ab8e25914f.png"></td>
</tr>
</table>

Student names displayed anonymous survey responses

---

rn/Teacher/src/modules/inbox/Compose.js
rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Inbox.test.js.snap
rn/Teacher/src/modules/inbox/components/FilterHeader.js
rn/Teacher/src/modules/inbox/components/__tests__/__snapshots__/FilterHeader.test.js.snap

Improve accessibility in inbox

---

Core/Core/UIViews/PagesViewController.swift

refs: MBL-15379
release note: Fixed initial calendar swiping.
test plan: see ticket, also try pressing today a few times, and test again

Fix Calendar swiping

---

Core/Core/Todos/TodoListViewController.swift

refs: MBL-15388
release note: Fixed TodoItems not showing above 100
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/119150363-aac22e00-ba4e-11eb-9738-98ef13f7cff9.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/119150371-abf35b00-ba4e-11eb-9607-6b346bfde35b.png"></td>
</tr>
</table>

Use pagination for todoItems

---

Core/Core/Submissions/Submission.swift
Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentListCell.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift

refs: MBL-15433
release note: Fixed Todo and grades not loading when new annotation type submission is present.

Annotation submission type breaks to do list and grades

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Modules/APIModule.swift
Core/Core/Modules/Module.swift
Core/Core/Modules/ModuleItem.swift
Core/Core/Modules/ModuleList/ModuleItemSubHeaderCell.swift
Core/CoreTests/Modules/ModuleItemTests.swift
Core/CoreTests/Modules/ModuleListViewControllerTests.swift
Core/CoreTests/Modules/ModuleTests.swift

refs: MBL-15405
release note: Fixed module item locking.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/119981433-e95f6780-bfbd-11eb-9b90-eca38711b6cd.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/119981488-f9774700-bfbd-11eb-8b5c-e8bc1fa6fefb.png"></td>
</tr>
</table>

Fix module item locking

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/PagesE2ETest.swift

refs: MBL-15442
test plan: Test is enabled in nightly testplan, will have to monitor its stability

Added PagesE2ETests for Teacher

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/DashboardE2ETests.swift

Add DashboardE2ETests for Teacher

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/TodosE2ETests.swift

Add TodosE2ETests for teacher

---

Core/Core/Quizzes/QuizListViewController.swift
rn/Teacher/src/modules/assignments/AssignmentList.js
rn/Teacher/src/modules/assignments/__tests__/AssignmentList.test.js

refs: MBL-14834
release note: Fix cross shard user quizzes.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/120811041-df081500-c54b-11eb-9306-ad53a523bb5a.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/120811049-e0394200-c54b-11eb-9b0b-534c4f4e1140.png"></td>
</tr>
</table>

Fix quiz detail routing url.

---

Parent/Parent/Assignments/AssignmentDetailsViewController.swift

refs: MBL-15303
release note: Fixed Submission state inconsistency
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/121042591-209af900-c7b4-11eb-8d21-323c405e0b9f.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/121042447-fcd7b300-c7b3-11eb-8cf6-fb3be6d398df.png"></td>
</tr>
</table>

Include submissions in network call

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/ModulesE2ETests.swift

Added ModulesE2ETests for teacher

---

Core/Core/Pages/PageDetails/PageDetailsViewController.swift

refs: MBL-15443
release note: Fixed page title not updating after edit

Use pageID to identify edited page

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/AssignmentsE2ETests.swift

Add AssignmentsE2ETest for Teacher

---

rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift

refs: MBL-15309
release note: Fixed wrong submission opening in case of more than 100 students

Wait for all the submissions to download before updating

---

TestsFoundation/TestsFoundation/CoreUIElements/Courses/CourseNavigation.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/SyllabusE2ETests.swift

SyllabusE2ETests added for teacher

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/PeopleE2ETests.swift

Add people e2e tests for teacher

---

Core/Core/Profile/SideMenu/SideMenuHeaderView.swift
Core/Core/Profile/SideMenu/SideMenuView.swift

refs: MBL-15130
release note: Fix display name in side menu.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/122727744-a7050f80-d277-11eb-9a07-9413a6edd752.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/122727756-ac625a00-d277-11eb-967a-744156470eb8.png"></td>
</tr>
</table>

User profile display full name instead of display name

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/DiscussionsE2ETests.swift

Add discussionsE2ETest for Teacher

---

Core/Core/People/ContextCard/Course/ContextCardView.swift

refs: MBL-15407
release note: Fixed error page for pending users
test plan: see ticket, use balintbartok, "nota" user
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/123109334-71108880-d43b-11eb-91e3-b1e20f3382d5.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/123109029-327ace00-d43b-11eb-94bf-feb7279f8487.png"></td>
</tr>
</table>

Display fitting panda for pending users

---

Core/Core/Dashboard/View/CourseCard.swift
Core/Core/Dashboard/View/DashboardCardView.swift

refs: MBL-15451
test plan: Dashboard cards should announce course code after course name.

Add course code to dashboard card's a11y label.

---

Core/Core/Courses/APICourse.swift
Core/Core/Courses/Course.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Planner/Plannable.swift
Core/CoreTester/Info.plist
Core/CoreTests/CoreTestCase.swift
Core/CoreTests/Courses/CourseTests.swift
Core/CoreTests/Planner/PlannableTests.swift
rn/Teacher/index.ios.js
rn/Teacher/src/canvas-api/flow/course.js
rn/Teacher/src/modules/app/index.js
rn/Teacher/src/modules/assignments/AssignmentList.js
rn/Teacher/src/modules/courses/courses-reducer.js

refs: MBL-15504
test plan: K5 course colors in the app should match what is set on the web interface by the teacher.

K5 course colors

---

Student/StudentE2ETests/Dashboard/DashboardE2ETests.swift
Student/StudentE2ETests/Profile/ProfileE2ETests.swift

Fix Student E2ETests related to course card a11y changes

---

Core/Core/UIViews/BottomSheetPickerViewController.swift
Core/Core/UIViews/BottomSheetTransitioning.swift

refs: MBL-15410
release note: Fix discussion action sheet layout issues.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/123430679-c0d08a80-d5c8-11eb-9dd2-4a6172cbd1a3.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/123430694-c332e480-d5c8-11eb-80ef-07805880eb7e.png"></td>
</tr>
</table>

Discussion action sheet layout issues

---

Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
rn/Teacher/src/modules/assignments/AssignmentList.js
rn/Teacher/src/modules/assignments/__tests__/AssignmentList.test.js

refs: MBL-15404
release note: Fix cross shard user assignments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/123619673-b2bd7c80-d809-11eb-9119-da0e527fce68.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/123619685-b51fd680-d809-11eb-86ea-a1a20fa49e8e.png"></td>
</tr>
</table>

Fix assignment routing for cross shard users.

---

Core/Core/Profile/SideMenu/SideMenuBottomSection.swift

refs: none
test plan: act as student, try to use "leave student view" button from sidemenu

fix leave student view

---

Core/Core/Planner/CalendarDaysViewController.swift

refs: MBL-15499
release note: Fixed a crash on the calendar screen.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/123795015-cd642400-d8e3-11eb-9e4b-c8c6259bd22b.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/123795024-d05f1480-d8e3-11eb-9250-b2618f32a441.PNG"></td>
</tr>
</table>

Fix date calculation.

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/GradesE2ETests.swift

Add grades e2e test for teacher

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/SubmissionsE2ETests.swift

Add SubmissionsE2E tests for teacher

---

CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift
rn/Teacher/src/modules/courses/CourseNavigation.js

Fix course navigation and assignments list rotation on iPhones supporting master-detail layout.

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/FilesE2ETests.swift

Add FilesE2ETest for Teacher

---

Core/Core/Courses/APICourse.swift
Core/Core/Courses/Course.swift
Core/Core/Courses/GetCourses.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Enrollments/APIEnrollment.swift
Core/CoreTests/Courses/GetCoursesTest.swift
TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift

refs: MBL-15117
release note: Display completed courses in All courses.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/124619379-e5eeb400-de78-11eb-9622-041a8412c224.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/124619387-e71fe100-de78-11eb-86d9-ba58473cf454.png"></td>
</tr>
</table>

Hard-completed enrollments cannot be accessed

---

Core/Core/Files/FileDetails/FileDetailsViewController.swift
Core/Core/Router/RouteHandler.swift
Core/CoreTests/Router/RouteHandlerTests.swift

Files handling fix extracted to the [linked ticket.](https://instructure.atlassian.net/browse/MBL-15530)
refs: MBL-15305
release note: Fix cross-shard user quiz, discussion details.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/125318925-986fbc80-e33a-11eb-8131-ab99973fe6f5.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/125318913-96a5f900-e33a-11eb-9801-7217a1ef724e.png"></td>
</tr>
</table>

Classic quizzes discussions and files do not load for cross shard users

---

Core/Core/UIViews/HorizontalMenuViewController.swift

refs: MBL-15519
release note: Fix Syllabus page rotation.

App crash on rotating with Syllabus

---

Core/Core/People/PeopleListViewController.storyboard

Make people list cell height dynamic

---

Core/Core/UIViews/CoreWebView.swift
Core/CoreTests/UIViews/CoreWebViewTests.swift

refs: MBL-15197
release note: Navigate course links from embedded web content to native screens.

Webview renders blank for wiki pages that are loaded from an embedded iframe in canvas content

---

Core/Core/UIViews/CoreWebView.swift

Quiz details opened 3 times after finishing quiz

---

Core/Core/Extensions/UIFontExtensions.swift

Handle not supported font traits.

---

Core/Core/Courses/CourseListView.swift

Fix all courses showing roles from deleted enrolments.

---

Core/Core/People/PeopleListViewController.swift

People context card resets roles on people list

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleSubjectView.swift
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleSubjectViewModel.swift
Core/CoreTests/Dashboard/K5/ViewModel/Schedule/K5ScheduleSubjectViewModelTests.swift

refs: MBL-15475
test plan: Not testable yet, just a UI element for the upcoming schedule page.

K5 schedule subject

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Dashboard/K5/View/K5Preview.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleSubjectView.swift
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleSubjectViewModel.swift
scripts/coverage/config.json

refs: MBL-15475
test plan: Not testable. Helper entity to speed up K5 preview creation.

Extract preview data and K5 font setup to a helper entity.

---

TestsFoundation/TestsFoundation/CoreUIElements/Quizzes/Quiz.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/QuizzesE2ETests.swift

refs: MBL-15528
test plan: The test is failing intentionally, should be merged after https://instructure.atlassian.net/browse/MBL-15560 is fixed

Added E2E Test for classic quiz

---

TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Announcements/Announcements.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/AnnouncementsE2ETests.swift

Add AnnouncementsE2ETests for Teacher

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Core/AppEnvironment/Secret.swift
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/K5/K5StudentE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/K5/K5CourseCard.swift
TestsFoundation/TestsFoundation/CoreUIElements/Profile/Profile.swift
TestsFoundation/TestsFoundation/Element/K5NavigationBar.swift
TestsFoundation/TestsFoundation/Element/TabBar.swift
TestsFoundation/TestsFoundation/UITests/K5UITestCase.swift
TestsFoundation/TestsFoundation/UITests/UITestUser.swift

Introduce K5 capability for E2E Student

---

Core/Core/Dashboard/View/DashboardCardView.swift
Core/Core/Groups/Group.swift
Core/CoreTests/Groups/GroupTests.swift

refs: MBL-15548
release note: Fixed groups showing for inactive courses
test plan: see ticket, check normal groups with own account

Check if group has an active course

---

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/MessagesE2ETest.swift

Add MessagesE2ETests for Teacher

---

Core/Core/Dashboard/K5/View/K5DashboardView.swift
Core/Core/Profile/SideMenu/SideMenuBottomSection.swift
Core/Core/Profile/SideMenu/SideMenuFooterView.swift
Core/Core/Profile/SideMenu/SideMenuHeaderView.swift
Core/Core/Profile/SideMenu/SideMenuItem.swift
Core/Core/Profile/SideMenu/SideMenuMainSection.swift
Core/Core/Profile/SideMenu/SideMenuOptionsSection.swift
Core/Core/Profile/SideMenu/SideMenuSubHeaderView.swift
Core/Core/Profile/SideMenu/SideMenuToggleItem.swift
Core/Core/SwiftUIViews/CustomTextField.swift
Core/Core/SwiftUIViews/TopBar/View/TopBarItemView.swift

Encase previews in debug blocks

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/AppEnvironment/SessionDefaults.swift
Core/Core/Assignments/APIAssignment.swift
Core/Core/Dashboard/K5/Model/Schedule/K5ScheduleItemInfo.swift
Core/Core/Dashboard/K5/View/K5Preview.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleDayView.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleMissingItemsView.swift
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleDayViewModel.swift
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleEntryViewModel.swift
Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleWeekViewModel.swift
Core/Core/Extensions/DateExtensions.swift
Core/Core/Extensions/FontExtensions.swift
Core/Core/Extensions/UIFontExtensions.swift
Core/Core/SwiftUIViews/HorizontalPager.swift
Core/Core/en.lproj/Localizable.stringsdict
Core/CoreTests/Extensions/FontExtensionTests.swift

refs: MBL-15476
release note: Add missing items to schedule view in homeroom.
test plan: See specification.

Missing items section in homeroom schedule

---

TestsFoundation/TestsFoundation/CoreUIElements/Quizzes/Quiz.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/QuizzesE2ETests.swift

Add QuizzesE2ETests for teacher

---

Core/Core/Profile/SideMenu/SideMenuHeaderView.swift

refs: MBL-15554
release note: Fix student view side menu student details.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/131333125-77fd7aa1-981c-493b-9fc8-25b64790e5ef.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/131333148-9ea4ad00-1b99-474a-9df2-0fb5129a0b75.png"></td>
</tr>
</table>

Side menu header does not populate on student view

---

Core/Core/Modules/ModuleItem.swift
Core/CoreTests/Modules/ModuleTests.swift

refs: MBL-15577
release note: Fix sequential module requirements.
test plan: see ticket, should match web, you can also test the sequential module requirement in my 'This test course'.

Module requirements do not work correctly

---

rn/Teacher/src/modules/quizzes/submissions/map-state-to-props.js

refs: MBL-15550
release note: Only show quiz submissions from active enrollments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/131999970-b561cc03-1d13-480e-a689-a988fa8edbae.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/132000004-5b5102d8-468d-4479-b527-81472ca821cb.png"></td>
</tr>
</table>

Classic quiz submissions list shows invited users

---

Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Quizzes/NewQuizzesE2ETests.swift
TestsFoundation/TestsFoundation/CoreUIElements/Quizzes/Quiz.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/NewQuizzesE2ETests.swift
rn/Teacher/ios/TeacherE2ETests/QuizzesE2ETests.swift

refs: MBL-15539
affects: All
test plan:

Add NewQuizzesE2ETest for teacher and student

---

CanvasCore/CanvasCore/Extensions/UINavigationControllerExtensions.swift
CanvasCore/CanvasCore/Helm/FullScreenPrimaryHelmSplitViewController.swift
CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift

Fix discussion rotation in K5 mode.

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/K5/K5GradesE2ETests.swift
Student/StudentE2ETests/K5/K5ScheduleE2ETests.swift
Student/StudentE2ETests/K5/K5StudentE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/K5/K5Grades.swift
TestsFoundation/TestsFoundation/CoreUIElements/K5/K5Schedule.swift
TestsFoundation/TestsFoundation/Element/K5NavigationBar.swift
TestsFoundation/TestsFoundation/UITests/K5UITestCase.swift

Add K5 schedule and grades e2e tests

---

Core/Core/Notifications/APINotificationPreferences.swift
Core/Core/Notifications/NotificationCategory.swift
Core/Core/Notifications/NotificationManager.swift

refs: MBL-15616
release note: Fix email notification settings.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/133107604-3c717a59-a133-4995-88b1-dc70bb20b27c.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/133107100-8332e50e-3299-45ba-8b67-fe3587814831.jpeg"></td>
</tr>
</table>

Email Notification Settings throws error

---

Core/Core/Dashboard/K5/View/Grades/K5GradeCell.swift
Core/Core/Dashboard/K5/View/K5DashboardView.swift
Core/Core/Dashboard/K5/View/Schedule/K5ScheduleWeekView.swift
Core/Core/SwiftUIViews/TopBar/View/TopBarView.swift
Core/Core/SwiftUIViews/ViewPreferences/Bounds.swift

refs: MBL-15602
test plan: See ticket for details.

Homeroom improvements

---

Core/Core/Submissions/APISubmission.swift
Core/Core/Submissions/SubmissionComment.swift
Core/CoreTests/Submissions/APISubmissionTests.swift

refs: MBL-15638
release note: Fixed submissions list not loading in some cases.

Fix url decoding error

---

Student/StudentE2ETests/K5/K5ScheduleE2ETests.swift

Fix K5ScheduleE2ETest

---

Core/Core/Conversations/ComposeReplyViewController.swift
Core/Core/UIViews/AvatarView.swift
Core/Core/UIViews/CircleProgressView.swift
Core/CoreTests/Conversations/ComposeReplyViewControllerTests.swift

refs: MBL-15641
release note: Fixed app getting frozen when opening SpeedGrader on landscape iPhones.

Avoid using layoutSubviews which can cause infinite cycle.

---

Student/StudentE2ETests/Dashboard/DashboardE2ETests.swift

Disable flaky Dashboard Tests

---

TestsFoundation/TestsFoundation/Element/Element.swift

Lowering the timeout needed for element checking

---

Core/Core/Assignments/APIAssignment.swift
Core/Core/Assignments/Assignment.swift
Core/CoreTests/Assignments/AssignmentTests.swift

refs: MBL-15682
release note: Fixed Grades and To Do screens not loading in some cases.

Make API assignment position field optional.

---

Core/Core/SwiftUIViews/EditorForm.swift

refs: MBL-15677
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/141138887-8c8d43bb-53bf-4275-a62e-ffef4d91a2b7.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/141138766-2ad27ce9-d208-44b0-b4f2-db60fb205ec2.png"></td>
</tr>
</table>

Fix layout issues on the Edit Discussion page for iOS 14.

---

Core/Core/Notifications/NotificationManager.swift

refs: MBL-15676
release note: Fixed the error message while switching to Student view.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/141787740-6c2be156-da04-4716-8d0f-e66ecef8f1de.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/141787808-42913434-4191-45ea-9a99-d32c68c4314b.jpeg"></td>
</tr>
</table>

Switching to student view produces an error alert message

---

Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift

refs: MBL-15711
release note: Fixed the options menu on module discussion pages.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/142221344-e6b51ff9-04cb-4bc4-9fb1-d20dbb97f0f9.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/142221337-9c28a947-75dc-4ea8-bba8-e3899ac346c0.png"></td>
</tr>
</table>

Fix module page removes sub page navigation items.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Enrollments/GetEnrollments.swift
Core/CoreTests/Enrollments/GetEnrollmentsTests.swift

refs: MBL-15718
release note: Fixed grading periods not displaying total grades when they should.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/142442729-63645d07-f35f-4049-af0a-c4b7b1aa06bd.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/142442801-6f3e6e37-8f4b-4389-8c40-48642b323a69.png"></td>
</tr>
</table>

Fix grading periods not displaying total grades.

---

Core/Core/AppEnvironment/AppEnvironment.swift
Core/Core/AppEnvironment/K5State.swift
Core/Core/AppEnvironment/SessionDefaults.swift
Core/Core/Login/LoginSession.swift
Core/CoreTests/AppEnvironment/K5StateTests.swift
Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-15654
release note: Added support for Elementary student view.

K5 Subject pages - Student view

---

Parent/Parent/Dashboard/DashboardViewController.swift

refs: MBL-15778
release note: Fixed the status bar color theming.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/144033232-e23bdf09-c59b-497a-9b22-3cdb05a9ae69.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/144033225-b4060966-e68a-4a49-a130-97d10ad2a66d.png"></td>
</tr>
</table>

Statusbar text is black on all screens

---

scripts/build_automation/bitrise_workflows/tests.yml

refs: none
affects: none
test plan:

Added xtrace option for Bitrise script

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/People/ContextCard/Course/ContextCardView.swift

refs: none
test plan:
- Check edit button color on assignment details screen.
- Check mail button color on people context card.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144437227-5738c1e7-bdab-4102-ad6d-9af38673974a.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/144437270-3e4c1bd4-5db5-4df8-bac9-1ba87d38fc5a.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144437323-20d113a9-f08d-47ed-b6ac-0f740b23fe9d.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/144437373-dd7f144f-1d38-401a-aaaa-c94b23825686.PNG"></td>
</tr>
</table>

Add nav bar button colors to assignment details and people context card.

---

Student/StudentE2ETests/K5/K5GradesE2ETests.swift
Student/StudentE2ETests/K5/K5StudentE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/K5/K5Grades.swift
TestsFoundation/TestsFoundation/Element/K5CourseBrowser.swift

Fix failing CI tests

---

Core/Core/Grades/GradeListViewController.swift
Parent/Parent/Courses/CourseListViewController.swift

refs: MBL-15796
release note: Fix total grades not showing on course list
test plan: see ticket, also check MBL-15675

Fix grades not showing

---

Core/Core/UIViews/HorizontalMenuViewController.swift

refs: none
test plan:
* Parent: check grades list and click on grading period title

Fix pages greying out

---

Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift
Core/Core/Dashboard/Model/DashboardCard.swift
Core/Core/Dashboard/View/DashboardCardView.swift
Core/CoreTests/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModelTests.swift

refs: MBL-15776
release note: Fixed invited courses shown on dashboard
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/146151036-11545137-68e6-4706-a922-3d49995e1326.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/146151016-b5383047-3af2-4004-a291-cdad1e693ccd.png"></td>
</tr>
</table>

Invited K5 course shown on dashboard

---

Core/Core.xcodeproj/project.pbxproj
Parent/Parent.xcodeproj/project.pbxproj
Podfile
Podfile.lock
Student/Student.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj

refs: MBL-15772
test plan: Update to cocoapods 1.11.2. Make sure each app starts without issues.

Update firebase dependency versions.

---

Core/Core/Grades/GradeListViewController.swift
Core/CoreTests/Grades/GradeListViewControllerTests.swift

refs: MBL-15799
release note: Show grade letter on the grades page.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/148237270-ef148a03-0539-4bf1-90fa-ca31b339c765.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/148237260-020accdc-856b-4dcf-8cf9-3bf0c24d2232.png"></td>
</tr>
</table>

Grading scheme letter grade does not appear in total mark

---

Core/Core/Dashboard/Model/DashboardCard.swift

refs: MBL-15841
release note: Fixed courses with multiple enrollments disappearing from dashboard.
test plan: see ticket, check on K5 as well

Fix disappearing course.

---

Core/Core/API/APIRequestable.swift
Core/Core/AppEnvironment/Secret.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/DataSeeding/Course/CreateDSCourseRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/DSCourse.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/DataSeeder+DSCourse.swift
TestsFoundation/TestsFoundation/DataSeeding/DataSeeder.swift
TestsFoundation/TestsFoundation/DataSeeding/Enrollment/DataSeeder+Enrollment.swift
TestsFoundation/TestsFoundation/DataSeeding/Enrollment/EnrollRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/User/CreateDSUserRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/User/DSUser.swift
TestsFoundation/TestsFoundation/DataSeeding/User/DataSeeder+DSUser.swift
TestsFoundation/TestsFoundation/UITests/UITestUser.swift

refs: MBL-15482
affects: none
test plan:

Data seeding foundations

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Assignments/Assignments.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/CreateDSAssignmentRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/DSAssignment.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/DataSeeder+DSAssignment.swift
TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
TestsFoundation/TestsFoundation/UITests/E2ETestCase.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSAssignmentsE2ETests.swift

refs: MBL-15858
affects: Teacher, Student, Parent
test plan:

Introduce AssignmentsE2ETests with DataSeeding

---

Core/Core/AppEnvironment/AppStoreReview.swift

refs: MBL-15890
test plan:
- Launch the app.
- Go to Developer menu.
- Enter Manage Rating Request menu.
- Clear "Last Request" and "Last View" fields.
- Set "Consecutive Days" to 10.
- Go back.
- Put the app to background.
- Tap the app icon to bring it foreground.
- App review dialog should appear.

No longer use deprecated store review method.

---

TestPlans/TeacherE2E.xctestplan
TestsFoundation/TestsFoundation/CoreUIElements/Dashboard/Dashboard.swift
TestsFoundation/TestsFoundation/Extensions/XCUIElementExtensions.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSDashboardTest.swift

Add DataSeeder Dashboard Test for Teacher, disable old DashboardE2ETest

---

rn/Teacher/src/modules/inbox/Inbox.js

refs: MBL-15897
test plan: Check if course filter appears in Inbox.

Filter out invalid courses from course filter in Inbox.

---

Parent/Parent.xcodeproj/project.pbxproj
Parent/Parent/Courses/CourseListViewController.swift
Parent/ParentUnitTests/Courses/CourseListCellGradesTests.swift
Parent/ParentUnitTests/Courses/CourseListViewControllerTests.swift

refs: MBL-15828
release note: Fixed dashboard showing course total score instead of current total when between active grading periods.

Fix parent grade display

---

Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift
Core/CoreTests/Dashboard/K5/ViewModel/Grades/K5GradesViewModelTests.swift

refs: MBL-15896
release note: Fixed a grade displaying issue on homeroom's Grades tab.

Use different fields if multiple grading periods are enabled.

---

TestPlans/TeacherE2E.xctestplan
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/DataSeeding/Pages/CreateDSPageRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Pages/DSPage.swift
TestsFoundation/TestsFoundation/DataSeeding/Pages/DataSeeder+DSPage.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSPagesTests.swift

Add DataSeeding support for Pages

---

Core/Core/People/ContextCard/Course/ContextCardSubmissionRow.swift
Student/Student/Routes.swift

refs: MBL-15846
test plan:
- Log in as a student to a course with assignments.
- Go to Course > People > Your Name.
- Submissions should be visible on people page.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/154045822-565fed6b-38ce-4239-a146-4680705b1e36.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/154045831-212a5196-1e68-4b50-b24d-5374dbd26d5c.png"></td>
</tr>
</table>

Show self submissions on people page.

---

TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/Submissions/SubmissionsListPage.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/CreateDSAssignmentRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/DSAssignment.swift
TestsFoundation/TestsFoundation/DataSeeding/Pages/CreateDSPageRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/CreateDSSubmissionRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/DSSubmission.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/DataSeeder+DSSubmission.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSSubmissionsE2ETests.swift

Add DataSeeding Submissions support, test happy path for teacher

---

Core/Core/Profile/SideMenu/SideMenuBottomSection.swift

refs: MBL-15915
release note: Fixed leaving student view would log out the teacher.

Leave student view button logs out teacher as well

---

Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Dashboard/DSDashboardE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/CoreUIElements/EmptyPanda/EmptyPanda.swift

Added DataSeeding Dashboard E2E Tests

---

Core/Core/People/ContextCard/Group/GroupContextCardView.swift
Core/Core/People/PeopleListViewController.swift

Group people page UI glitches

---

Core/Core/Courses/GetCourses.swift
Core/CoreTests/Courses/CourseList/ViewModel/CourseListViewModelTests.swift
Core/CoreTests/Courses/GetCoursesTest.swift
Core/CoreTests/Store/PreviewStoreTests.swift

refs: MBL-15924
release note: Unpublished courses are now hidden.

Unpublished course is visible for student

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Discussions/APIDiscussion.swift
Core/Core/Discussions/DiscussionListViewController.storyboard
Core/Core/Discussions/DiscussionListViewController.swift
Core/Core/Discussions/DiscussionTopic.swift
Core/Core/Discussions/GetDiscussions.swift
Student/StudentUITests/Assignments/AssignmentDetailsTests.swift
Student/Widgets/AnnouncementsWidget/Controller/AnnouncementsProvider.swift
Student/Widgets/AnnouncementsWidget/Model/AnnouncementItem.swift

refs: MBL-15912
release note: Fix discussions are not displaying when anonymous discussions are added.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/158807015-aed13af6-a79f-4d22-b31b-ee0f6d9a7a6d.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/158807019-e1dde4df-5724-4b58-ae7c-606f7e5bf862.png"></td>
</tr>
</table>

Discussion redesign discussion index only shows graded discussions

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Enrollments/Enrollment.swift
Core/Core/Grades/Grade.swift
Core/Core/Grades/GradeListViewController.swift
Core/CoreTests/Grades/GradeListViewControllerTests.swift

refs: MBL-15920
release note: Fixed total grade display for grading periods.

Total grade display is misaligned with web

---

Core/Core/People/ContextCard/Course/ContextCardView.swift
Core/Core/People/ContextCard/Course/ContextCardViewModel.swift
rn/Teacher/ios/Teacher/Routes.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentListCell.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionHeader.swift

refs: MBL-15946
release note: Fixed profile screen top buttons in SpeedGrader comments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/160158638-4aa50fc8-8a6c-4722-9765-8ee29c25a059.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/160158645-ac0ca8e5-a69b-4561-9181-c492e86e2979.png"></td>
</tr>
</table>

Profile screen opened from SpeedGrader comments has no close nor send buttons

---

Student/Student.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj

Code signing method is removed from Teacher and Student targets, use project settings instead

Use inherited code signing methods

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
CanvasCore/CanvasCore.xcodeproj/project.pbxproj
Core/Core.xcodeproj/project.pbxproj
Core/Core/SwiftUIViews/TopBar/View/TopBarItemView.swift
Core/Core/SwiftUIViews/TopBar/View/TopBarView.swift
Core/Core/SwiftUIViews/TopBar/ViewModel/TopBarItemViewModel.swift
Core/Core/SwiftUIViews/TopBar/ViewModel/TopBarViewModel.swift
Core/CoreTests/SwiftUIViews/TopBar/ViewModel/TopBarViewModelTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
scripts/build_automation/bitrise_workflows/tests.yml

refs: MBL-15704
test plan: Project builds with Xcode 13.3. Top menu bar in K5 mode works properly.

Update to Xcode 13.3

---

TestPlans/TeacherE2E.xctestplan
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSContextCardE2ETests.swift
rn/Teacher/ios/TeacherE2ETests/Assignments/DSTodosE2ETests.swift

Added some more DataSeeding based tests, disabled the old ones

---

scripts/build_automation/bitrise_workflows/tests.yml
scripts/swift/RunUITests.swift

refs: MBL-15704
test plan: Nightly tests should start.

Use the latest 15.4 simulator for tests.

---

rn/Teacher/ios/TeacherE2ETests/GradesE2ETests.swift

Fixed grades e2e tests for teacher

---

Core/Core/Courses/CourseDetails/View/CourseDetailsView.swift
Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsHeaderViewModel.swift
Core/Core/Extensions/UITableViewExtensions.swift
Core/CoreTests/Courses/CourseDetails/ViewModel/CourseDetailsHeaderViewModelTests.swift

Share screen is transparent over the submission detail page

---

Core/Core/Login/LoginFindSchoolViewController.swift
Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift

refs: MBL-16004
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/162720748-b324094e-eed9-425f-b95d-151a37295d04.png"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/162720867-044d09b9-9a3e-4e5d-b145-04ea1e1a8fc1.png"></td>
</tr>
</table>

MBL-16004 Add next button to find school view

---

Core/Core/Dashboard/K5/View/Grades/K5GradesView.swift

Improve k5 grading period selector

---

Student/Student/StudentAppDelegate.swift

refs: MBL-15943
release note: Fixed notifications would trigger duplicate navigation to pages.

Fix duplicate announcements for user

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/People/APIUser.swift
Core/Core/Profile/UserProfile.swift
Parent/Parent/ParentAppDelegate.swift
Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-16007
release note: Fixed language won't sync with account settings on the web.
test plan: 
1. log in in the app
2. log in on the web
3. change the language on the web
4. put the app in the background
5. reopen the app
6. the language shouldn't change
7. kill the app
8. reopen the app
9. the app should present the language change popup

Web language selection does not get applied on mobile

---

Student/Student/StudentAppDelegate.swift

refs: MBL-16049
test plan:
- Test is student view works correctly in all scenarios. (Student app running with a user logged in, student app not running, no recent users.)
- Test if profile language change on web still works as per [this PR](https://github.com/instructure/canvas-ios/pull/2152).

Fix student view

---

Core/Core/SwiftUIViews/EmptyPanda.swift

refs: MBL-15972
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/166896411-b7d3a6e6-d2ee-407b-8dd8-c69335202c8b.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/166896423-15929543-74ac-42e1-9a76-5e14ef420684.jpeg"></td>
</tr>
</table>

Hide panda image from voice over, group title and message

---

Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomSubjectCardView.swift
Core/Core/Dashboard/View/CourseCard.swift
Core/Core/Dashboard/View/GroupCard.swift

refs: MBL-16029
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/166957456-5b9536b7-1f20-4e12-af48-d6968f36caf4.png"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/166957773-c7deefa1-972a-4f79-bc73-7728779f391a.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/166957304-f4d27a83-0b00-4e9a-8fcf-ce74674356f1.png"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/166956971-fac92cd0-a884-4991-98cc-fa66b1c6b786.png"></td>
</tr>
</table>

Replaced shadow from dashboard cards

---

Core/Core/Profile/Help/View/HelpItemView.swift
Core/Core/Profile/Help/View/HelpView.swift

refs: MBL-16052
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/167433287-5e6a409e-3119-479c-a413-897fd1c3e387.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/168573571-7dae3299-4b5f-4cdf-912a-a4f93e83391e.png"></td>
</tr>
</table>

Changed cell divider to edge to edge and the selection indicator

---

Core/Core/Assignments/AssignmentList/View/AssignmentCellView.swift

refs: MBL-16053
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/168597569-859f71da-9a7a-4a04-8e1f-79d6fa39374d.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/168597554-94c8fe4d-25a6-4ace-9924-7f1f2c5775a8.jpeg"></td>
</tr>
</table>

Match the selection indicator's style in the assignment list with the course's style

---

Student/StudentE2ETests/Grades/DSGradesE2ETests.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/CreateDSAssignmentRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/DSAssignment.swift
TestsFoundation/TestsFoundation/UITests/E2ETestCase.swift

Extend e2e tests with grade types

---

Core/Core/Grades/GradeListViewController.swift
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Grades/GradeTotalsE2ETests.swift
TestsFoundation/TestsFoundation/CoreUIElements/Assignments/Assignments.swift

refs: MBL-16070
test plan:
Will be extended with grading schemes under https://instructure.atlassian.net/browse/MBL-16088

Add E2E Test for grade totals

---

Core/Core/Discussions/DiscussionDetailsViewController.swift
Core/Core/UIViews/CoreWebView.swift

refs: Student, Teacher
affects: MBL-15806
release note: Fixed LaTeX equations not rendering correctly.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/171412808-400bda7d-2690-45a4-af30-8ee47104c4d9.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/171412848-1c9e6f2c-9454-4233-a34b-686751f687be.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/171412886-1d811169-aab8-4768-a17b-683bdea7e0aa.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/171412911-a2b26ab6-9575-4894-b663-fc55244dc48a.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/171412963-ed40b8da-aaba-4610-a40e-4348d1f02 …

Fix Latex equations

---

Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Grades/DSGradingStandardsE2ETests.swift
Student/StudentE2ETests/Grades/GradeTotalsE2ETests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/DataSeeding/Course/CreateDSCourseRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/UpdateDSCourseRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/CreateDSGradingStandardsRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/DSGradingStandard.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/GradingStandard/DataSeeder+DSGradingStandards.swift

Added E2E Test for Grading Standards

---

CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift
Core/Core/Extensions/UIWindowExtensions.swift

refs: MBL-16124, MBL-16118
test plan: See tickets.

Fix empty screens and parent dark mode switch

---

Core/Core/Assignments/AssignmentList/View/AssignmentCellView.swift

Fix assignment list selection indicator.

---

Core/Core/Profile/Settings/ProfileSettingsViewController.swift
Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift

refs: MBL-16119
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/175309021-92869612-da12-4d61-9c47-6979953a7cf4.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/175309078-52ac9e92-83a5-4235-8f2b-06fb27b33d9d.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/175309113-aa071135-9ea5-4f92-9f6d-4c7deb787b3e.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/175309153-b2ca301a-2651-4429-b999-451e55e68418.png"></td>
</tr>
</table>

Update appearance setting texts.

---

Core/Core/Courses/CourseDetails/ViewModel/Cells/StudentViewCellViewModel.swift
Core/Core/Login/LoginDelegate.swift
Core/Core/People/APIUser.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-16076
release note: Fixed student view for Consortium accounts.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/176706959-fb1a596c-9db4-4246-afb2-98e21507bef1.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/176706957-9852282b-7032-4229-911c-abe2aae802d0.png"></td>
</tr>
</table>

Student view does not work for Consortium accounts

---

Core/Core/People/ContextCard/Course/ContextCardView.swift
Core/Core/UIViews/CircleProgressView.swift

refs: MBL-16121
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/177362116-676fd4ed-e98c-4901-a864-545cbfa3d956.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/177362294-31979903-e0f0-420d-8ae7-086a3ac49ce4.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/177362124-1a19701e-399e-4532-9106-4d166d44e209.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/177362106-ca32db75-e22e-4331-842e-0cd9e7f03323.PNG"></td>
</tr>
</table>

Fix dark mode loading state color mismatch

---

Core/Core/Extensions/NSPersistentContainerExtensions.swift

refs: MBL-16105
release note: Fixed a crash during startup if the device was low on free space.
test plan:
- Fill your device until it runs out of free space.
- Start all apps.
- Apps should start without crashing.
OR
- Check out the branch.
- Setup a simulator with low disk space conditions according to our wiki.
- Build and start all apps from Xcode.
- Apps should start without crashing.

Use in-memory CoreData storage when low on free disk space

---

scripts/build_automation/release.sh

refs: MBL-15741
test plan:
Download the modified release.config from 1password in order to execute the script

Updated release script

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Files/Model/ComposeBatchUpload.swift
Core/Core/Files/Model/FileSubmissionsStatus.swift
Core/Core/Files/Model/FileUploadObservation.swift
Core/Core/Files/Model/UploadManager.swift
Core/Core/Notifications/LocalNotifications.swift
Core/Core/RichContentEditor/RichContentEditorViewController.swift
Core/Core/SubmitAssignmentExtension/Model/AttachmentSubmissionService.swift
Core/CoreTests/Files/UploadManagerTests.swift
TestsFoundation/TestsFoundation/Files/MockUploadManager.swift

refs: MBL-16143
affects: none
test plan: No changes in behaviour just code extraction from UploadManager and API documentation.

Refactor UploadManager

---

Core/Core/Courses/APICourse.swift
Core/CoreTests/Dashboard/Model/CourseSectionStatusTests.swift
Core/CoreTests/Dashboard/ViewModel/Invitations/DashboardInvitationsViewModelTests.swift

refs: MBL-16181
release note: Fix showing public classes with sections.
test plan: Check ticket

Remove deprecated, unused field

---

Parent/Parent/ParentAppDelegate.swift
Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-16187
test plan: check if everything works

remove userID and domain from crashlytics reports

---

CODEOWNERS

Add new code owner

---

Core/Core/Analytics/Analytics.swift
Core/Core/AppEnvironment/CacheManager.swift
Core/Core/Assignments/AssignmentEditor/AssignmentAssigneePicker.swift
Core/Core/Files/Model/FileSubmissionsStatus.swift
TestsFoundation/TestsFoundation/Element/Element.swift
scripts/swift/main.swift

refs: MBL-16197
test plan:
- PR checks/tests should pass

Fix new swiftlint warnings

---

Core/Core/SubmitAssignmentExtension/Model/FilePreviewProvider.swift
Core/Core/SubmitAssignmentExtension/View/AttachmentPreviewView.swift
Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift
Core/Core/SubmitAssignmentExtension/ViewModel/AttachmentPreviewViewModel.swift
Core/Core/SubmitAssignmentExtension/ViewModel/SubmitAssignmentExtensionViewModel.swift

refs: MBL-16201
test plan:
- Share a file with the Student file extension.
- Start typing text in the comment field.
- Text should update without the preview being re-generated.
https://user-images.githubusercontent.com/72396990/184637737-46d51f9e-52d3-4eed-b325-dd51ed3e8393.mov
https://user-images.githubusercontent.com/72396990/184637941-1b590204-1d2d-4b54-998b-2b2912deb89e.mov

Fix blinking preview.

---

scripts/measure_build_times.sh

Add script to measure Student app build times

---

Parent/Parent/ParentAppDelegate.swift
Podfile
Podfile.lock
Student/Student.xcodeproj/project.pbxproj
Student/Student/StudentAppDelegate.swift
Student/SubmitAssignment/SubmitAssignmentViewController.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
rn/Teacher/src/common/CanvasAnalytics.js

refs: MBL-16169
release note: Remove Google Analytics tracking
test plan:

Remove Google Analytics tracking

---

Core/Core/Planner/CreateTodoViewController.swift

refs: MBL-16203
release note: Fix todo item description color in dark mode.
test plan: Check ticket

Add description text color

---

CanvasCore/CanvasCore/Helm/Helm.swift
Core/Core/API/APIError.swift
Core/Core/Assignments/AssignmentEditor/AssignmentAssigneePicker.swift
Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift
Core/Core/Conversations/EditComposeRecipientsViewController.swift
Core/Core/Dashboard/K5/View/Grades/K5GradesView.swift
Core/Core/Files/View/FilePicker/FilePickerViewController.swift
Core/Core/Planner/CalendarViewController.swift
Core/Core/UIViews/CoreWebView.swift
Core/Core/UIViews/LoadingCell.swift
Student/Student.xcodeproj/project.pbxproj
Student/Student/Notifications/ActivityStreamViewController.swift
rn/Teacher/ios/Teacher/SpeedGrader/RubricAssessor.swift
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift

Refact to reduce compile times

---

Core/Core/Files/Model/API/APIFile.swift
Core/Core/Profile/UploadAvatar.swift

refs: MBL-16205
release note: Fix profile picture change
<table>
<tr><th>Before</th><th>After in progress</th><th>After done</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/186862174-e43dd59b-25cc-422f-804a-ad36b93b2472.png" height=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/186862281-1574a5d4-27ce-40f7-8041-4ed479bd8029.png" height=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/186862603-37e07ce9-fd76-4532-9915-98111c9178bb.png" height=500></td>
</tr>
</table>

Fix profile picture change

---

Core/Core/Dashboard/K5/View/Grades/K5GradesView.swift
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Deep Links/DeepLinkE2ETests.swift
Student/StudentE2ETests/K5/K5GradesE2ETests.swift
Student/StudentE2ETests/People/PeopleE2ETests.swift
Student/StudentE2ETests/Quizzes/NewQuizzesE2ETests.swift
Student/StudentUITests/Syllabus/SyllabusTests.swift
TestsFoundation/TestsFoundation/CoreUIElements/K5/K5Grades.swift

Fix some tests. 
refs: MBL-16214
test plan:

Fix some tests

---

Canvas.xcworkspace/contents.xcworkspacedata
Student/Student.xcodeproj/xcshareddata/xcschemes/PRTests.xcscheme
TestPlans/PRTests.xctestplan

Added TestPlan and Scheme for PR tests including all UI tests

---

Student/StudentE2ETests/Announcements/DSAnnouncementsE2ETests.swift
Student/StudentE2ETests/Dashboard/DashboardE2ETests.swift
TestPlans/TeacherE2E.xctestplan
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/DataSeeding/AccountNotifications/CreateDSAccountNotificationRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/AccountNotifications/DSAccountNotification.swift
TestsFoundation/TestsFoundation/DataSeeding/AccountNotifications/DataSeeder+AccountNotification.swift
rn/Teacher/ios/TeacherUITests/Files/FilesUITests.swift

Global Announcements DataSeeding

---

Student/StudentUITests/Inbox/InboxTests.swift
rn/Teacher/src/canvas-api/apis/courses.js

Fix student inbox UI tests

---

Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift

refs: MBL-16316
release note: Fix voice over for add comment text in share extension

Fix voice over for add comment text in share extension

---

Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift

Localized string for add comment field

Use localized string for add comment field

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Core.xcodeproj/project.pbxproj
Core/Core/Analytics/Analytics.swift
Core/Core/AppEnvironment/AppEnvironment.swift
Core/Core/AppEnvironment/Secret.swift
Parent/Parent/ParentAppDelegate.swift
Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

Heap SDK integration

---

Core/Core/SwiftUIViews/ProgressViewStyle/IndeterminateCircleProgressViewStyle.swift

refs: MBL-16377
release note: Fixed floating edit dialog buttons

Fix edit dialog buttons floating around

---

Core/Core/SubmitAssignmentExtension/View/AssignmentPickerView.swift
Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift
Core/Core/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModel.swift
Core/Core/SubmitAssignmentExtension/ViewModel/CoursePickerViewModel.swift
Core/CoreTests/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModelTests.swift
Student/SubmitAssignment/SubmitAssignmentViewController.swift

refs: MBL-16342
release note: Refined share extension VoiceOver 
<table>
<tr><th>Voice Over video</th></tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/110813321/202455564-d146f2d8-f411-4775-9ffc-6f2c42270f12.mov" maxHeight=500></td>
</tr>
</table>

Refine share extension voice over

---

Core/Core/Login/LoginStartViewController.storyboard
Core/Core/Login/LoginStartViewController.swift
Core/CoreTests/Login/LoginStartViewControllerTests.swift
TestPlans/StudentE2E.xctestplan
TestsFoundation/TestsFoundation/Element/LoginStart.swift
TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
TestsFoundation/TestsFoundation/UITests/E2ETestCase.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Assignments/DSTeacherAnnouncementsE2ETests.swift

Teacher's AnnouncementE2ETests reporting indicated a failure within the Student tests, since their class and test names were identical. Fixed the test itself and added support to use previously logged in instance in case of test retry.
refs: MBL-16405
test plan:

Fixed Teacher AnnouncementE2ETests

---

Student/StudentE2ETests/Login/LoginE2ETests.swift

Fix testMDMHost in StudentE2E

---

Core/Core/Submissions/Submission.swift
TestsFoundation/TestsFoundation/DataSeeding/AccountNotifications/CreateDSAccountNotificationRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Assignment/CreateDSAssignmentRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/Tabs/CreateDSTabsRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Discussions/CreateDSDiscussionRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Pages/CreateDSPageRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/CreateDSSubmissionRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/CreateDSGradesRequest.swift

Fix build warnings

---

Student/Student/StudentAppDelegate.swift

refs: MBL-16412
release note: Fixed a crash when changing user

Fix app delegate crash

---

Core/Core/Submissions/Submission.swift
Student/Student/Notifications/ActivityStreamViewController.swift

refs: MBL-16434
release note: Fixed notification screen getting stuck after too many refreh attempts

Fix Notification Freeze

---

Parent/Parent/ParentAppDelegate.swift
Student/Student/StudentAppDelegate.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-16451
test plan:
- Setup production secrets for crashlytics.
- Switch scheme's Run action to build Production config, uncheck debug executable.
- Run the app.
- Switch screens.
- Go to developer menu and tap Force Native Crash.
- Restart the app.
- Locate the app.DSYM file in derived data, zip it.
- Upload it to crashlytics.
- Wait for the crash to be symbolicated.
- Check if crash logs include screen routes.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/210786927-8023a59d-8d2f-4dd9-8514-170fbdbc588a.png" maxHeight=500></td>
</tr>
</table>

Enhance crash reports

---

Podfile
Podfile.lock

refs: MBL-16480
test plan:
- Test annotations in the teacher and student apps.

Update PSPDFKit version

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Core/Dashboard/View/DashboardCardView.swift
Core/Core/Extensions/BundleExtensions.swift
Core/Core/PageViewAnalytics/APIPandata.swift
Core/Core/PageViewAnalytics/PageViewEvent.swift
Core/Core/PageViewAnalytics/PageViewEventController.swift
Core/Core/ScreenViewLogger/ScreenViewTracker.swift
Core/Core/Syllabus/SyllabusTabViewController.swift
Core/CoreTests/PageViewAnalytics/APIPandataTests.swift
Core/CoreTests/PageViewAnalytics/PageViewEventTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
rn/Teacher/ios/Teacher/Attendance/AttendanceViewController.swift
rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift
rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift
rn/Teacher/ios/Teacher/Syllabus/TeacherSyllabusTabViewController.swift
rn/Teacher/ios/Teacher/TeacherAppDelegate.swift

refs: MBL-16511
test plan: API is not ready yet, so check if every screen is tracked that is available on the web

Teacher Pandata tracking

---

Core/Core/SubmitAssignmentExtension/ViewModel/AttachmentPreviewViewModel.swift
Core/Core/SubmitAssignmentExtension/ViewModel/SubmitAssignmentExtensionViewModel.swift
Core/Core/ViewModel/ListSelectionViewModel.swift
Core/CoreTests/Submissions/SubmissionTests.swift

Fix combine memory leaks. Update iOS 15 deprecated properties.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Dashboard/View/DashboardContainerViewController.swift
Core/CoreTests/Extensions/UIBarButtonItemExtensionsTests.swift
Core/CoreTests/Extensions/UIButtonExtensionTests.swift
Student/Student/StudentTabBarController.swift
rn/Teacher/ios/Teacher/TeacherTabBarController.swift

- Rename files for clarity.
- Add test for back button helper method.
refs: MBL-16550
affects: none

Test updates

---

Core/Core/Login/LoginStartViewController.storyboard
Core/Core/Login/LoginStartViewController.swift
Core/CoreTests/Login/LoginStartViewControllerTests.swift

Login refinements, see [Figma](https://www.figma.com/file/ucO95BbZULecZelrkAplKc/02.02-Student-%5BAndroid-iOS-iPadOS%5D?node-id=458%3A0&t=S9KoCjfYQpD7e3of-0) for details. 
<table>
<tr><th>Before - No prev. logins </th><th>After - No prev. logins</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/223127138-f4e3db85-600f-48ab-be3d-9cad510f11e0.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/223127154-66b16a9f-594a-4e2f-bddc-eb7c3c8f7d8d.png" maxHeight=500></td>
</tr>
<tr><th>Before - 1 prev login </th><th>After - 1 prev login</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/223127318-e452e0d6-58ce-4604-8e69-8b96371df3bc.png" maxHeight=500></td>
<td><img …

Login screen refinements

---

Core/Core/Router/Router.swift
Core/CoreTests/Router/RouterTests.swift

refs: MBL-16535
release note: Fixed external urls not opening 3rd party apps but displaying the url's content in a dialog.

Forward external url to system instead of opening in-app browser.

---

Core/Core/CoreWebView/CoreWebView.swift
Core/Core/RichContentEditor/RichContentEditorViewController.swift

refs: MBL-16540
release note: Fixed an issue where image upload was not possible on Pages

Fix pages image upload

---

Core/Core/Login/LoginStartViewController.storyboard

Fix LoginStart animatable logo size

Fix LoginStart animatable logo size

---

Core/Core/UIViews/BottomSheetPickerViewController.swift
Core/Core/UIViews/BottomSheetTransitioning.swift

refs: MBL-16585
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225047523-2c8790d4-fce7-424e-8c5a-45573ce1318f.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225047643-911ed599-07de-4d53-9f9b-0d41795e9fa2.png" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225047743-79f9f976-808f-4cab-8bf5-eb49497082e9.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225047800-de636f36-4069-48c3-999b-79c8542e7e19.png" maxHeight=500></td>
</tr>
</table>

Update picker sheet colors

---

Core/Core/SwiftUIViews/DynamicHeightTextEditor.swift
rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift

refs: MBL-16590
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225089706-251caa55-6470-4e89-b3ad-d6ec1ce2f224.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225584369-7fc9fefb-15dd-4c07-b912-64ee88239044.png" maxHeight=500></td>
</tr>
</table>

Update SpeedGrader send button layout

---

Core/Core/Modules/GetModuleItem.swift
Core/Core/Modules/ModuleItem.swift

refs: MBL-16527
release note: Fixed mastery path disappearing from modules list when opening module details.
test plan: See ticket. Use my test student.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225914506-91f3c378-a22d-46f2-8e1d-f542c05f5487.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225914564-6667e419-77c8-4e45-a03e-7f8e531d9418.png" maxHeight=500></td>
</tr>
</table>

Fix mastery path item being deleted by assignment details screen

---

Brewfile
README.md

Updated the README file with findings when setting up the project on a brand new machine.

Refined README

---

CanvasCore/CanvasCore/Helm/HelmViewController.swift

refs: MBL-16586
release note: Fixed QuizDetails navigation bar color
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/227216731-79620d14-0a06-421d-9441-bd5443ab1c76.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/227216778-2d0e4930-90af-4f2c-9a92-d069c9933b68.png" maxHeight=500></td>
</tr>
</table>

Fix QuizDetails nav bar color

---

Core/Core/Files/Model/UploadManager.swift

Fix folder path not getting forwarded to upload request method.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Extensions/BundleExtensions.swift
Core/Core/NetworkAvailability/NWAvailabilityService.swift
Core/Core/NetworkAvailability/NWAvailabilityStatus.swift
Core/Core/NetworkAvailability/NWPathMonitorWrapper.swift
Core/Core/Profile/SideMenu/SideMenuBottomSection.swift
Core/Core/Profile/SideMenu/SideMenuDeveloperOptionsSection.swift
Core/CoreTests/NetworkAvailability/NWAvailabilityServiceTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

refs: MBL-16602
test plan: 
1. Create an NWAvailabilityServiceLive instance in StudentAppDelegate
2. Call the startMonitoring function
3. Check the instance's status

NetworkAvailabilityService component

---

Core/Core/UIViews/HorizontalMenuViewController.swift
Parent/Parent/Courses/CourseDetailsViewController.swift

Disable bounce effect to work around gesture recogniser interference

---

Parent/Parent/Conversations/ParentConversationListViewController.swift

refs: MBL-16615
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/228763983-e696ae4b-4efe-441e-a212-26d5b9a76a25.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/228764030-16f569bc-9dac-45b7-b975-77213baeb000.png" maxHeight=500></td>
</tr>
</table>

Remove tableview's native refresh control.

---

Core/Core/Conversations/ConversationDetailViewController.swift
Parent/Parent/Assignments/AssignmentDetailsViewController.swift
Parent/Parent/Conversations/ParentConversationListViewController.swift
Parent/Parent/Courses/CourseDetailsViewController.swift

New message dialog easily dismissible by accident

---

Core/Core/Conversations/ConversationDetailCell.swift
Parent/Parent/Routes.swift

Inbox links open in external browser

---

Parent/Parent/Dashboard/DashboardViewController.swift
Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift

Navigation bar color mismatch

---

Core/Core/Conversations/ConversationDetailViewController.swift
Parent/Parent/Assignments/AssignmentDetailsViewController.swift
Parent/Parent/Conversations/ParentConversationListViewController.swift
Parent/Parent/Courses/CourseDetailsViewController.swift

Send button background color contrast mismatch

---

package.json
rn/Teacher/package.json
rn/Teacher/yarn.lock
scripts/build_automation/bitrise_workflows/tests.yml
yarn.lock

Update danger to its latest version to make test failure reporting in PRs working.
refs: MBL-16645
affects: none
test plan:

CI Updates

---

rn/Teacher/src/canvas-api/index.js

Remove no longer existing but otherwise unused import.
refs: MBL-16645
affects: Teacher, Student, Parent
test plan:

Fix adhoc builds not working on CI

---

rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDatesEditor.test.js.snap
rn/Teacher/src/modules/assignment-details/components/__tests__/__snapshots__/AssignmentDates.test.js.snap
rn/Teacher/src/modules/assignment-details/components/__tests__/__snapshots__/AssignmentDatesEditor.test.js.snap
rn/Teacher/src/modules/assignment-due-dates/__tests__/__snapshots__/AssignmentDueDates.test.js.snap
rn/Teacher/src/modules/quizzes/details/__tests__/__snapshots__/QuizDetails.test.js.snap
rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap

refs: MBL-16645
affects: Teacher, Student, Parent
test plan:

Use simple space instead of non-breaking space in react snapshots.

---

CanvasCore/CanvasCore/ReactNativeModules/NativeAccessibility.m

Investigate crash [NativeAccessibility subviewWithIdentifier:]

---

Core/Core/Assignments/AssignmentList/View/AssignmentGroupView.swift
Core/Core/Assignments/AssignmentList/View/AssignmentListView.swift
Core/Core/Inbox/View/InboxView.swift
Core/Core/SwiftUIViews/SearchBar.swift

Update background colors.
refs: MBL-16622
test plan: See ticket. Check the screens from the screenshots section.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/230339747-ed346e5e-3c2f-484c-b712-f4d5748a4c63.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/230339795-30c7b601-5226-4f94-96e1-c249e29ebf50.png" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/230339884-45125b25-9f66-4c97-94c9-b86e86e88a8a.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/230339954-2f2efcaa-2ab4-4497-a2d4-99b3586b661b.png" maxHeight=500></td>
</tr>
<tr>
<td><img …

Update list background safe area color

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/AppEnvironment/ExperimentalFeature.swift
Core/Core/NetworkAvailability/NetworkAvailabilityService.swift
Core/Core/NetworkAvailability/NetworkAvailabilityStatus.swift
Core/Core/Offline/OfflineService.swift
Core/Core/Profile/SideMenu/SideMenuDeveloperOptionsSection.swift
Core/Core/Store/Store.swift
Core/CoreTests/NetworkAvailability/NetworkAvailabilityServiceTests.swift
Core/CoreTests/Store/StoreTests.swift
Parent/Parent/Dashboard/DashboardViewController.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

refs: MBL-16603
test plan:
1. I'd suggest a clean install of the app 
2. Have Wifi or Cellular internet enabled 
3. Launch the app
4. Open a Course
5. Open Developer Options and enable `offline_mode` Experimental Feature
6. Turn off internet
7. Try to refresh the dashboard, open the same course, refresh the course details

Network availability aware Store

---

Parent/ParentE2ETests/DSLoginE2ETests.swift
Student/StudentE2ETests/Login/DSLoginE2ETests.swift
TestsFoundation/TestsFoundation/Element/Element.swift
TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
TestsFoundation/TestsFoundation/UITests/E2ETestCase.swift
rn/Teacher/ios/TeacherE2ETests/DSLoginE2ETests.swift

- upgraded tapUntil to be parametrisable (retries)
- created pullToRefreshUntil
- upgraded logInDSUser method with lastLoginButton logic

Implement helper functions for e2e tests

---

package.json
yarn.lock

CI fix - danger version bump

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncAssignmentsInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncAssignmentsInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

Builds upon the [container](https://github.com/instructure/canvas-ios/pull/2443) interactor and adds logic for downloading assignments. 
Test plan: 
1. Have internet on 
2. Enable `offline_mode` feature flag
3. Open Course Sync menu 
4. Select Pages and Assignments for download.
5. Turn off internet 
6. Open course, go to pages 
7. You should see a list of pages and assignments

Course Sync Assignments Interactor

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift
Core/Core/Assignments/AssignmentList/View/AssignmentListView.swift
rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/QuizSubmissionListInteractor.swift
rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/QuizSubmissionListInteractorLive.swift
rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/QuizSubmissionListInteractorPreview.swift
rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/View/QuizSubmissionListView.swift
rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/ViewModel/QuizSubmissionListViewModel.swift
rn/Teacher/ios/TeacherTests/Submissions/QuizSubmissionList/QuizSubmissionViewModelTests.swift

refs: MBL-16819
test plan: Test teacher app for pandata events

Add missing Teacher Pandata events

---

rn/Teacher/src/common/inst-colors.js
scripts/build-colors.js

Login screen buttons should work on master build on iPad.

Fix inst color typos

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/ViewModifiers/Hidden.swift

refs: MBL-16839
release note: Fixed quiz assignment detail page role handling.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/e5488228-be1b-4486-9358-2b6db552e371" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/2f814c92-92fa-4c3e-b360-87bf0e55f40b" maxHeight=500></td>
</tr>
</table>

Students able to take New Quizzes in Teacher app which are locked by date

---

Core/Core/Extensions/UITabBarExtensions.swift

refs: MBL-16847
release note: Fixed bottom tab bar text alignment.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/d0ac2b90-5d8c-4202-b582-fb9340d1b1dc" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/f89c0edd-f4aa-43ef-a50f-f3b5ad4f1242" maxHeight=500></td>
</tr>
</table>

Rotating the device back and forth creates a truncated menu item

---

Core/Core/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift

Remove unnecessary init.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncSelector/CourseSyncSelectorAssembly.swift
Core/Core/Dashboard/Container/ViewModel/DashboardContainerViewModel.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift

- Move sync interactors into an array and extract creation to an assembly.
- Use zip to merge as many sync interactors as needed.

Improve CourseSyncInteractorLive creation

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncSyllabusInteractor.swift
Core/Core/Courses/CourseDetails/Model/TabFilter.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncSyllabusInteractorLiveTests.swift

refs: MBL-16767
test plan:
- Sync the syllabus tab for offline usage.
- Turn off internet on the device.
- Go to syllabus page.
- Syllabus html content should display along with any assignments if syllabus summary is enabled.

Add syllabus downloader

---

Core/Core/PageViewAnalytics/Persistency.swift
Core/CoreTests/PageViewAnalytics/PersistencyTests.swift

refs: MBL-16867
release note: Fixed a silent crash that occurred while processing data
test plan: See more below
1. Open a few screens. 
2. Close the app
3. Open the app

Fix PageViewEvent persistency crash

---

Core/Core/Courses/APICourse.swift
Core/Core/Courses/Course.swift
Core/Core/Dashboard/Container/View/DashboardContainerView.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncSyllabusInteractorLiveTests.swift
Core/CoreTests/Courses/APICourseTests.swift

- Extended already existing course settings entity with the new feature flag.
- Added course settings include to course fetch calls.
- Connect course and course settings coredata entities.
- Tested that both Parent and Student apps fetch course settings on dashboard.
refs: MBL-16908

Add feature flag for letter grade

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/Common/Models/CourseSyncEntryComposerInteractor.swift
Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift
Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntryFile.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncFilesInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/Extensions/FileManagerExtensions.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncEntryComposerInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncFilesInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/Model/Entities/CourseSyncItemSelectionTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/Model/Entities/CourseSyncSelectorEntryTests.swift

refs: MBL-16808
test: 
Unchanged file:
1. Sync a file
2. Sync the same file again  - Download shouldn't happen 
Changed file: 
1. Sync a file
2. Log in as teacher on web, rename this file
3. Sync the same file again - It should be downloaded

Offline file version control

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift

refs: MBL-16949
release note: Fixed a crash that triggered when an assignment or quiz that was part of a module was opened.
test plan:
- See ticket for repro steps.
- Also test if the teacher app denies the edit action on the assignment details screen when logged in with a student.

Use safe bar button items

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Courses/Course.swift
Core/CoreTests/Courses/CourseSettingsTests.swift

refs: MBL-16987
test plan: testSyllabusOfCourse E2E test should pass.

Update course settings save logic not to overwrite DB with empty data

---

Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorPreview.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelTests.swift

Computer! I need a student build to test if cancelling still works.

Add syncronous cancel method to CourseSyncInteractor

---

Student/StudentE2ETests/Dashboard/DashboardTests.swift
TestsFoundation/TestsFoundation/Helpers/DashboardHelper.swift
TestsFoundation/TestsFoundation/Helpers/GradesHelper.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/ToDo/ToDoTests.swift

[Bitrise - Canvas iOS - Student - E2ETests](https://app.bitrise.io/build/1f4e1374-6234-4a6f-91e3-d99c41faec69)
[Bitrise - Canvas iOS - Teacher - E2ETests](https://app.bitrise.io/build/35a15b47-e1f4-4a98-91da-89a1c53e2c5b)
- ToDoTests
- Fix for failing Student tests

Teacher - ToDo Tests

---

Core/Core/Dashboard/K5/Model/ImportantDates/K5ImportantDateItem.swift

refs: MBL-17075
release note: Fixed Important dates duplication in elementary view.
test plan:
See ticket
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72031065/f1952663-2158-43f4-b861-d61ec044b099" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72031065/26ead83d-f72b-469d-93fb-ad2d3b094d54" maxHeight=500></td>
</tr>
</table>

Fix Important dates multiplication

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/BackgroundActivity/BackgroundActivity.swift
Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractor.swift
Core/Core/Files/FileSubmission/Model/FileSubmissionAssembly.swift
Core/Core/Files/FileSubmission/Model/FileSubmissionBackgroundTerminationHandler.swift
Core/CoreTests/BackgroundActivity/BackgroundActivityMock.swift
Core/CoreTests/BackgroundActivity/BackgroundActivityTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractorLiveTests.swift
Core/CoreTests/Files/FileSubmission/Model/FileSubmissionBackgroundTerminationHandlerTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

refs: MBL-16723
test plan:
- Start an offline sync.
- Put the app into the background.
- If the sync finishes in a reasonable time (OS dependent) you should receive the success notification.
- In case the background activity is interrupted you won't see any notifications.
- Opening the app in this case should display the sync failed banner on the dashboard.
- Opening the sync progress screen should display either completed or failed states.

Background sync

---

Student/StudentE2ETests/Offline/OfflineTests.swift
TestsFoundation/TestsFoundation/Extensions/XCUIElementExtensions.swift
TestsFoundation/TestsFoundation/Helpers/DashboardHelper.swift
TestsFoundation/TestsFoundation/Helpers/K5Helper.swift
TestsFoundation/TestsFoundation/Helpers/ThirdPartyApp/SafariAppHelper.swift
rn/Teacher/ios/TeacherE2ETests/Files/FilesTests.swift

[Bitrise - Canvas iOS - Student - E2ETests](https://app.bitrise.io/build/6f695773-cab3-41be-9dbd-429677aba925)
[Bitrise - Canvas iOS - Teacher - E2ETests](https://app.bitrise.io/build/810117e9-09e0-4a3d-94ed-30b660921877)
- New test case for Offline, covering MBL-17063
- Fix tests failing with XCode15

New test for Offline feature, Fix tests failing with XCode15

---

Core/Core/Dashboard/Invitations/View/CourseInvitationCard.swift
Makefile

CI: Give me a Student and a Teacher build, please!
<table>
<tr>
<td><video src="https://github.com/instructure/canvas-ios/assets/72396990/7f634eeb-6d26-41c7-a159-7871ddf27e45"/></td>
<td><video src="https://github.com/instructure/canvas-ios/assets/72396990/61636ad6-5d66-4722-a9f2-54bf92488c73"/></td>
</tr>
</table>

Fix course invite action animation. Add make pod command to work around code signing issues.

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractor.swift
Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorPreview.swift
Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift
Core/CoreTests/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelItemTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

refs: MBL-17135
test plan: Check dialog message
<table>
<tr><th>Before</th>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/afa4a149-506b-419c-8e8c-782f69940238" width=300></td>
</tr>
</table>

Offline sync selector dialog text

---

Parent/Parent.xcodeproj/project.pbxproj
Podfile
Podfile.lock
Student/Student.xcodeproj/project.pbxproj
Student/StudentE2ETests/Offline/OfflineTests.swift
rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
rn/Teacher/ios/TeacherE2ETests/Inbox/InboxTests.swift
rn/Teacher/ios/TeacherE2ETests/People/PeopleTests.swift

Check if debug console commands work.
Computer! I need Student, Teacher and Parent builds.

Move PSPDFKit from cocoapods to swiftpm

---

Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift
Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncModulesInteractor.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncModulesInteractorLiveTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

refs: MBL-17137
test plan: 
1. Login as tamaskozmer 
2. Sync course "course with no tabs" 
3. Check if module subitems are downloaded 
4. Check an other account/regular course if everything still works.

Module list item download

---

Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift

test plan: Check if sync size still correctly appears when syncing offline content.

Update localizable string

---

Core/Core/CoreWebView/View/CoreWebView.swift
Core/Core/CourseSync/CourseSyncSettings/View/CourseSyncSettingsView.swift
Core/Core/CourseSync/CourseSyncSettings/ViewModel/CourseSyncSettingsViewModel.swift
Core/Core/RichContentEditor/RichContentEditorViewController.swift
Core/Core/ViewModel/ListSelectionViewModel.swift
Core/Core/ViewModel/SplitViewModeObserver.swift
Core/CoreTests/CourseSync/CourseSyncSettings/ViewModel/CourseSyncSettingsViewModelTests.swift

refs: MBL-16557
test plan:
- Test webviews including the Switch To Dark Mode button
- Test if RCE editor works
- Test if list selection indicator appears on course details when going from portrait mode to landscape

Fix memory leaks

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CourseSync/Common/Models/CourseSyncListerInteractor.swift
Core/Core/CourseSync/Common/Models/Entities/CDCourseSyncDownloadProgress.swift
Core/Core/CourseSync/Common/Models/Entities/CourseSyncDownloadProgress.swift
Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift
Core/Core/CourseSync/Common/Models/Entities/CourseSyncListFilter.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift
Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractor.swift
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift
Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractorPreview.swift
Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractor.swift
Core/Core/CourseSync/CourseSyncSelector/Model/UseCase/GetCourseSyncSelectorCourses.swift
Core/Core/Dashboard/OfflineSync/Model/DashboardOfflineSyncInteractorPreview.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/CourseSync/Common/CDCourseSyncDownloadProgressTests.swift
Core/CoreTests/CourseSync/Common/CourseSyncListInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncNotificationInteractorTests.swift
Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractorLiveTests.swift
Core/CoreTests/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorLiveTests.swift
Core/CoreTests/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModelTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj

Course sync progress screen fixes
refs: MBL-17178

Course sync progress screen fix

---

Core/Core/AppEnvironment/FeatureFlags/FeatureFlag.swift
Core/Core/AppEnvironment/FeatureFlags/GetEnabledFeatureFlags.swift
Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModelLive.swift
Core/CoreTests/AppEnvironment/FeatureFlags/FeatureFlagTests.swift
Core/CoreTests/AppEnvironment/FeatureFlags/GetEnabledFeatureFlagsTests.swift

refs: MBL-16516
test plan: Check if the discussion redesign feature flag still works correctly after the refactor.

Add feature flag constant for assignment enhancements. Refactor helper methods.

---

Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift

Fix course sync modules file selection

---

rn/Teacher/ios/Teacher/SpeedGrader/ViewModel/SubmissionCommentLibraryViewModel.swift

- Move Published state modification to main thread.
- Fix edge cases where continuation was not resumed.
refs: MBL-17239
release note: Fixed a crash affecting comment library.
test plan: Check if force refresh on comment library works.

Fix comment library crash

---

rn/Teacher/ios/Teacher/Localizable.xcstrings
rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift

CI: Build the Teacher app, please.

Fix teacher translations

---

Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.storyboard
Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift
Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.storyboard
Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.swift

refs: MBL-17218
release note: Fixed an issue with loading indicator on module sequence screen.

Fix double loading indicator on module sequence

---

Student/StudentE2ETests/Assignments/AssignmentsTests.swift
Student/StudentE2ETests/Settings/SettingsTests.swift
TestsFoundation/TestsFoundation/Helpers/AssignmentsHelper.swift
rn/Teacher/ios/TeacherE2ETests/Settings/SettingsTests.swift

refs: MBL-17270
affects: None
[Student test run](https://app.bitrise.io/build/c7afbbb0-2a9e-4cf1-80e3-3e6d60911b8f)
[Teacher test run](https://app.bitrise.io/build/cc5f5505-e3c8-4d97-a495-1f9159e06593)

Automation - Fix for failing E2E tests

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/CoreWebView/Model/Features/ForceDisableHorizontalScroll.swift
Core/Core/EmbeddedWebPage/View/EmbeddedWebPageView.swift
Core/CoreTests/CoreWebView/Model/Features/ForceDisableHorizontalScrollTests.swift

refs: MBL-17317
test plan: Hybrid discussion page shouldn't bounce horizontally.

Disable horizontal bouncing of hybrid discussion page

---

Student/StudentE2ETests/Profile/ProfileTests.swift
TestsFoundation/TestsFoundation/DataSeeding/User/CreateDSUserRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/User/DataSeeder+DSUser.swift
TestsFoundation/TestsFoundation/Helpers/ProfileHelper.swift

Student - New Profile E2E tests for profile picture change and short name

---

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentCellViewModel.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift

Fix how hybrid discussions are handled in the Teacher app

---

CODEOWNERS
Student/Student.xcodeproj/project.pbxproj
Student/Student.xcodeproj/xcshareddata/xcschemes/Student.xcscheme
Student/Student/student.yml
Student/SubmitAssignment/student-submit-assignment.yml
Student/Widgets/student-widgets.yml

- Update codeowners.
- Fix Student targets not extracting strings to string catalog.
- Fix student test action not generating code coverage data.
- Removed CoreTester from Student test action as this isn't a testable target.

Project fixes

---

Student/Student.xcodeproj/xcshareddata/xcschemes/E2ETests-Student.xcscheme
Student/StudentE2ETests/CourseDetails/CourseDetailsTests.swift
Student/StudentE2ETests/Syllabus/SyllabusTests.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/CreateDSCourseRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/DSCourse.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/DataSeeder+DSCourse.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/UpdateDSCourseRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Course/UpdateDSCourseSettingsRequest.swift

- testCourseHomeDefaultView: checks if the correct view is displayed when tapping home on course details view depending on different default_view settings
- testCourseSummaryDisabled: checks if tabs are not displayed on the syllabus view when syllabus_course_summary is set to false for the course

Student - New E2E tests for Syllabus and CourseDetails

---

Parent/ParentE2ETests/Help/HelpTests.swift
Student/StudentE2ETests/Assignments/AssignmentsTests.swift
Student/StudentE2ETests/Help/HelpTests.swift
TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
TestsFoundation/TestsFoundation/DataSeeding/Assignment/CreateDSAssignmentRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Rubric/CreateDSRubricRequest.swift
TestsFoundation/TestsFoundation/DataSeeding/Rubric/DSRubric.swift
TestsFoundation/TestsFoundation/DataSeeding/Rubric/DataSeeder+DSRubric.swift
TestsFoundation/TestsFoundation/DataSeeding/Submissions/Grades/CreateDSGradesRequest.swift
TestsFoundation/TestsFoundation/Extensions/XCUIElementExtensions.swift
TestsFoundation/TestsFoundation/Helpers/AssignmentsHelper.swift
TestsFoundation/TestsFoundation/Helpers/GradesHelper.swift
rn/Teacher/ios/TeacherE2ETests/Help/HelpTests.swift

- testLockedAssignment
- testFutureAssignment
- testExcusedStatus
- testAttemptSelectorAndSubmissionAndRubricScreen
- The URL for "Search the Canvas Guides" button in Help screen has changed lately and caused test failures

Student - New E2E tests for Assignments

---

Student/StudentE2ETests/People/PeopleTests.swift
TestsFoundation/TestsFoundation/Helpers/InboxHelper.swift
TestsFoundation/TestsFoundation/Helpers/PeopleHelper.swift

1. Creates a course, and different type of users with DataSeeder (Student, Teacher, Observer)
2. Logs in with Student
3. Navigates to People screen
4. Checks the number of visible people (Observers should not be visible)
5. Filters for Students
6. Checks the list
7. Filters for Teachers
8. Checks the list
9. Filters for Observers
10. Checks the list (no people should be visible)
1. Creates a course, a Student and a Teacher user with DataSeeder
2. Logs in with Student
3. Navigates to People screen
4. Filters for Teachers
5. Taps on Teacher
6. Taps on Send Email icon
7. Checks recipient and other fields of the message composer view
8. Sets the subject and the message body
9. Tap send button
10. Navigates to Inbox tab and checks the Sent tab for the recently sent message

Student - New E2E tests for People screen

---

CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift
Core/Core/Extensions/UIViewControllerExtensions.swift
Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift
Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.swift
Core/Core/Modules/ModuleList/ModuleListViewController.swift
Core/Core/Pages/PageDetails/PageDetailsViewController.swift
Core/Core/UIViews/PagesViewController.swift

refs: [MBL-17401](https://instructure.atlassian.net/browse/MBL-17401)
release note: Fix Navigation title disappearing when rotated, backgrounded or fullscreened
test plan: Please see ticket for details.
[MBL-17401]: https://instructure.atlassian.net/browse/MBL-17401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Navigation title disappearing when rotated, backgrounded or fullscreened

---

Parent/ParentE2ETests/Grades/GradesTests.swift
Student/StudentE2ETests/Assignments/AssignmentsTests.swift
Student/StudentE2ETests/Calendar/CalendarTests.swift
Student/StudentE2ETests/Offline/ContentSyncTests.swift

- Updated testViewAssignmentAndDetails test case of AssignmentTests to check "Submission & Rubric" button before having any submission available.
- Possible fix for flaky tests on Bitrise (we'll see how it goes).

Automation - Assignments tests update and maintenance

---

Core/Core/CoreWebView/View/CoreWebView.swift
Core/CoreTests/CoreWebView/View/CoreWebViewThemeSwitcherTests.swift

refs: [MBL-17383](https://instructure.atlassian.net/browse/MBL-17383)
affects: none
[MBL-17383]: https://instructure.atlassian.net/browse/MBL-17383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add CoreWebViewThemeSwitcher tests

---

Core/Core/Grades/View/GradeListView.swift

Disable swipe action when What-if is disabled

---

Core/Core/API/APIRequestable.swift
Core/CoreTests/API/APIRequestableTests.swift
Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift

refs: MBL-17413
release note: Fixed an issue where File Upload was not possible when using Student View. Fixed act as user not loading the impersonated user's dashboard.

Fix ActAsUser param not being added

---

Core/TestsFoundation/Helpers/AssignmentsHelper.swift
Student/Student/Assignments/AssignmentDetails/Reminders/View/AssignmentReminderDatePickerView.swift
Student/Student/Assignments/AssignmentDetails/Reminders/View/AssignmentRemindersView.swift
Student/StudentE2ETests/Assignments/AssigmentReminderTests.swift
TestPlans/IPadStudentTests.xctestplan

refs: MBL-17405
- testAssignmentReminder - Checks UI elements and happy path with a 5 minute reminder
- testAssignmentReminderWithCustomDate - Checks custom date picker functionality
- testRemoveAssignmentReminder - Checks the removal process
- testDuplicatedAssignmentReminder - Checks the warning message when the user tries to set the same assignment reminder twice

Student - Automation - Assignment Reminder Tests

---

scripts/release-notes-list.sh

Add script to list changes between a tag and master

---

rn/Teacher/ios/TeacherE2ETests/Assignments/AssignmentsTests.swift
rn/Teacher/ios/TeacherE2ETests/Pages/PagesTests.swift

Fix for 2 Teacher E2E tests that started failing because of the latest merge with the Student tests

Automation | Maintenance

---

Core/Core/Assets.xcassets/icons/chevronDown.imageset/Contents.json
Core/Core/Assets.xcassets/icons/chevronDown.imageset/chevron-down.svg
Core/Core/Extensions/DateExtensions.swift
Core/Core/Extensions/InstIconExtensions.swift
Core/Core/Planner/Model/API/APIPlannable.swift
Core/Core/Planner/Model/CoreData/Plannable.swift
Core/Core/Planner/Model/UseCase/GetPlannables.swift
Core/Core/Planner/ToDoDetails/View/ToDoDetailsScreen.swift
Core/Core/Planner/View/CalendarDaysViewController.swift
Core/Core/Planner/View/CalendarViewController.storyboard
Core/Core/Planner/View/CalendarViewController.swift
Core/Core/Planner/View/PlannerListViewController.storyboard
Core/Core/Planner/View/PlannerListViewController.swift
Core/Core/Planner/View/PlannerViewController.swift
Core/CoreTests/Extensions/DateExtensionsTests.swift
Core/CoreTests/Planner/Model/API/APIPlannableTests.swift
Core/CoreTests/Planner/View/CalendarDaysViewControllerTests.swift
Core/CoreTests/Planner/View/CalendarViewControllerTests.swift
Core/TestsFoundation/Fixtures/Model/PlannableFixture.swift

refs: [MBL-17286](https://instructure.atlassian.net/browse/MBL-17286)
- Changed Today button icon & added day text
- Adjusted Year label font & spacing
- Adjusted Month button font & spacing
- Changed dropdown icon to chevronDown
- Adjusted Calendars button font
- Fixed Calendars button alignment to not jump around when month is changing
- Adjusted Weekday labels font & fixed automatic resizing
- Adjusted Day button font
- Changed Day button selected/today styles to match new design
- Fixed clipping issues after rotation
- Added bottom divider to last Event
- Adjusted Event cell spacings
- Added "To Do" text after course name for ToDos
- Added calendar color for ToDos in list
- Added calendar color to the left side of selected Event and …

Facelift main calendar UI

---

Core/TestsFoundation/DataSeeding/Course/DSCourse.swift
Core/TestsFoundation/DataSeeding/Course/DataSeeder+DSCourse.swift
Core/TestsFoundation/DataSeeding/User/DataSeeder+DSUser.swift
Core/TestsFoundation/Helpers/CalendarHelper.swift
Core/TestsFoundation/Helpers/LTIHelper.swift
Student/StudentE2ETests/Calendar/CalendarTests.swift
Student/StudentE2ETests/LTI/StudioTests.swift
Student/StudentE2ETests/Quizzes/QuizzesTests.swift

- New test case for checking Studio availability and embedded video in a page.
- Some maintenance stuff here and there to fix tests that have been failing lately due to recent changes in the app.

Student - Studio LTI tests and maintenance

---

Core/Core/Modules/ModuleList/Model/ModulePublishItem.swift
Core/Core/Modules/ModuleList/ModuleListViewController.swift
Core/Core/Modules/ModuleList/View/ModulePublishProgressView.swift
Core/Core/Modules/ModuleList/ViewModel/ModulePublishMenu.swift
Core/TestsFoundation/Helpers/ModulesHelper.swift
rn/Teacher/ios/TeacherE2ETests/Modules/ModulesTests.swift

refs: MBL-17306
- testBulkPublishAllModulesAndItems
- testBulkPublishModulesOnly
- testBulkUnpublishModulesAndItems
- added accessibility identifiers for some elements for easier testing

Teacher - E2E tests for Bulk Publish feature

---

Core/TestsFoundation/Helpers/CommandLineHelper.swift
Core/TestsFoundation/UITests/E2ETestCase.swift
package.json
scripts/terminal-server/server.js
scripts/terminal-server/start.sh
yarn.lock

- yarn will now wait until the terminal server have started.
- yarn will now fail if the terminal server failed to start.
- E2E tests now will fail in case the terminal server is not running or an invalid response was received.

Fix terminal connection waiting forever

---

Core/Core/People/ContextCard/Course/ContextCardHeaderView.swift
Core/Core/People/ContextCard/Group/GroupContextCardView.swift

refs: MBL-17699
release note: Pronouns have been added to People details screen
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/72715c2f-7e32-46d4-b7da-5ba05011c8c0" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/afe0e7c4-b7bb-4c71-aa71-2f352e0f4900" maxHeight=500></td>
</tr>
</table>

Add pronouns to PeopleDetails Screen

---

Core/Core/Dashboard/CourseCardList/Model/DashboardCourseCardListInteractorLive.swift

refs: MBL-17487
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/6efe313b-4ba6-4e2d-9eb4-93646142a986" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/53480952/7a8abfac-7ec8-46ae-be09-768314a6e2d0" maxHeight=500></td>
</tr>
</table>

Fix Empty state on Dashboard screen

---

Core/Core/InstUI/Views/NavigationBarButton.swift
Core/TestsFoundation/Helpers/CalendarHelper.swift
Student/StudentE2ETests/Calendar/CalendarTests.swift
Student/StudentE2ETests/Dashboard/DashboardTests.swift
rn/Teacher/ios/TeacherE2ETests/Dashboard/DashboardTests.swift

Fix - Student/Teacher - DashboardTests
Add - Student - DeleteTodo test in CalendarTests
refs: MBL-17763
affects: None

Automation - Fix DashboardTests, Add DeleteTodo test in CalendarTests

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Todos/APITodo.swift
Core/Core/Todos/Todo.swift
Core/Core/Todos/TodoListViewController.swift
Core/CoreTests/Todos/APITodoTests.swift
Core/CoreTests/Todos/TodoListViewControllerTests.swift

Include ungraded quizzes and surveys in ToDos screen.
refs: MBL-17750
release note: Ungraded quizzes and surveys now show up in ToDo.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/8a861ee2-1d47-4de1-8917-620e5cfc94c7" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/ee6c0170-a481-4ff5-ad36-0df731d10ecc" maxHeight=500></td>
</tr>
</table>

Fix ungraded surveys not being shown in todo list

---

Core/CoreTests/Store/UseCaseTests.swift
Core/CoreTests/Syllabus/SyllabusSummaryViewControllerTests.swift

Increase timeouts. Wait for tableview refresh.

Stabilize some tests.

---

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Inbox/Model/Entities/InboxMessageListItem.swift

Set InboxMessageListItem dateRaw optional

---

Core/Core/Extensions/InstIconExtensions.swift
scripts/build_automation/bitrise_workflows/tests.yml
scripts/swift/ExportCoverage.swift
scripts/swift/SuggestLintFix.swift

Remove yarn lint from danger-yarn

---

Core/Core/AppEnvironment/ExperimentalFeature.swift
Core/Core/Planner/CalendarEvent/View/CalendarEventDetailsScreen.swift
Core/Core/Planner/CalendarMain/PlannerViewController.swift
Core/CoreTests/Planner/CalendarMain/PlannerViewControllerTests.swift

refs: [MBL-17878](https://instructure.atlassian.net/browse/MBL-17878)
release note: Calendar events can now be created, updated and deleted.
- Verify Add button on the Calendar screen opens menu with "Add To Do" and "Add Event" options
- Verify creating, updating and deleting events
[MBL-17878]: https://instructure.atlassian.net/browse/MBL-17878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove ModifyCalendarEvent FF

---

Core/TestsFoundation/Helpers/CalendarHelper.swift
Parent/ParentE2ETests/Help/HelpTests.swift
Student/StudentE2ETests/Calendar/CalendarTests.swift
Student/StudentE2ETests/Help/HelpTests.swift
Teacher/TeacherE2ETests/Help/HelpTests.swift

affects: None
- Updated Student Calendar tests regarding latest changes
- Updated Help tests in all apps (Covid19 menu item has been removed from Help page)

Automation - E2E Maintenance

---

Core/Core/Planner/CalendarMain/PlannerListViewController.swift

refs: [MBL-17946](https://instructure.atlassian.net/browse/MBL-17946)
release note: Fixed issues on calendar event screen.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/3425445e-be8e-4acf-9080-b39a9449a02a" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/454f2b36-a2d6-4619-8a3e-2f59c6a5fac9" maxHeight=500></td>
</tr>
</table>
[MBL-17946]: https://instructure.atlassian.net/browse/MBL-17946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix wrong CalendarEventDetails screen showing in Parent app

---

Core/Core/InstUI/Views/Cells/DatePickerCell.swift

refs: _
affects: Student,Teacher
release note: Fixed a glitch with date picker used in calendar event and todo forms.
https://github.com/user-attachments/assets/062d9fb8-2846-48a8-b68b-2a06d77a1dac

Fixing a DatePicker glitch of InstUI

---

Core/Core/Profile/Help/View/HelpView.swift
Core/CoreTests/Profile/Help/View/HelpViewTests.swift

<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/cc7ee0b9-961a-4279-aede-ab5c1feddada" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/00eac6cc-15b5-4af1-af76-e7fc52b0960a" maxHeight=500></td>
</tr>
</table>

Filter out invalid help item links

---

Core/Core/Grades/Model/GradeListInteractor.swift

refs: [MBL-17726](https://instructure.atlassian.net/jira/software/c/projects/MBL/boards/476?assignee=712020%3A158831a2-3c34-417e-b104-55ca208bcd5f&selectedIssue=MBL-17726)
affects:Student , Parent
release note: Implemented new design on grade screen
https://github.com/user-attachments/assets/9dd55a47-928d-4898-879d-44228a002eb2
[MBL-17726]: https://instructure.atlassian.net/browse/MBL-17726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix more empty space in grade list 

---

Core/Core/Extensions/DateExtensions.swift
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+Description.swift
Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule.swift
Core/Core/Planner/CalendarEvent/ViewModel/EditCustomFrequencyViewModel+Entities.swift
Core/CoreTests/Planner/CalendarEvent/Model/Helpers/RecurrenceRuleTests.swift
Core/CoreTests/Planner/CalendarEvent/ViewModel/EditCustomFrequencyViewModelTests.swift

refs: [MBL-17968](https://instructure.atlassian.net/browse/MBL-17968)
See ticket for details.
[MBL-17968]: https://instructure.atlassian.net/browse/MBL-17968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Update Calendar Event issue

---

Core/Core/Grades/Model/GradeListInteractor.swift
Core/Core/Grades/View/GradeListView.swift
Core/CoreTests/Grades/GradeListInteractorLiveTests.swift

refs: [MBL-17951](https://instructure.atlassian.net/browse/MBL-17951)
affects: Student , Parent
release note: Added letter grade when toggling based on graded assignments on grade screen
- Open student or parent app.
- Navigate to grade.
- Change toggle graded assignments state  will see the grade letter change.
https://github.com/user-attachments/assets/3acb0e31-ef04-4e5b-bb6f-b157dbd14bd4
https://github.com/user-attachments/assets/d211c7d1-ad19-47f9-82d2-e937f607b56a
[MBL-17951]: https://instructure.atlassian.net/browse/MBL-17951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change letter grade when toggling based on graded assignments on grade screen

---

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved
Horizon/Horizon.xcodeproj/project.pbxproj
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/View/LearningObjectHeaderView.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/AssignmentDetailsAssembly.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/Data/HAssignment.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetails.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentViewModel.swift
Horizon/Horizon/Sources/Features/Session/SessionInteractor.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift

Adds a basic assignment details screen with mock description.

[Horizon] Assignment Details

---

Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/View/ExpandingModuleView.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift
Horizon/Horizon/Sources/Features/Programs/ProgramsAssembly.swift
Horizon/Horizon/Sources/Features/Programs/View/ProgramDetailsView.swift
Horizon/Horizon/Sources/Features/Programs/View/ProgramDetailsViewModel.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift

Adds support for opening external links and external tools. 
[CLX-77](https://instructure.atlassian.net/jira/software/c/projects/CLX/boards/1806?label=clx-ios&selectedIssue=CLX-77), [CLX-78](https://instructure.atlassian.net/jira/software/c/projects/CLX/boards/1806?label=clx-ios&selectedIssue=CLX-78)
[CLX-77]: https://instructure.atlassian.net/browse/CLX-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLX-78]: https://instructure.atlassian.net/browse/CLX-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Horizon] External url and tool routing

---

Core/Core/Files/View/FileDetails/FileDetailsViewController.swift

refs: [MBL-17988](https://instructure.atlassian.net/browse/MBL-17988)
affects: Student,Teacher
release note: Fix the issue of annotation bar move button being cut off on landscape mode.
See ticket description for more information about use case testing:
https://instructure.atlassian.net/browse/MBL-17988
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/27afc58e-5c9b-40f5-b6dc-ea00d7bb70dd" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/a2080c19-2cf5-4d4b-9926-2536ed11d0da" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/2d0dbdb2-8b09-41c2-8c3a-cce4b6164451" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/689a15b5-9f80-4199-874a-0d0436 …

Fix the issue of annotation bar move button being cut off on landscape mode

---

.github/README.md
.github/guidelines/swift-style-guide.md

Swift Style Guide proposal

---

Horizon/Horizon/Sources/Features/HorizonTabBar.swift

Fix tab bar on SE size
https://instructure.atlassian.net/browse/CLX-178

[Horizon] Fix tab bar on SE size

---

Core/TestsFoundation/Helpers/CalendarHelper.swift

refs: MBL-18105
affects: None
test plan: Tests to pass on CI.
[Bitrise E2E test build](https://app.bitrise.io/build/c9aa4daa-9073-4d16-aa4a-7c38909c7912)
Fix for StudentE2ETests/CalendarTests/navigateToEvents test case.

E2E Test Maintenance

---

Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Data/HModule.swift
Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/View/ExpandingModuleView.swift
Horizon/Horizon/Sources/Common/View/ProgramCheckMarkIcon.swift
Horizon/Horizon/Sources/Common/View/ProgramItemOverdueView.swift
Horizon/Horizon/Sources/Common/View/ProgramItemView.swift
Horizon/Horizon/Sources/Common/View/ProgramLine.swift
Horizon/Horizon/Sources/Features/Programs/View/ProgramDetailsView.swift

Add module completion checkmark
https://instructure.atlassian.net/browse/CLX-149

[Horizon] Add completion checkmark

---

Core/Core/AppEnvironment/SessionDefaults.swift
Core/Core/Assignments/APIAssignment.swift
Core/Core/Assignments/Assignment.swift
Core/Core/Assignments/AssignmentList/View/AssignmentCellView.swift
Core/Core/Assignments/AssignmentList/View/AssignmentGroupView.swift
Core/Core/Assignments/AssignmentList/View/AssignmentListPreferencesScreen.swift
Core/Core/Assignments/AssignmentList/View/AssignmentListScreen.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentCellViewModel.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentGroupViewModel.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListPreferencesViewModel.swift
Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift
Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/Core/Models/Viewable/GradeViewable.swift
Core/CoreTests/Assignments/AssignmentList/ViewModel/AssignmentCellViewModelTests.swift
Core/CoreTests/Assignments/AssignmentList/ViewModel/AssignmentListPreferencesViewModelTests.swift
Core/CoreTests/Assignments/AssignmentList/ViewModel/AssignmentListViewModelTests.swift
Teacher/Teacher.xcodeproj/xcshareddata/xcschemes/Teacher.xcscheme
TestPlans/CoreTests.xctestplan

refs: MBL-18056
release note: Improved filtering and grouping options for assignment list.
- Assignment list items are now upgraded and showing more info. (State, Points)
- Design has changed. (See [Figma](https://www.figma.com/design/d0XYwwGe37hEWdmArVVBhr/%E2%8F%B3-%5BWIP%5D-Mobile-Desig-Sprint-%5BQ2-Q4%5D?node-id=3779-83207&node-type=canvas&t=UK7I4MnethYPN1N6-0))
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/faf541df-3e47-46d0-9424-c8b5cd3cb68e" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/b7882311-8200-4ad5-ae91-10f3dd6f3242" maxHeight=500></td>
</tr>
</table>
- Assignment list items are now upgraded and showing more info. (Points)
- Design …

Assignment List Screen Improvements

---

packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Typography/HorizonUI.Typography.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Typography/HorizonUI.Typography.swift

Adds variants, small update to the storybook.

[Horizon] Typography variants

---

packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/CornerRadius/HorizonUI.CornerRadius.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/CornerRadius/HorizonUI.CornerRadius.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/CornerRadius/HorizonUI.Corners.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/CornerRadius/HorizonUI.SmoothRoundedRectangle.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Spaces/HorizonUI.Spaces.Primitivies.swift

Adds space variants and corner radius levels.

[Horizon] Spaces and Corner Radius levels

---

packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Borders/HorizonUI.Borders.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Borders/HorizonUI.Borders.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Storybook.swift

[Horizon] Border levels

---

packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Typography/HorizonUI.Typography.swift

Adds letter spacing to typography view.

[Horizon] Letter spacing

---

packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Borders/HorizonUI.Borders.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Borders/HorizonUI.Borders.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Util/Color+Extension.swift

Adds Pill component, updates Border component so color is not coupled with border level.

[Horizon] Pill component, update border usage

---

packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Tag/HorizonUI.Tag.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Tag/HorizonUI.Tag.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Storybook.swift

[Horizon] Tag component

---

Core/CoreTests/AppEnvironment/BackgroundVideoPlayerTests.swift

Fix flaky test

---

packages/HorizonUI/Sources/HorizonUI/Resources/Assets.xcassets/Icons/calendar_today.imageset/Contents.json
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.Styles.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Pill/HorizonUI.Pill.swift

Updated pill component to latest figma iterations. Renamed styles to `outline`, `solid`, `inline` so that they are the same as in figma.

[Horizon] Pill update

---

Core/Core/AppEnvironment/AppEnvironment.swift
Horizon/Horizon/Sources/Features/HorizonTabBarController.swift

Fix TabBar issue for iPad in iOS 18 
https://instructure.atlassian.net/browse/CLX-320
https://github.com/user-attachments/assets/fdbe4f9b-06f2-4d39-a9dd-7a0b5607fa07

[Horizon] Fix tabBar  issue

---

Core/Core/Features/Profile/SideMenu/SideMenuHeaderView.swift

test plan: VoiceOver should read Avatar image as button.

Accessibility - Teacher - Profile - Avatar as button

---

Core/Core/Modules/ModuleItemType.swift
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Data/HModule.swift
Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/Data/HModuleItemLockMessage.swift
Horizon/Horizon/Sources/Common/Data/HModuleStatus.swift
Horizon/Horizon/Sources/Common/View/ExpandingModuleView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.Type.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.ModuleItemCard.Status.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleContainer/HorizonUI.ModuleContainer.Status.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleContainer/HorizonUI.ModuleContainer.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleContainer/HorizonUI.ModuleContainer.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/LearningObjectCard/HorizonUI.LearningObjectCard.swift

[Update courseDetails with new UI](https://instructure.atlassian.net/browse/CLX-326)
[Fix CourseDetails Overview page](https://instructure.atlassian.net/browse/CLX-355)
[Fix dashboard course card icons](https://instructure.atlassian.net/browse/CLX-356)
Note
In `HModuleItemLockMessage`, the lock message is needed as a dependency, which is HTML content. Its responsibility is to fetch the lock date or the first message. In the future, it is necessary to align with the backend team to add a new property without HTML.

[Horizon] Update courseDetails version 2

---

.bitrise/pr_adhoc/workflow_pr_adhoc_builds.yml

Update trigger to match the one used previously.

---

Core/Core/Common/CommonUI/InstUI/Views/Cells/DatePickerCell.swift
Core/Core/Features/Planner/CalendarEvent/View/EditCalendarEventScreen.swift
Core/Core/Features/Planner/CalendarEvent/View/EditCustomFrequencyScreen.swift
Core/Core/Features/Planner/CalendarToDo/View/EditCalendarToDoScreen.swift

Accessibility - Teacher - Calendar event font size fix
refs: MBL-18306
Original PR: https://github.com/instructure/canvas-ios/pull/3061
(reopened due to CI issues)

Accessibility - Teacher - Calendar event font size fix

---

.bitrise/bitrise.yml

Update bitrise stack from the non-existing m1 machine type

---

Core/Core/Common/CommonUI/UIViews/RightDetailTableViewCell.swift
Core/Core/Features/Profile/Settings/ProfileSettingsViewController.swift

Settings - Add "link" accessibilityTrait to "Privacy Policy" and "Canvas on GitHub" buttons.
refs: MBL-18304

Accessibility - Settings - Add accessibilityTrait to cells

---

Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Features/Account/AccountAssembly.swift
Horizon/Horizon/Sources/Features/Account/AccountView.swift
Horizon/Horizon/Sources/Features/Account/AccountViewModel.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/HorizonTabBarController.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/CornerRadius/HorizonUI.CornerRadius.swift

Main account screen. Sub screens like profile, password, etc will be separate tickets, prs.

[Horizon] Account screen

---

Horizon/Horizon/Sources/Features/Account/Common/AccountNavigationBar.swift

[Horizon] Horizon Account Navigation Bar

---

Core/Core/Common/CommonModels/AppEnvironment/SessionDefaults.swift
Core/CoreTests/Common/CommonModels/AppEnvironment/AppEnvironmentOverrideTests.swift
Core/CoreTests/Common/CommonModels/Store/FetchedCollectionTests.swift
Core/CoreTests/Common/Extensions/Foundation/CGSizeExtensionsTests.swift
Core/CoreTests/Common/Extensions/SwiftUI/UIColor+ColorTests.swift
Core/CoreTests/Features/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncPagesInteractorLiveTests.swift
Core/CoreTests/Features/Courses/SmartSearch/Model/CourseSmartSearchViewAttributesTests.swift
Core/CoreTests/Features/Search/Model/SearchSupportButtonModelTests.swift

refs: MBL-18564
affects: none
test plan:
- No code coverage warnings on PRs.

Improve test coverage

---

Core/Core/Features/Pages/PageDetails/PageDetailsViewController.swift
Core/CoreTests/Features/Pages/PageDetails/PageDetailsViewControllerTests.swift
Parent/Parent/Routes.swift
Student/Student/Routes.swift
Teacher/Teacher/Routes.swift

refs: [MBL-18553](https://instructure.atlassian.net/browse/MBL-18553)
release note: Fixed issue where Studio embedded videos not shown in some cases.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18553) description.
[MBL-18553]: https://instructure.atlassian.net/browse/MBL-18553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Consortia root account issue where Studio Embedded Videos not shown properly in pages created with RCE

---

Core/Core/Features/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift

refs: MBL-18303
In Teacher or Student app,
1- Go to "Calendar" tab, then hit the "+" button and choose "Add Event"
2- Fill in required fields in the shown form, then hit "Add" button with VoiceOver on.
3- A message "Event has been added successfully" must read out when event is added successfully.
4- Form screen will be closed once message is fully read out.
5- Make sure the normal* Event Creation flow works as before.
* VoiceOver deactivated.

Accessibility - Student/Teacher - Event Added Announcement

---

Core/Core/Features/Grades/ViewModel/GradeFilterViewModel.swift

refs: [MBL-18462](https://instructure.atlassian.net/browse/MBL-18462)
test plan:
- Check if changing the grading filter and closing the modal with the done button announces that the filter was applied.
[MBL-18462]: https://instructure.atlassian.net/browse/MBL-18462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Accessibility - Student/Parent - Add grade list filter change announcement

---

Horizon/Horizon/Sources/Features/Session/SessionInteractor.swift

[Horizon] Fix Network issue

---

packages/HorizonUI/Sources/HorizonUI/Sources/Components/Modal/HorizonUI.Modal.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Modal/HorizonUI.Modal.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Modal/HorizonUI.ModalViewModifier.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Toast/HorizonUI.Toast.Storybook.ViewModel .swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Toast/HorizonUI.Toast.Style.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Toast/HorizonUI.Toast.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Storybook.swift

[Create Modal UI](https://instructure.atlassian.net/browse/CLX-518)
**Please note,**
I made the body of the modal generic because we will need it in the assignment details in case of success.
https://github.com/user-attachments/assets/5b39d710-f218-4b28-b2f6-d82fcc5c9833

[Horizon] Create Modal UI

---

Core/Core/Features/Notifications/CoreData/AlertThreshold.swift
Core/CoreTests/Features/Notifications/CoreData/AlertThresholdTests.swift
Parent/Parent/Students/StudentDetailsViewController.storyboard
Parent/ParentUnitTests/ObserverAlerts/ObserverAlertListViewControllerTests.swift

Rename institution announcements to global announcements

---

Horizon/Horizon/Sources/Features/AssignmentDetails/AssignmentAttempts/View/AssignmentAttemptsView.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetails.swift
Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetailsViewModel.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Toast/HorizonUI.Toast.swift

1- Fix border issue in toast
2- Make `AssignmentAttemptsView` dismissible, when tap one any attempt  dismiss view

[Horizon] Fix toast ui issue

---

Horizon/Horizon/Sources/Features/Splash/View/SplashView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Colors/HorizonUI.Colors.Icon.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Colors/HorizonUI.Colors.Primitives.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Colors/HorizonUI.Colors.Surface.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Colors/HorizonUI.Colors.Text.swift

[Horizon] Updated color palette

---

Core/Core/Common/CommonModels/Constants/UserAgent.swift

Horizon/Career specific user agent.

[Horizon] User agent

---

Core/Core/Features/Courses/CourseProgression/GetCoursesProgressionRequest.swift
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Features/AssignmentDetails/View/AssignmentDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/Scores/ScoresAssembly.swift

[Horizon] Fix overview, course details tab lag

---

Horizon/Horizon/Resources/Info.plist

[Horizon] Disable dark mode

---

Core/Core/Features/Files/FileSubmission/Model/Submission/FileSubmissionSubmitter.swift
Core/Core/Features/Files/Model/UploadManager.swift
Core/Core/Features/Submissions/GetSubmissions.swift

Fix missing imports

---

Core/Core/Features/Courses/CourseProgression/CDCourseProgression.swift
Core/Core/Features/Courses/CourseProgression/GetCoursesProgressionUseCase.swift
Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Data/HCourse.swift
Horizon/Horizon/Sources/Common/Data/IncompleteModule.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Account/AccountAssembly.swift
Horizon/Horizon/Sources/Features/Account/AccountViewModel.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetailsAssembly.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/Domain/ModuleItemSequenceInteractor.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/ModuleItemSequenceAssembly.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/LearningObjectCard/HorizonUI.LearningObjectCard.swift

1- [Set Institution Name from GetCoursesInteractor](https://instructure.atlassian.net/browse/CLX-439)
2- [Fix module item progress pill](https://instructure.atlassian.net/browse/CLX-926)
3-[Fix caching](https://instructure.atlassian.net/browse/CLX-927)
4- Fixed warning in core data

[Horizon] Fix dashborad Caching 

---

Parent/Parent/Inbox/ParentInboxCoursePicker/Model/ParentInboxCoursePickerInteractorLive.swift

Parent inbox picker distinct items

---

Core/Core/Common/CommonModels/Analytics/AnalyticsMetadataInteractor.swift

refs: MBL-18620
Followup for the Pendo integration PR: https://github.com/instructure/canvas-ios/pull/3250
Verify apps don't crash after login.
The crash was only reproducible in Parent app AND using Attila's account AND running in simulator...

Fix Pendo setup crash

---

Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Dashboard/DashboardAssembly.swift
Horizon/Horizon/Sources/Features/Dashboard/Data/DashboardCourse.swift
Horizon/Horizon/Sources/Features/Dashboard/Data/NextUpViewModel.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift

1- Fix dashboard loading  issues 
2-  Set pull to refresh in course details

[Horizon] Fix dashboard  loading issue

---

Core/Core/Common/Extensions/WebKit/WKWebViewExtensions.swift
Horizon/Horizon/Sources/Common/View/EmbeddedWebPage/EmbeddedWebPageNavigation.swift
Horizon/Horizon/Sources/Common/View/EmbeddedWebPage/HEmbeddedWebPageContainerView.swift
Horizon/Horizon/Sources/Common/View/EmbeddedWebPage/HEmbeddedWebPageContainerViewModel.swift
Horizon/Horizon/Sources/Features/Inbox/HInboxAssembly.swift
Horizon/Horizon/Sources/Features/Inbox/View/BackButton.swift
Horizon/Horizon/Sources/Features/Inbox/View/HInboxView.swift
Horizon/Horizon/Sources/Features/Inbox/View/HInboxViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/MyAssignmentSubmissions/View/MyAssignmentSubmissionsView.swift
Horizon/Horizon/Sources/Features/LearningObjects/FileDetails/Views/FileDetailsViewRepresentable.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageDetailsView.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageDetailsViewModel.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageViewRepresentable.swift

1- Fix notebook in page view
2- https://instructure.atlassian.net/browse/CLX-1016
3- https://instructure.atlassian.net/browse/CLX-1065
4- https://instructure.atlassian.net/browse/CLX-1058
5- https://instructure.atlassian.net/browse/CLX-1064

[Horizon] Inbox - Conversations details double back button

---

Core/Core/Features/TokenRefresh/Model/AccessTokenRefreshInteractor.swift
Core/Core/Features/TokenRefresh/Model/LoginAgainInteractor.swift
Core/CoreTests/Features/TokenRefresh/Model/AccessTokenRefreshInteractorTests.swift

This is a follow-up for the token expiration PR.

Make error check more readable

---

Core/Core/Common/CommonUI/ViewableModels/SubmissionViewable.swift
Core/Core/Features/Assignments/AssignmentDetails/AssignmentDetailsView.swift
Core/Core/Features/Grades/View/GradeRowView.swift
Core/Core/Features/Quizzes/QuizDetails/Teacher/View/TeacherQuizDetailsView.swift
Core/Core/Features/Submissions/Submission.swift
Core/CoreTests/Common/CommonUI/ViewableModels/SubmissionViewableTests.swift
Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
Teacher/Teacher/SpeedGrader/SubmissionHeader.swift
Teacher/Teacher/Submissions/SubmissionListViewController.storyboard
Teacher/Teacher/Submissions/SubmissionListViewController.swift

refs: [MBL-18693](https://instructure.atlassian.net/browse/MBL-18693)
release note: Corrected assignment state icons.
test plan:
- Check if an assigned assignment has a lined icon.
- Check if a graded assignment has a filled icon.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/2f25834b-24f0-4148-8f45-502d41feeb10" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/5688304f-2ca8-4a00-a8c8-750988066995" maxHeight=500></td>
</tr>
</table>
[MBL-18693]: https://instructure.atlassian.net/browse/MBL-18693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lined icon for submitted assignment

---

Core/Core/Features/Courses/K5/ViewModel/K5SubjectViewModel.swift

## Student - K5 - Add groupLine icon to groups tab item
refs: MBL-18750

Student - K5 - Add groupLine icon to groups tab item

---

Core/Core/Features/People/APIUser.swift
Core/Core/Features/Profile/UserProfile.swift
Horizon/Horizon/Sources/Features/Account/Profile/Domain/UpdateUserUseCase.swift

https://github.com/user-attachments/assets/b3da4276-a175-4c51-97b5-b0d740e4ea35
https://instructure.atlassian.net/browse/CLX-1076

[Horizon] Time Zone Not Saving to Profile - CLX-1076

---

Core/Core/Features/Courses/CourseProgression/CDDashboardCourse.swift
Core/Core/Features/Courses/CourseProgression/GetDashboardCoursesWithProgressionsUseCase.swift
Core/Core/Features/Login/APIOAuth.swift
Core/Core/Features/Modules/MarkModuleItemDone.swift
Core/Core/Features/Modules/MarkModuleItemRead.swift
Core/Core/Features/Modules/Module.swift
Core/Core/Features/Modules/ModuleItem.swift
Core/Core/Features/Submissions/GetSubmissions.swift
Core/Core/Features/TextSubmission/TextSubmissionViewController.swift
Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Features/Login/APIOAuthTests.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/Scores/Domain/ScoresInteractor.swift
Horizon/Horizon/Sources/Features/Learn/Scores/Domain/ScoresInteractorPreview.swift
Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/Domain/AssignmentInteractor.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/Domain/AssignmentInteractorPreview.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Notification/Domain/NotificationInteractor.swift

Refreshes course/module/module item details when one of the followings is triggered:
- mark as read
- mark as done
- submitting a submission

[Horizon] CLX-1039 Refresh course details upon module completion

---

Core/Core/Common/CommonUI/SwiftUIViews/WebView.swift
Core/Core/Features/Files/Model/UploadManager.swift
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/Utilities/Double+.swift
Horizon/Horizon/Sources/Common/View/ModuleItemListView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetails.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetailsViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentSubmissionView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizAssembly.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizViewModel.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceView.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageViewRepresentable.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/IntroBlock/HorizonUI.IntroBlock.swift

1- [LO Assignment - Unable to take an additional NQ attempt](https://instructure.atlassian.net/browse/CLX-1031)
2- [My Progress - page wording for NQ is not correct](https://instructure.atlassian.net/browse/CLX-1045)
3- [Content "Bounces" when scrolling content](https://instructure.atlassian.net/browse/CLX-1061)
4-[Able to Scroll My Progress Tab Items](https://instructure.atlassian.net/browse/CLX-1164)
5- https://instructure.atlassian.net/browse/CLX-1029
6- https://instructure.atlassian.net/browse/CLX-1044
7- Fixed point count number formate from "10.0 pts" to "10 pts"
8- New UI for Quiz

[Horizon] Fixed Assignment Issues

---

Core/Core/Common/CommonModels/Store/ReactiveStore.swift
Core/CoreTests/Common/CommonModels/Store/ReactiveStoreTests.swift

ReactiveStore can only make API calls using the shared environment object but when working with cross-shards we need to use custom environments. This change is also needed for the SpeedGrader improvements but it's also valuable alone so I extracted it to a separate PR.
refs: MBL-18708

Add support for ReactiveStore to use custom environment other than shared

---

Core/Core/Features/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift

- List section headers on Assignment list screen are now localized.
refs: MBL-18768
release note: Localized "Assignments" list.
test plan:
- Check if Assignment list headers are appearing in the selected language instead of English.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/7182ec21-99d4-4ac8-af60-0294ba2d204c" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/6c9434d9-5f9a-4a79-a46b-610f6b2eccdb" maxHeight=500></td>
</tr>
</table>

Assignmentlist section header localization

---

Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/GraphQL/GetNotesQuery.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Domain/GetCourseNotesInteractor.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/NotebookAssembly.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift

Adding the ability to filter by module ID when viewing notes and fixing the version of the notes that's embedded in the course details [ignore-commit-lint]
https://github.com/user-attachments/assets/38fd184d-453b-43fb-b8cf-bc29908eb20c

[Horizon] Fixing the notebook embedded in the course details

---

Core/Core/Features/Modules/APIModule.swift
Core/Core/Features/Modules/GetModuleItem.swift
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Dashboard/Data/DashboardCourse.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/HorizonTabBarController.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/Learn/View/LearnView.swift
Horizon/Horizon/Sources/Features/Learn/Learn/View/LearnViewModel.swift
Horizon/Horizon/Sources/Features/Learn/LearnAssembly.swift

1- https://instructure.atlassian.net/browse/CLX-968
2- https://instructure.atlassian.net/browse/CLX-1051
3- https://instructure.atlassian.net/browse/CLX-1052
<table>
<tr><td>Empty Learn Tab</td> <td>Empty Dashboard Tab</td></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0a1b8a6c-1b46-44ce-b055-a1981aeabd0a" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/994c3de1-4cf9-44da-882d-bebcc522c7fd" maxHeight=500></td>
</tr>
</table>
https://github.com/user-attachments/assets/f45706b2-aaa1-4608-aeb5-509fd505f34e

[Horizon ]Add learn tab

---

Horizon/Horizon/Sources/Features/Account/AccountView.swift
Horizon/Horizon/Sources/Features/Account/AccountViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentSubmissionView.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/FileDrop/HorizonUI.FileDrop.swift

1- https://instructure.atlassian.net/browse/CLX-1053
2- https://instructure.atlassian.net/browse/CLX-1080
3- https://instructure.atlassian.net/browse/CLX-1084
4- https://instructure.atlassian.net/browse/CLX-1231
5- https://instructure.atlassian.net/browse/CLX-1251

[Horizon] Fix assignment & Profiles issues 

---

Horizon/Horizon/Config/Release.xcconfig
Horizon/Horizon/Sources/Common/View/EmbeddedWebPage/HEmbeddedWebPageContainerViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageViewRepresentable.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Domain/CourseNoteInteractor.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Domain/GetCourseNotesInteractor.swift
Horizon/Horizon/Sources/Features/Notebook/Common/View/HighlightWebView/HighlightWebView.swift
Horizon/Horizon/Sources/Features/Notebook/Note/NotebookNoteAssembly.swift
Horizon/Horizon/Sources/Features/Notebook/Note/View/NotebookNoteViewModel.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/NotebookAssembly.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift
Horizon/project-ci.yml
Horizon/project.yml

The web was using the page ID for associating a note with a page. This adds loading the page to the interactors so that I can get at the page ID.

[Horizon] Fixing Notebook Syncing

---

Core/Core/Features/Modules/ModuleItems/ExternalURLViewController.storyboard
Core/Core/Features/Modules/ModuleItems/ExternalURLViewController.swift
Core/Core/Features/Modules/ModuleItems/ModuleItemSequenceViewController.swift

refs: MBL-18769
<table>
<tr><th>ExternalURLViewController</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/ccac92d7-9695-4b9c-8ec7-869ef3e78a09" height=500></td>
</tr>
</table>

Fix ExternalURLViewController is not localized

---

Horizon/Horizon/Sources/Common/Data/HCourse.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetailsViewModel.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/DidSubmitQuiz.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizAssembly.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/LTIQuiz/LTIQuizViewModel.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/Domain/ModuleItemSequenceInteractor.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/Domain/Preview/ModuleItemSequenceInteractorPreview.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/LearningObjectCard/HorizonUI.LearningObjectCard.swift

https://instructure.atlassian.net/browse/CLX-1028
https://instructure.atlassian.net/browse/CLX-1288

[Horizon] Update course progress after submit quiz

---

Core/TestsFoundation/UITestDataSeeding/Assignment/DSAssignment.swift
Student/StudentE2ETests/Files/FilesTests.swift
TestPlans/ParentE2E.xctestplan
TestPlans/StudentE2E.xctestplan

- Fixed a data seeder decoding error. The position should have been optional as it is optional in the project as well.
- Skipped a files related test that needs to be updated due to change in the latest iOS.
- Disabled test video recording to reduce the load on the host machine.

Update E2E tests

---

Core/Core/Common/CommonUI/InstUI/BaseScreen.swift
Core/Core/Common/CommonUI/SwiftUIViews/Pandas/InteractivePandaConfig.swift
Core/Core/Common/CommonUI/SwiftUIViews/Pandas/Scenes/HorizonError.swift
Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Features/Account/AccountView.swift
Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresView.swift

1- https://instructure.atlassian.net/browse/CLX-982
2- https://instructure.atlassian.net/browse/CLX-1306
3- https://instructure.atlassian.net/browse/CLX-1309
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/32c25242-c43f-4993-a783-0f51b8147ce1" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/e65f4cd9-85f4-459d-ae0a-682ad513c0e5" maxHeight=500></td>
</td>
<td><img src="https://github.com/user-attachments/assets/a383205d-cad3-4539-b9c3-84da13d97527" maxHeight=500></td>
</td>
<td><img src="https://github.com/user-attachments/assets/fec31713-3208-467a-9b96-d82de88832cc" maxHeight=500></td>
</tr>
</table>

[Horizon] Set empty state at score & fix ui issues 

---

Core/Core/Features/Courses/CourseProgression/CDDashboardCourse.swift
Core/Core/Features/Courses/CourseProgression/GetCoursesProgressionRequest.swift
Core/Core/Features/Courses/CourseProgression/GetCoursesProgressionResponse.swift
Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents
Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift

[Horizon] Fetch first moduleItem in case incomplete module is empty in dashboard

---

Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift

https://github.com/user-attachments/assets/83d24b07-0f53-4157-87d3-a8827fac8e52

[Horizon] Padding update on CourseDetailsView

---

Core/Core/Features/Login/LoginQRCodeTutorialViewController.storyboard
Core/Core/Features/Login/LoginQRCodeTutorialViewController.swift
Core/Core/Features/Login/LoginStartViewController.swift

refs: MBL-18766
release note: Added further explanation to the QR login screen.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/7c55294e-2314-4c83-9bb4-30785a19678c" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/738d82f5-0981-4a56-b2fa-6acfbde85be1" maxHeight=500></td>
</tr>
</table>

QR login helper text

---

Core/Core/Common/CommonModels/AppEnvironment/AppEnvironmentOverride.swift
Core/Core/Common/CommonModels/Router/Router.swift
Core/Core/Common/CommonUI/EmbeddedWebPage/ViewModel/EmbeddedWebPageContainerViewModel.swift
Core/Core/Features/Discussions/AnnouncementListViewController.swift
Core/Core/Features/Discussions/DiscussionDetailsViewController.swift
Core/Core/Features/Discussions/DiscussionListViewController.swift
Core/Core/Features/Discussions/DiscussionsAssembly.swift
Core/Core/Features/Discussions/Editor/ViewModel/DiscussionCreateWebViewModel.swift
Core/CoreTests/Common/CommonUI/EmbeddedWebPage/ViewModel/EmbeddedWebPageContainerViewModelTests.swift
Core/CoreTests/Features/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncAnnouncementsInteractorLiveTests.swift
Core/CoreTests/Features/Discussions/AnnouncementListViewControllerTests.swift
Core/CoreTests/Features/Discussions/DiscussionDetailsViewControllerTests.swift
Core/CoreTests/Features/Discussions/DiscussionListViewControllerTests.swift
Core/CoreTests/Features/Discussions/Editor/ViewModel/DiscussionCreateWebViewModelTests.swift
Student/Student/Routes.swift
Teacher/Teacher/Routes.swift

refs: MBL-18802
release note: Fixed issue of Discussions being inaccessible for cross-shared users.
See ticket's description. Also, we need to test edit & create pages for discussions and announcements.

Fixed issue of Discussions being inaccessible for cross-shared users

---

Horizon/Horizon/Sources/Common/Data/API/DomainService.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/DropdownMenu.swift
Horizon/Horizon/Sources/Features/Learn/Learn/Data/LearnCoursesInteractor.swift
Horizon/Horizon/Sources/Features/Learn/LearnAssembly.swift
Horizon/Horizon/Sources/Features/Learn/Scores/Domain/ScoresInteractor.swift
Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresViewModel.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Domain/CourseNoteInteractor.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift

1- https://instructure.atlassian.net/browse/CLX-1387
2- https://instructure.atlassian.net/browse/CLX-1414
3- Fix memory leaks in scores & notes
4- Prevent render the course details when open module item sequence  view

[Horizon] Add drop list courses at course details

---

packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/HorizonUI.ButtonStyles.swift

for some reason,  this wasn't getting picked up when running swiftlint locally

[Horizon] Removing a trailing comma that the linter doesn't like

---

Core/Core/Features/Login/LoginStartViewController.swift

Adds missing route handling for QR login.

[Horizon] Fix QR login

---

Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/Learn/View/LearnView.swift
Horizon/Horizon/Sources/Features/Learn/Learn/View/LearnViewModel.swift
Horizon/Horizon/Sources/Features/Learn/LearnAssembly.swift

https://instructure.atlassian.net/browse/CLX-1522

[Horizon] Fix DropDownList course

---

Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Common/Data/HModuleItem.swift
Horizon/Horizon/Sources/Common/View/ModuleItemListView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.Storybook.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.LearningObjectItem.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/LearningObjectItem/HorizonUI.ModuleItemCard.Status.swift

https://instructure.atlassian.net/browse/CLX-1523

[Horizon] Display all requirement for module item

---

Horizon/Horizon/Sources/Common/View/EmbeddedWebPage/HEmbeddedWebPageContainerViewModel.swift
Horizon/Horizon/Sources/Features/Assist/AssistQuiz/View/AssistQuizView.swift
Horizon/Horizon/Sources/Features/Assist/AssistQuiz/View/AssistQuizViewModel.swift

https://instructure.atlassian.net/browse/CLX-1481
https://instructure.atlassian.net/browse/CLX-1056

[Horizon] Fix skillSpace router & Assist - Loading spinner

---

Core/Core/Common/CommonModels/AppEnvironment/BrandStyle/Brand.swift
Core/Core/Common/CommonModels/AppEnvironment/BrandStyle/CDBrandVariables.swift
Core/CoreTests/Common/CommonUI/NavigationBar/NavigationBarColorConfigurationTests.swift
Core/CoreTests/Common/Extensions/UIKit/UITabBarExtensionsTests.swift

https://instructure.atlassian.net/browse/CLX-1556

[Horizon] Add base URL for institution logo when not set

---

Horizon/Horizon/Sources/Features/Assist/AssistAssembly.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/AssistChatInteractor.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatView.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatViewModel.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistTitle.swift
Horizon/Horizon/Sources/Features/Assist/AssistFlashCard/View/AssistFlashCardView.swift
Horizon/Horizon/Sources/Features/Assist/AssistFlashCard/View/AssistFlashCardViewModel.swift
Horizon/Horizon/Sources/Features/Assist/AssistQuiz/View/AssistQuizView.swift
Horizon/Horizon/Sources/Features/Assist/AssistQuiz/View/AssistQuizViewModel.swift
Horizon/Horizon/Sources/Features/HorizonTabBarController.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift

https://instructure.atlassian.net/browse/CLX-1460
https://github.com/user-attachments/assets/dc379945-9c2b-4fd7-a423-4b037cab150b

[Horizon] Add back button & fix navigation on AI chats

---

Core/Core/Features/Modules/APIModule.swift
Core/Core/Features/Modules/GetModule.swift
Core/Core/Features/Modules/Module.swift
Horizon/Horizon/Sources/Common/Data/HCourse.swift
Horizon/Horizon/Sources/Features/Dashboard/Domain/DashboardInteractor.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift
Horizon/Horizon/Sources/Features/Learn/Scores/Domain/ScoresInteractor.swift
Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresViewModel.swift

https://instructure.atlassian.net/browse/CLX-1562
https://instructure.atlassian.net/browse/CLX-1582
https://github.com/user-attachments/assets/e8c9b061-9c9a-495a-9494-581ef965e52b

[Horizon] Fix Eliminate double network calls on learn tab

---

Core/Core/Features/Login/LoginFindSchoolViewController.swift

https://github.com/user-attachments/assets/126f2ca6-2f67-4508-aea7-d0deda6f07b8

[Horizon] Handle http:// in account name

---

Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractorPreview.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsViewModel.swift

https://instructure.atlassian.net/browse/CLX-1631

[Horizon] Refresh the course overview when performing a pull-to-refresh.

---

Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresAssignmentsView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Inputs/SingleSelect/HorizonUI.SingleSelect.swift

https://github.com/user-attachments/assets/990eea14-e400-4a8a-a915-2095efd03d78

[Horizon] Add searchable feature  for SingleSelect component

---

Core/Core/Features/Courses/CourseProgression/CDHCourse.swift
Core/Core/Features/Courses/CourseProgression/GetHCoursesProgressionRequest.swift
Core/Core/Features/Courses/CourseProgression/GetHCoursesProgressionResponse.swift
Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents
Core/CoreTests/Features/Courses/CourseProgression/Model/CDHCourseTests.swift
Horizon/Horizon/Sources/Common/Data/HCourse.swift
Horizon/Horizon/Sources/Common/Data/LearningObjectType.swift
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/LearningObjectCard/HorizonUI.LearningObjectCard.swift

https://instructure.atlassian.net/browse/CLX-2161

[Horizon] Add next modules icons in Dashboard

---

Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsTabs.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/CourseDetailsView.swift
Horizon/Horizon/Sources/Features/Learn/CourseDetails/View/DropdownMenu.swift
Horizon/Horizon/Sources/Features/Learn/Scores/Data/ScoresAssignment.swift
Horizon/Horizon/Sources/Features/Learn/Scores/View/ScoresAssignmentsView.swift
Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/Data/HAssignment.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleContainer/HorizonUI.ModuleContainer.Status.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Cards/ModuleContainer/HorizonUI.ModuleContainer.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Inputs/SingleSelect/HorizonUI.SingleSelect.swift

1- https://instructure.atlassian.net/browse/CLX-2179
2- https://instructure.atlassian.net/browse/CLX-2178
3- https://instructure.atlassian.net/browse/CLX-2180
4- https://instructure.atlassian.net/browse/CLX-2182
5- https://instructure.atlassian.net/browse/CLX-2181
6- https://instructure.atlassian.net/browse/CLX-2183
7- https://instructure.atlassian.net/browse/CLX-2185

[Horizon] Fix some UI bugs

---

Horizon/Horizon/Sources/Features/Inbox/Create/HCreateMessageView.swift
Horizon/Horizon/Sources/Features/Inbox/Create/HCreateMessageViewModel.swift

The send button was not getting enabled after the user would select a recipient in the inbox

[Horizon] Send Button Not Enabled After Selecting Recipient

---

Horizon/Horizon/Sources/Features/Inbox/Attachment/AttachmentItemViewModel.swift
Horizon/Horizon/Sources/Features/Inbox/Attachment/AttachmentViewModel.swift
Horizon/Horizon/Sources/Features/Inbox/MessageDetails/HMessageDetailsView.swift

https://github.com/user-attachments/assets/7d040d0b-f87e-46fc-8459-d83c2d415599

[Horizon] Cancel Download Fix

---

Horizon/Horizon/Sources/Features/Notification/View/HNotificationView.swift

https://instructure.atlassian.net/browse/CLX-2266

[Horizon] Fix notification header

---

Horizon/Horizon/Sources/Features/Inbox/Create/HCreateMessageView.swift
Horizon/Horizon/Sources/Features/Inbox/Inbox/View/HInboxView.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/FileDrop/HorizonUI.UploadedFile.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Inputs/MultiSelect/HorizonUI.MultiSelect.swift
packages/HorizonUI/Sources/HorizonUI/Sources/Components/Inputs/SingleSelect/HorizonUI.SingleSelect.swift

1- https://instructure.atlassian.net/browse/CLX-2276
2- https://instructure.atlassian.net/browse/CLX-2271
3- https://instructure.atlassian.net/browse/CLX-2273
4- https://instructure.atlassian.net/browse/CLX-2275

[Horizon] Fix Inbox Bugs

---

Teacher/TeacherE2ETests/SpeedGrader/SpeedGraderTests.swift

refs: MBL-19078
affects: None
test plan: [Teacher E2E test suite to pass on CI.](https://app.bitrise.io/build/00a21fe7-1b30-477a-9771-c8d0ee259b44)

Teacher - Fix E2E tests

---

Horizon/Horizon/Resources/Localizable.xcstrings
Horizon/Horizon/Sources/Features/Assist/AssistAssembly.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Data/AssistChatMessage.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/AssistChatInteractor.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/Goal/AssistCourseTextSelectionGoal.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/Goal/AssistGoal.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/Goal/AssistSelectCourseGoal.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/Goal/CourseItem/AssistCourseItemGoal.swift
Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistDataEnvironment.swift
Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/View/PageViewRepresentable.swift
Horizon/Horizon/Sources/Features/Notebook/Common/View/HighlightWebView/HighlightWebView.swift
Horizon/Horizon/Sources/Features/Notebook/Common/View/HighlightWebView/HorizonWebView.swift
Horizon/Horizon/Sources/Routing/HorizonRoutes.swift

This feature allows you to select a block of text in a page and Assist will allow the learner to ask questions about the text.
https://github.com/user-attachments/assets/792be39e-07a2-4881-b865-890dcec37d36

[Horizon] Text Selection in Assist

---

Parent/Parent/Dashboard/DashboardViewController.swift
Parent/Parent/Localizable.xcstrings
Student/Student/Localizable.xcstrings
Student/Student/StudentTabBarController.swift
Teacher/Teacher/Localizable.xcstrings
Teacher/Teacher/TeacherTabBarController.swift

Fix navigation buttons not handling long texts

---

Student/Student/InfoPlist.xcstrings

Update Canvas Student localization entries

---

Horizon/Horizon/Sources/Common/Domain/CDNotebookNoteExtension.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/CourseNotebookNote.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/GraphQL/CreateNoteMutation.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/GraphQL/GetNotesQuery.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/GraphQL/UpdateNoteMutation.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Data/RedwoodNote.swift
Horizon/Horizon/Sources/Features/Notebook/Common/Domain/CourseNoteInteractor.swift
Horizon/Horizon/Sources/Features/Notebook/Common/View/HighlightWebView/HorizonWebView.swift
Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift

Various bug fixes:
https://instructure.atlassian.net/browse/CLX-2733
https://instructure.atlassian.net/browse/CLX-2684
https://instructure.atlassian.net/browse/CLX-2683
https://instructure.atlassian.net/browse/CLX-2682

[Horizon] Notebook Bug Fixes

---

Horizon/Horizon/Sources/Common/Data/API/DomainService.swift

builds: student
test plan: Navigate to the Assistant and verify that it's responding from an account other than horizon.cd

[Career] - Production Journey URL Fix

---

Core/Core/Features/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModel.swift
Core/CoreTests/Common/CommonModels/API/APIPageInfoTests.swift
Core/CoreTests/Common/CommonModels/Store/ScopeTests.swift
Core/CoreTests/Common/CommonUI/CoreWebView/View/CoreWebViewAccessibilityHelperTests.swift
Core/CoreTests/Features/Assignments/Assignment/Model/Entities/GradingTypeTests.swift
Core/CoreTests/Features/Submissions/Submission/Model/API/APITurnItInDataTests.swift
Core/CoreTests/Features/Submissions/Submission/Model/UseCase/GetSubmissionAttemptsLocalTests.swift
Core/CoreTests/Features/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModelTests.swift
scripts/coverage/config.json

Add missing unit tests

---

Core/CoreTests/Features/Pages/APIPageTests.swift

refs: CLX-2864
builds: Student

[CLX-2864][S] Fix unit test failures

---

.github/copilot-instructions.md
CLAUDE.md

Add Claude instruction file
