Core/Core/Dashboard/K5/View/Grades/K5GradesView.swift
refs: MBL-15971
release note: Fixed grading period selector accessibility announcement.
=> Select Current Grading Period Button on the Grades tab in K5 does not read if it's expanded/collapsed

Core/Core/Planner/CreateTodoViewController.swift, Core/CoreTests/Planner/CreateTodoViewControllerTests.swift
refs: MBL-16012
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/165097475-dd182d40-9762-40f3-9a01-be10af1ab85a.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/165097471-72a52110-de1e-405f-8834-a6c8f38bf7ef.png"></td>
</tr>
</table>
=> Calendar add to-do page description placeholder misalignment

Student/Student.xcodeproj/project.pbxproj, Student/StudentE2ETests/Announcements/DSAnnouncementsE2ETests.swift, Student/StudentE2ETests/Discussions/DSDiscussionsE2ETest.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, TestsFoundation/TestsFoundation/DataSeeding/Course/Tabs/CreateDSTabsRequest.swift, TestsFoundation/TestsFoundation/DataSeeding/Course/Tabs/DataSeeder+Tabs.swift, TestsFoundation/TestsFoundation/DataSeeding/Discussions/CreateDSDiscussionRequest.swift, TestsFoundation/TestsFoundation/DataSeeding/Discussions/DSDiscussionTopic.swift, TestsFoundation/TestsFoundation/DataSeeding/Discussions/DataSeeder+Discussion.swift
refs: MBL-15981
test plan: Course tabs update was added aswell, but it is unused at the moment. Tests are basic to validate DS methods, will expand them once we are done with the hybrid integration, so no old tests were disabled
=> Added DataSeeding support for discussions

Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift
=> Add event name to the accessibility label of checkboxes in K5 Schedule

Core/Core/DocViewer/PSPDFAnnotationExtension.swift, Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift
refs: MBL-16038
release note: Fixed text annotation background color changing from transparent to white.
=> Transparent background is not retained when editing existing text annotations

Core/Core/API/SafeURL.swift, Core/Core/Courses/GetCourseNavigationToolsRequest.swift, Core/CoreTests/API/SafeURLTests.swift
refs: MBL-16043
release note: Fixed attendance tool opening in a web view.
test plan: See ticket. Attendance tool should open natively.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/165733076-244f203c-d8c5-4160-9c0f-d0441be742c6.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/165733126-a601fc12-32d0-4625-bfb2-2d2faa3b2835.PNG"></td>
</tr>
</table>
=> Make url parsing in course navigation response more tolerant.

Core/Core/Courses/CourseList/ViewModel/CourseListViewModel.swift, Core/Core/Dashboard/Model/CourseSectionStatus.swift, Core/Core/Dashboard/ViewModel/DashboardCardsViewModel.swift, Core/CoreTests/Courses/CourseList/ViewModel/CourseListViewModelTests.swift, Core/CoreTests/Dashboard/Model/CourseSectionStatusTests.swift
refs: MBL-16035
release note: Fixed concluded section courses listed as active.
test plan:
- Enroll a student/teacher to a course's section.
- Go to the user's profile and conclude this section's enrollment.
- Go to the app and check the contents of the Edit Dashboard menu.
- All courses should list this course amongst past enrollments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/167857830-cbef2214-076e-40c3-a204-ad9722512fd3.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/167857845-0c7dad83-b328-4f8e-b02b-db4be938c0ce.PNG"></td>
</tr>
</table>
=> Fix concluded section enrollment courses listed as active.

Core/Core/Courses/Course.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Extensions/NSManagedObjectContextExtensions.swift, Core/Core/Planner/GetPlannerCourses.swift, Core/Core/Planner/Planner.swift, Core/Core/Planner/PlannerFilterViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/Store/Scope.swift, Core/CoreTests/Extensions/NSManagedObjectContextExtensionsTests.swift
refs: MBL-16016
test plan:
- Go to Calendar tab, tap Calendars
- De-select a course, tap Done
- Switch tabs, do pull to refreshes, restart the app
- Calendar's course filter shouldn't change
- Calendar should only show course events based on the saved selection
--
- Also test if this change caused any regression issues in the parent app
- Add two students to a parent
- Add each student to a different course with some upcoming assignments
- Start the parent app, login with the parent account
- Go to calendar
- Check if switching students correctly updates the calendar filter, only the active student's course should be visible
- Switch tabs, restart the app
- Per student calendar filter state should remain unchanged 
<table> …
=> Fixed calendar's course filter reseting upon leaving calendar tab

Core/Core/Courses/CourseList/View/CourseListCellView.swift, Core/Core/Courses/CourseList/View/CourseListView.swift
refs: MBL-16024
test plan:
- Enroll a teacher and a student to a past course.
- Go to Dashboard > Edit Dashboard
- Star icon shouldn't be displayed for past courses.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/168087634-7aa0cc11-c7d6-4c04-8d1a-69bafdc0e717.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/168087675-104b1a2c-0100-4168-a3b6-37b90119853c.png"></td>
</tr>
</table>
=> Removed favorite button for past courses.

Core/Core/Assignments/LatePolicyStatus.swift, Core/CoreTests/Assignments/LatePolicyStatusTests.swift
refs: MBL-16064
test plan: This change adds the extended enumeration option to LatePolicyStatus to make sure that when this is available on the API the app won't fail parsing it. Since we don't use this field in the app there's no way to manually test it.
=> Add extended late policy status.

Core/Core/Dashboard/Model/DashboardCard.swift, Core/CoreTests/Dashboard/Model/DashboardCardTests.swift
refs: MBL-16046
test plan:
- Do a pull to refresh on the dashboard.
- Card colors shouldn't reset back to gray before getting their final color.
=> Update already existing DashboardCard objects instead of delete and re-create.

Core/Core/Courses/Course.swift, Core/CoreTests/Courses/CourseTests.swift
refs: MBL-16074
release note: Fixed a dashboard issue that caused only one group from a course appearing at a time.
test plan:
- Create two groups in the same active course.
- Add a user to both groups.
- Start the app, login with the user, dashboard should display both groups.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/171428387-7fda50f0-efcf-4e86-841d-85b09767dad6.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/171428321-3bd0e017-2254-4fdd-9470-2125029b02b2.png"></td>
</tr>
</table>
=> Update all groups when saving a course that has group assignments.

Core/Core/Contexts/Tab.swift, Core/CoreTests/Contexts/TabTests.swift
refs: MBL-16068
test plan:
- Hide a LTI tool in a course.
- Go to the app and check course details.
- Hidden LTI tool shouldn't be visible.
=> Map hidden property from API entity to CoreData.

Core/Core/Assignments/Assignment.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift
Force refresh discussion details to make sure discussion entry is available. Don't delete discussion assigned to an assignment, only clear the relation.
refs: MBL-16075
test plan:
- Test on iPad, see ticket.
- Also test if doing a pull to refresh on the detail view doesn't remove any entries from the discussions list.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/171836082-9e0d4571-928b-4a04-9711-607a322d394b.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/171836095-048c9cec-7ce9-41e3-adb1-6715586b1d2a.png"></td>
</tr>
</table>
=> Fix discussion loading

Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/CoreTests/AppEnvironment/ExperimentalFeatureTests.swift
refs: MBL-16113
test plan: K5 feature flag in debug builds should be enabled after a clean app install.
=> Add default value to K5 flag.

rn/Teacher/src/modules/assignment-due-dates/AssignmentDueDates.js, rn/Teacher/src/modules/assignment-due-dates/__tests__/__snapshots__/AssignmentDueDates.test.js.snap
Remove nav bar color setting to keep the previous screen's context color. Set page title to change long back button text to a one word back.
refs: MBL-16080
test plan:
- Navigate to Course > Assignments > Assignment Details.
- Tap on Due section.
- Nav bar color should retain the context color.
- Back button should read as back instead of the previous screen's title.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/175496667-aa16a9e3-06c7-4f84-9ff1-6ec8ffd32ecb.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/175497599-adbc8b1e-686d-4f85-8bbe-57baa568faf9.png"></td>
</tr>
</table>
=> Fix edit due dates screen nav bar

Student/Student/StudentAppDelegate.swift
refs: MBL-16067
release note: Fixed admin is logged out leaving student view.
test plan: See ticket. **Use your own siteadmin login.**
=> Exiting "Act As User" logs the admin out of their account as well

Core/Core/UIViews/HelmNavigationController.swift
refs: MBL-16123
test plan:
- See ticket.
- Check if pop gesture still works correctly if there are multiple view controllers in the stack (except on Homeroom tab where this gesture is disabled)
=> Disable pop gesture on root navigation controllers

Student/Student/StudentTabBarController.swift
refs: MBL-16134
test plan:
- Log in to a K5 account using a split capable iPhone.
- Rotate homeroom while in a course details to landscape and back.
- App should stay on course details.
- Check for regression issues on small screen iPhones and on an iPad also in non-K5 mode.
=> Disable split view on homeroom tab.

Core/Core/LTI/LTITools.swift, Core/Core/Login/LoginDelegate.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, TestsFoundation/TestsFoundation/Login/TestLoginDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
refs: MBL-16109
release note: Fixed open external tools in Safari settings.
test plan: See ticket. 
- In the Canvas app settings toggle the 'Open external tools in Safari' and see if Canvas opens the New Analytics in Safari. 
- In Safari settings set the 'Prevent Cross-Site Tracking' off to see the tool in iframe load on the Online Attendance tab.
=> New Analytics Online Attendance gives 401 error

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/API.swift, Core/Core/API/APIFormData.swift, Core/Core/API/APIRequestable.swift, Core/Core/Extensions/InputStreamExtensions.swift, Core/Core/Extensions/OutputStreamExtensions.swift, Core/Core/Extensions/URLRequestExtensions.swift, Core/Core/Files/APIFile.swift, Core/CoreTests/API/APIFormDataTests.swift, Core/CoreTests/API/APIRequestableTests.swift, Core/CoreTests/Extensions/InputStreamExtensionsTests.swift, Core/CoreTests/Extensions/URLRequestExtensionsTests.swift
refs: MBL-16104
release note: Fixed a crash on submitting big files.
test plan:
- Try to submit a big file with the share extension. (On an iPhone SE2 a 105 MB pdf was enough. The app also crashes but it requires a larger file.)
- Submission should go through without the share extension crashing.
- Check if file upload works from the application.
<table>
<tr><td/><th>Application memory usage while uploading a 105 MB pdf file</th></tr>
<tr>
<th>Before</th>
<td><img src="https://user-images.githubusercontent.com/72396990/177749296-4ec3d7d6-8405-46cd-8ffe-413eac9e0f0d.png"></td>
</tr>
<tr>
<th>After</th>
<td><img src="https://user-images.githubusercontent.com/72396990/177749336-52c066d5-478a-41bc-b558-f167dacb6f9b.png"></td>
</tr>
</table>
=> Move http upload body creation from memory to file

Core/Core/Dashboard/Model/CourseSectionStatus.swift, Core/CoreTests/Dashboard/Model/CourseSectionStatusTests.swift
refs: MBL-16157
release note: Fixed courses show as past enrollments when logged in through trust URL
test plan: See ticket. Check if [MBL-16035](https://github.com/instructure/canvas-ios/pull/2160) and [MBL-16035_2](https://github.com/instructure/canvas-ios/pull/2161) are still working properly.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/178981483-680e09df-143b-493c-9d40-8643de406c3c.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/178981243-4a93a28b-cfea-48a3-972d-204f0a878079.png"></td>
</tr>
</table>
=> Courses show as past enrollments when logged in through trust URL

Core/Core/Assignments/APIAssignment.swift, Core/Core/Assignments/Assignment.swift, Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift, Core/Core/Assignments/AssignmentEditor/AssignmentOverridesEditor.swift, Core/Core/Assignments/GetAssignments.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Assignments/APIAssignmentTests.swift
refs: MBL-16189
release note: Fixed assign to everyone else still shows up when it does not apply to an assignment.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/186427225-0d11662b-8aef-4fba-801c-5abde66760a3.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/186427234-18acae30-2b99-4091-a847-94ea0141de6f.png"></td>
</tr>
</table>
=> Assign to everyone else still shows up when it does not apply to an assignment

Core/Core/Profile/SideMenu/SideMenuBottomSection.swift, Core/Core/Profile/SideMenu/SideMenuItem.swift, Core/Core/Profile/SideMenu/SideMenuMainSection.swift, Core/Core/Profile/SideMenu/SideMenuOptionsSection.swift, Parent/Parent/Dashboard/DashboardViewController.swift, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
refs: MBL-16219
release note: Fixed the count of unread Inbox messages won't show in the side menu.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/187470104-dc92eb97-39d4-4489-b0d9-2861f08fbf4e.png" height=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/187469875-a5b77b6e-c623-4d35-880c-fffbe1b52e73.png" height=500></td>
</tr>
</table>
=> Side menu won't show unread Inbox capsule

Core/Core/Courses/APICourse.swift, Core/Core/Courses/Course.swift, Core/Core/Courses/K5/View/Subject/K5SubjectView.swift, Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Courses/APICourseTests.swift
refs: MBL-16129
release note: Added banner image support for Canvas for elementary courses.
<table>
<tr><th>Course image overlay</th><th>Banner image overlay</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/188158687-a6118f2e-036f-43c1-9c44-bfc3688ede8d.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/188158695-7e313f41-d54a-432f-9704-ff7e051b6232.png" maxHeight=500></td>
</tr>
</table>
=> Support for course banner image

CanvasCore/CanvasCore/ReactNativeModules/CoreWebViewWrapper.swift, Core/Core/Courses/K5/View/Subject/K5SubjectView.swift, Core/Core/Dashboard/K5/Model/Schedule/PlannerOverrideUpdater.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Discussions/DiscussionReplyViewController.swift, Core/Core/EmbeddedWebPage/View/EmbeddedWebPageView.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Pages/PageDetails/PageDetailsViewController.swift, Core/Core/SwiftUIViews/WebView.swift, Core/Core/Syllabus/SyllabusViewController.swift, Core/Core/TermsOfService/TermsOfServiceViewController.swift, Core/Core/UIViews/CoreWebView.swift, Core/Core/UIViews/CoreWebViewController.swift, Core/Core/WebSitePreview/ViewModel/WebSitePreviewViewModel.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift, Core/CoreTests/Discussions/DiscussionReplyViewControllerTests.swift, Core/CoreTests/Syllabus/SyllabusViewControllerTests.swift, Core/CoreTests/UIViews/CoreWebViewTests.swift, Parent/Parent/AccountNotifications/AccountNotificationDetailsViewController.swift, Parent/Parent/Assignments/AssignmentDetailsViewController.swift, Parent/Parent/Discussions/DiscussionDetailsViewController.swift, Parent/Parent/Planner/CalendarEventDetailsViewController.swift, Student/Student/Planner/CalendarEventDetailsViewController.swift, Student/Student/Quizzes/QuizDetails/QuizDetailsViewController.swift, Student/Student/Quizzes/QuizDetails/QuizWebViewController.swift, Student/Student/Routes.swift, Student/Student/Submissions/SubmissionRubric/RubricLongDescriptionViewController.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift
Adds the option to pull to refresh `CoreWebView` and `WebView`. 
refs: MBL-16026
release note: Added pull to refresh for webViews
<table>
<tr><th>K5SubjectView</th><th>Hybrid Discussion Details</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/187870346-e40570e4-7b36-4844-9418-513e4caf8157.png" height=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/187870358-cbf05101-2844-48af-8e00-b5a575cdceb0.png" height=500></td>
</tr>
</table>
=> Pull to refresh for webViews

Core/Core.xcodeproj/project.pbxproj, Core/Core/Dashboard/View/FileUploadNotificationCard.swift, Core/Core/Files/FileUploadProgress/View/FileProgressListView.swift, Core/Core/SwiftUIViews/ProgressBar.swift
The iOS SDK doesn’t provide an infinite progress indicator in its standard library, but we need a way to indicate that a long running task is being processed.
refs: MBL-16253
test plan: Submit file via share extension
<table>
<tr><th>Preparing and progress animation</th></tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/110813321/190137282-24e0dc15-2cab-4b9e-9b1a-17e2bcdf983d.mp4" maxHeight=500></td>
</tr>
</table>
=> ProgressBar SwiftUI component

rn/Teacher/src/modules/inbox/Compose.js, rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Compose.test.js.snap
refs: MBL-16222
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/190637059-8006d8d7-5d61-47a2-b599-a18df18dd856.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/190637061-7e5ef3e9-c469-406a-ad8c-bc41c88e922a.png" maxHeight=500></td>
</tr>
</table>
=> Dark Mode | + Button in "To" field is dark on black

Core/Core.xcodeproj/project.pbxproj, Core/Core/AppEnvironment/InterprocessNotificationCenter.swift, Core/CoreTests/AppEnvironment/InterprocessNotificationCenterTests.swift
This PR adds a notification center class to support communication between the app and its share extension. This will be used to communicate file upload state changes between the app and the file share extension. So far it's not used anywhere yet.
refs: MBL-16144
affects: none
=> Interprocess notifications center

Core/Core.xcodeproj/project.pbxproj, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Profile/Settings/PairWithObserverViewController.swift, Core/Core/UIViews/CoreActivityViewController.swift, Core/CoreTests/Files/View/FileDetails/FileDetailsViewControllerTests.swift, Core/CoreTests/UIViews/CoreActivityViewControllerTests.swift
refs: MBL-16254
test plan:
- Start either Student or Teacher app.
- Go to Files.
- Select a file.
- Tap the share icon on the top right corner.
- Send the app to background.
- Activate the app.
- Share extension shouldn't be visible.
--
- Start either Student or Teacher app.
- Go to Files.
- Select a file.
- Tap the share icon on the top right corner.
- Select student app to activate file share extension.
- Send the app to background.
- Activate the app.
- Share extension should still be visible.
=> Dismiss share sheet on app backgrounding.

Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift, Core/CoreTests/Courses/K5/ViewModel/K5SubjectViewModelTests.swift
refs: MBL-16229
release note: Fixed elementary module progress not updating when submitting a module assignment with the share extension.
<table>
<tr>
<td><video src="https://user-images.githubusercontent.com/72396990/192723721-13111410-48a6-4778-b026-8dbfdedcd1a9.mov" maxHeight=500></td>
<td><video src="https://user-images.githubusercontent.com/72396990/192723797-6c0e2c6e-4c74-4dbc-8bae-c077471824f8.mov" maxHeight=500></td>
</tr>
</table>
=> Refresh elementary modules page on app foreground event.

Core/Core/Profile/SideMenu/SideMenuItem.swift, rn/Teacher/src/canvas-api/apis/courses.js, rn/Teacher/src/modules/inbox/CourseSelect.js, rn/Teacher/src/modules/inbox/__tests__/CourseSelect.test.js
refs: MBL-16248, MBL-16279
release note: Fixed soft-concluded enrollments still appear in Inbox course list.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/193039298-6770b908-9c92-4637-a077-84840691648a.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/193039288-ad3da3ed-31a7-439d-a88a-0f25078bec11.png" maxHeight=500></td>
</tr>
</table>
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/193039527-2dada17c-5b00-4d70-ab9a-45ca8fe3f6f7.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/193039537-ffb45e5f-5e07-47a9-8c94-5eec8e2e88a7. …
=> Soft-concluded enrollments still appear in Inbox list

Core/CoreTests/Dashboard/ViewModel/Invitations/DashboardInvitationsViewModelTests.swift, Core/CoreTests/Files/FileSubmission/Model/BackgroundActivityTests.swift, Core/CoreTests/UIViews/CoreActivityViewControllerTests.swift, TestsFoundation/TestsFoundation/Element/Element.swift
=> Use waitUntil instead of running the main RunLoop for a fixed amount of time in unit tests.

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Planner/CalendarEvent.swift, Core/Core/Syllabus/SyllabusSummaryViewController.swift, Core/CoreTests/SubmitAssignmentExtension/Model/FilePreviewProviderTests.swift, Core/CoreTests/Syllabus/SyllabusSummaryViewControllerTests.swift
refs: MBL-16258
release note: Fixed calendar events from other course sections showing up in syllabus summary.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/193298073-787b8f6c-4bf0-41a9-9f61-56472bccc30c.PNG" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/193298126-5ea4fa7c-a58d-4020-a112-440e2e156836.PNG" maxHeight=500></td>
</tr>
</table>
=> Do not show hidden events in syllabus summary

Core/Core/DocViewer/ViewModel/AnnotationDrag/Gesture/DragStartViewModel.swift
refs: MBL-16280
release note: Fixed read-only student annotations being movable in SpeedGrader.
test plan:
- Create a student annotation assignment.
- As a student add a text annotation and submit the document.
- As a teacher open this submission in SpeedGrader.
- Select hand tool and try to move the student’s annotation.
=> Disable moving of non-editable annotations.

Core/Core/DocViewer/Comments/CommentListViewController.storyboard, Core/Core/DocViewer/Comments/CommentListViewController.swift
refs: MBL-16301
release note: Fix annotation comment page dark appearance.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/194236947-170db681-e938-4a79-aa45-c9e69611504d.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/194235866-22b69adb-19c4-4d8c-9b68-d745d2af5a28.png" maxHeight=500></td>
</tr>
</table>
=> Annotation comment page has dark text in textfield and white top section in dark mode

Core/Core/SwiftUIViews/DynamicHeightTextEditor.swift, Core/Core/SwiftUIViews/ViewPreferences/Bounds.swift, rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift
refs: MBL-15705
release note: Fixed comment text box not being tappable in SpeedGrader when Button Shapes a11y feature is enabled.
test plan:
- Disable comment library in the web based SpeedGrader.
- Go to iOS Settings > Accessibility > Display & Text Size, turn on Button Shapes toggle
- Start the teacher app, go to an assignment.
- Check if comment text field if visible and tappable.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/192989227-15f5bc5f-7e4f-41fb-99aa-03dd566258e7.PNG" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/192989276-c063be1f-843b-472b-8ed6-30a6ea1023e3.PNG" maxHeight=500></td>
</tr>
</table>
=> Work around text box rendered out of screen when button shapes is enabled.

Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift, Core/CoreTests/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModelTests.swift
refs: MBL-16298
release note: Fixed homeroom resources tab not loading for elementary accounts in some cases.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/194063747-d63b34e8-e1a6-47c2-803f-70ee71d252f2.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/194063794-858a84da-58b5-4448-ab93-1484efb0be1f.png" maxHeight=500></td>
</tr>
</table>
=> Fetch only active courses for homeroom resources

Core/Core/Syllabus/SyllabusSummaryViewController.swift, Core/Core/UIViews/CircleProgressView.swift, Core/Core/UIViews/CircleRefreshControl.swift, Core/CoreTests/UIViews/CircleProgressViewTests.swift, Core/CoreTests/UIViews/CircleRefreshControlTests.swift
=> Fix pull to refresh circle not disappearing when syllabus is empty.

Core/Core.xcodeproj/project.pbxproj, Core/Core/Planner/PlannerListViewController.storyboard, Core/Core/Planner/PlannerListViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/UIViews/TableViewBackgroundView.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift
refs: MBL-16282
release note: Fix calendar freeze
test plan:
1. Have an account with many events so that they don't fit on one page. (You can spam ToDo events on the calendar page with the + button, create at least 11 items.)
2. Start the app in landscape (iPhone 13 Pro Max).
3. Tap on calendar tab.
=> Fix student calendar freeze

Core/Core.xcodeproj/project.pbxproj, Parent/Parent.xcodeproj/project.pbxproj, Student/Student.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
Student, Teacher, Parent apps were crashing when running on a physical device, because the Heap SDK was not present. This PR fixes it by adding the Heap package to each project.  
refs: MBL-16371
test plan: Try to run the QR build
=> Fix Heap SDK integration

Core/Core.xcodeproj/project.pbxproj, Core/Core/Courses/CourseDetails/View/CourseDetailsView.swift, Core/Core/ViewModifiers/iOS16HideListScrollContentBackground.swift
refs: MBL-16218
release note: Fixed blank course details header on iOS 16.
--- edit or delete this section ---
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/200609801-8efcfdce-d348-42ec-b367-09940185c3ee.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/200609805-10c56308-ae13-4c13-b03d-eaa8991f6ac7.png" maxHeight=500></td>
</tr>
</table>
=> Course details header will not load on iOS 16.0

Core/Core/UIViews/CircleProgressView.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-16350
release note: Fixed non animating loading spinners
<table>
<tr>
<td><video src="https://user-images.githubusercontent.com/110813321/201621466-5a8a87bc-036a-4dd8-a215-d97ce7e5b0f8.mp4" maxHeight=500></td>
<td><video src="https://user-images.githubusercontent.com/110813321/201621478-8b4da397-2460-42cf-a1c4-cf13c34a327d.mp4" maxHeight=500></td>
</tr>
</table>
=> Fix non animating loading spinners

Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
refs: MBL-16392
test plan: Verify that events are not propagated to Heap
=> Disable heap

Core/Core/SwiftUIViews/RemoteImage.swift
refs: MBL-16394
release note: Fixed course header images are flickering on refresh.
=> Dashboard course card images are flickering on refresh

Core/Core/Discussions/DiscussionListViewController.swift, Core/Core/EmbeddedWebPage/ViewModel/DiscussionWebPageViewModel.swift, Student/Student/Routes.swift, Student/StudentUnitTests/RoutesTests.swift
Adds support to redesigned group discussion webview. 
refs: MBL-16028
release note: none 
test plan: 
1. Enabled `react_discussions_post` on web
2. Enabled `hybrid_discussion_details` in the Developer menu
<table>
<tr><th>Native</th><th>WebView</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/203821828-41ee0cd6-06e6-46e6-a566-1208976dcc69.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/203821842-83a34eda-00cb-45f1-93be-a57bb5f6ed03.png" maxHeight=500></td>
</tr>
</table>
=> Add support to group discussions

Core/Core/ViewModifiers/iOS16HideListScrollContentBackground.swift
refs: MBL-16432
release note: Fixed course detail crash 
Potential fix for a crash that occurs on iOS 16.0
=> Fix course details crash

Core/Core.xcodeproj/project.pbxproj, Core/Core/Discussions/AnnouncementListViewController.swift, Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModelLive.swift, Core/CoreTests/EmbeddedWebPage/ViewModel/DiscussionWebPageViewModelTests.swift, Student/Student/Routes.swift, Student/StudentUnitTests/RoutesTests.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/ios/TeacherTests/RoutesTests.swift
Added extra functionality and renamed the `DiscussionWebPageViewModel` to a more generic class that configures itself based on the `EmbeddedWebPageType`. 
---
refs: MBL-16027
release note: none 
<table>
<tr><th>Native</th><th>WebView</th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/205073562-fe49c95e-934b-4bff-8390-4dcb6c008491.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/205073571-8bf9a565-aeb1-4afd-a524-b00b5b4a5682.png" maxHeight=500></td>
</tr>
</table>
=> Add support to hybrid announcement details

Core/Core/Assignments/AssignmentList/ViewModel/AssignmentCellViewModel.swift, Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift, Core/Core/Courses/CourseDetails/ViewModel/Cells/StudentViewCellViewModel.swift, Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsHeaderViewModel.swift, Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift, Core/Core/Courses/CourseDetails/ViewModel/CourseSettingsViewModel.swift, Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift, Core/Core/People/ContextCard/Course/ContextCardViewModel.swift, Core/Core/People/ContextCard/Group/GroupContextCardViewModel.swift, Core/Core/Profile/SideMenu/SideMenuHeaderView.swift, Core/Core/Quizzes/QuizDetails/ViewModel/QuizDetailsViewModel.swift, rn/Teacher/ios/Teacher/SpeedGrader/ViewModel/SubmissionCommentLibraryViewModel.swift
refs: MBL-16459
test plan: No warnings should appear about using an Environment variable outside of an installed view in Xcode.
=> Use AppEnvironment's shared instance instead of Environment

Core/Core/Extensions/URLComponentsExtensions.swift, Core/Core/Router/Router.swift, Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift, Core/CoreTests/Router/RouterTests.swift, Student/StudentUnitTests/RoutesTests.swift
refs: MBL-16427
release note: Fixed some external website urls opening in-app screens instead of the actual url.
test plan:
- See ticket for test data.
- From now on all external http(s) urls passed to the router will open a modal webview with the contents of that url.
=> Fix non-canvas urls opening native screens if the path matches a valid route in the app.

TestPlans/NightlyTests.xctestplan, TestPlans/PRTests.xctestplan, TestPlans/StudentE2E.xctestplan
- `testReplyingWithAttachment` was disabled because it fails on bitrise but it was still enabled in some test plans. Now it's disabled in every test plan.
- There was a non-existing test bundle called SubmitAssignmentTests in the Nightly test plan, I removed it.
=> Student UI test updates

Core/Core/Constants/PermissionName.swift, Core/Core/Contexts/APIPermissions.swift, Core/Core/Contexts/Permissions.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Contexts/PermissionsTests.swift, rn/Teacher/ios/Teacher/Syllabus/TeacherSyllabusTabViewController.swift, rn/Teacher/ios/TeacherTests/Syllabus/TeacherSyllabusTabViewController.swift, rn/Teacher/ios/TeacherTests/TeacherTestCase.swift
refs: MBL-16478
release note: Fixed syllabus edit button not being visible.
test plan:
- Log in to the teacher app.
- Go to syllabus.
- Edit button should be present on the top right corner.
- Tapping it should display the edit syllabus screen.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/214335364-00e172f8-ba14-496a-9e29-bd8df5b0bca4.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/214335428-0be482bb-ee67-4124-90e4-202d9e32754f.png" maxHeight=500></td>
</tr>
</table>
=> Fix syllabus edit button not being visible

Podfile.lock, Student/Student/Notifications/ActivityStreamViewController.swift
I couldn't reproduce the issue but I believe that adding some synchronization logic will prevent the problem from occurring.  
refs: MBL-16450
release note: Fixed no notification message appering on top of notification list
=> Fix no notification message appearing on top of notification list

Core/Core.xcodeproj/project.pbxproj, Core/Core/Login/ViewModel/LoginViewModel.swift, Core/CoreTests/Login/ViewModel/LoginViewModelTests.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
There is a crash that is caused by dropping a user to the dashboard without it being logged in. I couldn't reproduce the crash but found an inconsistency which could cause such issue. What I could always reproduce was an in finite loading spinner.
refs: MBL-16453
test plan:
- Test login, user switching, masquerade, student view in general.
--
- Login to the app.
- Login to web, go to Settings and delete token that was just created for the app.
- In the app tap change user.
- Tap on the account you used to activate it.
- App should return to start page after failing the token validity checks instead of loading infinitely.
=> Fix invalid token user not being logged out properly.

Core/Core/Notifications/NotificationManager.swift
refs: MBL-16455
release note: Fixed an error where disabling the edit communication channel setting causes Unauthorized Error message on startup
=> Fix unauthorized error popup when edit communication channel is disabled

Core/Core/Modules/ModuleList/ModuleItemCell.swift
refs: MBL-16505
release note: Fixed locked mastery path item displaying an empty screen when tapped.
test plan:
- Create a mastery path for an assignment.
- Add the assignment to a module.
- Log in to the app with a student assigned to the assignment.
- Go to course > modules.
- Observe locked mastery path cell below the mastery path assignment.
- Cell text color should be dimmed and taps on it should be ignored.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/217272815-a3015276-1ed0-4ddf-ab4a-951253d4fb7f.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/217272899-9612f0b1-52e0-43dc-8300-059d8a9bb9c7.png" maxHeight=500></td>
</tr>
</table>
=> Add check to mastery path locked state.

Core/Core/LTI/APIExternalTool.swift, Core/Core/LTI/LTITools.swift, Core/CoreTests/LTI/APIExternalToolTests.swift, Core/CoreTests/LTI/LTIToolsTests.swift, Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift, Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift, Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift, rn/Teacher/ios/TeacherTests/Attendance/RollCallSessionTests.swift
Add a check for resource_link_lookup_uuid in url and forward it to API.
refs: MBL-16454
release note: Fixed some embedded LTI tools not opening.
test plan: See my comment in the ticket.
=> Fixed some embedded LTI tools not opening

Core/CoreTests/AppEnvironment/BackgroundVideoPlayerTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, TestsFoundation/TestsFoundation/Element/Element.swift, TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift, TestsFoundation/TestsFoundation/UITests/XCUIApplication.swift, rn/Teacher/ios/TeacherE2ETests/Assignments/DSAssignmentsE2ETests.swift, rn/Teacher/ios/TeacherE2ETests/Assignments/DSContextCardE2ETests.swift
Fix NightlyTests by adding a function that uninstalls the app before each run.
=> fix: Nightly Tests by uninstalling the app before each run

Core/Core.xcodeproj/project.pbxproj, Core/Core/Notifications/NotificationManager.swift, Core/Core/Notifications/PushNotificationError.swift, Core/CoreTests/Notifications/PushNotificationErrorTests.swift, rn/Teacher/ios/TeacherTests/Attendance/AttendanceViewControllerTests.swift
refs: MBL-16520
release note: Fixed an error dialog being shown upon app start for institutions where no push notifications are configured.
test plan:
- Log in to the app on an instance that has no push notifications setup (See ticket for credentials).
- No error messages should display on dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/219326585-f48f0c12-d8e5-45b9-89b4-32b2fc23bfa1.PNG" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/219326645-27e82c5b-4d07-4a4c-b940-a561426b2f28.PNG" maxHeight=500></td>
</tr>
</table>
=> Skip displaying error in case push notifications are not configured.

Core/Core/CoreWebView/CoreWebView.swift, Core/Core/Discussions/DiscussionReplyViewController.swift
refs: MBL-16504
release note: Fixed discussion reply text being cut off.
test plan: Check discussion text in the discussion reply dialog.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/219385466-c5bb7d79-3474-456a-ba1e-c23ad59b8934.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/219385521-e102932e-3323-4f24-b6ce-f3ec4a281c34.png" maxHeight=500></td>
</tr>
</table>
=> Update dark mode switcher button height calculation

Core/Core.xcodeproj/project.pbxproj, rn/Teacher/src/modules/assignment-due-dates/AssignmentDueDates.js, rn/Teacher/src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js, rn/Teacher/src/modules/assignment-due-dates/__tests__/__snapshots__/AssignmentDueDates.test.js.snap
refs: MBL-16521
release note: Removed edit button on Due Date Page 
test plan: Open an assignment's due date page
--- edit or delete this section ---
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/220872161-9eafc565-405e-4a26-97e9-93245ffe22f0.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/220872152-4b4d65ef-0508-4d93-9cdc-9de735367c62.png" maxHeight=500></td>
</tr>
</table>
=> Remove edit button on Due Date Page

Core/Core/CoreWebView/CoreWebView.swift, Core/Core/SwiftUIViews/WebView.swift
refs: MBL-16502
test plan: See video ticket.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/221031577-7acba92a-9c99-4786-a069-9ace2f6a3cc1.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/221031604-e7526fe7-2c70-4114-9d1f-c943f7ff8cc9.png" maxHeight=500></td>
</tr>
</table>
=> Fix webview height calculation

Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
refs: MBL-16536
release note: Fixed text entry submission views can be dismissed with tap out or swipe down gestures.
=> Disable swipe and tap out dismiss for text entry submission view.

Core/Core/Profile/Settings/ProfileSettingsViewController.swift, Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift
refs: MBL-15480, MBL-16523
test plan:
- Open Settings in side menu.
- Subscribe to Calendar Feed and Pair with Observer menu items shouldn't be visible.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/223727388-75ed7a00-2c01-4cc0-ad4b-a1eafcacc6a1.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/223727426-bae2d5a2-1771-4fa2-8eff-59a07c287bcc.png" maxHeight=500></td>
</tr>
</table>
=> Hide non-relevant menu items in teacher app

Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift
=> Empty view's nav color not darkened enough

Core/Core/RichContentEditor/RichContentEditor.js
refs: MBL-16583
test plan: 
1. Open a Page for Edit
2. You should see one remove button per image
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/110813321/225045113-6cd5eac2-c220-45b5-866b-70c385c13427.jpeg" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/110813321/225045062-4c3e90fa-97fc-4f59-961b-00423b19b28f.png" maxHeight=500></td>
</tr>
</table>
=> Fix RCE editor remove image overlay button

CanvasCore/CanvasCore/Helm/Helm.swift, Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift, Core/Core/Discussions/AnnouncementListViewController.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Discussions/DiscussionListViewController.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Files/View/FileList/FileListViewController.swift, Core/Core/Pages/PageDetails/PageDetailsViewController.swift, Core/Core/Pages/PageList/PageListViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/Quizzes/QuizDetails/ViewModel/QuizDetailsViewModel.swift, Core/CoreTests/Discussions/AnnouncementListViewControllerTests.swift, Core/CoreTests/Discussions/DiscussionListViewControllerTests.swift, Core/CoreTests/Files/View/FileList/FileListViewControllerTests.swift, rn/Teacher/ios/Teacher/Syllabus/TeacherSyllabusTabViewController.swift, rn/Teacher/src/modules/quizzes/details/QuizDetails.js, rn/Teacher/src/modules/quizzes/details/__tests__/QuizDetails.test.js
refs: MBL-16583
test plan:
- Edit a page in iPad.
- The dialog shouldn't be dismissible with a swipe down gesture nor with a tap outside of the dialog.
- Dialog size should match the New Page dialog's size.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/225021428-3f107217-a5b9-4de5-9ff2-9d968aafe554.PNG" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/225021481-6ebf8f73-69d6-4783-9928-e8d3bab7b536.PNG" maxHeight=500></td>
</tr>
</table>
=> Update edit page dialog presentation options.

Core/Core.xcodeproj/project.pbxproj, Core/Core.xcodeproj/xcshareddata/xcschemes/Core.xcscheme, Core/Core/Courses/CourseDetails/View/CourseDetailsCellView.swift, Core/Core/Courses/CourseDetails/View/CourseDetailsView.swift, Core/Core/Extensions/CGFloatExtensions.swift, Core/CoreTests/Extensions/CGFloatExtensionsTests.swift
refs: MBL-16574
release note: Fixed course details list layout on large accessibility sizes.
test plan:
- Set text accessibility size to the largest possible value.
- Go to course details.
- Cell contents shouldn't overlap.
- Cell icons should also scale with the text.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/226343360-d48216d8-682a-4fc5-aec7-56d3e8422b4d.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/226545083-2351195f-66ff-419a-a8a3-f6d30265c417.png" maxHeight=500></td>
</tr>
</table>
=> Update course details cell layout for large dynamic types

Parent/Parent/Dashboard/DashboardViewController.swift
refs: MBL-16608
release note: Added an acceptable use policy screen on login.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/227897087-e49a27a1-e353-4f7a-8ee5-9348aefe9919.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/79920680/227897083-1633dbb1-2c68-4dea-b989-8d04c00a1c73.png" maxHeight=500></td>
</tr>
</table>
=> Show Acceptable Use Policy (AUP) when needed

Core/Core/UIViews/HelmNavigationController.swift, Parent/Parent/Conversations/ParentConversationListViewController.swift, Parent/Parent/Dashboard/DashboardViewController.swift
=> Inbox status bar color is white on white background

Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Files/View/FileEditor/FileEditorView.swift
refs: MBL-16582
test plan:
- In the teacher app add a file as a comment in the SpeedGrader, then delete it.
- Open student app and go to the comment in submission & rubric.
- Tap on the deleted file.
- An appropriate error message should be displayed.
- Tapping close should dismiss the file dialog.
- The same should happen if you tap on the deleted file in SpeedGrader in the teacher app.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/227218215-49aa9386-9876-4c21-a1e3-734f93527b0e.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/227535687-3d565df2-7826-4bc5-a062-ac5a87c5d330.png" maxHeight=500></td>
</tr>
<tr>
<td><img …
=> Add error message to deleted files

Core/Core/DocViewer/Comments/CommentListViewController.storyboard, Core/Core/DocViewer/Comments/CommentListViewController.swift, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.storyboard, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
refs: MBL-16596
test plan:
- Check comment field in Submission & Rubric menu in assignment details.
- Also check the comment field on a Pin annotation's comments screen.
- They should look the same without any misplacement of the button or the text.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/228369478-6f3a47cc-c95e-40fa-8c24-b95e554fe584.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/228369503-71f4a802-4f86-4a84-920f-e95ff8e7b8e0.png" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/228369538-1a13e76e-8603-48b4-94d1-24316d01c67c.png" maxHeight=500></td>
<td><img …
=> Fix comment text field layout

Core/Core/Login/LoginDelegate.swift, Core/Core/Login/LoginStartViewController.storyboard, Core/Core/Login/LoginStartViewController.swift, Core/CoreTests/Login/LoginDelegateTests.swift, Core/CoreTests/Login/LoginStartViewControllerTests.swift, Parent/Parent/ParentAppDelegate.swift, TestsFoundation/TestsFoundation/Element/LoginStart.swift
refs: MBL-16389
test plan:
- parent app should no longer have the ? icon in the top right corner
- login method label should stay where it was (it was aligned to the help button)
- rest of the login screen should stay the same
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/229132986-4d43a980-dfd4-4e19-9cbc-4d963cc0ad81.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72031065/229132359-68d6704d-b602-4a82-b5ec-ad98ab281625.png" maxHeight=500></td>
</tr>
</table>
=> Remove help icon from parent login screen

Student/StudentE2ETests/Login/LoginStartE2ETests.swift
refs: MBL-16389
affects: none
test plan:
E2E tests should not fail
=> update E2E testcase

Core/Core/Files/View/FileDetails/FileDetailsViewController.swift
refs: MBL-16662
release note: Updated file annotation toolbar icon color for better readability.
test plan:
- Open a pdf file. The easiest is to find/add one in the Files menu in the hamburger menu.
- Turn on editing mode in the navigation bar.
- Observe annotation toolbar icon color.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/233679068-622d5152-02be-463f-82cb-a702cb28cc48.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/233679083-e5b0d998-9318-447e-80d6-56bc1f3f859a.png" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/233679101-d17fa0aa-96ad-4b8b-8a78-4d317df56568.png" maxHeight=500></td>
<td><img …
=> Update file annotation toolbar icon color for better readability

Core/Core/Router/Router.swift, Core/CoreTests/Router/RouterTests.swift
refs: MBL-16663
release note: Fixed push notifications not opening screens inside the app for institutes with multiple domains.
=> Update router to always try to open urls from push notifications natively

Core/Core/UIViews/ListBackgroundView.swift
This change removes a hack from ListBackgroundView that causes an infinite layout cycle in some cases. This view is used on a lot of other places in the app so I marked all apps as affected. When testing please also take a look on these pages if the layout is still ok.
- Conferences
- Announcements
- Discussions
- Files
- Grades
- Modules
- Pages
- Peoples
- Calendar Filter
- Quizzes
- ToDos
- CourseList
- Students (parent app only)
- Alerts (parent app only)
- Submissions (teacher app only)
refs: MBL-16703
release note: Fixed a crash on app start when landing page is set to the ToDo tab.
test plan:
- Use an iPhone with notch and iOS 16.
- Start the teacher app.
- Set the landing page to the ToDo tab.
- Restart the app.
- Check layout on affected pages.
=> Remove tableview header and footer re-set to avoid infinite cycle.

Core/Core/AppEnvironment/Keychain.swift, Core/Core/UITestHelpers/UITestHelpers.swift, Core/CoreTests/CoreTestCase.swift, Student/StudentUnitTests/StudentTestCase.swift, TestsFoundation/TestsFoundation/Fixtures/Keychain/KeychainEntryFixture.swift, TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift, rn/Teacher/ios/TeacherTests/TeacherTestCase.swift
In case of testing the regular keychain ID was replaced by a test keychain ID in order not to delete already logged in users on the test device and separate test users from manually logged in users.
This had multiple downsides:
- The test ID wasn't shared so its contents were't visible by the share extension or the widgets.
- It added extra logic to the app and tests were running in an altered app state.
- In order to add support to share extension or widget testing some code would have had to be added to production code within these modules.
Our decision was to remove this extra code so now we can test the share extension or the widgets.
refs: MBL-16261
test plan: E2E tests should run just as before.
=> Remove the usage of the test keychain.

Core/Core/API/API.swift, Core/CoreTests/API/APITests.swift, rn/Teacher/src/canvas-api/apis/file-uploads.js
- Update file upload API to work with uppercase parameter name in file upload target response.
- Increase rate-limit timeout to avoid API requests being retried in an infinite cycle.
refs: MBL-16697
release note: Fixed Inbox attachments not uploaded correctly on some self-hosted instances.
test plan: Test if file attachments from inbox upload correctly on the account in the ticket and on a regular canvas-hosted account.
=> Update file upload API for self-hosted institutions

Core/Core/UIViews/GradeCircleView.swift, Core/CoreTests/UIViews/GradeCircleViewTests.swift
refs: MBL-16715
release note: Fixed 89 points being displayed for assignments without any points possible no matter what the submission's score was.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/236865926-06f4bf93-dbb1-4fad-ad5e-7762edfc3440.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72396990/236865943-672a26a3-b62a-4768-af4f-4c705dc473ab.png" maxHeight=500></td>
</tr>
</table>
=> Update grade display logic to display the score when there are no points possible

Core/Core/API/APIMock.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift, TestPlans/NightlyTests.xctestplan, TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
refs: MBL-16743
release note: Fixed file picker dialog not always dismissed after a successful submission.
test plan:
- Submit a file to a file submission.
- After successful submission the file picker dialog should disappear.
- Related UI test should pass on CI.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/bbd28343-3911-4b67-9573-8da1f8ef6974" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/fe995928-e98a-4429-a36f-b93aa36ac813" maxHeight=500></td>
</tr>
</table>
=> Fix file picker dialog not always dismissed after a successful submission

Core/Core/PageViewAnalytics/PageViewEventController.swift, Core/Core/PageViewAnalytics/PageViewEventRequestManager.swift, Core/Core/PageViewAnalytics/Persistency.swift, Core/CoreTests/PageViewAnalytics/PageViewEventRequestManagerTests.swift, Core/CoreTests/PageViewAnalytics/PageViewEventViewControllerLoggingProtocolTests.swift, Core/CoreTests/PageViewAnalytics/PersistencyTests.swift
The issue was that all page events were stored in a single file and were uploaded using the currently logged in user's credentials even if those events were registered by another user. I modified the queue logic so that events are filtered based on the reporting user's ID when working with the queue.
refs: MBL-16692
test plan: 
- See ticket for usernames and passwords. (First two links in the additional details section.)
- Log in as Eliza Moran on the tudy domain to the student app.
- Switch user and log in as Augusta McDaniel to the zac domain.
- Visit a few screens in the app as either user.
- Switch user to the other one.
- You can repeat the screen visits and user switches a few times.
- Check both account's page views on web.
- There …
=> Change queue handling to work only with the currently logged-in user.

CanvasCore/CanvasCore/ReactNativeModules/CanvasCrashlytics.m, Core/Core/CourseSync/CourseSyncSelector/CourseSyncSelectorAssembly.swift, Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractor.swift, Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorPreview.swift, Core/Core/CourseSync/CourseSyncSelector/View/CourseSyncSelectorView.swift, Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift, Core/Core/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Dashboard/CourseCardList/View/DashboardCourseCardView.swift, Core/CoreTests/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelItemTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelTests.swift, Student/Student/Routes.swift, Student/StudentUnitTests/RoutesTests.swift
refs: MBL-16738
test plan:
- Added kebab menu to dashboard nav bar and to the customize course button. These appear in the student app if the offline feature flag is enabled.
- Added a filtering option to the offline selector screen. Opening this screen from a course should display only that course in the selector.
- The navigation bar subtitle should also reflect if course filtering is enabled or not. I couldn't work out the clipped subtitle so far.
- Raised react log level to maximum, this should eliminate all the annoying console logs.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/4d450e54-ebb6-483f-92b3-fee1231c5cdd" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/0483 …
=> Add support for course filtered offline sync UI

Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/DeveloperMenu/DeveloperMenuView.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
HeapID and Access Token is now available in the Developer Menu. 
refs: MBL-16732
release note: none 
test plan:  See ticket
<table>
<tr><th>HeapID</th><th>Access Token</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/7d96ec05-baa6-475e-ba5c-3a756ab795e2" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/bc5502c6-647c-4263-aabd-031463636847" maxHeight=500></td>
</tr>
</table>
=> Add HeapID and Access Token to developer menu

Core/Core/CourseSync/CourseSyncSettings/View/CourseSyncSettingsView.swift
refs: MBL-16665
test plan: Description texts on offline sync settings screen should be left aligned.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/5c49f624-d277-4850-b263-217c5eb7001f" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/6b5eac00-54c6-4efd-b903-db285d48a822" maxHeight=500></td>
</tr>
</table>
=> Fix offline settings text layout

Core/Core/Assignments/AssignmentList/View/AssignmentListView.swift
I noticed this typo while working on another ticket.
=> Fix assignment list page view name.

Core/Core/Extensions/UITextViewExtensions.swift, Core/Core/SwiftUIViews/DynamicHeightTextEditor.swift, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.storyboard, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift, rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift
refs: MBL-16726
release note: Improved submission comment entry field.
test plan: See ticket. Submission comments should grow up to 10 lines both on student submission and teacher speedgrader pages. Drawer should override the textview height. Comments should be scrollable.
=> Long submission comments do not retain focus

Core/Core/AppEnvironment/Brand.swift, Core/CoreTests/Extensions/UITabBarExtensionsTests.swift
refs: MBL-16823
release note: Fixed tab bar bright selection color.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/0e2859b9-30d8-45bb-8118-617da14ac364" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/b4c5ccb7-71bb-481b-998c-d52083b34d4b" maxHeight=500></td>
</tr>
</table>
=> Certain hex colors will not show in the app and appear invisible

scripts/generate-release-notes.js
refs: MBL-16820
affects: none
test plan: Release script should work even if a jira ticket number in the commit template is missing the MBL- prefix.
=> Prefix jira ticket numbers if they only contain numbers.

Core/Core/Extensions/ArrayExtensions.swift, Core/Core/Extensions/UIViewControllerExtensions.swift, Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.swift
Test the following things: 
- The fix for this [PR](https://github.com/instructure/canvas-ios/pull/2457) fix still works
- Open a Student/Teacher, open a Course, Discussion, rotate the device back and forth. You shouldn't see items appearing multiple times
=> Fix navigation items being added multiple times

Core/Core/DeveloperMenu/DeveloperMenuView.swift
refs: MBL-16706
test plan:
- Open developer menu.
- Design should be according to the latest app standards.
- Cells should register taps when touched on an empty area.
- Open a menu item and close it.
- Menu items shouldn't duplicate.
- Two new items should be available. One for the app directory and another for the shared container dir.
=> Update developer menu

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift, Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntryProgress.swift, Core/Core/CourseSync/Common/Models/Entities/CourseSyncFileProgress.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractor.swift, Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressObserverInteractor.swift, Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractor.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressObserverInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/Model/Entities/CourseSyncItemSelectionTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/Model/Entities/CourseSyncSelectorEntryTests.swift, Core/project.yml, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
Progress reporting logic
refs: MBL-16724
test plan: See more below
1. In terminal, cd to project root. 
2. Copy this git diff below to your clipboard
<details closed>
<summary>  Click here to expand </summary>
<br>
```
diff --git a/Core/Core/Dashboard/CourseCardList/ViewModel/DashboardCourseCardListViewModel.swift b/Core/Core/Dashboard/CourseCardList/ViewModel/DashboardCourseCardListViewModel.swift
index f6ac6a9f07..2e342e1e90 100644
--- a/Core/Core/Dashboard/CourseCardList/ViewModel/DashboardCourseCardListViewModel.swift
+++ b/Core/Core/Dashboard/CourseCardList/ViewModel/DashboardCourseCardListViewModel.swift
@@ -33,6 +33,7 @@ public class DashboardCourseCardListViewModel: ObservableObject {
// MARK: - Private properties
private var subscriptions = …
```
=> Offline course sync progress reporting logic

Core/Core.xcodeproj/project.pbxproj, Core/Core/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Dashboard/OfflineSync/DashboardOfflineSyncProgressCardAssembly.swift, Core/Core/Dashboard/OfflineSync/Model/DashboardOfflineSyncInteractorPreview.swift, Core/Core/Dashboard/OfflineSync/View/DashboardOfflineSyncProgressCardView.swift, Core/Core/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModel.swift, Core/Core/en.lproj/Localizable.stringsdict, Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractorLiveTests.swift, Core/CoreTests/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModelTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, TestsFoundation/TestsFoundation/Router/TestRouter.swift
refs: MBL-16649
test plan:
- Start an offlline sync.
- Observe the dashboard notification about the sync progress.
- Try using the dismiss button.
- Check voiceover.
https://github.com/instructure/canvas-ios/assets/72396990/0d408ff0-b32f-40c2-af81-aa975cbe56b4
=> Offline sync dashboard notification

Core/Core/Contexts/TabName.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift, Core/Core/Courses/CourseDetails/Model/TabFilter.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
- Extract offline syncable tabs array to a public property.
- Update CourseSyncInteractor to automatically sync all offline syncable tabs.
- Added a safety check that triggers in debug builds when the CourseSyncInteractor received no CourseSyncContentInteractor from the assembly.
CI: I want a Student build so we can check if sync still works.
=> Improve course sync interactor setup

Core/Core.xcodeproj/project.pbxproj, Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/Conferences/ConferenceDetailsViewController.swift, Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncConferencesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift, Core/Core/Courses/CourseDetails/Model/TabFilter.swift, Core/Core/Offline/OfflineModeInteractor.swift, Core/Core/Offline/View/NotSupportedInOfflineAlert.swift, Core/Core/Offline/View/UIButtonOfflineSupport.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncConferencesInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift
- Added conference data downloader.
- Updated conference details for offline mode.
- Fixed a crash when presenting offline alert from tap gesture recognizer.
- Fixed a warning about UI being modified from background thread.
refs: MBL-16769
test plan:
- Sync the BigBlueButton tab for offline usage.
- Turn off internet on the device.
- Go to BigBlueButton page.
- List should show both ongoing and concluded conferences.
- Conference details page should have the join button disabled when visiting an active conference.
=> Offline conferences

Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncAnnouncementsInteractor.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncAnnouncementsInteractorLiveTests.swift
refs: MBL-16770
test plan:
- Sync Announcements tab for offline usage.
- Turn off internet on the device.
- Go to Announcements list.
- Announcements should appear.
- Enter an announcement.
- Announcement and replies should render.
- Images/MathJax equations won't be available.
- User actions shouldn't be available beside the replies button that is show is there are too many replies in a thread.
=> Offline announcements

Core/Core/Discussions/DiscussionReplyViewController.swift, Core/Core/Files/View/FilePicker/FilePicker.swift, Core/CoreTests/Files/View/FilePicker/FilePickerTests.swift
Move picked file from app inbox to temp folder.
refs: MBL-16906
release note: Fixed multiple issues with file attachment while replying to a discussion.
test plan:
- Go to a discussion, tap on reply.
- Use the paperclip icon to attach a file using the "Upload File" option.
- Send the app to the background for 1 minute.
- Go back to the app.
- Tap the paperclip icon, tap "View".
- File should be displayed instead of a gray screen with its filename on it.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/5f31a579-bc8a-4831-b1cb-cf2138c44b33" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/a89f6652-e49c-4923-905b-4b17877441ac" maxHeight=500></td> …
=> Fix attached file getting deleted by iOS

Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift, Core/Core/Router/Router.swift, Core/CoreTests/Modules/ModuleItems/ModuleItemDetailsViewControllerTests.swift, TestsFoundation/TestsFoundation/Router/TestRouter.swift
Add screen view event when ModuleItemDetailsViewController loads a child view controller without using the router's route method.
refs: MBL-16906
test plan:
- Module sequence still works.
- Upcoming crashes should include screen view events visited via the module sequence view controller.
=> Add screen view logging to ModuleItemDetailsViewController

Core/Core/Pages/APIPage.swift, Core/CoreTests/Pages/APIPageTests.swift
refs: MBL-16763
test plan:
- Sync "Pages" for offline mode.
- Go offline, check page details page.
- Page body should display.
- Go online, pull to refresh the pages list screen.
- Go offline again check page details.
- Page body should still display.
=> Update page list API call to include page body

Core/Core/Assignments/AssignmentList/View/AssignmentListView.swift, Core/Core/Offline/OfflineModeInteractor.swift, Core/Core/Offline/View/UIButtonOfflineSupport.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift
refs: MBL-16761
test plan:
- Sync assignments for offline mode.
- Go offline.
- Enter assignments list view.
- Filter button should be disabled.
- Go to an assignment detail page.
- Submission and rubric, submit buttons should be disabled.
=> Disable not available assignment buttons in offline mode

Core/Core/DocViewer/DocViewerViewController.swift, Core/Core/DocViewer/Model/DocViewerAnnotationProvider.swift, Core/Core/DocViewer/ViewModel/AnnotationDrag/Gesture/Helpers/DocumentExtensions.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift, Core/CoreTests/DocViewer/Mocks/MockDocViewerAnnotationProvider.swift
- Use `isEditable` property instead of `readOnly` flag to disable editing on annotations inside the pdf file.
- Amend move tool to check for this new property.
- Embed annotation fetch calls in thread safe blocks according to the guidelines.
refs: MBL-16848
release note: Fixed annotations in pdf files not styled to correctly.
test plan:
- See ticket if the correct style is applied to pdf annotations.
- Annotations from a pdf file shouldn't be editable.
- Move tool should work on canvas annotations.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/9c2a7156-766a-4f2a-974d-2c0eeabe69fb" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/18e4edc4-04e2-45 …
=> Fix annotations in pdf files not styled to correctly

Core/Core/Login/LoginStartViewController.storyboard, Core/Core/Login/LoginStartViewController.swift
refs: MBL-169968
release note: Fixed color contrast accessibility requirements on the login page.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/35f375ae-7ee1-4cfb-be70-8a29af97aaa1" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/e7470106-6e6b-4e88-a614-24335582d6ed" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/a1c0fc3d-a923-48ae-86ce-78aeb2fb9259" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/69fb4305-7c0a-429c-9a59-c2642b38a02e" maxHeight=500></td>
</tr>
<tr>
<td><img …
=> "Canvas" text on the login page does not meet contrast requirements

Core/Core/Offline/View/OfflineBannerView.swift, Core/Core/Offline/View/OfflineBannerView.xib
refs: MBL-16773
test plan:
- Change app to dark mode to make the error stand out.
- Go offline.
- Scroll the dashboard up and down to see if there's a space between the tab bar and the offline banner.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/8d514b2d-a892-4d1c-aa02-98c14cb9ffa7" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/1ec841b5-cd9d-4782-b91e-16fa5e70d8f4" maxHeight=500></td>
</tr>
</table>
=> Fix offline banner alignment

Core/Core/CoreWebView/CoreWebView.swift, Core/Core/CoreWebView/CoreWebViewJSInjections.swift
refs: MBL-16989
release note: Studio media content now shows up on details and edit pages instead of launching as an external LTI tool.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/25fe452e-273f-434b-be49-263082183c4c" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/79920680/9f19ac80-9f07-4c63-8e19-b61d0a7f54fa" maxHeight=500></td>
</tr>
</table>
=> Allow embedded Studio videos in RCE content

Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/Common/Models/Entities/CourseSyncDownloadProgress.swift, Core/Core/CourseSync/Common/Models/Entities/CourseSyncEntry.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncProgressWriterInteractor.swift, Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractor.swift, Core/Core/CourseSync/CourseSyncProgress/View/CourseSyncProgressView.swift, Core/Core/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressInfoViewModel.swift, Core/Core/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressViewModel.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/Model/CourseSyncProgressObserverInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressInfoViewModelTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressViewModelTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
refs: MBL-16885
test: 
1. I suggest to use my account because "Test" course has 100+ MB of files so you can play around with the retry logic. 
2. Start a course sync 
3. Open the progress screen
4. Turn off Wi-Fi
5. Turn back the Wi-Fi (To have an established connection you might need to wait an additional second after the Wi-Fi icon appears) 
6. Tap Retry 
7. You should see the previously failed Course/Tab/File row switches state from Error to Loading
8. If you previously successfully downloaded a couple of files, the total number of bytes should decrease because we are only downloading the ones that failed.
https://github.com/instructure/canvas-ios/assets/110813321/71f9f931-87a0-45a4-b250-a8ee06ceaa01
=> Offline sync retry logic

scripts/generate-release-notes.js
The generate-release-notes script should ignore any case of none (None, NoNe, nONE, etc.) 
with up to one punctuation (eg. nonE?) added.
Longer release notes starting with none should be retained (eg. None of this makes any sense.)
=> Fix 'none' release note handling

scripts/update-jira-issues.js
We have one invalid ticket number (MBL-169968) on master that makes the release script interrupt. With this change we ignore any jira update failures and just continue as it was successful.
=> Make script continue updating issues when one update fails

Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/Common/Models/CourseSyncListerInteractor.swift, Core/CoreTests/CourseSync/Common/CourseSyncListInteractorLiveTests.swift
Make CourseSyncListInteractorLive stateless so calling `getCourseSyncEntries` no longer requires to keep the interactor in memory along with the stream subscription anymore.
=> Refactor CourseSyncListInteractorLive

Core/Core.xcodeproj/project.pbxproj, Core/Core/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Dashboard/OfflineSync/View/DashboardOfflineSyncProgressCardView.swift, Core/Core/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModel.swift, Core/CoreTests/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModelTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
refs: MBL-16998
release note: none 
test plan: Start download, turn off Wi-Fi, check notification. 
Notes: 
1. The actual retry logic needs some polish, please focus on the dashboard notification handling for now. 
2. As discussed earlier, the error messages are not yet finalized. 
https://github.com/instructure/canvas-ios/assets/110813321/5d05da7c-23b3-4323-9fd7-4f8be096a02e
=> Offline dashboard notification error state

Core/Core.xcodeproj/project.pbxproj, Core/Core/BackgroundProcessing/BackgroundProcessingAssembly.swift, Core/Core/BackgroundProcessing/Model/BackgroundProcessingInteractor.swift, Core/Core/BackgroundProcessing/Model/BackgroundTask.swift, Core/Core/BackgroundProcessing/Model/CoreBGTask.swift, Core/Core/BackgroundProcessing/Model/CoreBGTaskScheduler.swift, Core/CoreTests/BackgroundProcessing/Model/BackgroundProcessingInteractorTests.swift, Student/Student.xcodeproj/project.pbxproj, Student/Student/BackgroundProcessing/CoreTaskSchedulerLive.swift, scripts/coverage/config.json
This PR adds entities to facilitate background app updates in a generic way.
- **BackgroundProcessingInteractor**: This class communicates with the system and executes the background task that was previously registered for running.
- **BackgroundTask**: Conform to this protocol and implement any custom logic that needs to be run in the background.
- **CoreBGTask**: This is just an abstraction over the `BGTask` class that has no available initializers so we can't use it for testing purposes. This protocol makes testing of `BackgroundProcessingInteractor` possible.
- **CoreBGTaskScheduler**: This is again a protocol and its purpose is to hide the `BGTaskScheduler` from the `Core` project. The reason is that `Core` is an "App-Extension-Safe API" project and it can't directly use …
=> Add background update service

Student/StudentE2ETests/Discussions/DiscussionsTest.swift, Student/StudentE2ETests/Files/FilesTests.swift, Student/StudentE2ETests/Settings/SettingsTests.swift, TestPlans/CalendarE2E.xctestplan, TestPlans/CoreTests.xctestplan, TestPlans/IPadTests.xctestplan, TestPlans/NightlyTests.xctestplan, TestPlans/PRTests.xctestplan, TestPlans/ParentE2E.xctestplan, TestPlans/StudentE2E.xctestplan, TestPlans/TeacherE2E.xctestplan, TestsFoundation/TestsFoundation/Helpers/CourseDetailsHelper.swift, TestsFoundation/TestsFoundation/Helpers/DiscussionsHelper.swift
- All of the test plans were set to parallelable.
- Latest [Student E2E test run](https://app.bitrise.io/build/a3db16db-72da-48a8-a503-1b5458242725) resulted in 37 minutes duration. Previous runs had 78 minutes or larger duration.
- Some small minor fixes on some test cases.
=> Parallelise test runs

Core/Core/CourseSync/Common/Models/CourseSyncEntryComposerInteractor.swift
refs: MBL-16871
test plan: Open sync selector, double check if every file is listed.
=> Fix course sync file list

Core/Core/Courses/K5/View/Subject/K5SubjectHeaderView.swift, Core/Core/Courses/K5/View/Subject/K5SubjectView.swift, Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomSubjectCardView.swift, Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomSubjectCardViewModel.swift, Core/CoreTests/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModelTests.swift
- Removed color overlay from subject images.
- Ensured subject card text contrast ratio is high enough.
- Fixed long course names not having a background in homeroom details page.
refs: MBL-17039, MBL-17036, MBL-17037
release note: Fixed contrast issues in homeroom view.
test plan: See tickets
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/149e58f2-3405-40a7-8b65-83e706892b3d" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/e84278a8-1081-4eea-b0a6-a3a5ad17d861" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/a7e588f3-7a62-4410-9e48-39ace6762c4f" maxHeight=500></td>
<td><img …
=> Homeroom updates

Core/Core/CoreWebView/CoreWebViewJSInjections.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift
- Removed unicode combining marks from strings passed to JS to avoid illegal character exception.
- Modified discussion render error handler to load the discussion website instead of showing an alert dialog.
refs: MBL-17012
release note: Fixed discussions not being rendered in some cases.
test plan:
- Log into my account either as a teacher or a student.
- Go to Primary Course > Discussions > Javascript Error
- Discussion should load.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/a58e9b02-0a9e-4d5e-ae0c-d3375fe5f5b4" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/be254769-4214-4b5e-9790-976348cc57e0" maxHeight=500></td>
</tr>
</table>
=> Fix discussions not being rendered in some cases

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/Common/Models/CourseSyncEntryComposerInteractor.swift, Core/Core/CourseSync/Common/Models/CourseSyncListerInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncFilesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractor.swift, Core/Core/Extensions/URLExtensions.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Offline/Model/OfflineFileInteractor.swift, Core/CoreTests/CourseSync/Common/CourseSyncCleanupInteractorTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncEntryComposerInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncFilesInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncInteractorLiveTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
This PR includes the following changes: 
- Whenever we sync a course, files that are persisted on the disk but not present on the server, will be deleted. 
- In order to be able to identify which file belongs to which course, files are now organized as `/Documents/Offline/Files/courseId/fileId/fileName`. 
- Moved file related logic from `CourseSyncEntryComposerInteractor` to `CourseSyncFilesInteractor`.  
refs: MBL-16813
=> Offline sync delete unavailable files

Core/Core/Discussions/APIDiscussion.swift, Core/Core/Discussions/DiscussionEntry.swift, Core/CoreTests/Discussions/DiscussionEntryTests.swift
refs: MBL-17023
release note: Fixed like counter not displaying the proper amount of likes in case someone disliked a post.
test plan:
- Go to a doiscussion that can be liked.
- Like a post with no likes.
- Like counter should display 1
- Dislike it the post.
- Like counter should go to 0.
- Do a pull to refresh.
- Like counter should still show 0.
- It can happen that the like button shows that the post is liked but this will go away after the API refreshes the data and you do a pull to refresh.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/58e7ad5b-782e-448e-83cc-853553edc0a8" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/ed1cc519-8f5a-410c …
=> Fix like counter not displaying the proper amount of likes in case someone disliked a post

Core/Core/CoreWebView/View/CoreWebView.swift
refs: MBL-17016
release note: Improved "Switch To Light Mode" feature for documents.
test plan: See ticket for test files. Also check other places where "Switch To Light Mode" appears if it's still works correctly.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/141ea763-f2cc-4d79-b5eb-f671e879a61c" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/b4afb1ca-f2d5-4b7d-b717-60f407b2768b" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/d1ed2f05-db56-4ee6-9ea6-05666e8f5dbc" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/9ddc4007-3d1b-473a-bb47-4190d2330e …
=> Override user interface style unconditionally when switch to light mode button is pressed.

Core/Core/Modules/ModuleList/ModuleListViewController.swift
refs: MBL-17019
test plan:
- Create a course with modules as home page.
- Log in to the student app with a split view capable device and go to the course's details.
- Modules should display in the detail view.
- Tap on modules on the master list.
- Modules list should appear on the master list and the detail view should show an empty state instead of displaying also the modules list.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/22d8b6f2-089f-4ba2-95e3-c9b5210b94e5" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/fbff7870-713c-4bc5-90e8-0f7a6f940491" maxHeight=500></td>
</tr>
</table>
=> Fix duplicated modules list on screen.

Core/Core/CourseSync/CourseSyncSelector/CourseSyncSelectorAssembly.swift, Core/Core/CourseSync/CourseSyncSelector/View/CourseSyncSelectorView.swift, Core/Core/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Dashboard/CourseCardList/View/DashboardCourseCardView.swift
refs: MBL-17087
test plan:
- Turn the student app to offline mode.
- On the dashboard, tap the kebab menu on the top right corner and select "Manage Offline Content".
- Offline mode dialog should show.
- Tap on the kebab menu on a course and select "Manage Offline Content".
- Offline mode dialog should show.
=> Disable offline mode selection screens in offline mode

Core/Core.xcodeproj/project.pbxproj, Core/Core/Analytics/Analytics.swift, Core/Core/BackgroundProcessing/Model/BackgroundProcessingInteractor.swift, Core/Core/CoreWebView/View/CoreWebView.swift, Core/Core/CourseSync/BackgroundUpdates/Model/OfflineSyncBackgroundTask.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Files/Model/UploadManager.swift, Core/Core/Login/LoginStartViewController.swift, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListService.swift, Core/Core/SubmitAssignmentExtension/Model/AttachmentCopyService.swift, Core/Core/SubmitAssignmentExtension/Model/UTIFromNSItemProvider.swift, Core/Core/SubmitAssignmentExtension/ViewModel/CoursePickerViewModel.swift, Core/CoreTests/Analytics/AnalyticsTests.swift, Core/CoreTests/Analytics/MockAnalyticsHandler.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Files/View/FileDetails/FileDetailsViewControllerTests.swift, Core/CoreTests/Modules/ModuleItems/ModuleItemDetailsViewControllerTests.swift, Core/CoreTests/Router/RouterTests.swift, Core/CoreTests/SubmitAssignmentExtension/Model/API/AssignmentPickerListServiceTests.swift, Core/CoreTests/SubmitAssignmentExtension/Model/UTIFromNSItemProviderTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModelTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/CoursePickerViewModelTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/SubmitAssignmentExtensionViewModelTests.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, Student/SubmitAssignment/SubmitAssignmentViewController.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
- Created dedicated methods for screen view and error events instead of using the generic logEvent method and parsing its payload.
- Merged two AnalyticsHandler mock instances into one.
- Added error logging to error cases.
refs: MBL-17047
test plan: Check crashlytics error logs after a new version is released with these changes.
=> Add error logging to crashlytics

Student/Student/StudentTabBarController.swift
refs: MBL-17111
test plan:
- Change landing page to something other than the Dashboard
- Go offline
- Change user
- Select the previous user
- Landing page should be the dashboard
- Go back online
- Repeat change user, landing page should be the set value
=> Make dashboard the landing page in offline mode

Core/Core/Login/LoginNavigationController.swift, Core/Core/Login/LoginStartViewController.swift, Core/Core/Offline/Model/OfflineModeInteractor.swift, Core/Core/Offline/Model/OfflineModeInteractorMock.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncConferencesInteractorLiveTests.swift, Core/CoreTests/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModelTests.swift, Core/CoreTests/DocViewer/DocViewerViewControllerTests.swift, Core/CoreTests/Login/LoginStartViewControllerTests.swift, Core/CoreTests/Offline/View/UITabBarItemOfflineSupportTests.swift, Core/CoreTests/Offline/ViewModel/OfflineBannerViewModelTests.swift, Core/CoreTests/Offline/ViewModel/OfflineModeViewModelTests.swift
refs: MBL-17003
test plan:
- Go offline
- Any button should result in error popup
- Previous login should work
=> Disable buttons on login screen in offline mode

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core.xcodeproj/project.pbxproj, Core/project.yml, Podfile, Podfile.lock, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
PSPDFKit version bump to 13.0.1 which will fix the crashes. 
Note: Don't forget to pull the secret repo and setup the new keys. 
refs: MBL-16907
release note: Fixed a crash when viewing annotated documents
test plan: Test if PSPDFKit functionality is unchanged.
=> Fix PSPDFKit crash, bump version to 13.0.1

Core/Core/DocViewer/Model/AnnotationContextMenu/DocViewerAnnotationContextMenuModel.swift, Core/CoreTests/DocViewer/Model/AnnotationContextMenu/DocViewerAnnotationContextMenuModelTests.swift
refs: MBL-17128
release note: Fixed text annotation context menu not showing all edit actions without the document being re-opened.
test plan:
- Create a text annotation.
- Tap on it to make its context menu appear.
- 4 context items should appear: Comments, Style, Edit, Remove.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/7e67eb53-1726-4ac2-994b-954e7e23b047" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/1353cc43-2b6f-4644-a903-b425b32cd10f" maxHeight=500></td>
</tr>
</table>
=> Fix text annotation type not being recognized when creating context menu items

Core/Core/CourseSync/BackgroundUpdates/Model/OfflineSyncBackgroundTask.swift, Core/Core/NetworkAvailability/NetworkAvailabilityService.swift, Core/Core/NetworkAvailability/NetworkAvailabilityStatus.swift, Core/Core/Offline/Model/OfflineModeInteractor.swift, Core/CoreTests/CourseSync/BackgroundUpdates/Model/OfflineSyncBackgroundTaskTests.swift
- Also changed the network availability interactor to have an initial state value of nil instead of disconnected so we can decide if the service have received a connection status update from the system or not.
refs: MBL-17134
test plan:
- Do an offline sync in the background while sync only on wifi option is set to on.
- Sync should be skipped in this case and a next sync should be scheduled according to the schedule settings.
=> Respect WiFi only sync setting during background sync.

Core/Core/Quizzes/QuizDetails/ViewModel/QuizEditorViewModel.swift, Core/CoreTests/Quizzes/QuizDetails/QuizEditorViewModelTests.swift
refs: MBL-17139
release note: Fixed multiple attempt setting in classic quiz editor.
=> Correct default allowed attempt number in Quiz Editor

Core/Core/Courses/CourseList/Model/CourseListInteractorLive.swift, Core/CoreTests/Courses/CourseList/Model/CourseListInteractorLiveTests.swift
refs: MBL-16986
release note: Fixed an issue where future unpublished courses were shown in All Courses menu
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/d6b3baca-d6a5-472c-8109-5831a7df8aab" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/1e65fb51-2804-4fca-a302-7201cad0a21c" maxHeight=500></td>
</tr>
</table>
=> Hide unpublished future courses

rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentListCell.swift
refs: MBL-16501
release note: Fixed multi-line file names are not left aligned in SpeedGrader
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/fcd72669-b2df-4d0f-93ad-c1f12e0891ae" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/e86454da-994d-4270-b975-bc760b197f65" maxHeight=500></td>
</tr>
</table>
=> Fix multi-line file names are not left aligned in SpeedGrader

Core/Core/Discussions/DiscussionDetailsViewController.swift
refs: MBL-16503
release note: Fixed an issue where double loading indicators were visible on the discussion details screen
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/231d8b10-cf05-4423-9481-1d80f44a7580" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/e5dd67bd-1657-4b8c-aba2-451715d10b63" maxHeight=500></td>
</tr>
</table>
=> Fix double loading indicator on discussion details

Parent/Parent/Students/StudentDetailsViewController.swift
refs: MBL-17155
release note: Fixed an issue on the Manage Student screen where text field got reset after toggling an alert switch
=> Fix manage student screen alert and threshold behaviour

Core/Core/CoreWebView/Model/CoreWebViewJSInjections.swift
refs: MBL-17167
release note: Fixed accent marks not appearing in discussions and announcements.
test plan: See ticket for details. Check if special characters discussed in MBL-17012 load the web based discussion instead of showing an empty page.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/bef67831-d623-48e9-9f49-fb9898d882bc" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/80ed7735-cbb0-47cb-a690-ca7f1650d082" maxHeight=500></td>
</tr>
</table>
=> Fix accent marks not appearing in discussions and announcements

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-17216
test plan:
- Tap the grade circle on the assignment details page while offline.
- A dialog notifying about action not available in offline mode should appear.
=> Fix grade circle being tappable while in offline mode.

Core/Core/AppEnvironment/FeatureFlags/GetEnabledFeatureFlags.swift, Core/Core/Store/Store.swift, Core/Core/UIViews/GradeCircleView.swift, Core/CoreTests/UIViews/GradeCircleViewTests.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/Student/Submissions/SubmissionRubric/RubricViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift, TestsFoundation/TestsFoundation/Helpers/TestEnvironment.swift
refs: MBL-16516
release note: Added attempt selector to the assignment details page to institutes where Assignment Enhancements is turned on.
test plan: Go to assignment details and select a previous attempt. Grade box should update to reflect that attempt's grade.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/3a631ceb-a317-4e19-bdb7-1496c3bb2fa9" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/c2b49f6e-bead-42b7-8fdc-3590280a81e6" maxHeight=500></td>
</tr>
</table>
=> Add attempt picker to assignment details

Core/Core/SwiftUIViews/CoreDatePicker.swift, Parent/Parent/Assignments/AssignmentDetailsViewController.swift
refs: MBL-17223
release note: Fixed accessibility color issues when selecting a reminder date
<table>
<tr><th>Before- Dark</th><th>After - Dark</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/1e743a85-9a70-4836-a403-9a7c7c4ca2b7" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/a6a7aca9-baf9-4a65-b595-3e647092a186" maxHeight=500></td>
</tr>
<tr><th>Before - Light</th><th>After - Light</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/efc67ef8-ffcc-471f-9a79-1d9ed37d3b21" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/42e51d6c-3b3a-45bd-98b0-3f548dac4db6" maxHeight=500></td> …
=> Fix parent remind me colors

Student/Student/Submissions/SubmissionRubric/RubricLongDescriptionViewController.swift
refs: MBL-17217
release note: Fixed transparent background on rubric description popup.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/7281fd40-2d0f-4c4a-9508-7e559b063d36" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/ff593665-176d-47e5-b7d3-06115b85b3fd" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/8d54e888-df5f-413c-abb2-a53d58b5afd8" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/34bfb1b2-2b23-4340-811e-e40a39e13e36" maxHeight=500></td>
</tr>
</table>
=> Add background to rubric description popup

Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
refs: MBL-17219
release note: Fixed module item screen dismissing itself sometimes.
test plan:
- See ticket for video.
- Try these:
- Go to a module item.
- Switch between module items.
- Go to a module item after a fresh install.
- Rarely the module item screen pops back to modules list (sometimes it does 2 pops) after a short loading.
=> Fixed module item screen dismissing itself sometimes

scripts/translations/export.js, scripts/translations/import.js, scripts/translations/localizables.json, scripts/translations/projects.json
- Removed exporting of react-native translations.
- Deleted step that made PR of new english react strings.
- Removed hub dependency install step that was use by the PR creation step.
- Extracted localizable files list to external file so the import script also can use it.
- Modified the script to use new string catalogs.
- Builds now can fail in case of a misformatted translation so I added the `affects` line to the translations import PR to trigger all app builds and reveal any compilation errors.
- Removed importing of react-native translations.
refs: MBL-17281
test plan: New translations should be correctly imported.
Example [PR](https://github.com/instructure/canvas-ios/pull/2682) is here, just ignore the changes from this branch.
=> Update translation import script

Parent/ParentE2ETests/About/AboutTests.swift, Parent/ParentE2ETests/Help/HelpTests.swift, Student/StudentE2ETests/K5/K5Tests.swift, TestsFoundation/TestsFoundation/Helpers/AssignmentsHelper.swift, TestsFoundation/TestsFoundation/Helpers/DashboardHelper.swift
refs: MBL-17779
affects: None
- testK5DashboardNotificationLimit: Creates 12 assignments with past due date and checks if the dashboard course card shows the correct number
- Some other minor changes in parent tests to be consistent with other tests
=> E2ETest that covers the K5 missing assignments notification limit bug

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Routes.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift, Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsViewControllerTests.swift
- The selected attempt on the assignment details screen will also be shown on the submission and rubric screen.
- Added attempt number to attempt picker on the submission details screen.
refs: MBL-17245
test plan:
- Select an attempt on the assignment details screen.
- Tap on submission and rubric button.
- Submission details screen should show the selected attempt.
- Tap on the attempt selector, attempt numbers should be visible below the attempt date.
- The showed attempt should be pre-selected.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/e11a75b5-45bd-484f-a060-9392ccca7f42" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/2405f49 …
=> Show selected attempt on submission details

Core/Core.xcodeproj/project.pbxproj, Core/Core/CoreWebView/Model/Features/DarkModeForWebDiscussions.swift, Core/Core/CoreWebView/Model/Features/InvertColorsInDarkMode.swift, Core/Core/EmbeddedWebPage/View/EmbeddedWebPageView.swift, Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModelLive.swift, Core/CoreTests/CoreWebView/Model/Features/DarkModeForWebDiscussionsTests.swift
- Reverted the changes we made in the color-invert webview feature for discussions and no longer use it.
- Created a separate feature specifically for dark mode discussions that adds CSS overrides to achieve a dark mode like look.
- Not all elements were turned dark, the RCE editor for example remained in light mode including many others.
- The goal was to make everything readable while add as much dark as possible.
refs: MBL-17311
test plan: Check hybrid discussion in dark mode. Everything should be readable.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/6fc9f80c-7659-4572-8a6e-77735d64f8ff" maxHeight=500></td>
<td><img …
=> Add dark mode css for discussions

Student/StudentE2ETests/K5/K5Tests.swift
refs: MBL-15780
affects: None
Creates a K5 course with invitation state then checks if there is no course card shown on the dashboard for this invited course.
=> K5 E2E test that covers a previous bug

Core/Core/CoreWebView/View/CoreWebView.swift, Core/Core/LTI/LTITools.swift, Core/CoreTests/LTI/LTIToolsTests.swift
refs: MBL-17315
release note: LTI apps like Zoom and Microsoft apps now open properly from K5 courses
https://github.com/instructure/canvas-ios/assets/110813321/578807f7-1c49-4d82-9b01-0557722766f9
=> Handle K5 and other WebView embedded LTI button launches

Parent/ParentE2ETests/Grades/GradesTests.swift, TestsFoundation/TestsFoundation/DataSeeding/User/DataSeeder+DSUser.swift
refs: MBL-17326
affects: None
Modified grade values
An implicit sleep has been added to the createUsers function of DataSeeder so that we can avoid users having the same name
=> Modified occasionally failing test cases

Core/Core/Analytics/Analytics.swift, Core/Core/LTI/LTITools.swift, Core/Core/Router/Router.swift, Core/CoreTests/Router/RouterTests.swift, Parent/Parent/ParentAppDelegate.swift
refs: MBL-17260
release note: Fixed a crash when swiping back to a previous screen.
test plan:
- Manual repro steps not available, most probably somehow a button that causes a navigation is activated on a view controller that is being dismissed with the swipe to back gesture.
- Add a delayed router.show call to a view controller's viewWillDisapper method.
- Do a swipe to back gesture from this view controller but don't finish the gesture just keep the view floating halfway on the screen.
- Wait until the delayed presentation kicks in.
- App shouldn't crash.
- All regular navigation should work just as before.
In the video below I added the following code to the `GradeListViewController.swift` file:
```
public override func viewWillDisappear(_ animated: …
```
=> Detect and swallow invalid presentation state to prevent crash.

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core.xcodeproj/project.pbxproj, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncAnnouncementsInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncAssignmentsInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncConferencesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncDiscussionsInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncFilesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncGradesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncModulesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncPagesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncPeopleInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncQuizzesInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncSyllabusInteractor.swift, Core/Core/CourseSync/CourseSyncProgress/Model/CourseSyncProgressObserverInteractor.swift, Core/Core/Courses/AllCourses/Model/CourseListInteractor.swift, Core/Core/Courses/AllCourses/Model/GroupListInteractor.swift, Core/Core/Dashboard/Container/ViewModel/DashboardContainerViewModel.swift, Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModelLive.swift, Core/Core/Offline/Model/OfflineModeInteractor.swift, Core/Core/Store/ReactiveStore.swift, Core/Core/Store/UseCase.swift, Core/CoreTests/Store/ReactiveStoreTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentListViewModel.swift
Rework ReactiveStore to prevent crashes
refs: MBL-17259
release note: Fixed an issue that caused occasional crashes.
test plan: Test the whole app if everything works as before.
=> Rework ReactiveStore to prevent crashes

Core/Core.xcodeproj/project.pbxproj, Core/Core/DocViewer/DocViewerViewController.swift, Core/Core/DocViewer/Model/DocViewerAnnotationProvider.swift, Core/Core/DocViewer/Model/PDFDocumentProviderExtensions.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift, Core/CoreTests/DocViewer/Model/PDFDocumentProviderExtensionsTests.swift
refs: MBL-17249
test plan:
- Upload a pdf file using web to your user's files.
- Open the file on web and rotate it.
- Submit this file on web to an assignment.
- Open teacher app and check if the file appears rotated in SpeedGrader.
- Open student app and go to submission and rubric of the assignment and check if the file appears rotated.
- Neither app should crash while doing these.
=> Move document rotation setup out of annotation provider initializer

Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift
Only enable offline syncable tabs in course details while device is offline and the whole course is selected for offline sync.
test plan:
- Select a course as a whole for offline sync and sync it.
- Go offline and enter the synced course.
- Only offline available tabs should be enabled, LTI tools should be disabled.
=> Fix course menu in offline mode

Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift
Disable Discussions tab in offline mode if discussionRedesign is enabled.
=> Disable Discussions tab in offline mode if discussionRedesign is enabled

rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift, rn/Teacher/ios/TeacherTests/SpeedGrader/SpeedGraderViewControllerTests.swift
refs: MBL-17324
release note: Fixed inactive students showing up in SpeedGrader when opened from the ToDo list.
test plan: See ticket. Only reproducible if you don't visit the submission list from the assignment details screen.
=> Add enrollment refresh to SpeedGrader load.

Student/Widgets/AnnouncementsWidget/View/AnnouncementWidgetView.swift, Student/Widgets/AnnouncementsWidget/View/MediumLarge/AnnouncementItemView.swift, Student/Widgets/AnnouncementsWidget/View/Small/SmallAnnouncementsView.swift, Student/Widgets/Common/View/CompatibleContainerBackground.swift, Student/Widgets/GradesWidget/View/GradesWidgetView.swift, Student/Widgets/GradesWidget/View/MediumLarge/MediumLargeGradesView.swift, Student/Widgets/GradesWidget/View/Small/SmallGradeView.swift
refs: MBL-17360
release note: Changed background color on all widgets to match app colors
test plan: Please see ticket for details
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/64eb13a8-a8f3-4151-a603-cfb5bc02d312" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/81ade704-2a2b-41e7-b262-031779742844" maxHeight=500></td>
</tr>
</table>
=> Fix Widget background colors

Core/Core/CoreWebView/Model/Features/InvertColorsInDarkMode.swift
refs: MBL-17366
release note: Fixed profile images being inverted when viewing graded discussions in dark mode.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/b613801b-2423-42c5-be21-e256623a0573" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/dcf8c2fe-2d09-47b3-b12e-7824e12777f4" maxHeight=500></td>
</tr>
</table>
=> Fix profile images being inverted when viewing graded discussions in dark mode

Core/Core/Store/UseCase.swift, Core/CoreTests/Store/UseCaseTests.swift
Fix Student dashboard crash
refs: MBL-17373
release note:  Fixed an occasional crash upon launching the application for the first time.
test plan: See below
1. Comment out `DashboardContainerView L84 and L86 so the Theme Switcher pops up when the app starts. 
2. When launching the application, abort every request via Charles/Proxyman
3. You should see the Theme Switcher appear.
=> Fix Student dashboard crash

Student/Widgets/AnnouncementsWidget/Model/GetWidgetAnnouncements.swift
refs: [MBL-17380](https://instructure.atlassian.net/browse/MBL-17380)
release note: Fixed the Announcements widget to sort by newest first
test plan: Verify the latest Announcements are shown first in Announcements widgets (test all 3 widget variants)
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/6e9eedbb-9fc2-426a-a2aa-f7d35bc51d2a" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/c07ef4b3-d55f-4b22-9823-abc51fae2450" maxHeight=500></td>
</tr>
</table>
[MBL-17380]: https://instructure.atlassian.net/browse/MBL-17380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Announcement widget to sort by newest first

Core/Core/DocViewer/Model/APIDocViewer.swift, Core/Core/DocViewer/Model/AnnotationTypes/PSPDFAnnotationExtension.swift, Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift
Remove zero dimensions from annotation comment uploads.
refs: MBL-17376
release note: Fixed comments added to annotations not being visible on web.
=> Fix comments added to annotations not being visible on web

Core/Core/Enrollments/Enrollment.swift, Core/Core/Grades/Model/GradeListInteractor.swift, Core/Core/Grades/Model/GradeListInteractorPreview.swift, Core/Core/Grades/View/GradeListView.swift, Core/Core/Grades/ViewModel/GradeListViewModel.swift, Core/CoreTests/Grades/GradeListInteractorLiveTests.swift, Core/CoreTests/Grades/GradeListViewModelTests.swift, Core/CoreTests/Store/UseCaseTests.swift
Base on graded assignment toggle.
- Added core functionality 
- Locked state 
- Loading state when switching grading periods
refs: MBL17302
release note: Added the ability to show grades based on graded assignments
test plan: Compare to Android, Web
<table>
<tr><th>Toggle</th><th>Locked state</th><th>Loading state</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/d0b99375-a293-4d49-b68c-ea2a305e1b83" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/6611f9da-7d85-45be-bf42-596eadc8914a" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/203e0b42-6d85-4a27-b9cc-f115e2abdaaa" maxHeight=500></td>
</tr>
</table>
=> Base on graded assignment toggle

Core/Core/Planner/PlannerNoteDetailViewController.storyboard, Core/Core/Planner/PlannerNoteDetailViewController.swift
refs: [MBL-17395](https://instructure.atlassian.net/browse/MBL-17395)
release note: Fixed Calendar ToDo items added by Student not displaying full details
Also fixed
- accessibility issues with Title & Date labels
- removed hardcoded heights
- changed Date to wrap instead of truncating
- changed background color to `backgroundLightest`
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/dc9fc30f-249a-4941-8360-0833d922e105" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/cdfdf0b4-e6d5-4741-b51d-88d92579b26a" maxHeight=500></td>
</tr>
</table>
[MBL-17395]: https://instructure.atlassian.net/browse/MBL-17395?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
=> Fix Calendar ToDo items added by Student not displaying full details

Core/Core/ActAsUser/ActAsUserWindow.swift, Core/Core/CoreWebView/View/CoreWebView.swift, Core/Core/CoreWebView/View/CoreWebViewThemeSwitcher.swift, Core/Core/CoreWebView/View/CoreWebViewThemeSwitcherButton.swift, Core/Core/Extensions/NotificationCenterExtensions.swift, Core/Core/Extensions/UIColorExtensions.swift, Core/Core/Extensions/UITraitCollectionExtensions.swift, Core/Core/RichContentEditor/RichContentEditorViewController.swift
refs: [MBL-17383](https://instructure.atlassian.net/browse/MBL-17383)
release note: Fixed some screens reloading and resetting videos after switching back from other apps.
test plan: See ticket + Test WebView inverting and dark/light mode changes throughout the apps.
If you encounter a related issue please compare with build from before this PR, because there are many Dark Mode related issues already, but this PR should not introduce new ones :)
- fixed CoreWebView reloading after app is backgrounded
- fixed flickering when inverting via switcher button
- fixed switcher button remaining on screen when switched to light first and disabled dark mode after
Before:
https://github.com/instructure/canvas-ios/assets/15140172/95e9acfd-87ff-42ef-92e9-1c42a9dc4460 …
=> Page gets reloaded and scrolled to the top

Core/Core/CourseSync/CourseSyncProgress/View/CourseSyncProgressInfoView.swift, Core/Core/Dashboard/FileUploadNotification/View/FileUploadNotificationCard.swift, Core/Core/Dashboard/OfflineSync/View/DashboardOfflineSyncProgressCardView.swift, Core/Core/Modules/ModuleList/Model/ModulePublishInteractor.swift, Core/Core/Modules/ModuleList/Model/ModulePublishItem.swift, Core/Core/Modules/ModuleList/ModuleItemCell.swift, Core/Core/Modules/ModuleList/ModuleListViewController.swift, Core/Core/Modules/ModuleList/ModuleSectionHeaderView.swift, Core/Core/Modules/ModuleList/View/ModulePublishProgressView.swift, Core/Core/Modules/ModuleList/ViewModel/ModulePublishMenu.swift, Core/Core/Modules/ModuleList/ViewModel/ModulePublishProgressViewModel.swift, Core/Core/Modules/PutModuleItemPublishRequest.swift, Core/Core/SnackBar/View/UIKit/SnackBarProvider.swift, Core/Core/SwiftUIViews/ProgressViewStyle/DeterminateBarProgressViewStyle.swift, Core/Core/SwiftUIViews/ProgressViewStyle/DeterminateCircleProgressViewStyle.swift, Core/Core/SwiftUIViews/ProgressViewStyle/IndeterminateBarProgressViewStyle.swift, Core/Core/SwiftUIViews/ProgressViewStyle/IndeterminateCircleProgressViewStyle.swift, Core/Core/SwiftUIViews/ProgressViewStyle/ProgressViewStyleConstants.swift, Core/CoreTests/Modules/ModuleList/ViewModel/ModulePublishMenuTests.swift, Core/CoreTests/Modules/ModuleList/ViewModel/ModulePublishProgressViewModelTests.swift
refs: [MBL-17305](https://instructure.atlassian.net/browse/MBL-17305)
- added Progress screen for All Modules or single Module bulk publish
- added Cancel snackbar
- integrated them into ModuleList
- added view & viewmodel
- added temporary dummy interactor for QA purposes
- refactored publish action enum to `ModulePublishAction` to include `subject`
- updated `findSnackBarViewModel()` to handle more cases
- unified ProgressViewStyle coloring
- Enable experimental feature flag in Developer Menu
- To reproduce success case: publish/unpublish All Modules (in navBar)
- To reproduce failure case: publish/unpublish a Module (in Module section header)
- update should fail after a few seconds
- See ticket for expectations
<table>
<tr>
<td><img …
=> Teacher Bulk Publish Progress screen UI

Core/Core/Discussions/DiscussionListViewController.swift, Core/CoreTests/Discussions/DiscussionListViewControllerTests.swift
refs: MBL-17439
release note: Anonymous discussions can be opened when it's enabled on course level.
test plan: Enable Discussion Redesign flag and check discussion list
- When Discussion Redesign is enabled on course level, anonymous discussions are not greyed out/disabled anymore, they can be opened. 
- Creating anonymous discussion is not possible on mobile yet. 
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/85e4fec0-cca8-49f0-bfed-edfd57d39d8d" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/de56e79f-b400-4f7a-9640-19e10e95eef9" maxHeight=500></td>
</tr>
</table>
=> Support anonymous discussion when redesign is enabled

Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Files/Model/Entities/FileAvailability.swift, Core/Core/Modules/APIModule.swift, Core/Core/Modules/ModuleItem.swift, Core/Core/Modules/ModuleList/Model/ModulePublishInteractor.swift, Core/Core/Modules/ModuleList/ModuleItemCell.swift, Core/Core/Modules/ModuleList/ModuleItemPublishIndicatorView.swift, Core/Core/Modules/ModuleList/ModuleItemPublishIndicatorView.xib, Core/Core/Modules/ModuleList/ModuleListViewController.storyboard, Core/Core/Modules/ModuleList/ModulePublishControl.swift, Core/Core/Modules/ModuleList/ModuleSectionHeaderView.swift, Core/Core/Modules/ModuleList/ModuleSectionHeaderView.xib, Core/Core/Modules/ModuleList/View/ModuleFilePermissionEditorView.swift, Core/Core/Modules/ModuleList/View/ModulePublishProgressView.swift, Core/Core/UIViews/CircleProgressView.swift, Core/CoreTests/Modules/ModuleItemTests.swift, Core/CoreTests/Modules/ModuleList/Model/ModulePublishInteractorTests.swift, Core/CoreTests/Modules/ModuleList/ModuleListViewControllerTests.swift
refs: [MBL-17347](https://instructure.atlassian.net/browse/MBL-17347), [MBL-17456](https://instructure.atlassian.net/browse/MBL-17456)
- added support to disable action for Items which are not unpublishable
- reworked Publish Button to include the Published icon and an extended hit area
- improved Bulk Publish Progress Screen accessibility
- fixed freezing Progress Animation when navigating forward and back or backgrounding and back
- added `unpublishable` to`APIModuleItem`
- added `ModulePublishControl` to replace the individual Publish icons/buttons
- refactored & rearranged `ModuleItemCell` and to a lesser extent `ModuleSectionHeaderView`
- added a11y label to ProgressView (X) button & added unified a11y label for progress title and bar
- …
=> Bulk Publish - Disable Unpublish, Extend hit area

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
refs: MBL-17442
release note: Improved support for larger text sizes in Assignment Details.
Submitted title & description layout is fixed
Rest of the issues will be done in a followup task
- Verify Submitted title & description is displayed inside card and truncated
- Verify screen layouts properly in other scenarios
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/a10d1cb9-7c05-4f0e-8eff-0d48782977b7" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/15140172/13c4d1cb-0237-43de-9129-096f3c4348bc" maxHeight=500></td>
</tr>
</table>
=> Improve support for larger text sizes in Assignment Details

Core/Core/Groups/Group.swift, Core/CoreTests/Groups/GroupTests.swift
refs: MBL-17444
release note: Fixed groups from unpublished courses showing up on dashboard.
=> Check course's published state when determining if a group is active.

Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncModulesInteractor.swift
refs: MBL-17470
test plan: Login to Judit's account. Download Canvas for teachers course.
Offline download seemingly never finishes downloading. 
It looks like files that have been locked, don't have urls available, which caused the file downloader stream to never emit. 
Change the `Empty` publisher so it finished the stream.
=> Fix offline progress behaviour

Core/Core/CoreWebView/Model/Features/HidePeerReviewLinkInDiscussions.swift, Core/Core/EmbeddedWebPage/View/EmbeddedWebPageView.swift, Core/CoreTests/CoreWebView/Model/Features/HidePeerReviewLinkInDiscussionsTests.swift
refs: MBL-17445
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/da41febd-14d7-4ec6-8ebe-78c786253655" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/bd147fe5-8965-4573-86d2-5e635166420b" maxHeight=500></td>
</tr>
</table>
=> Hide non-functioning peer review link in hybrid discussions screen.

Core/Core/Grades/ViewModel/GradeListViewModel.swift
refs: MBL-17450
release note: Fixed an issue that caused an occasional crash on Grades Screen.
test plan: Wasn't able to reproduce, check if everything still works.
=> Fix Grade screen crash

Core/Core/Submissions/APISubmission.swift, Core/CoreTests/Submissions/APISubmissionTests.swift, rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift
refs: [MBL-17464](https://instructure.atlassian.net/browse/MBL-17464)
release note: Fixed Submissions List showing Students instead of Groups. Fixed SpeedGrader presenting a different Submission from the list then the one selected.
See ticket and use already setup account described there.
The problem was that `GetSubmissionsRequest` (plural) included `"group"` but `GetSubmissionRequest` (singular) did not, and the later request got called by `GetSubmissionComments` usecase whenever CoreDate didn't have it, clearing out the group `id` and `name`.
This resulted in Student names displayed instead of Group names.
Also since these also drive the sort ordering, SpeedGrader showed the submissions in weird order.
[MBL-17464]: …
=> Fix Submissions mixing up Student and Group names and therefore ordering

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/PrivacyInfo.xcprivacy, Podfile, Podfile.lock, Student/Student/PrivacyInfo.xcprivacy, Student/SubmitAssignment/PrivacyInfo.xcprivacy, Student/SubmitAssignment/student-submit-assignment.yml, Student/project-ci.yml, Student/project.yml, rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/PrivacyInfo.xcprivacy
- Updated Firebase and HEAP SDKs.
- Moved file share extension's Firebase dependency from SPM to pods due to a linker error.
- Added privacy info files for API usage declaration.
refs: MBL-17496
test plan:
- All apps build and start.
=> Fix missing API declarations for App Store

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Quizzes/APIQuiz.swift, Core/Core/Quizzes/Quiz.swift, Core/Core/SwiftUIViews/Avatar.swift, rn/Teacher/ios/Teacher/Localizable.xcstrings, rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/Entities/QuizSubmissionListItem.swift, rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/Model/QuizSubmissionListInteractorLive.swift, rn/Teacher/ios/Teacher/Submissions/QuizSubmissionList/ViewModel/QuizSubmissionListItemViewModel.swift, rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift, rn/Teacher/ios/TeacherTests/Submissions/QuizSubmissionList/QuizSubmissionListItemTests.swift, rn/Teacher/ios/TeacherTests/Submissions/SubmissionListViewControllerTests.swift
refs: MBL-17458
release note: Anonymous ungraded surveys now hide student names. Anonymous submissions show a numbered list of students instead of showing student multiple times. 
test plan: See ticket and test other anonymized submission formats. 
- Anonymous ungraded surveys now hide Student names and avatars and use a numbered anynomized list. (Student 1, Student 2, etc..)
- Other anonymous submissions are displayed with the same logic as above instead of simply showing (Student, Student) 
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/f569cbbe-5b1d-4902-830b-8f6e6c77e275" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/91e59df8-7ded-478b-a2b0-0a6eb …
=> Hide student names in anonymous ungraded surveys

Core/Core/Grades/View/GradeRowView.swift, Core/Core/Models/Viewable/SubmissionViewable.swift, Core/CoreTests/Models/Viewable/SubmissionViewableTests.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-17468
release note: Missing tag is visible for all submission types now.
test plan: See ticket, check web.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/4d82bbde-cf25-4710-b555-d4968acf6227" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/b62813cd-3796-4c82-af17-fcf4fbbe7cad" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/8205cf28-b8e3-465d-9701-533f23ded3a6" maxHeight=500></td>
<td></td>
</tr>
</table>
=> Show missing tag for all submission types

Core/Core/Courses/CourseDetails/View/CourseDetailsHeaderView.swift, Core/Core/Courses/CourseDetails/View/CourseSettingsView.swift, Core/Core/Courses/K5/View/Subject/K5SubjectHeaderView.swift, Core/Core/Dashboard/CourseCardList/View/CustomizeCourseView.swift, Core/Core/Dashboard/CourseCardList/View/DashboardCourseCardView.swift, Core/Core/Extensions/ResultExtensions.swift, Core/Core/Extensions/UIImageViewExtensions.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/SwiftUIViews/ImageWrapperWebView.swift, Core/Core/SwiftUIViews/RemoteImage.swift, Core/CoreTests/Extensions/ResultExtensionsTests.swift, Core/CoreTests/Extensions/UIImageViewExtensionsTests.swift
refs: [MBL-17453](https://instructure.atlassian.net/browse/MBL-17453)
release note: Optimized memory and bandwidth usage for Course Image and uploaded files.
- Animated GIFs were loaded as bitmaps frame by frame, which eats up a lot of memory.
- Image caching was based on the full image URLs, which included token in the query as well. Because it changes slighly in each request, this resulted in each Course Image downloaded and loaded into memory multiple times.
- In-memory image cache was never reseted.
- Animated GIFs are displayed and animating in WebViews, where deemed important:
- Course Details screen
- Customize Course screen
- Course Settings screen
- Files
- K5 Subject Details screen
- Animated GIFs are showing only the first frame, without animating in …
=> Large GIF course image causes app to crash

Core/Core/EmbeddedWebPage/View/EmbeddedWebPageView.swift, Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModel.swift, Core/Core/EmbeddedWebPage/ViewModel/EmbeddedWebPageViewModelLive.swift
refs: MBL-17520
release note: Fixed discussion redesign unauthorized error when masquerading a user
The issue is fixed by providing a webview configuration where the data source is `nonPersistent`. 
We might want to look into how `WKWebViewConfiguration` is used across the app and turn it into a `CoreWebViewFeature`, but I only fixed the issue locally now.
=> Fix discussion redesign unauthorized error when masquerading a user

Core/Core/Pages/PageDetails/PageDetailsViewController.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-17586
release note: Fixed embedded Studio videos not loading on some screens.
test plan:
- Check if embedded Studio videos load on the assignment details and page details screens.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/5359acf4-a97f-4eec-bdf2-c941f468ee66" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/23ef005c-555e-4e22-a895-8e031ac771c0" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/f87fa9b8-4320-4944-b46b-28ad842be268" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/86415340-992c-4852-aa5d-e6c24de2001e" …
=> Add baseURL to webview content loads

Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncModulesInteractor.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Modules/APIModule.swift, Core/Core/Modules/ModuleItem.swift, Core/Core/Modules/ModuleItemType.swift, Core/Core/Modules/ModuleItems/ModuleItemSequenceViewController.swift, Core/CoreTests/Modules/ModuleItemTests.swift, Core/CoreTests/Modules/ModuleItemTypeTests.swift, Core/CoreTests/Modules/ModuleItems/ModuleItemSequenceViewControllerTests.swift
refs: MBL-17545
affects: Students
test plan: Check regular module sequences, modules linked in pages. 
- Module sequence wasn't handled correctly if a module was referenced within a page. 
- When opening a page from the `Pages` course navigation menu where the page is part of a module sequence and is locked now show up as a locked page instead of a white page. 
Check Tamas' offline account 
- Onboarding/Modules
- Onboarding 
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/133c276d-9fc3-4f2b-8662-1a1258df96bb" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/614a2ac3-6a90-4a6b-ba07-0df241569099" maxHeight=500></td>
</tr>
<tr>
<td><img …
=> Offline modules refinement

Parent/Parent/Courses/CourseDetailsViewController.swift
refs: MBL-17604
release note: Enabled embedded videos on the front page to play.
test plan:
- Create a page that has a embedded Studio video in it.
- Set this page as the course home.
- Start the parent app and check if the embedded video loads.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/f057a26f-34c2-4894-aa23-ad7c2cd3c152" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/6f754ce5-1b2c-4826-9232-4a89172db3df" maxHeight=500></td>
</tr>
</table>
=> Enabled embedded videos on the front page to play

Core/Core/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressInfoViewModel.swift, Core/Core/Dashboard/OfflineSync/View/DashboardOfflineSyncProgressCardView.swift, Core/Core/Notifications/LocalNotifications.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncNotificationInteractorTests.swift, Core/CoreTests/CourseSync/CourseSyncProgress/ViewModel/CourseSyncProgressInfoViewModelTests.swift, Core/CoreTests/Notifications/LocalNotificationsTests.swift, Student/Student/InfoPlist.xcstrings
refs: MBL-17225
test plan: Fail an offline download
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/0666cc3b-f2cb-4c6e-adb5-224fb75c7722" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/9c4fae66-9fdb-47be-aa31-b4991c4a5503" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/4bb366ef-8b7b-4ec8-834a-0246eac361fa" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/a661b0aa-4507-4cdb-b6df-1916e6d81cb9" maxHeight=500></td>
</tr>
</table>
=> Update offline error messages

.swiftlint.yml, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/LTI/EmbeddedExternalTools.swift, Core/CoreTests/.swiftlint.yml, Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/Widgets/AnnouncementsWidget/Model/GetWidgetAnnouncements.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift, scripts/swift/.swiftlint.yml
- I disabled the `non_optional_string_data_conversion` rule since part of it will be reverted in the next swiftlint version.
- Removed the `identifier_name` rule configuration since it's disabled and now it generates a warning if we have it disabled but with an active config.
- Fixed misc new warnings.
=> Update codebase for the latest swiftlint

Core/TestsFoundation/Helpers/BaseHelper.swift, Core/TestsFoundation/Helpers/DashboardHelper.swift, Core/TestsFoundation/UITests/E2ETestCase.swift, Student/StudentE2ETests/Offline/FeatureFlagOfflineTests.swift
refs: MBL-17634
affects: None
Test started failing due to recent changes in feature behaviour.
Previous behaviour:
If new discussion feature flag is turned on then after syncing course for offline use and opening discussions a warning message appeared that it's not available offline.
Current behaviour:
Fallback to old discussions screen.
Test has been updated accordingly.
=> Student - Fix FeatureFlagOffline tests

Core/Core/Groups/APIGroup.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetCalendarFilters.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/UseCase/GetCalendarFiltersTests.swift
refs: [MBL-17646](https://instructure.atlassian.net/browse/MBL-17646)
release note: Fixed calendar trying to load events for concluded groups.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/d8aa69f2-97aa-4a2d-a96e-c6b5717afed6" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/ed44a301-2ae5-460b-bf0f-ab0c9ec70f7f" maxHeight=500></td>
</tr>
</table>
[MBL-17646]: https://instructure.atlassian.net/browse/MBL-17646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Filter out concluded groups from calendar filter

Core/Core/CourseSync/BackgroundUpdates/Model/Helpers/OfflineSyncNextDateInteractor.swift, Core/Core/CourseSync/Common/Models/CourseSyncListerInteractor.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/CourseSyncNotificationInteractor.swift, Core/CoreTests/CourseSync/BackgroundUpdates/Model/Helpers/OfflineSyncNextDateInteractorTests.swift, Core/CoreTests/CourseSync/Common/CourseSyncListInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/CourseSyncNotificationInteractorTests.swift
Skip offline sync without selected courses.
refs: MBL-17204
release note: Offline sync skips cases when there are no courses selected
test plan: Build from Xcode to easily trigger a sync, check if sync only occurs when there are offline selected courses.
=> Skip offline sync without courses

Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift, Core/Core/Courses/CourseSettingsInteractor.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/ObserverAlerts/APIObserverAlert.swift, Core/Core/ObserverAlerts/ObserverAlert.swift, Core/CoreTests/Courses/CourseSettingsInteractorTests.swift, Core/CoreTests/ObserverAlerts/ObserverAlertTests.swift, Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/ObserverAlerts/Model/ObserverAlertsInteractor.swift, Parent/Parent/ObserverAlerts/ObserverAlertListViewController.swift, Parent/ParentUnitTests/ObserverAlerts/Model/ObserverAlertsInteractorTests.swift, Parent/ParentUnitTests/ObserverAlerts/ObserverAlertListViewControllerTests.swift
refs: MBL-17542
release note: Threshold alerts are hidden now for courses where quantitative data restriction is enabled.
test plan:
- Have a course where restrict quantitative data is disabled.
- Set up alert threshold for a student in parent app.
- Grade a submission in a way to trigger the threshold.
- Open the parent app and check the alert.
- Turn on restrict quantitative data for the course.
- Refresh the alerts page and check if the alerts have disappeared.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/a19343fa-fe29-4ab2-8569-8b3b46986d25" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/ebc17913-f777-442c-b8de-f19fbfb32630" maxHeight=500></td> …
=> Filter out threshold alerts for courses where quantitative data restriction is enabled

Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractor.swift, Core/Core/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorPreview.swift, Core/Core/CourseSync/CourseSyncSelector/View/CourseSyncSelectorView.swift, Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift, Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift, Core/Core/SwiftUIViews/ConfirmationAlert.swift, Core/CoreTests/CourseSync/CourseSyncSelector/Model/CourseSyncSelectorInteractorLiveTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelItemTests.swift, Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelTests.swift
Offline selector updates
refs: MBL-17104
<table>
<tr><th>Dialog</th>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/110813321/49112bbb-5cdb-4a1a-9622-27b22fd7dd67" height=500></td>
</table>
=> Offline sync selector updates

Core/Core/Courses/CourseDetails/ViewModel/CourseDetailsViewModel.swift, Core/Core/Grades/Model/GradeListInteractor.swift, Core/Core/People/User.swift, Core/CoreTests/Grades/GradeListInteractorLiveTests.swift, Core/CoreTests/People/UserTests.swift, Student/Student/InfoPlist.xcstrings
refs: MBL-17207
release note: Fixed an issue where visiting people screen corrupted grade information across the app in offline mode
[MBL-17205]: https://instructure.atlassian.net/browse/MBL-17205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix invalid grade data in offline mode

Core/Core/PageViewAnalytics/PageViewEventRequestManager.swift, Core/CoreTests/PageViewAnalytics/PageViewEventRequestManagerTests.swift
refs: [MBL-1031](https://instructure.atlassian.net/browse/MBL-17031)
- Enter a Course
- Background the app to send Pandata events
- Rewrite the `POST */pandata-event` response body to something different than `"OK"`
- Foreground the app, navigate to a different screen and background it again
- Verify that the events sent in the first request are not sent again in the second
=> Change Pandata response parsing

Core/Core/CourseSync/CourseSyncSelector/View/CourseSyncDiskSpaceInfoView.swift, Core/Core/CourseSync/CourseSyncSelector/View/CourseSyncSelectorView.swift, Core/Core/SwiftUIViews/ViewPreferences/Bounds.swift, Core/Core/ViewModifiers/ViewFrameBinding.swift
refs: MBL-17148
release note: Disk space info header now collapses on the offline sync screen when scrolling.
test plan:
- Check if collapse works correctly without any glitches.
- Known issue: if dynamic text size is changed while on screen it could introduce glitches.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/163a1aa7-b2ab-4ae3-8558-c977ba37cd87" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-ios/assets/72396990/f93cacef-db3e-4733-9ebc-ef804ad8ceaf" maxHeight=500></td>
</tr>
</table>
=> Make disk info header collapse when scrolling the screen's content.

Core/Core/CoreWebView/View/CoreWebView.swift, Core/CoreTests/CoreWebView/View/CoreWebViewTests.swift
refs: [MBL-15465](https://instructure.atlassian.net/browse/MBL-15465)
- Changed keep alive request method from `GET` to `HEAD`
- Changed keep alive request path from `/users/self` to `/`
- Fixed initial request duplication
- Observe requests sent to `https://*.instructure.com/`
- Make sure you are not filtering only for the given app, but for the domain
- Start the app
- Find the first `HEAD https://*.instructure.com/?session_token=...` request
- Verify it's response code is `302`
- Verify it's response header has `Set-Cookie` with `canvas_session`
- Verify it's followed by a `HEAD https://*.instructure.com/` request
- Verify it's response code is `200`
- Verify it's request header has `canvas_session` cookie matching the value set in …
=> Change keep alive request method from GET to HEAD

Core/Core/Dashboard/OfflineSync/DashboardOfflineSyncProgressCardAssembly.swift, Core/Core/Dashboard/OfflineSync/Model/DashboardOfflineSyncInteractorPreview.swift, Core/Core/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModel.swift, Core/CoreTests/Dashboard/OfflineSync/ViewModel/DashboardOfflineSyncProgressCardViewModelTests.swift
refs: MBL-17224
release note: Failed offline sync banner on the dashboard won't reappear after closing it.
=> Clear failed offline progress upon dismissing dashboard notification

Core/Core/Courses/Course.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncGradesInteractorLiveTests.swift, Core/CoreTests/Courses/CourseTests.swift
- When we downloaded a course we received an enrollment with grade fields in it. This enrollment was associated with the course but it had no ID.
- When we fetched all enrollments for the user we received another enrollment object with different fields and with an ID.
- The dashboard and the grade screen's grade calculation was based on the first enrollment that had no ID but this was not specified while looking up the enrollment from the DB and it was undefined which one we receive.
- The solution was to explicitly state that we want to work with the one without ID.
refs: MBL-17205
release note: Fixed dashboard displaying invalid grades sometimes.
test plan:
- Sync a course for offline mode.
- Go to people page, select your profile.
- Wait until the profile loads.
- …
=> Fixed course's associated enrollment not being fetched properly.

Core/Core/CoreWebView/View/CoreWebViewFullScreenVideoSupport.swift, Core/CoreTests/CoreWebView/View/CoreWebViewFullScreenVideoSupportTests.swift
- When moving a html video to full screen hosted from a webview embedded inside SwiftUI the webview got deallocated after moving to full screen.
- I solved this by keeping a strong reference (effectively a retain cycle) to the webview from the full screen handler until the webview is in fullscreen mode and release it after it exits.
- There might be animation / display glitches, like a white border during fullscreen playback. I couldn't get rid of them. Also the touch areas seem to be off sometimes in full screen.
refs: MBL-17645
release note: Fixed full screen video playback in announcements and discussions not working.
test plan:
- Embed a studio video inside a discussion.
- Turn on new discussion feature flag.
- Go to the discussion inside the app and move the …
=> Fix webview getting released after moving to full screen

Core/Core/InstUI/Views/Cells/CheckboxCell.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetCalendarFilters.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetParentCalendarFilters.swift
refs: MBL-17669
release note: Fixed not all courses and groups appearing in the calendar filter.
test plan: See ticket for test account.
=> Exhaust all courses and groups for calendar filter

Core/Core/InstUI/Views/Cells/CheckboxCell.swift, Core/Core/InstUI/Views/Cells/RadioButtonCell.swift, Core/Core/InstUI/Views/DisclosureIndicator.swift, Core/Core/InstUI/Views/ListSectionHeader.swift, Core/Core/InstUI/Views/MenuItem.swift, Core/Core/InstUI/Views/NavigationBarButton.swift, Core/Core/LTI/EmbeddedExternalTools.swift, Core/Core/Offline/View/OfflineObservingMenu.swift, Core/Core/Planner/CalendarFilter/View/CalendarFilterScreen.swift, Core/Core/Planner/CalendarMain/PlannerListViewController.swift, Core/Core/Planner/CalendarSelector/View/SelectCalendarScreen.swift, Core/Core/Planner/CalendarToDo/Model/API/DeletePlannerNoteRequest.swift, Core/Core/Planner/CalendarToDo/Model/CalendarToDoInteractor.swift, Core/Core/Planner/CalendarToDo/Model/CalendarToDoInteractorPreview.swift, Core/Core/Planner/CalendarToDo/Model/UseCase/DeletePlannerNote.swift, Core/Core/Planner/CalendarToDo/View/CalendarToDoDetailsScreen.swift, Core/Core/Planner/CalendarToDo/View/EditCalendarToDoScreen.swift, Core/Core/Planner/CalendarToDo/ViewModel/CalendarToDoDetailsViewModel.swift, Core/Core/Planner/CalendarToDo/ViewModel/EditCalendarToDoViewModel.swift, Core/Core/Planner/PlannerAssembly.swift, Core/Core/SwiftUIViews/ConfirmationAlert.swift, Core/Core/SwiftUIViews/ErrorAlert.swift, Core/CoreTests/Planner/CalendarToDo/Model/API/DeletePlannerNoteRequestTests.swift, Core/CoreTests/Planner/CalendarToDo/Model/CalendarToDoInteractorTests.swift, Core/CoreTests/Planner/CalendarToDo/Model/UseCase/DeletePlannerNoteTests.swift, Core/CoreTests/Planner/CalendarToDo/ViewModel/CalendarToDoDetailsViewModelTests.swift, Core/CoreTests/Planner/CalendarToDo/ViewModel/EditCalendarToDoViewModelTests.swift, Core/TestsFoundation/Router/TestRouter.swift
refs: [MBL-17291](https://instructure.atlassian.net/browse/MBL-17291)
release note: Calendar To Dos are now deletable.
- Replaced kebab button with menu on ToDo Details screen, which now has Edit and Delete items
- Added delete confirmation dialog
- Updated PlannerList to retain selection on iPad after reappearance or refresh
- Updated Create/Edit/Delete error messages
- Added to `InstUI.NavigationBarButton`
- `menuItems` parameter
- `accessibilityLabel` parameter for image init
- Added generic `userConfirmation` method to `ConfirmationAlert` to pass value downstream
- Added `InstUI.MenuItem`
- Added `OfflineObservingMenu`
- Unified `InstUI` String type name/label/title properties to `title`
- Verify Edit ToDo screen is reachable properly from ToDo Details screen
- Verify …
=> Calendar Delete ToDo

Core/Core/Dashboard/Notification/View/NotificationCard.swift
refs: MBL-17738
release note: Fixed media not displaying in account notifications.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/3b86d79a-a44a-4973-8bd7-caa0cc33cc53" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/e7b7ea16-5ab9-4179-88cb-40337ded2817" maxHeight=500></td>
</tr>
</table>
=> Fixed media not displaying in account notifications

Core/Core/Conversations/AttachmentCardsViewController.swift, Core/Core/Conversations/ConversationDetailViewController.storyboard
It seems like `AVPlayerViewController` changed and the thumbnail size we used is no longer enough for it to display video controls so I increased the video player's size with trial and error to find the smallest size that displays controls.
refs: MBL-17743
release note: Fixed videos not being played in inbox messages.
test plan: See ticket for account with video.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/a1729e7e-3a3e-4bfa-b564-37d68a496972" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/1f4888aa-f658-485a-a3fa-719e7dfe594e" maxHeight=500></td>
</tr>
</table>
=> Fix videos not being played in inbox messages

Core/Core/Submissions/Submission.swift, Core/CoreTests/Submissions/SubmissionTests.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonAlertView.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
A file extension check was added to Online File Uploads submission types to only allow Studio submission in case:
- There is no file extension limitation.
- The file extension limit is a valid video mime type.
Previously we offered studio all the time in case the submission type was Online File Uploads.
refs: [MBL-17735](https://instructure.atlassian.net/browse/MBL-17735)
release note: Fixed Studio being allowed for submission on non video assignments.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/e04c7719-86ab-4ad9-904e-f2d6f59c877a" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/2bddbdfc-fa07-4606-a196-527319c4e83d" maxHeight=500></td>
</tr>
</table> …
=> Filter out studio in case the assignment is not a video file type

Core/Core/API/APIError.swift, Core/Core/Extensions/ErrorExtensions.swift, Core/Core/Extensions/NSErrorExtensions.swift, Core/Core/Extensions/URLResponseExtensions.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/CoreTests/Extensions/ErrorExtensionsTests.swift, Core/CoreTests/Extensions/URLResponseExtensionsTests.swift
- Upon app start we initialize pandata that makes an API call to the backend to start a pandata session.
- In case an account has no pandata set up the API call is rejected with a 403 Developer key not registered.
- During a [bug fix](https://github.com/instructure/canvas-ios/pull/2216/files) in the past we mistakenly defined the 403 response code as unauthorised and thus eligible for a token refresh and retry.
- Upon logging into the no pandata account the app instantly renewed the access token.
- The old access token was invalidated since a new one was created and because of this in-flight API calls failed with error 401.
- These 401 API calls again renewed the access token causing another round of invalid access token API calls which renewed the token again.
- This cascade of token …
=> Fix 403 API responses triggering a token renewal

Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncFilesInteractor.swift
refs: MBL-17774
test plan:
- Check if offline management screen loads on my student account.
=> Update download to ignore forbidden files

Core/Core/Notifications/PushNotificationsInteractor.swift
refs: MBL-17774
test plan:
- Turn off "Users can edit their communication channels" account setting.
- Start the app.
- No "user not authorized to perform this action" popup should appear.
=> Update code to ignore forbidden API errors

Core/Core/CoreWebView/Model/Features/DarkModeForWebDiscussions.swift
refs: MBL-17791
test plan:
- Switch to dark mode.
- Open a discussion.
- Discussion text fields and button in the header should use dark theme.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/1cc38188-98fc-4460-abac-e2cae6b3f5b1" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/a7bc6f90-66d5-4862-bb67-1d22eeebc23b" maxHeight=500></td>
</tr>
</table>
=> Update dark mode discussion css

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Files/FileSubmission/Model/Entities/FileSubmission.swift, Core/Core/Files/FileSubmission/Model/PrepareUpload/FileSubmissionComposer.swift, Core/Core/Files/FileSubmission/Model/Submission/FileSubmissionSubmitter.swift, Core/Core/Files/Model/UploadManager.swift, Core/Core/Submissions/APISubmission.swift, Core/Core/Submissions/GetSubmissions.swift, Core/Core/SubmitAssignmentExtension/Model/API/APIAssignmentPickerListItem.swift, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListRequest.swift, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListResponse.swift, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListService.swift, Core/Core/SubmitAssignmentExtension/Model/AttachmentSubmissionService.swift, Core/Core/SubmitAssignmentExtension/ViewModel/AssignmentPickerItem.swift, Core/Core/SubmitAssignmentExtension/ViewModel/SubmitAssignmentExtensionViewModel.swift, Core/CoreTests/Files/FileSubmission/Model/FileSubmissionAssemblyTests.swift, Core/CoreTests/Files/FileSubmission/Model/PrepareUpload/FileSubmissionComposerTests.swift, Core/CoreTests/Files/FileSubmission/Model/Submission/FileSubmissionSubmitterTests.swift, Core/CoreTests/Files/UploadManagerTests.swift, Core/CoreTests/Submissions/APISubmissionTests.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift, Core/CoreTests/SubmitAssignmentExtension/Model/API/AssignmentPickerListServiceTests.swift, Core/CoreTests/SubmitAssignmentExtension/Model/AttachmentSubmissionServiceTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/AssignmentPickerItemTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModelTests.swift, Student/StudentUnitTests/Submissions/ArcSubmission/ArcSubmissionPresenterTests.swift, Student/StudentUnitTests/Submissions/TextSubmission/TextSubmissionViewControllerTests.swift, Student/StudentUnitTests/Submissions/UrlSubmissionPresenterTests.swift
refs: MBL-17690
release note: Fixed group submission comment not being uploaded when using share extension
test plan: See ticket but use *.beta.instructure.com environment by logging in on the web and generate QR code to log in on mobile.
=> Fix group submission comment upload when using share extension

Core/Core/CoreWebView/View/CoreWebViewFullScreenVideoSupport.swift, Core/CoreTests/CoreWebView/View/CoreWebViewFullScreenVideoSupportTests.swift
I couldn't reproduce the crash on device but could set up multiple scenarios with unit tests that lead to this crash. Hope this will fix the crash we see.
refs: [MBL-17779](https://instructure.atlassian.net/browse/MBL-17779)
test plan:
- Test if full screen/pip video playback still works and you can exit these modes.
[MBL-17779]: https://instructure.atlassian.net/browse/MBL-17779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix fullscreen video crash

Core/Core/Inbox/Addressbook/View/AddressbookRecipientView.swift, Core/Core/Inbox/Addressbook/View/AddressbookRoleView.swift, Core/Core/Inbox/ComposeMessage/View/ComposeMessageView.swift, Core/Core/Inbox/ComposeMessage/View/RecipientPillView.swift, Core/Core/Inbox/InboxCoursePicker/View/InboxCoursePickerView.swift, Core/Core/Inbox/MessageDetails/View/MessageDetailsView.swift, Core/Core/Inbox/MessageDetails/View/MessageView.swift, Core/Core/Inbox/View/InboxFilterBarView.swift, Core/Core/Inbox/View/InboxMessageView.swift, Core/Core/Inbox/View/InboxView.swift, Core/TestsFoundation/Helpers/InboxHelper.swift, Student/StudentE2ETests/Help/HelpTests.swift, Student/StudentE2ETests/Inbox/InboxTests.swift, Student/StudentE2ETests/People/PeopleTests.swift, Student/StudentE2ETests/Settings/SettingsTests.swift, rn/Teacher/ios/TeacherE2ETests/Inbox/InboxTests.swift, rn/Teacher/ios/TeacherE2ETests/Settings/SettingsTests.swift
Core has been touched, and even if it's just adding accessibilityIds, please review this thoroughly to avoid future issues.
After merging this PR, all E2E tests should pass so we should start seeing green colors in Bitrise.
- added ids to elements of inbox and related screens
- updated helper structs to use the fresh ids for locating the elements (instead of labels)
- updated student and teacher e2e tests regarding the latest changes on inbox screen
=> Student, Teacher | Automation - E2E test maintenance

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Notifications/API/APIActivity.swift, Core/Core/Notifications/CoreData/Activity.swift
Parsing and saving of notification items failed:
- There's a new activity type called `DiscussionEntry`. Since this field is an enum the parsing failed since it lacked this value.
- The Activity entity's `htmlURL` field was optional in the swift file but was no optional in the CoreData model that caused a validation failure upon saving.
refs: [MBL-17805](https://instructure.atlassian.net/browse/MBL-17805)
release note: Fixed an issue that caused the notifications tab not to display any items.
test plan: See ticket for test account.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/89c899e2-4d90-44c3-8fbf-c29db11ee938" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/bed6ed33-3c07-4e44-a4 …
=> Fix activity stream not displaying any items

Core/Core/CourseSync/CourseSyncDownloader/CourseSyncDownloaderAssembly.swift, Core/Core/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncStudioMediaInteractor.swift, Core/Core/Extensions/ErrorExtensions.swift, Core/Core/Extensions/UINavigationControllerExtensions.swift, Core/Core/Studio/Model/StudioMetadataDownloadInteractor.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncStudioMediaInteractorLiveTests.swift, Core/CoreTests/Extensions/ErrorExtensionsTests.swift, Core/CoreTests/Studio/Model/StudioMetadataDownloadInteractorLiveTests.swift
During offline sync if a course is selected for sync but has no studio videos embedded then the API call for that course fails with a 404 making the whole studio sync stream fail. I extracted the download logic to make it more easily testable and modified it to ignore 404 errors.
refs: [MBL-17806](https://instructure.atlassian.net/browse/MBL-17806)
test plan:
- Sync two courses at once for offline availability. One that should have studio videos embedded while the other shouldn't.
- (You can double check this with a proxy, api/public/v1/courses/123/media should return 404 for courses without studio videos.)
- Sync should finish successfully and studio videos should be available in offline mode.
- Check the debug menu's logs if there are any entries for …
=> Ignore 404 errors while downloading studio video metadata.

Core/Core/SwiftUIViews/EditorForm.swift
refs: [MBL-17821](https://instructure.atlassian.net/browse/MBL-17821)
release note: Fixed keyboard hiding too much of some screens.
Verify keyboard showing up doesn't hide area above it on screens:
- AssignmentEditor (Teacher)
- DiscussionEditor (Teacher / Student)
- PageEditor (Teacher / Student)
- QuizEditor (Teacher)
- SyllabusEditor (Teacher)
Verify keyboard appearance still works as it should on screens:
- CourseSettings
- CustomizeCourse
- FileEditor
- WebSitePreview
Doublecheck that https://instructure.atlassian.net/browse/MBL-17814 is also fixed
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/2d0bb994-a8be-475c-a326-503c8b8f00b9" maxHeight=500></td>
<td><img …
=> Fix RCE keyboard hiding much of the screen

Core/Core/CoreWebView/Model/Features/DarkModeForWebDiscussions.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.storyboard
While checking RC issues I was able to fix a few of them on the spot.
- Missing CSS override for discussions in dark mode.
- Hidden tab bar that revealed the "Back online" banner. The `hidesBottomBarWhenPushed` for the view controller was turned on but it hid only for elementary users.
refs: MBL-17807
test plan:
- Create a discussion that requires a post before you can see other replies.
- Load the discussion in dark mode.
- The banner for the post requirement should have the appropriate contrast ratio.
--
- Log in to an elementary account and go to an assignment's submission and rubric page.
- Tab bar should be visible on the page. Back online banner shouldn't be visible.
<table>
<tr>
<td><img …
=> Fix some UI issues

Core/Core/Conversations/StarConversation.swift, Core/CoreTests/Conversations/StarConversationTests.swift
refs: [MBL-17833](https://instructure.atlassian.net/browse/MBL-17833)
affects: Student , Teacher
release note: Fixed archive message swipe action not always available in Inbox
test plan:
See ticket
https://github.com/user-attachments/assets/bcded85f-b8c1-45b5-a26a-119dacbf4888
https://github.com/user-attachments/assets/e27d57c6-8c96-499c-84a2-58934ddb39a9
[MBL-17833]: https://instructure.atlassian.net/browse/MBL-17833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Archive swipe action not available after staring a message

Parent/Parent/Assignments/View/AssignmentDetailsViewController.swift
refs: MBL-17798
release note: Fixed an issue where submission status would sometimes display an incorrect value
https://github.com/user-attachments/assets/2858e569-141f-4dc9-a9e4-3e91b927a411
=> Fix submission status on assignment details

Core/Core/Conversations/APIConversation.swift, Core/Core/Conversations/Conversation.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Inbox/MessageDetails/View/MessageDetailsView.swift, Core/Core/Inbox/MessageDetails/View/MessageView.swift, Core/Core/Inbox/MessageDetails/ViewModel/MessageDetailsViewModel.swift, Core/CoreTests/Inbox/MessageDetails/MessageDetailsViewModelTests.swift
refs: [MBL-17826](https://instructure.atlassian.net/browse/MBL-17826)
release note: Removed the reply button for messages where replying was disabled
test plan:
- Open inbox messages
- Open message details
- When the replay messages is disable must hide the button
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/d95e732a-4006-4241-83aa-8b9a7d1763c9" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/9ff325c3-c0ce-49b1-960f-753344317bc0" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/c4224c99-2cd1-4c4b-a77b-6646dba3779b"  maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/3c2ff17b-10d7-4bcd-b465-2d8104d2b0f2" …
=> Remove reply button for messages where reply is disabled

Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/CoreWebView/View/CoreWebView.swift, Core/Core/Extensions/HTTPCookieExtensions.swift, Core/Core/Extensions/WKHTTPCookieStoreExtensions.swift, Core/CoreTests/Extensions/WKHTTPCookieStoreExtensionTests.swift
What happened?
- When you logged in with a user the cookie keep alive kicked in and saved cookies to the shared cookie store.
- After switching users the same cookies were in the store since user switch didn't reset them and the automatic cookie refresh only happens at every 10 minutes so this also didn't overwrite the cookies.
- The result was a forbidden error page for the second elementary user since it still had the cookies for the previous user.
refs: [MBL-17832](https://instructure.atlassian.net/browse/MBL-17832)
release note: Fixed elementary view not loading content after switching users.
test plan:
- Log out will all users to clean keychain entries and prevent automatic login after install.
- Re-install the app.
- Log in with a non-elementary user.
- Change user …
=> Reset cookies and force a cookie refresh when a new user logs in.

Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift, Core/Core/Discussions/DiscussionEditorView.swift, Core/Core/InstUI/Views/Cells/RichContentEditorCell.swift, Core/Core/InstUI/Views/Cells/ToggleCell.swift, Core/Core/Pages/PageEditor/PageEditorView.swift, Core/Core/Planner/CalendarEvent/View/EditCalendarEventScreen.swift, Core/Core/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift, Core/Core/Planner/PlannerAssembly.swift, Core/Core/Quizzes/QuizDetails/View/QuizEditorView.swift, Core/Core/RichContentEditor/Model/RichContentEditorUploadParameters.swift, Core/Core/RichContentEditor/RichContentEditor.js, Core/Core/RichContentEditor/RichContentEditor.swift, Core/Core/RichContentEditor/RichContentEditorViewController.swift, Core/Core/Syllabus/SyllabusEditorView.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModelTests.swift, Core/CoreTests/RichContentEditor/RichContentEditorViewControllerTests.swift
refs: [MBL-17818](https://instructure.atlassian.net/browse/MBL-17818)
- Replaced TextEditor with RCE for Add/Edit Calendar Event details
- RCE should scroll to the end of it's content when focused
- Fix `ToggleCell` label swallowing taps
Already existing issues with RCE:
- VoiceOver sometimes reads RCE content twice
- Links sometimes duplicate when edited
- RCE doesn't scroll to cursor position when focused
- Verify Add/Edit CalendarEvent Details RCE works in Student app
- Smoke test RCE in other places, eg.:
- Submit text entry for assignment
- Add announcement
- Edit page
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/b4627929-e6d1-42de-b11a-257d6ea771f6" maxHeight=500></td>
<td><img …
=> Replace Calendar Event Details TextEditor with RCE

Core/Core/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Dashboard/CourseCardList/Model/Entities/DashboardCard.swift, Core/Core/Dashboard/CourseCardList/View/CustomizeCourseView.swift, Core/Core/Dashboard/CourseCardList/View/DashboardCourseCardView.swift, Core/Core/Dashboard/CourseCardList/ViewModel/DashboardCourseCardListViewModel.swift, Core/Core/Groups/Group.swift
- Fixed cached dashboard card color not being invalidated on course color change.
- Fixed dashboard color overlay and the grade and options bubble using different color sources.
- Fixed selected color not displaying the selection checkmark.
- Fixed colors in the color picker being slightly different than the one that actually got applied after selecting it.
- Known issue: after changing theme (e.g. light to dark) the checkmark won't appear.
refs: MBL-17801
release note: Fixed course color change not updating on the dashboard until app restart.
test plan:
- Change the color of a course in the app using the "Customize course" screen.
- After the color picker dialog is dismissed the course's color on the dashboard should have updated.
- Open the customize screen …
=> Fix course color change not being detected by the dashboard screen

Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/Assignments/Model/ParentSubmissionURLInteractor.swift, Parent/Parent/Assignments/View/AssignmentDetailsViewController.swift, Parent/ParentUnitTests/Assignments/Model/ParentSubmissionURLInteractorTests.swift, Parent/ParentUnitTests/Assignments/View/AssignmentDetailsViewControllerTests.swift
refs: [MBL-17856](https://instructure.atlassian.net/browse/MBL-17856)
release note: Add support to submission viewer to properly display for non-enhanced assignments.
test plan:
- Turn assignment enhancements off.
- Create an assignment, submit an attempt, add a grade.
- Open the parent app and go to the assignment and view the submission.
- Submission viewer should show the attempt.
- Close the window.
- Turn assignment enhancements on.
- Pull to refresh the parent app's assignment screen.
- Open the submission viewer.
- Submission viewer should still show the attempt.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/00ee8e1b-7543-4ebb-976f-76dc7464cdfd" maxHeight=500></td>
<td><img …
=> Add support to submission viewer to properly display for non-enhanced assignments

Core/Core/Modules/ModuleList/ModuleListViewController.storyboard
refs: MBL-17834
release note: Module items now can display more than two lines.
test plan:
- Create a module text header with a very long text.
- Go to modules in both apps.
- The full text should display without any cropping.
- See ticket for an already existing account with test data.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/99116c99-4401-4f84-892e-7967fad40810" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/d45d200f-4638-40ec-afef-663338ed0484" maxHeight=500></td>
</tr>
</table>
=> Enable multiple lines for module item names.

Core/Core/API/APIError.swift, Core/Core/Extensions/ErrorExtensions.swift, Core/Core/Extensions/NSErrorExtensions.swift, Core/Core/Planner/CalendarEvent/Model/API/APICalendarEventRequestBody.swift, Core/Core/Planner/CalendarEvent/Model/API/PutCalendarEventRequest.swift, Core/Core/Planner/CalendarEvent/Model/CalendarEventInteractor.swift, Core/Core/Planner/CalendarEvent/Model/CalendarEventInteractorPreview.swift, Core/Core/Planner/CalendarEvent/Model/UseCase/CreateCalendarEvent.swift, Core/Core/Planner/CalendarEvent/Model/UseCase/UpdateCalendarEvent.swift, Core/Core/Planner/CalendarEvent/View/EditCalendarEventScreen.swift, Core/Core/Planner/CalendarEvent/ViewModel/CalendarEventDetailsViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift, Core/Core/SwiftUIViews/Confirmation.swift, Core/CoreTests/API/APIErrorTests.swift, Core/CoreTests/Extensions/ErrorExtensionsTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/API/APICalendarEventRequestBodyTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/API/PutCalendarEventRequestTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/CalendarEventInteractorTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/UseCase/CreateCalendarEventTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/UseCase/UpdateCalendarEventTests.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModelTests.swift
refs: [MBL-17861](https://instructure.atlassian.net/browse/MBL-17861)
Added confirmation for updating recurring calendar events.
Some cases are considered invalid, and backend responds via HTTP status code 400 and a message in such cases.
These localized, user facing error messages are displayed to the user instead of the generic save error message.
Some of the cases (probably not a full list, that's why I didn't replicate this logic on client side):
- Change recurrence rule on just one instance of an event
- Update start date on all instances of an event
- Verify edit confirmation works just like on the web
- different options for first event and the rest
- (localized) error messages (see cases above and screenshots below)
- Verify confirmation is only …
=> Calendar Event Edit confirmation

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift, Core/Core/Planner/CalendarFilter/Model/CoreData/CDCalendarFilterEntry.swift, Core/Core/Planner/CalendarFilter/Model/Interactor/FilterProviders/CalendarFilterEntryProviderTeacher.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetCalendarFilters.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetTeacherCalendarFilters.swift, Core/Core/Planner/CalendarMain/PlannerViewController.swift, Core/Core/Planner/PlannerAssembly.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModelTests.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/FilterProviders/CalendarFilterEntryProviderTeacherTests.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/UseCase/GetTeacherCalendarFiltersTests.swift
refs: MBL-17889
release note: Enabling events & todos creation on Teacher's calendars
Done smoke tests for both "Add Todo" & "Add Event" actions, the methodology:
- Logged-in to Teacher app with user with `teacher` role assigned to him of at least one course.
- Navigated to "Calendar" tab, tapped on Calendars to view all calendars assigned to the user.
- On the top right corner, tapped on "+" button, selected any of those actions.
- Filled in form and hit submit.
- On both forms, tried to create instances on all available Calendars, and they seem to work as expected.
https://github.com/user-attachments/assets/a77aee4b-bef4-4806-9332-1d98b0d9993f
=> Enable Creating Events & Todo on Teacher Calendars

Teacher/Teacher/Attendance/StatusCell.swift, Teacher/Teacher/Localizable.xcstrings, Teacher/TeacherTests/Attendance/AttendanceViewControllerTests.swift, Teacher/TeacherTests/Attendance/StatusCellTests.swift
refs: [MBL-17846](https://instructure.atlassian.net/browse/MBL-17846)
release note: Added icon for unmarked users in Roll Call Attendance.
- Verify unmarked icon is visible according to ticket.
- Verify "Unmarked" is added in VoiceOver for unmarked users.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/586b3b4e-1b16-4ccd-b5db-4b0bc302096a" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/5068b7f2-3d01-4967-abfd-286ed55086de" maxHeight=500></td>
</tr>
</table>
[MBL-17846]: https://instructure.atlassian.net/browse/MBL-17846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add icon for unmarked users in Roll Call Attendance

Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift, Core/CoreTests/Inbox/ComposeMessage/ComposeMessageViewModelTests.swift
refs: [MBL-17836](https://instructure.atlassian.net/browse/MBL-17836)
release note: did't show inbox leave confirmation for empty message
1- Open new or reply to message
2- Tap on cancel button will dismiss the view without showing confirmation alert 
3- If you did any changes and hit cancel button will show alert
https://github.com/user-attachments/assets/a7d00972-1d5b-4b71-84d8-618faf33722c
[MBL-17836]: https://instructure.atlassian.net/browse/MBL-17836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't show inbox leave confirmation for empty message

Core/Core/AppEnvironment/ExperimentalFeature.swift, Teacher/Teacher/TeacherTabBarController.swift
refs: MBL-17934
release note: Remove support for Teacher calendar experimental feature flag.
- Logged in Teacher app with teacher account on a sandbox school.
- Navigated through Side menu > Developer menu > View Experimental Features.
- Observed results, "teacher_calendar" toggle is expected to be removed. 
- Dismissed Side menu > navigated to "Calendar" tab, observed results.
- Calendar tab is expected to be present and functional.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/8c20f6e8-c571-4cba-8c92-1886fbab81e8" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/76b183fe-3b0e-4b6b-8db6-73adcb10735a" maxHeight=500></td>
</tr>
</table>
=> Remove Teacher Calendar Experimental Feature Flag

Core/Core/Inbox/ComposeMessage/View/ComposeMessageView.swift
refs: [MBL-17958 ](https://instructure.atlassian.net/browse/MBL-17958)
affects:Student , Teacher
release note: Showed send button when scrolling down while sending new message
The bug occurred after I added InstUI.BaseScreen. This resulted in two ScrollViews: the first one inside InstUI.BaseScreen and the second in the compose view. The interaction between these two scroll views caused conflicts, preventing the correct coordinate systems from being obtained.
- Open new message.
- Set more text.
- Scroll down must show send button on the navigation bar.
https://github.com/user-attachments/assets/2f3c7e86-a443-40b6-ab69-644af90c8141
=> Show send button when scrolling down while sending new message

Teacher/Teacher/SpeedGrader/SubmissionViewer.swift
refs: MBL-17939
release note: Fixed LTI content embedded in RCE submissions not displaying in SpeedGrader.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/96db8ef5-0ee9-4227-8530-4b994cf42d69" maxHeight=500>
</td>
<td><img src="https://github.com/user-attachments/assets/2950393a-280a-4c83-bad2-c6552ba3cd20" maxHeight=500></td>
</tr>
</table>
=> Fix LTI content embedded in RCE submissions not displaying in SpeedGrader

Core/Core/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModel.swift, Core/Core/Files/Model/API/APIFile.swift, Core/CoreTests/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelTests.swift, Core/CoreTests/Files/Model/API/APIFileTests.swift
- Fixed file parsing failing when filename is null.
- Fixed offline content selector screen not reacting to cancel when in error or loading states.
refs: MBL-17877
release note: Fixed cancel not working on offline sync picker screen while the screen is loading or displaying an error. Fixed offline sync picker failing to load in some cases.
=> Offline content picker fixes

Core/Core/Conversations/APIConversation.swift, Core/Core/Conversations/CreateConversation.swift, Core/Core/Inbox/ComposeMessage/Model/ComposeMessageInteractorLive.swift, Core/Core/Inbox/ComposeMessage/Model/MessageParameters.swift, Core/Core/Inbox/ComposeMessage/View/ComposeMessageView.swift, Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift, Core/CoreTests/Conversations/APIConversationTests.swift, Core/CoreTests/Conversations/ComposeViewControllerTests.swift, Core/CoreTests/Inbox/ComposeMessage/ComposeMessageInteractorLiveTests.swift, Core/CoreTests/Inbox/ComposeMessage/ComposeMessageViewModelTests.swift, Core/CoreTests/Inbox/Stubs/ReceiptStub.swift
refs: [MBL-17936](https://instructure.atlassian.net/browse/MBL-17936)
affects: Student , Teacher
release note: Enabled sending messages to an unlimited number of recipients
- Open a new message
- Send a message to over 100 recipients.
- Observe that the "Send Individually" toggle becomes disabled.
- If you send a reply message to over 100 recipients, you will receive an error. This is not an issue on our side but a backend issue.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/d1c5fc16-cc4c-4a97-9ba3-f5d555888e72" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/bb59a55a-1e8d-4445-86ad-043ec8a2b11c" maxHeight=500></td>
</tr>
https://github.com/user-attachments/assets/8be1c566-abb7-4f2b-98c0-450c1595503 …
=> Enable sending messages to an unlimited number of recipients

Core/Core/SwiftUIViews/ButtonStyles/ContextButton.swift
I noticed that there are significant lags and fps drops on screens using the ContextButton button style. This was because this style re-calculated the color to get it to the minimum contrast ratio but in fact colors reaching the UI should already have enough contrast ratio after the color palette update that we delivered recently.
<table>
<tr>
<td>
https://github.com/user-attachments/assets/3df4621c-ce83-43b0-8e66-9453c455691d
</td>
<td>
https://github.com/user-attachments/assets/dbe9e510-a701-4990-a7b7-ba7e24cda95f
</td>
</tr>
</table>
=> Remove unnecessary color contrast calculation

Core/Core/API/ID.swift, Core/Core/Analytics/Analytics.swift, Core/Core/Contexts/Context.swift, Core/Core/Planner/CalendarFilter/Model/CoreData/CDCalendarFilterEntry.swift, Core/Core/Planner/CalendarFilter/Model/Interactor/CalendarFilterInteractor.swift, Core/Core/Planner/CalendarFilter/Model/Interactor/FilterProviders/CalendarFilterEntryProviderStudent.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetCalendarFilters.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetParentCalendarFilters.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetStudentCalendarFilters.swift, Core/Core/Planner/CalendarFilter/Model/UseCase/GetTeacherCalendarFilters.swift, Core/CoreTests/Analytics/AnalyticsTests.swift, Core/CoreTests/Contexts/ContextTests.swift, Core/CoreTests/Planner/CalendarFilter/Model/CoreData/CDCalendarFilterEntryTests.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/UseCase/GetStudentCalendarFiltersTests.swift
refs: [MBL-17976](https://instructure.atlassian.net/browse/MBL-17976)
Because it was not reproducible, this is a best effort attempt to fix the crash during CalendarFilter load.
`CDCalendarFilterEntry` is sometimes stored without a valid contextID, which results in a crash while force unwrapping `CDCalendarFilterEntry.context`. We assume that this may be a result of some old ID format which we are not aware of, but still used in some accounts.
- Removing the force unwrap would have required extensive changes and complications.
- Providing a default value is also difficult, because there is no meaningful fallback context here.
- Silently ignoring the filters with invalid (which means empty) contextIDs seemed to be the lesser evil here, …
=> Calendar Filter crash

Core/Core/Inbox/ComposeMessage/View/ComposeMessageView.swift, Core/Core/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift, Core/Core/Inbox/MessageDetails/View/MessageView.swift, Core/Core/Inbox/MessageDetails/ViewModel/MessageViewModel.swift, Core/Core/Inbox/Model/Entities/InboxMessageListItem.swift, Core/Core/Inbox/View/AttachmentsView.swift
refs: [MBL-17959](https://instructure.atlassian.net/browse/MBL-17959)
release note: Show media from media comment in the Inbox
- Open your account as a teacher or student from the web.
- Go through your inbox.
- Try to add a media comment, such as a video or audio.
- Open the iOS app and go through your inbox to access the media.
- I've tried to play the media inside the app, but i've seen the url got from  "mediaComment" is totally different and can't get the file id. 
- In my opinion, we should create a new ticket to develop a new media player that can handle this URL, instead of applying a workaround to the current player, which is already very large.
<table>
<tr>
<td><img …
=> Show media from media comment in the Inbox

Core/Core/Extensions/DateExtensions.swift, Core/Core/Planner/CalendarEvent/Model/API/DeleteCalendarEventRequest.swift, Core/Core/Planner/CalendarEvent/Model/API/PostCalendarEventRequest.swift, Core/Core/Planner/CalendarEvent/Model/API/PutCalendarEventRequest.swift, Core/Core/Planner/CalendarEvent/Model/Helpers/FrequencyPreset.swift, Core/Core/Planner/CalendarEvent/Model/Helpers/RecurrenceRule.swift, Core/Core/Planner/CalendarEvent/View/SelectEventFrequencyScreen.swift, Core/Core/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/EditCustomFrequencyViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/FrequencyHelpers/FrequencyPresetViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/FrequencyHelpers/FrequencySelection.swift, Core/Core/Planner/CalendarEvent/ViewModel/SelectEventFrequencyViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/SelectionModels/FrequencyChoice.swift, Core/Core/Planner/CalendarEvent/ViewModel/SelectionModels/FrequencyPreset.swift, Core/Core/Planner/CalendarEvent/ViewModel/SelectionModels/FrequencyPresetViewModel.swift, Core/Core/Planner/CalendarEvent/ViewModel/SelectionModels/FrequencySelection.swift, Core/Core/Planner/CalendarToDo/Model/API/DeletePlannerNoteRequest.swift, Core/Core/Planner/CalendarToDo/Model/API/PostPlannerNoteRequest.swift, Core/Core/Planner/CalendarToDo/Model/API/PutPlannerNoteRequest.swift, Core/Core/Planner/Model/CoreData/CalendarEvent.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Dashboard/View/DashboardSettingsViewTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/Helpers/FrequencyPresetTests.swift, Core/CoreTests/Planner/CalendarEvent/Model/Helpers/RecurrenceRule+SelectionDescriptionTests.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/EditCustomFrequencyViewModelTests.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/FrequencyPresetViewModelTests.swift, Core/CoreTests/Planner/CalendarEvent/ViewModel/SelectEventFrequencyViewModelTests.swift, Core/CoreTests/Planner/Model/CoreData/CalendarEventTests.swift, scripts/coverage/config.json
refs: [MBL-17971](https://instructure.atlassian.net/browse/MBL-17971)
release note: Custom calendar frequency screen now reuses the currently selected frequency.
CustomFrequency screen is now prefilled with values from the current selection in the previous screen.
Tapping "Custom" when current selection is:
- "Does not repeat", it still shows the default state, where nothing is prefilled
- a predefined option (daily/weekly/monthly/annually/weekdays), it prefills values accordingly
- custom frequencies, it prefills values accordingly, both when:
- coming from backend (and has it's own backend provided title)
- set by the user but not Saved to backend yet ("Custom" option)
- Improved Back button animation
- Renamed `EditEventFrequencyScreen` to …
=> Calendar event custom frequency prefill

Core/Core/Inbox/Model/InboxMessageInteractorLive.swift, Core/CoreTests/Files/FileSubmission/Model/BinaryUpload/FileSubmissionItemsUploadStarterTests.swift, Core/CoreTests/Inbox/Model/InboxMessageInteractorLiveTests.swift
refs: [MBL-18045](https://instructure.atlassian.net/browse/MBL-18045)
affects: Student,Teacher
release note: Fix the issue of missing Indicator of unread messages on Inbox icon
See [ticket](https://instructure.atlassian.net/browse/MBL-18045) description.
<table>
<tr><th colspan="2">Student App</th ></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/550804d2-b9b4-4dfc-b720-4867eee11dd8" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/4d264140-aa83-405d-926e-a55a9295344d" maxHeight=500></td>
</tr>
<tr><th colspan="2">Teacher App</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/1f6f7ccf-98c7-4861-9356-d6b56c077e11" maxHeight=500></td>
<td><img …
=> Fix the issue of missing Indicator of unread messages on Inbox icon

Core/Core/Courses/K5/ViewModel/K5SubjectViewMasqueradedSession.swift, Core/Core/Login/APIOAuth.swift, Core/CoreTests/Courses/K5/ViewModel/K5SubjectViewMasqueradedSessionTests.swift, Core/CoreTests/Login/APIOAuthTests.swift
refs: [MBL-17910](https://instructure.atlassian.net/browse/MBL-17910)
When an admin acted as a student, closed discussions were still repliable, although students should not be able to reply to closed discussions. This was because the hybrid discussion page was reached with the admin's permissions instead of the masqueraded user's.
When masquerading getting `session_token` needs to use `"/api/v1/login/session_token"` path instead of `"/login/session_token"`, and the URL in the `return_to` query parameter also needs to have the `as_user_id` parameter.
- Verify closed discussions are not repliable when an admin acts as a student. See ticket for details and credentials.
- Verify it works properly when logging in as the student, directly.
- …
=> Update GetWebSessionRequest to support masquerading

Core/Core/Files/View/FileDetails/FileDetailsViewController.swift
It seems that at some point during the offline file support delivery we broke the support for offline files when they are opened via a course's Files or Modules menu. The logic to load such offline files was non-existing so I implemented it.
refs: [MBL-17935](https://instructure.atlassian.net/browse/MBL-17935)
release note: Fixed downloaded files not being available in offline mode.
test plan:
- Have a course with a course file added to modules.
- Sync the course with files for offline mode.
- Go offline.
- Enter the course's Files menu.
- Check if the downloaded file displays in the file viewer.
- Go to Modules, test if the linked file in the module item it will display in offline mode.
- Test if course files (both embedded and linked) in rich content are working in …
=> Fix offline file loading logic

Core/Core/Offline/View/OfflineBannerView.swift, Core/Core/SnackBar/View/UIKit/SnackBarProvider.swift
refs: MBL-18078
release note: Fixed a startup crash which occurred on some devices.
- Fix startup crash
- Fix always visible Back Online banner
Test on iPad @ iOS 18 (and also on other devices)
- Verify the app doesn't crash when user is already logged in or after login
- Verify there is no green "Back Online" banner at the bottom in Student app
- Verify Offline/Onlin transitions show/hide the banners properly
=> Startup crash on iPads running iOS 18

Core/Core/Inbox/MessageDetails/View/MessageDetailsView.swift, Core/Core/Inbox/MessageDetails/View/MessageView.swift, Core/Core/SwiftUIViews/SelectableText.swift
refs: [MBL-18051](https://instructure.atlassian.net/browse/MBL-18051)
release note: Fixed the end of a message not being displayed in some cases.
On Message Details screen some messages were truncated, but not after a specific size or character count.
It happened only in some cases with some iOS font sizes.
- Ceiled the calculated text height, because fractions were not handled properly, causing the last line to not display even though the space for it was almost there.
- Updated the subject to dynamically respond to font size changes
- Verify that a message body which got truncated before this PR now displayed fully
- Play around with iOS font sizes to reproduce the truncation, and check that case in the PR build
<table> …
=> Inbox messages truncated

Core/Core/Grades/View/GradeRowView.swift, Core/Core/People/ContextCard/Course/ContextCardSubmissionsView.swift, Core/Core/Submissions/Submission.swift, Core/CoreTests/Submissions/SubmissionTests.swift, Parent/Parent/Assignments/View/AssignmentDetailsViewController.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: [MBL-18029](https://instructure.atlassian.net/browse/MBL-18029)
affects: Student,Parent
release note: "No Submission" & "On Paper"  assignments displayed status fixed.
See [ticket](https://instructure.atlassian.net/browse/MBL-18029) description.
<table>
<tr><th colspan="2">Student App</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/55d17ca3-f28a-4913-83e0-2dbb4431fb94" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/655fe6d6-aae7-4dcf-b4c8-729d71030215" maxHeight=500></td>
</tr>
<tr><th colspan="2">Parent App</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/63d0e607-b3ea-4f4f-ba21-d06786969644" maxHeight=500></td>
<td><img …
=> Fix the issue of shown status for "No Submission" & "On Paper"  assignments

Core/Core/AudioVideo/AudioPlayerViewController.swift
refs: MBL-17941
release note: Fixes crash of audio player showing infinite time 
Couldn't reproduce the issue on Teacher app.  Though those changes can definitely fix such anticipated issue.
=> Fix crash of audio player showing infinite time

Core/Core/CoreWebView/View/CoreWebView.swift, Core/Core/Login/LoginFindSchoolViewController.swift, Core/Core/Login/LoginManualOAuthViewController.storyboard, Core/Core/Login/LoginManualOAuthViewController.swift, Core/Core/Login/LoginWebViewController.swift, Core/CoreTests/Login/LoginFindSchoolViewControllerTests.swift, Parent/Parent/Info.plist, Student/Student/Info.plist, Teacher/Teacher/Info.plist
- Fixed continue button not being visible on the manual oauth screen.
- The app no longer appends `.instructure.com` to hosts when doing a manual oauth login.
- Added `canvas-web.inseng.test` and `*.docker` as http enabled domains.
- Enabled the inspection of in-app webviews in release mode.
refs: [MBL-17990](https://instructure.atlassian.net/browse/MBL-17990)
test plan:
[MBL-17990]: https://instructure.atlassian.net/browse/MBL-17990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve developer support

Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/AppEnvironment/CacheManager.swift, Core/Core/Extensions/URLExtensions.swift, Core/Core/Files/Model/LocalFileURLCreator.swift, Core/Core/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Login/LoginSession.swift, Core/CoreTests/AppEnvironment/CacheManagerTests.swift, Core/CoreTests/Files/View/FileDetails/FileDetailsViewControllerTests.swift
refs: [MBL-18069](https://instructure.atlassian.net/browse/MBL-18069)
release note: PDF annotations is preserved even when cache is reset
* Login to Student app
* Open a PDF file and make some annotations to it, then go back.
* Close the app entirely.
* Go to the App's page on Settings app.
* Turn on "Reset cache on next launch" toggle.
* Launch the app, then login back to the same user. 
* Open the PDF file that was annotated in step 2.
* You should see the previously saved annotations on that file.
Recording covering PDF annotation persistence scenarios, which are: 
- On logout
- On cache reset.
https://github.com/user-attachments/assets/6c5e7355-bbff-4950-8fbc-982cb9d5f0fa
[MBL-18069]: https://instructure.atlassian.net/browse/MBL-18069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> Preserve PDF annotations even when cache is reset

Core/Core/API/APIFormData.swift, Core/CoreTests/API/APIFormDataTests.swift
refs: [MBL-18046](https://instructure.atlassian.net/browse/MBL-18046)
release note: Fixed file uploads failing when the file's name contained a quotation mark.
test plan: 
- See ticket.
- You can share the file from anywhere, no need to create a file in the drive, just use the Files app.
- All apps affected, the parent is due to file uploads from inbox.
[MBL-18046]: https://instructure.atlassian.net/browse/MBL-18046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Escape quotation mark when uploading a file

Teacher/Teacher/Localizable.xcstrings, Teacher/Teacher/SpeedGrader/CommentEditor.swift, Teacher/Teacher/SpeedGrader/CommentLibrarySheet.swift, Teacher/Teacher/SpeedGrader/SubmissionCommentList.swift, Teacher/Teacher/SpeedGrader/SubmissionGrades.swift
refs: [MBL-18099](https://instructure.atlassian.net/browse/MBL-18099)
release note: Fixed comment library not showing up when tapping on the comment field.
test plan:
- Test if comment library properly shows up when tapping on the comment field.
- Turn off comment library on web.
- Log out and log in to the app to force a refresh on this setting.
- Test if text field properly activates and text can be entered.
[MBL-18099]: https://instructure.atlassian.net/browse/MBL-18099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix comment library not showing up when tapping on the comment field

Core/Core/AppEnvironment/EnvironmentSettings/CDEnvironmentSettings.swift, Core/Core/AppEnvironment/EnvironmentSettings/GetEnvironmentSettings.swift, Core/Core/AppEnvironment/EnvironmentSettings/GetEnvironmentSettingsRequest.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Planner/CalendarFilter/Model/Interactor/CalendarFilterCountLimit.swift, Core/Core/Planner/CalendarFilter/Model/Interactor/CalendarFilterInteractor.swift, Core/Core/Planner/CalendarFilter/Model/Interactor/CalendarFilterInteractorPreview.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/CalendarFilterCountLimit.swift, Core/CoreTests/Planner/CalendarFilter/Model/Interactor/CalendarFilterInteractorTests.swift
- There was a breaking API change in `/api/v1/settings/environment.json`: the `calendar_contexts_limit` field no longer returns a bool whether it's enabled or not but returns the actual limit as an integer in case the `Increase calendar context limit` toggle is enabled. If this setting is not enabled the API won't return this field at all.
- I changed how we store this setting and from now on we use the limit returned by the API instead of the hardcoded 20 value.
refs: [MBL-18102](https://instructure.atlassian.net/browse/MBL-18102)
release note: Fixed calendar not displaying the filter list and events properly.
test plan:
- Enable "Increase calendar context limit" in course settings on web.
- Go to all apps, check if calendar loads.
- Check if calendar …
=> Fix calendar not loading when calendar context limit is increased

Core/Core/Planner/Model/API/APICalendarEvent.swift, Core/CoreTests/BackgroundActivity/BackgroundActivityTests.swift, Core/CoreTests/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncSyllabusInteractorLiveTests.swift, scripts/coverage/config.json
- Improved `BackgroundActivityTests` not to be flaky. The expectation was fulfilled before the tested property got a value and the test teardown didn't terminate a background queue.
- Rounded the default dates on `GetCalendarEventsRequest` because it included the current minutes/seconds and that caused flakyness in `CourseSyncSyllabusInteractorLiveTests` if the second component of the current time have changed between the mock setup and the test execution.
- Updated the code coverage ignore file by removing no longer existing paths and excluding the swiftui based calendar code that is not yet production ready.
=> Fix flaky tests

Core/Core/Assignments/AssignmentList/View/AssignmentListScreen.swift, Core/Core/Courses/CourseDetails/View/CourseDetailsView.swift, Core/Core/Grades/GradeListAssembly.swift, Core/Core/Modules/ModuleList/ModuleListViewController.swift, Core/Core/Router/DefaultViewProvider.swift, Core/Core/SwiftUIViews/UIKitSwiftUIBridging/CoreHostingController.swift, Core/Core/UIViews/CoreSplitViewController.swift, Core/CoreTests/Router/DefaultViewProviderTests.swift
refs: [MBL-18180](https://instructure.atlassian.net/browse/MBL-18180)
release note: Fixed course home page not shown automatically in some cases on iPads.
- Verify on iPad Course Home showing a disabled tab loads automatically (see ticket)
- Verify on iPad AssignmentList screen
- not opening an assignment automatically
- opening an assignment once selected
- Verify on iPhone (non split view) Course Home showing a disabled tab loads once selected
[MBL-18180]: https://instructure.atlassian.net/browse/MBL-18180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix disabled Home page in SplitView details

Core/Core/Router/CourseTabUrlInteractor.swift, Core/CoreTests/Router/CourseTabUrlInteractorTests.swift
K5 Subject Tabs trigger logging for "Unexpected Course Tab path format", but those are false positives.
This PR is just to fix that, it doesn't touch user facing code.
=> Fix false positives for unknown tab format logging

Core/Core/Courses/AllCourses/Model/Entities/CDAllCoursesGroupItem.swift, Core/Core/Courses/AllCourses/Model/GroupListInteractor.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Groups/APIGroup.swift
refs: [MBL-18147](https://instructure.atlassian.net/browse/MBL-18147)
release note: Fixed groups from unpublished courses showing up on All Courses list.
See [ticket](https://instructure.atlassian.net/browse/MBL-18147) description.
[MBL-18147]: https://instructure.atlassian.net/browse/MBL-18147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue of Groups of Unpublished Courses showing in All Courses screen

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift, Core/Core/CoreWebView/Model/Features/HideReturnButtonInQuizLTI.swift, Core/Core/Courses/CourseDetails/ViewModel/Cells/LTICellViewModel.swift, Core/Core/LTI/LTITools.swift, Core/Core/LTI/View/LTIViewController.swift, Core/Core/Modules/ModuleItems/ModuleItemDetailsViewController.swift, Core/Core/Profile/SideMenu/SideMenuMainSection.swift, Core/Core/Studio/Model/StudioAPIAuthInteractor.swift, Core/CoreTests/CoreWebView/Model/Features/HideReturnButtonInQuizLTITests.swift, Core/CoreTests/LTI/LTIToolsTests.swift, Core/CoreTests/LTI/View/LTIViewControllerTests.swift, Student/Student/Routes.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift, Teacher/Teacher/Attendance/RollCallSession.swift
refs: [MBL-17982](https://instructure.atlassian.net/browse/MBL-17982)
release note: QuizLTIs now open internally.
- New Quizzes (= Quiz LTIs) now open in webview, instead of internal browser
- The "Return" button had been removed from the Quiz pages (based on `data-automation` id)
- Since we already have a native "Done" button, this was preferred option instead of fixing the return navigation
- The Quiz pages now respect dark/light mode preferences
- There is no back navigation after the user taps on a link or a button within the LTI pages. This is the result of using webview instead of a browser window.
- QuizLTI session seem to have 5sec send interval. When you tap Done to dismiss the screen quickly after a change, then the change may not get persisted. This is …
=> New Quiz LTI in dedicated web view

Core/Core/Contexts/Context.swift, Core/Core/Courses/SmartSearch/View/CourseSearchResultRowView.swift, Core/Core/Courses/SmartSearch/View/CourseSmartSearchFilterEditorView.swift, Core/Core/Courses/SmartSearch/View/CourseSmartSearchHelpView.swift, Core/Core/Extensions/UIColorExtensions.swift, Core/Core/Search/View/SearchContentContainerView.swift, Student/Student/Routes.swift
refs: [MBL-18169](https://instructure.atlassian.net/browse/MBL-18169)
release note: Fixed appearance (light/dark mode) issues for Course Smart Search
See [ticket](https://instructure.atlassian.net/browse/MBL-18169) description.
[MBL-18169]: https://instructure.atlassian.net/browse/MBL-18169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Appearance (Light/Dark Mode) Issues of Course Smart Search

Core/Core/Assignments/AssignmentList/View/AssignmentListPreferencesScreen.swift, Core/Core/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift, Core/CoreTests/Assignments/AssignmentList/ViewModel/AssignmentListViewModelTests.swift
refs: MBL-18168
release note: Improved assignment list and assignment list preferences screen.
- When opening the assignment list screen for the first time, the current grading period fails to get selected automatically and shows "All" instead of the current one, and only shows the correct one after PTR.
- Assignment List Preferences screen doesn't have backgroundLightest as background colour.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/80379aac-40db-4cf5-b073-8ad7da949233" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/1db69295-500d-4aea-959a-94ded441c7af" maxHeight=500></td>
</tr>
</table>
=> Assignment List and List Preferences Improvements

Core/Core/Grades/View/GradeListView.swift, Student/StudentE2ETests/Grades/GradingPeriodsTests.swift
refs: [MBL-18084](https://instructure.atlassian.net/browse/MBL-18084)
release note: Fixed grade preferences screen not displaying grading periods in some cases.
The resolution was basically to hide the filter button on screen appearance, until the loading finishes for the first time. Subsequent reloading won't hide it again.
https://github.com/user-attachments/assets/f87380ca-2692-43bb-9fcd-c807d7150c59
- Login to a student account
- Navigate to a course Grades screen
- While initial loading, filter button is not being displayed
- After first loading, on success or failure, filter button must be displayed.
- Try reloading the screen or picking a grading period from filter screen, at all cases filter button should still be displayed.
[MBL-18084]: …
=> Fix E2E test issue with Grading Periods Not being shown correctly on Grades Filter screen

Core/Core/Courses/Course.swift, Core/Core/Grades/Model/GradeListInteractor.swift, Core/CoreTests/Grades/GradeListInteractorLiveTests.swift, Core/CoreTests/Search/CoreSearchHostingControllerTests.swift
refs: [MBL-18151](https://instructure.atlassian.net/browse/MBL-18151)
release note: Fixed grades screen not showing total grades for concluded enrollments.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18151) description.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/37b65856-13ee-403b-aa46-6b8e88be34bb" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/38609d6f-2e43-409a-8d80-9bf0fa0b740a" maxHeight=500></td>
</tr>
</table>
[MBL-18151]: https://instructure.atlassian.net/browse/MBL-18151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue of Total Grades Restricted for Concluded Courses

Core/Core/Features/Inbox/ComposeMessage/View/ComposeMessageView.swift
test plan: VoiceOver should read out the "search recipient" input field as well.
=> Accessibility - Teacher - Inbox - Compose Message - Search recipients input field

Core/Core/Features/Inbox/ComposeMessage/View/ComposeMessageView.swift
test plan: VoiceOver should read the subject label of a composed message as a header.
=> Accessibility - Teacher - Inbox - Compose Message - Subject label as header

Core/Core/Features/Inbox/ComposeMessage/View/ComposeMessageView.swift
test plan: On Compose Message screen, subject and body elements should indicate themselves as input fields for VoiceOver.
=> Accessibility - Teacher - Inbox - Compose Message - Subject and Body input labels

Core/Core/Features/Planner/CalendarEvent/View/EditCalendarEventScreen.swift
test plan: Title field should indicate that it's a required field, both visually and with VoiceOver.
=> Accessibility - Teacher - Calendar - Edit Event screen - Title field as required

Core/Core/Common/CommonUI/Presenter/ColoredNavViewProtocol.swift
test plan: VoiceOver should read the title in Discussions List screen as a header.
=> Accessibility - Teacher - Discussions - Title as header

Core/Core/Common/CommonUI/Presenter/ColoredNavViewProtocol.swift
test plan: VoiceOver should read the title on Modules page as a header.
=> Accessibility - Teacher - Modules - Title as header

Core/Core/Features/Planner/CalendarMain/CalendarViewController.swift, Core/CoreTests/Features/Planner/CalendarMain/CalendarViewControllerTests.swift
test plan: VoiceOver should read "Calendars" button as "Filter events by Calendars" instead of "Filter events".
=> Accessibility - Teacher - Calendar - Filter events button label

Teacher/Teacher/Submissions/SubmissionListViewController.swift
test plan: VoiceOver should read Submission cells as buttons on Submission List screen.
=> Accessibility - Teacher - Submissions - List cells button trait

Core/Core/Features/Modules/ModuleList/ModuleItemCell.swift
test plan: VoiceOver should read Module Item cells as buttons on Module List screen.
=> Accessibility - Teacher - Modules - ModuleItemCell button trait

Core/Core/Common/CommonUI/UIViews/TitleSubtitleView.swift
test plan: VoiceOver should announce the navigation bar title as header.
VoiceOver should announce the navigation bar title on the AssignmentDetails screen (also QuizDetails, etc) as a "header".
=> Accessibility - Student - AssignmentDetails - Navigation bar title as header

Core/Core/Common/CommonUI/UIViews/RightDetailTableViewCell.swift
test plan: All submission filter options should be displayed correctly even when the font size is set to the maximum.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/d1d5f95f-3731-4c43-9990-c7e99b886b69" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/a0dd7152-7d4b-46f6-9d49-4781baeb5987" maxHeight=500></td>
</tr>
</table>
=> Accessibility - Teacher - Submission Filter Picker - Dynamic font size

Core/Core/Common/Extensions/Foundation/ArrayExtensions.swift, Core/Core/Features/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift, Core/Core/Features/Dashboard/K5/ViewModel/Grades/K5GradesViewModel.swift, Core/Core/Features/Grades/Model/Entities/GradingPeriod.swift
refs: [MBL-18150](https://instructure.atlassian.net/browse/MBL-18150)
In Canvas Web, grading periods are defined per account.
While in the app, the first point at which GradingPeriods are being fetched is in `Course.save()` method.
https://github.com/instructure/canvas-ios/blob/dd7302c583be57bfd321fb2a33a28857b89102f2/Core/Core/Features/Courses/Course.swift#L96
You can see that the implementation gives the notion that we have a GradingPeriod per course which is not correct.
The issue was actually caused by overriding the value of `GradingPeriod.courseID` whenever it get saved for a specific course in that `Course.save()` method, this because we are relying only on `GradingPeriod.id` to identify the object on the database.
The current fix solves …
=> Resolve the issue of GradingPeriods not getting persisted properly per Course in the Database

Core/Core/Common/CommonModels/Router/CourseTabUrlInteractor.swift, Core/CoreTests/Common/CommonModels/Router/CourseTabUrlInteractorTests.swift
refs: [MBL-18180](https://instructure.atlassian.net/browse/MBL-18180)
release note: Fixed external tool link being disabled in some cases.
This is a fix for a reopened ticket. The issue was that the enabled tabs list returned from backend contained the `?display=borderless` query in the `html_url` and this was not handled properly. Now all query and fragment are removed from these URLs before parsing them.
Also removed logging of `settings` tab as an `Unexpected Course Tab path format`, which was logged when teachers log into Student app. This is a known case, removed from logging to make actual exceptions visible in the logs.
Verify external tool link "Aleks" works for student linked in [ticket comment](https://instructure.atlassian.net/browse/MBL-18180?focusedCommentId=2 …
=> Disabled tab link with query

Core/Core/Common/CommonUI/UIViews/TitleSubtitleView.swift, Core/Core/Features/Assignments/AssignmentDetails/AssignmentDetailsView.swift, Core/Core/Features/Quizzes/QuizDetails/Teacher/View/TeacherQuizDetailsView.swift
Accessibility - Teacher - Quiz Details - Add header as trait
refs: MBL-18296
Original PR: https://github.com/instructure/canvas-ios/pull/3057
(reopened due to CI issues)
=> Accessibility - Teacher - Quiz Details - Add header as trait

Core/Core/Features/Dashboard/Container/View/DashboardContainerViewController.swift
refs: [MBL-18165](https://instructure.atlassian.net/browse/MBL-18165)
release note: Fix the iPad 18 layout issue of dashboard navigation bar.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18165) description.
https://github.com/user-attachments/assets/17c2b8c2-0d94-4450-92dd-665e0e4ecff8
[MBL-18165]: https://instructure.atlassian.net/browse/MBL-18165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix iPad 18 NavigationBar appearance issue on swipe-to-back gesture

Core/Core/Features/Conversations/ComposeViewController.storyboard, Core/Core/Features/Conversations/ComposeViewController.swift
Parent - VoiceOver shouldn't read Subject and Message fields as header
refs: MBL-18360
=> Accessibility - Parent - VoiceOver shouldn't read Subject and Message fields as header

Core/Core/Features/Courses/CourseDetails/Model/CourseHomeProperties.swift, Core/CoreTests/Features/Courses/CourseDetails/Model/CourseHomePropertiesTests.swift, Core/CoreTests/Features/Courses/CourseDetails/ViewModel/CourseDetailsViewModelTests.swift
refs: [MBL-18551](https://instructure.atlassian.net/browse/MBL-18551)
release note: Fixed course home front page not visible in some cases.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18551) description.
[MBL-18551]: https://instructure.atlassian.net/browse/MBL-18551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue Consortia root account unable to see Front Page content when set as course home page

Core/Core/Common/CommonUI/SwiftUIViews/WebView.swift, Student/StudentE2ETests/Announcements/AnnouncementsTests.swift, Teacher/TeacherE2ETests/Announcements/AnnouncementsTests.swift
refs: MBL-18561
(no release note, because the issue this one fixes was not released yet)
test plan:
- Create a global announcement.
- Start apps.
- Tap on the announcement on dashboard to view its contents.
- Content should appear.
=> Fix swiftui webview not loading string content 

Core/Core/Features/Planner/CalendarMain/CalendarViewController.swift, Core/CoreTests/Features/Planner/CalendarMain/CalendarViewControllerTests.swift
Add accessibilityValue to "Show a month at a time" button to indicate if expanded or collapsed.
refs: MBL-18301
=> Accessibility - Calendar - Add accessibilityValue to "Show a month at a time" button to indicate if expanded or collapsed

Core/Core/Features/Conversations/EditComposeRecipientsViewController.swift
VoiceOver should read the row items (cells) of EditRecipients screen as "Button" in TeacherChat.
Also, "Selected" accessibilityTraits should be used if the cell is selected.
See ticket for further understanding.
refs: MBL-18361
=> Parent - TeacherChat - EditRecipients - set accessibilityTraits of RecipientCell

Core/Core/Common/CommonModels/Contexts/Context.swift, Core/Core/Features/Files/View/FileList/FileListViewController.swift, Core/CoreTests/Features/CourseSync/Common/Model/CourseSyncCleanupInteractorTests.swift
refs: [MBL-18552](https://instructure.atlassian.net/browse/MBL-18552)
See [ticket's](https://instructure.atlassian.net/browse/MBL-18552) description.
[MBL-18552]: https://instructure.atlassian.net/browse/MBL-18552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes issue where Files are not showing for user of Consortia root account

Core/Core/Features/Grades/View/AssignmentSection.swift
refs: MBL-18395
test plan: VoiceOver should read section headers as button.
=> Parent - Grade List - Section header button trait

Parent/Parent/Students/StudentDetailsViewController.swift
refs: MBL-18394
test plan: VoiceOver should read student's name as a header.
=> Parent - Manage Students - Student name as header

Core/Core/Features/Conversations/ComposeViewController.swift
Ideally all input fields should have an accessibility trait as "text field" or "text input" or something like that, and most cases VoiceOver recognises these elements correctly, but for UITextView and UITextField it just doesn't work like that.
Since there is no accessibility trait that we could add to these for this case (textField or textInput) I added it as an accessibilityHint. VoiceOver reads it like it was a trait but it's a hint instead. I made some research and investigated what could be done and found no better solution than this one, but I'm open to any ideas. My guess is that UIKit text inputs have some issues with being accessible (the internet says other devs experienced similar accessibility issues with these components).
refs: MBL-18368 …
=> Parent - TeacherChat - Compose screen - add accessibilityHint to input fields

Core/Core/Features/Conversations/EditComposeRecipientsViewController.swift
refs: MBL-18357
test plan: VoiceOver should read title label as a header.
=> Accessibility - Parent - Chat - EditComposeRecipients - title label as header

Core/Core/Features/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift, Student/SubmitAssignment/SubmitAssignmentViewController.swift
refs: [MBL-18149](https://instructure.atlassian.net/browse/MBL-18149)
release note: Fixed file share submission failure after user change.
- Fixed the issue when upload failed after user change
- Recreated `FileSubmissionAssembly` for each submission screen instead of reusing static one
- Added the current user's name as a subtitle in the navigation bar
- It was like this before, but multiple simultaneous submissions from the extension can result in one of them getting lost:
- start an upload from extension, dismiss the screen
- open the Student app, observe upload is in progress
- start another upload from extension
- Both uploads will finish together with Success, but one of them might get lost
- It was like this before, but Upload progress bar on Student app Dashboard …
=> File share submission fails after user change

Parent/Parent/Dashboard/DashboardViewController.swift, Parent/Parent/Localizable.xcstrings, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
refs: MBL-18397
test plan: Dropdown button should be accessible by VoiceOver and not as last element of the screen.
Originally the ticket was about the dropdown button not being accessible by VoiceOver but as I checked it already was, it was just the last element of the screen that VoiceOver read. Now it's the first one. I think profile button should be the first one here but I didn't manage to find a way to change the priority order of the elements.
=> Accessibility - Parent - Dashboard - Dropdown button accessibility

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-18457
test plan: VoiceOver should read attempts date as a button only if it is really a button.
Previously that attemptsDateButton was read by VoiceOver as a "button" even if it was not active/clickable and that could be misleading to the user. Now if the button is not active then we set the accessibilityTraits of the button to staticText.
=> Accessibility - Student - AssignmentDetails - Attempts date button traits handling

Core/Core/Features/CourseSync/Common/Model/CourseSyncCleanupInteractor.swift, Core/CoreTests/Features/CourseSync/Common/Model/CourseSyncCleanupInteractorTests.swift, Core/CoreTests/Features/Files/FileSubmission/Model/FileSubmissionAssemblyTests.swift, Core/TestsFoundation/Helpers/CombineTestExtensions.swift, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift, Student/Student/Assignments/AssignmentDetails/Reminders/Model/Notifications/AssignmentNotificationHelpers.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/Reminders/Model/AssignmentRemindersInteractorLiveTests.swift
- `AssignmentRemindersInteractorLiveTests.swift`: Improved failure messages in `waitUntil` call to provide better debugging information since I was unable to reproduce the error locally.
- `CourseSyncCleanupInteractor.swift`: Modified the `clean` method to accept a custom scheduler parameter because testing file availability from mixed threads seemed to be unreliable.
- Increased timeouts for multiple assertions and for Combine assertions in general because timeout is a main source of flakyness.
refs: MBL-18578
affects: none
test plan:
- Unit tests should pass.
=> Fix flaky unit tests

Teacher/Teacher/SpeedGrader/RubricAssessor.swift, Teacher/Teacher/SpeedGrader/SubmissionGrades.swift
refs: MBL-18438
test plan: VoiceOver should read "Grade" and "Rubric" labels as headers.
=> Accessibility - Teacher - Submission - Grades - Add header trait to "Grade" and "Rubric" labels

Parent/Parent/Courses/CourseListViewController.swift
refs: MBL-18401
test plan: VoiceOver should read cells as buttons.
=> Accessibility - Parent - Course List - Button trait for cells

Core/Core/Features/Grades/Model/Entities/GradeListData.swift, Core/Core/Features/Grades/Model/GradeListInteractor.swift, Core/Core/Features/Grades/View/GradeListView.swift
refs: MBL-18469
test plan: VoiceOver should read section headers with list count.
The ticket wants the list count to be available for the user when using VoiceOver. It assumes we use UITableView but this screen is SwiftUI so I thought it might be a good idea here to extend the accessibilityLabel of the section headers instead.
Let me know if this is not the right or desired solution or if it's not the correct way to solve this issue.
=> Accessibility - Student - GradeList - Section header to contain list count

Student/Student/Localizable.xcstrings, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
- The ticket wanted voiceover to announce this action sheet as a list but this is a `UIAlertController` which isn't configurable in terms of accessibility so I added a title there to make it more explicit that there's a list of options to choose from.
refs: [MBL-18389](https://instructure.atlassian.net/browse/MBL-18389)
test plan:
- Check if the "Add media attachment" button has a title on the submission comment screen.
[MBL-18389]: https://instructure.atlassian.net/browse/MBL-18389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Student - Submissions Comments - Add title to media attachment type picker

Core/Core/Common/CommonUI/UIViews/FilterHeaderView.swift
- When submissions list was opened for the first time neither the label nor the header had the heading trait.
- I was able to get the header trait on the filter button by opening the filter screen and closing it with done.
- I think because this view was used as a header in a tableview this caused it to get the heading label on all subviews.
- Adding traits explicitly seemed to solved the issue.
refs: [MBL-18342](https://instructure.atlassian.net/browse/MBL-18342)
test plan:
- Make sure filter button on submissions list never has heading trait.
[MBL-18342]: https://instructure.atlassian.net/browse/MBL-18342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Teacher - Submissions List - Make traits explicit

Core/Core/Common/CommonUI/UIViews/GroupedSectionHeaderView.swift, Core/Core/Common/CommonUI/UIViews/ItemPickerViewController.swift, Core/Core/Common/Extensions/Foundation/StringExtensions.swift, Core/Core/Features/Files/View/FileList/FileListViewController.swift, Core/Core/Features/Grades/View/GradeListView.swift, Core/Core/Features/Profile/Settings/NotificationCategoriesViewController.swift, Core/Core/Features/Profile/Settings/NotificationChannelsViewController.swift, Core/Core/Features/Profile/Settings/ProfileSettingsViewController.swift, Core/Core/Features/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift, Core/CoreTests/Common/Extensions/Foundation/StringExtensionsTests.swift
refs: [MBL-18337](https://instructure.atlassian.net/browse/MBL-18337)
- In ProfileMenu Settings
- all section headers now have `header` trait
- all section headers read the number of rows, like "Preferences, 4 items, Heading"
- In all ItemPicker screens:
-  read the number of rows together with the first row, like: "List, 5 items, selected, Dashboard, Button"
- it's strange but this seems to be the default behavior for UITableView when it's a11y label is provided
- removed the empty gap above the section
NOTE: `ItemPickerViewController` is not fully improved to support multiple sections with or without titles, because it's always used with a single section, without title. It would be extra work and we won't create new screens using it, as UIKit …
=> Accessibility - Student/Teacher - ProfileMenu Settings headers and lists

Core/Core/Features/Dashboard/Container/View/DashboardContainerView.swift, Core/Core/Features/Dashboard/K5/View/K5DashboardView.swift, Core/Core/Features/Inbox/View/InboxView.swift, Core/Core/Features/Planner/CalendarMain/PlannerViewController.swift, Core/Core/Features/Todos/TodoListViewController.swift, Parent/Parent/Dashboard/DashboardViewController.swift, Parent/Parent/Localizable.xcstrings, Student/Student/Localizable.xcstrings, Student/Student/Notifications/ActivityStreamViewController.swift
- I only added the closed state to the menu button because when the menu is opened the button is not reachable so its closed state would be never heard.
- I tried to re-use strings from the Core project in Parent and Student but despite I added the Core bundle it still got localized in those projects.
refs: [MBL-18372](https://instructure.atlassian.net/browse/MBL-18372)
test plan:
- Test if profile button on all tabs announce its closed state.
[MBL-18372]: https://instructure.atlassian.net/browse/MBL-18372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - All Apps - Menu Button - Add closed state

Core/Core/Common/CommonUI/UIViews/HorizontalMenuViewController.swift
refs: [MBL-18414](https://instructure.atlassian.net/browse/MBL-18414)
test plan:
- Ensure course tab buttons don't have heading trait.
[MBL-18414]: https://instructure.atlassian.net/browse/MBL-18414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Parent - Course Details - Remove heading trait from course tab button

Teacher/Teacher/Localizable.xcstrings, Teacher/Teacher/SpeedGrader/SubmissionCommentList.swift
refs: [MBL-18471](https://instructure.atlassian.net/browse/MBL-18471)
test plan:
- Check if sending a comment from SpeedGrader announce the failure and success result of the sending.
[MBL-18471]: https://instructure.atlassian.net/browse/MBL-18471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Teacher - Add send action announcements to SpeedGrader send comment button

Core/Core/Features/Discussions/Editor/ViewModel/DiscussionCreateWebViewModel.swift
- The ticket was about saving and edited discussion but since that is a webview we can't improve it from our side.
- Instead I added an announcement to the end of the creation flow when we dismiss the create dialog.
refs: [MBL-18423](https://instructure.atlassian.net/browse/MBL-18423)
test plan:
- Create a new discussion and announcement.
- Check if the correct announcement is made after a successful save.
[MBL-18423]: https://instructure.atlassian.net/browse/MBL-18423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Teacher/Student - Add discussion save announcement

Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift, Core/CoreTests/Common/CommonUI/CoreWebView/View/CoreWebViewTests.swift, Core/TestsFoundation/Router/TestRouter.swift, Teacher/Teacher.xcodeproj/project.pbxproj, Teacher/Teacher/Routes.swift, Teacher/Teacher/SpeedGrader/SpeedGraderAssembly.swift, Teacher/Teacher/SpeedGrader/SpeedGraderViewController.swift, Teacher/TeacherTests/RoutesTests.swift, Teacher/TeacherTests/SpeedGrader/SpeedGraderViewControllerTests.swift
refs: [MBL-17942](https://instructure.atlassian.net/browse/MBL-17942)
release note: SpeedGrader now correctly opens from graded discussions.
test plan:
- Create a graded discussion.
- Post a comment as a student and as a non-student user.
- Open the discussion from the teacher app.
- Open SpeedGrader from the main post of the discussion.
- SpeedGrader should open.
- Open SpeedGrader from a post of a student.
- SpeedGrader should open focused on that student.
- Open SpeedGrader from a post of a teacher.
- SpeedGrader should open with a no submissions remark.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/5219f68f-664d-4a01-b459-d65512b4d5b3" maxHeight=500></td>
<td><img …
=> Open native speedgrader from web discussion

Core/Core/Common/Extensions/Foundation/ArrayExtensions.swift, Core/Core/Features/Planner/CalendarMain/CalendarDaysViewController.swift, Core/Core/Features/Planner/CalendarMain/CalendarViewController.swift, Core/Core/Features/Planner/CalendarMain/PlannerListViewController.swift, Core/Core/Features/Planner/CalendarMain/PlannerViewController.swift
refs: MBL-18323, MBL-18327
release note: None.
In Teacher or Student app,
1- Go to "Calendar" tab
2- Select day on Calendar.
3- Double tap on it with VoiceOver turned on.
4- Make sure focus is moved to the first or selected row of that day events list
5- With VoiceOver On, Tap on "Go to today" button on the top-right corner of Calendar tab screen.
6- Make sure focus is moved to calendar day button of today's date.
=> Accessibility - Student /Teacher - Focus on Events List when Calendar Day gets Selected, Focus on Calendar Day Button when "Go to Today" is tapped

Core/Core/Common/CommonUI/Accessibility/UIAccessibilityAnnouncement.swift, Student/Student/Localizable.xcstrings, Student/Student/Submissions/SubmissionComments/SubmissionCommentsPresenter.swift
refs: [MBL-18380](https://instructure.atlassian.net/browse/MBL-18380)
test plan:
- Send a comment successfully for a submission attempt.
- Voiceover should announce if the comment was sent successfully.
[MBL-18380]: https://instructure.atlassian.net/browse/MBL-18380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Student - Announce successful comment sending

Core/Core/Features/Inbox/Addressbook/ViewModel/AddressbookRecipientViewModel.swift, Core/Core/Features/Inbox/Addressbook/ViewModel/AddressbookRoleViewModel.swift
refs: MBL-18353
release note: None.
- Go to Inbox in Teacher or Student app.
- Start a new message by tapping on "+" button. This will show "compose message" form.
- Select course, then hit "+" button shown on the side of "To" field.
- With VoiceOver turned On, start typing on search field of the shown screen.
Also, you can tap on one of the shown roles, then starting search on that sub-screen as well.
- For both screens, when searching a message about results found must be read out as you typing.
=> Accessibility - Student /Teacher - Typehead Suggestions for Message Recipients searching

Core/Core/Features/Assignments/AssignmentList/View/AssignmentGroupView.swift
refs: [MBL-18480](https://instructure.atlassian.net/browse/MBL-18480)
Verify AssignmentList section headers read out number of items
[MBL-18480]: https://instructure.atlassian.net/browse/MBL-18480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Add number of items to a11y label in AssignmentList sections

Core/Core/Common/CommonUI/SwiftUIViews/SegmentedPicker.swift
refs: [MBL-18443](https://instructure.atlassian.net/browse/MBL-18443)
- Tried to use the iOS17+ trait `isTabBar` in our custom `SegmentedPicker`, without any success
- Ended up trying to replicate the tab bar a11y behavior:
- "Selected" state is read for the current tab
- "# of 3" is read for each tab, but in this order: `"Grades, 1 of 3, Button"` instead of `"Grades, Tab, 1 of 3"`
Some other examples in the app:
- Student > Submission > Comments/Files/Rubric tabs: uses `UISegmentedControl`, reads `"Comments, Button, 1 of 3"`
- main TabBar: uses `UITabBarController`, reads `"Dashboard, Tab, 1 of 5"`
Verify the Speedgrader Grades/Comments/Files tabs read out the selected state and the tab number as described above.
[MBL-18443]: …
=> Accessibility - Teacher - Speedgrader Grades-Comments-Files tabs

Core/Core/Features/Conversations/ComposeRecipientsView.swift
refs: [MBL-18356](https://instructure.atlassian.net/browse/MBL-18356)
In Parent app, go to Inbox section from Side Menu. Then try compose a message for some course.
Turn on VoiceOver on the Compose Message screen, and validate the ordering of recipients field in both states (expanded and collapsed).
[MBL-18356]: https://instructure.atlassian.net/browse/MBL-18356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Parent - Fixes Accessibility Focus Order of Recipients Field of Parent's Compose Message Form

Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
refs: MBL-18385
As per the ticket, in case we are on another tab (Files) and we tap on Comments tab then the VoiceOver focus should move to the comments (ticket wants it to move to the first comment on the list, but I thought it's better to move it to the latest comment).
=> Accessibility - Student - SubmissionDetails - Set VoiceOver focus on changing tabs on drawer

Core/Core/Common/CommonUI/UIViews/ItemPickerViewController.swift, Core/Core/Common/Extensions/Foundation/StringExtensions.swift, Core/Core/Features/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelItem.swift, Core/Core/Features/Inbox/Addressbook/View/AddressbookRecipientView.swift, Core/Core/Features/Inbox/Addressbook/View/AddressbookRoleView.swift, Core/Core/Features/Inbox/Addressbook/ViewModel/AddressbookRecipientViewModel.swift, Core/Core/Features/Inbox/Addressbook/ViewModel/AddressbookRoleViewModel.swift, Core/CoreTests/Common/Extensions/Foundation/StringExtensionsTests.swift, Core/CoreTests/Features/CourseSync/Common/ViewModel/OfflineListCellViewModelTests.swift, Core/CoreTests/Features/CourseSync/CourseSyncSelector/ViewModel/CourseSyncSelectorViewModelItemTests.swift, Core/CoreTests/Features/Inbox/Addressbook/ViewModel/AddressbookRecipientViewModelTests.swift, Core/CoreTests/Features/Inbox/Addressbook/ViewModel/AddressbookRoleViewModelTests.swift, Teacher/Teacher/SpeedGrader/SubmissionCommentList.swift
refs: [MBL-18348](https://instructure.atlassian.net/browse/MBL-18348)
- Added "List, # items" to the first element of both Recipients screens
- Added `String.localizedAccessibilityListCount()` for this
- Updated existing usages
- Updated Submission Comment Sent a11y label
Verify list count is read for Recipients screens (both when showing list of roles, and list of recipients)
Verify list counts are still read properly on Offline Sync screen
[MBL-18348]: https://instructure.atlassian.net/browse/MBL-18348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Inbox Recipients list count

Core/Core/Common/CommonUI/UIViews/CoreSplitViewController.swift, Core/CoreTests/Features/Files/FileSubmission/Model/FileSubmissionAssemblyTests.swift
refs: MBL-18549
release note: Fixed the issue where app doesn't refresh shown page properly after switching to another app
Upon testing on an isolated case, turned out that `UISplitViewController` always report collapse then expansion whenever app is put to background. For that, `CoreSplitViewController` in that case calls delegate's methods of:
`func splitViewController(_ splitViewController: UISplitViewController, separateSecondaryFrom primaryViewController: UIViewController)` upon **expansion**.
`func splitViewController(_ splitViewController: UISplitViewController, collapseSecondary secondaryViewController: UIViewController, onto primaryViewController: UIViewController)` upon **collapsing**.
Which causes the unnecessary disruption on SplitView, although …
=> Fix the issue of detail view of SplitViewController when switching out-in the app

Parent/Parent/Dashboard/DashboardViewController.swift
refs: MBL-18400
release note: None.
In Parent app, switch between tabs with VoiceOver On, double tap on the focused tab, focus should move to student avatar view.
=> Accessibility - Parent - Move Focus to Student Avatar on When activating a Tab

Core/Core/Common/CommonUI/UIViews/HorizontalMenuViewController.swift, Parent/Parent/Courses/CourseDetailsViewController.swift
refs: [MBL-18415](https://instructure.atlassian.net/browse/MBL-18415)
In Parent app, tap on any course of those shown on Courses tab.
With VoiceOver on, switch between tabs, when tab is selected (Grades, Syllabus, or Summary) focus should move to the first element shown on those screens.
For tab details page of `CoreWebViewController`, like "Front Page", when selected accessibility focus stay on the same tab button. It doesn't move to the first element of the shown web view. Not sure if this should belong to this scope, as it would require observing when web content is fully loaded, then after that move focus to it, which -to me- could lead to a bloated code for the task. 
[MBL-18415]: https://instructure.atlassian.net/browse/MBL-18415?atlOrigin=eyJpIjoiN …
=> Accessibility - Parent - Move focus to percent label when Grades tab is selected

Core/Core/Common/CommonModels/Router/CourseTabUrlInteractor.swift, Core/CoreTests/Common/CommonModels/Router/CourseTabUrlInteractorTests.swift
refs: [MBL-18581](https://instructure.atlassian.net/browse/MBL-18581)
release note: Fixed a bug where hidden tabs were not handled correctly.
- Grades and Discussions tabs are no longer disabled for access via direct links (like the rest of the tabs), but only hidden from the list of tabs (as they were already).
- Excluded LTI launch request format from logging.
- Not adding it to known tab formats at the moment, just excluding from logging
- Disable Grades, Discussion and some other tabs (as a Teacher or Admin)
- Create links for these tabs on a page, or message, or anywhere in the app
- for Discussions: `.../courses/42/discussion_topics`
- for Grades: `.../courses/42/grades`
- Verify these links open their respective screens in the app
- Verify links for other disabled …
=> Always enable Grades and Discussions tab links

Core/Core/Features/DocViewer/DocViewerViewController.swift, Core/CoreTests/Features/DocViewer/DocViewerViewControllerTests.swift
refs: [MBL-18463](https://instructure.atlassian.net/browse/MBL-18463)
Student or Teacher annotations has a status message at the top.
This should not act as a disabled button.
**NOTE:** the related error method is never used, but I've updated it anyway, didn't want to investigate deeply.
Verify the "Saving" or "All annotations saved" texts doesn't read "Button, Dimmed" in both places:
- Student app > Assignment with Student Annotation type > Submit Assignment screen
- Teacher app > Assignments > SpeedGrader
[MBL-18463]: https://instructure.atlassian.net/browse/MBL-18463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Student / Teacher - Fix Student Annotation status message a11y traits

Core/Core/Features/Planner/CalendarMain/PlannerViewController.swift
refs: MBL-18297
test plan: Accessibility label of Today button should contain today's date in short format (February 21).
=> Accessibility - Teacher - Calendar - Today button should have the date

Core/Core/Features/Planner/CalendarMain/CalendarDaysViewController.swift
VoiceOver should read weekday as well alongside with the date for day buttons in Calendar.
Also I moved the event count to accessibilityHint because I think it's nicer to provide it there, but let me know if you have any concerns with it.
refs: MBL-18299
=> Accessibility - Teacher - Calendar - Day button to have weekday in label

Core/Core/Common/CommonUI/InstUI/Views/Cells/DatePickerCell.swift, Core/Core/Common/Extensions/Foundation/DateExtensions.swift, Core/Core/Common/Extensions/Foundation/StringExtensions.swift, Core/Core/Features/Planner/CalendarEvent/View/EditCalendarEventScreen.swift, Core/Core/Features/Planner/CalendarEvent/View/EditCustomFrequencyScreen.swift, Core/Core/Features/Planner/CalendarToDo/View/EditCalendarToDoScreen.swift, Core/CoreTests/Common/Extensions/Foundation/DateExtensionsTests.swift, Core/CoreTests/Common/Extensions/Foundation/StringExtensionsTests.swift
refs: [MBL-18334](https://instructure.atlassian.net/browse/MBL-18334)
Ticket's recommendation is a bit unclear.
Initial recommendation from UX was to combine DatePickerCell's label with the actual datepicker button.
It would be okay for date-only or time-only cases, but not really for the date-time case.
Instead the following had been decided (which matches native iOS Calendar app):
- First focus is the label, which now includes the date/time as well: "Start time, 2025. 02. 12. at 13:13"
- and the error message (if present)
- Next focus is the date-picker (if present): "Date picker, 2025. 02. 12., Button, Collapsed, Double-tap to expand"
- Next focus is the time-picker (if present): "Time picker, 13:13, Button, Collapsed, Double-tap to expand" …
=> Accessibility - DatePickerCell

Core/Core/Features/Courses/SmartSearch/View/CourseSmartSearchFilterEditorView.swift, Core/Core/Features/Login/LoginQRCodeTutorialViewController.swift, Core/Core/Features/Login/PairWithStudentQRCodeTutorialViewController.swift
refs: [MBL-18640](https://instructure.atlassian.net/browse/MBL-18640)
(No notes, because the cause of the issue is also not released yet)
- Fix Next button missing on QR Login screen on iOS 17
- Fix Next button missing on Pair With Student QR Login screen on iOS 17
- Fix SmartSearch Results screen nav bar turning white when Filter is presented
Test both on iOS 17 & 18
Student + Teacher
- Reach Login screen, tap "QR Login" button
- Verify Next button is visible and working on QR code screen
Parent
- Reach Login screen, tap "QR Login" button
- Check both options (with and without Canvas Account)
- Verify Next button is visible and working on QR code screen (in both cases)
Student
- Reach SmartSearch in a Course
- Tap filter icon (without …
=> Fix Navigation Bar issues

scripts/generate-release-notes.js
Updated `generate-release-notes.js` to generate a more useful list from the commits, which includes direct links for tickets and PRs.
Also, now this same script can be used to generate the same list before the release process is started and the current tag is created. To generate a list since the last tag use simply `Student` (or the other app names, uppercased) as the argument instead of a tag.
=> Improve release notes generation

Core/Core/Common/CommonUI/InstUI/Views/Cells/DatePickerCell.swift, Core/Core/Common/CommonUI/ViewModifiers/A11yRefocusingOnPopoverDismissalViewModifier.swift, Core/Core/Features/Planner/CalendarEvent/View/EditCalendarEventScreen.swift
refs: [MBL-18312](https://instructure.atlassian.net/browse/MBL-18312)
release note: None.
This solution can be considered as a "hacky" solution, as it is being dependent on a UIKit value (`popoverDismissRegionAccessibilityID`) that was not officially declared in documentation for that use. Though upon testing, it turned out it serves our need perfectly. 
The main challenge of this work is to detect when popover is being presented, and which UI element caused it. While there is no way (officially documented by Apple) to tell that for `DatePicker`, in order to solve this, I had to rely on tracking a fixed ID of contributing elements in a global list, and use that to distinguish the source of popover upon dismissal.
When activating DatePicker fields using VoiceOver …
=> Accessibility - Student/Teacher - Refocus VoiceOver to DatePicker after selection is finished

Core/Core/Features/Discussions/AnnouncementListViewController.swift
refs: MBL-18654
test plan: Test if announcements are displayed properly.
=> Fix AnnouncementDetails showing DiscussionDetails by default on iPad

Teacher/Teacher/SpeedGrader/SubmissionCommentList.swift, Teacher/Teacher/SpeedGrader/SubmissionGrader.swift
refs: MBL-18442
test plan:
- Activating a grader tab should automatically move the voiceover focus to its content.
=> Accessibility - Add focus activation after tab is activated in SpeedGrader

Core/Core/Common/CommonUI/CoreWebView/Model/DefaultWKWebViewConfiguration.swift, Core/Core/Common/CommonUI/CoreWebView/Model/Features/DynamicFontSize.swift, Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift, Core/Core/Common/CommonUI/Typography/Typography.swift, Core/Core/Common/Extensions/Foundation/StringExtensions.swift, Core/CoreTests/Common/CommonUI/CoreWebView/Model/Features/DynamicFontSizeTests.swift, Core/CoreTests/Common/CommonUI/CoreWebView/View/CoreWebViewTests.swift, Core/CoreTests/Common/Extensions/Foundation/StringExtensionsTests.swift
- There's a new `CoreWebView` feature to dynamically adjust the font size in of the html content based on the system's dynamic font size settings.
- Since dynamic size category is an enum without values (*) I had to come up with a mapping to manually figure out the font scale for each enum value. For this I created a preview and I tweaked the scales until it matched the system font's size.
refs: MBL-18628
test plan:
- Test if webviews follow the device's dynamic font size.
- Note that webviews doesn't dynamically refresh when the font size is changed while on screen.
(*) Actually we can see in the control center the associated percentage values for each category but if I resize the font by that amount they don't match the font size …
=> Accessibility - Add support for webviews to change their font size based on the device's setting

Core/Core/Common/Extensions/UIKit/UITableViewCellExtensions.swift, Core/Core/Features/Conferences/ConferenceListViewController.swift, Core/Core/Features/Discussions/AnnouncementListViewController.swift, Core/Core/Features/Discussions/DiscussionListViewController.swift, Core/Core/Features/ErrorReports/ErrorReportViewController.storyboard, Core/Core/Features/Files/View/FileList/FileListViewController.swift, Core/Core/Features/Modules/MasteryPaths/MasteryPathAssignmentCell.xib, Core/Core/Features/Pages/PageList/PageListViewController.storyboard, Core/Core/Features/Pages/PageList/PageListViewController.swift, Core/Core/Features/People/PeopleListViewController.swift, Core/Core/Features/Planner/CalendarMain/PlannerListViewController.swift, Core/Core/Features/Profile/Settings/NotificationCategoriesViewController.swift, Core/Core/Features/Profile/Settings/NotificationChannelsViewController.swift, Core/Core/Features/Profile/Settings/ProfileSettingsViewController.swift, Core/Core/Features/Quizzes/QuizListViewController.swift, Core/Core/Features/Todos/TodoListViewController.swift, Parent/Parent/Students/StudentListViewController.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/Student/Groups/GroupNavigation/GroupNavigationViewController.swift, Teacher/Teacher/Submissions/PostGradesViewController.swift
This is a follow-up for a [previous PR](https://github.com/instructure/canvas-ios/pull/3220) that unified SwiftUI disclosure indicators but now it's for UIKit.
refs: [MBL-18325](https://instructure.atlassian.net/browse/MBL-18325)
test plan:
- UIKit based disclosure indicators should use textDark tint color.
[MBL-18325]: https://instructure.atlassian.net/browse/MBL-18325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update UIKit based disclosure indicators

Core/Core/Resources/Assets.xcassets/Colors/text/textPlaceholder.colorset/Contents.json, Parent/Parent/Students/StudentDetailsViewController.swift
=> Accessibility - Parent - ManageStudents - textDark for placeholder color

Core/Core/Common/Extensions/UIKit/UISegmentedControlExtensions.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift, Student/Student/Submissions/SubmissionDetails/Views/Drawer.swift
refs: MBL-18450
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/3df8a0ec-88d3-4897-97d0-85b2cb1d3a91" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/9a6909ac-e4a1-4d48-a7d3-db634589dfb8" maxHeight=500></td>
</tr>
</table>
=> Accessibility - Student - Fix Submission Details Selected Tab Color For Better Contrast

Student/Student/Submissions/StudentAnnotationSubmission/StudentAnnotationSubmissionViewModel.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/StudentUnitTests/Submissions/StudentAnnotationSubmission/StudentAnnotationSubmissionViewModelTests.swift
refs: [MBL-18642](https://instructure.atlassian.net/browse/MBL-18642)
release note: Fixes issue of Root Account unable to access Child PDFs for annotation submissions
See [ticket's](https://instructure.atlassian.net/browse/MBL-18642) description.
First login with root account on a master build then using the PR build posted here to perform the following steps:
1- Login with as a student to Root account.
2- Go to Course "Tracy Test 03" > Assignments > "Annotated Thing for ..."
3- Hit "Submit Assignment"
4- Upon that, on **PR build** you should be able **to see** a PDF file that you can annotate for submission.
While on `master` build, you'd get the following screen.
[MBL-18642]: https://instructure.atlassian.net/browse/MBL-18642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> Fix issue of Root Account unable to access Child PDFs for annotation submissions

Core/Core/Features/ActAsUser/ActAsUserWindow.swift
refs: [MBL-18648](https://instructure.atlassian.net/browse/MBL-18648)
release note: Fixes issue of a Masquerading user unable to pick files for assignment submission.
Probably the issue caused by a UIKit glitch whenever one of those "system-level-picker" controllers are about to be presented, caused mainly by `layoutSubviews()` overridden method on `ActAsUserWindow` attempts to tweak view hierarchy on presentation.
The resolution was to avoid those tweaks whenever a `UIDocumentPickerViewController` or host controllers of photo picker are about to be presented.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18648) description. 
Please note that the issue exist for Library selection as well, make sure to check it as this PR handle this issue as …
=> Fix issue of a Masquerading user unable to pick files for assignment submission

Core/Core/Features/Inbox/ComposeMessage/View/ComposeMessageView.swift
refs: MBL-18362
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/ad7f04f8-0c4c-4cdb-88a6-c013e34cdc2d" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/26972c16-f04c-4265-88df-10de0c3bbd97" maxHeight=500></td>
</tr>
</table>
=> Accessibility - Teacher - ComposeMessageView - Placeholder text of "Add" input field

Core/Core/Common/Extensions/Foundation/DateExtensions.swift, Core/Core/Features/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModel.swift, Core/CoreTests/Common/Extensions/Foundation/DateExtensionsTests.swift, Core/CoreTests/Features/Planner/CalendarEvent/ViewModel/EditCalendarEventViewModelTests.swift
refs: [MBL-18646](https://instructure.atlassian.net/browse/MBL-18646)
release note: Fixed new calendar events having incorrect end time in some cases.
See ticket for details.
You may need to test in a specific timeframe or mock this on your test device
[MBL-18646]: https://instructure.atlassian.net/browse/MBL-18646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Calendar Event start & end time calculation

Core/Core/Common/CommonUI/CoreWebView/Model/Features/DarkModeForWebDiscussions.swift
refs: MBL-18678
test plan:
- When you tap on a threaded reply, the dialog popping up should have dark theme.
=> Update dark modeCSS for discussions

Core/Core/Features/LTI/View/LTIViewController.storyboard, Core/Core/Features/LTI/View/LTIViewController.swift
refs: MBL-18679
release note: Fixed a bug that caused Open the Quiz button to be covered out by Comments drawer.
The original problem was that the "Open Button" was covered out by the "Comments Drawer". So it has been moved closer to the top for better reachability for the users.
However, upon testing the solution another issue was found:
When the font size was increased to the maximum accessibility value then the button went out of the screen and was completely unreachable. To solve this, a scroll view has been added, so even when the button goes out of the screen because of the insanely large fonts, it stays reachable by scrolling. Please test this on different devices.
Known issue: On iPhone SE 3, the "Open Button" is still covered out by the "Comments Drawer".
<table> …
=> LTIViewController - Rearrange views to make Open Button easily reachable

Core/Core/Features/Assignments/AssignmentList/View/AssignmentCellView.swift, Core/Core/Features/Assignments/AssignmentList/ViewModel/AssignmentCellViewModel.swift
- Same grade formatter is used as in Grade List screen, so the displayed grade should be in the same format as there.
- In case of LGO courses, now the letter grades are displayed properly.
refs: MBL-18732
release note: Fixed an issue that caused all types of grades to be displayed as points on the Assignment List.
test plan: Check if all grades are displayed correctly on Assignment List screen. Also check the displayed grades with a LGO course.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/f277f261-486a-484f-a4c7-bd551058ae3c" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/72fee7a1-8b73-4ce4-ac6c-b4e608134112" maxHeight=500></td>
</tr>
</table>
=> Student - AssignmentList - Use GradeFormatter for displaying grades

Core/Core/Common/CommonUI/SnackBar/View/UIKit/SnackBarProvider.swift, Core/Core/Common/CommonUI/UIViews/CoreNavigationController.swift, Core/Core/Features/Inbox/ComposeMessage/ComposeMessageAssembly.swift, Core/Core/Features/Inbox/ComposeMessage/ViewModel/ComposeMessageViewModel.swift, Core/Core/Features/Inbox/MessageDetails/ViewModel/MessageDetailsViewModel.swift, Core/Core/Features/Inbox/View/InboxView.swift, Core/Core/Features/Inbox/ViewModel/InboxViewModel.swift, Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/Dashboard/ParentContainerNavigationController.swift, Parent/Parent/ParentAppDelegate.swift
- I simplified the snack presentation logic in inbox. As a side effect this also made snacks to appear when you compose a message from a people detail page in Student and Teacher apps.
- Made the root navigation controller a snack provider in the parent app since that app was missing a root container providing snack bars. The confirmation snack after a successful message send now appears in this app as well.
refs: MBL-18675
test plan:
- Check if snack notifications appear in Parent app when sending a message from a course or from the inbox.
- Test if snack notification appears when sending a message from the people details page in Student and Teacher apps.
=> Add snackbar to parent app

Core/Core/Features/Notifications/API/APIActivity.swift, Core/Core/Features/Notifications/CoreData/Activity.swift, Core/Core/Features/Notifications/UseCase/GetActivities.swift, Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents, Horizon/Horizon/Resources/Localizable.xcstrings, Horizon/Horizon/Sources/Features/Dashboard/View/DashboardView.swift, Horizon/Horizon/Sources/Features/Dashboard/View/DashboardViewModel.swift, Horizon/Horizon/Sources/Features/Notification/Data/HActivity.swift, Horizon/Horizon/Sources/Features/Notification/Data/NotificationModel.swift, Horizon/Horizon/Sources/Features/Notification/Domain/NotificationFormatter.swift, Horizon/Horizon/Sources/Features/Notification/Domain/NotificationInteractor.swift, Horizon/Horizon/Sources/Features/Notification/Domain/Preview/NotificationInteractorPreview.swift, Horizon/Horizon/Sources/Features/Notification/NotificationAssembly.swift, Horizon/Horizon/Sources/Features/Notification/View/HNotificationView.swift, Horizon/Horizon/Sources/Features/Notification/View/HNotificationViewModel.swift
[Notification](https://instructure.atlassian.net/browse/CLX-958)
=> [Horizon] Notification

Core/Core/Common/CommonModels/Contexts/GetContextTabs.swift, Core/Core/Features/Courses/APICourse.swift, Core/Core/Features/Courses/K5/ViewModel/K5SubjectViewModel.swift
To get the correct tabs for a K5 course `course_subject_tabs` must be included with the request to the tabs endpoint.
When we tap on the course then the K5SubjectViewModel retrieves the tabs and it uses the correct request with this `course_subject_tabs` included. However, when we arrive to the course screen we already have the tabs in CoreData because we already sent a request to the courses endpoint at app start with tabs included but without this `course_subject_tabs`, so when the course opens then we will see all tabs and not only the ones for K5 because the correct request with the include is not being sent.
The fix is to include `course_subject_tabs` also in the courses request at app start.
_Note: With mixed accounts (for users enrolled in both k5 and normal courses) it will only …
=> Student - K5 courses shows hidden tabs

scripts/translations/export.js
Use iphone simulator SDK because Pendo has no catalyst support. Fixed export is [here](https://app.bitrise.io/build/38d59307-634d-401c-ab9f-93d4040212a0).
=> Fix translation export

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core/Common/CommonModels/AppEnvironment/AppEnvironmentOverride.swift, Core/Core/Common/CommonModels/AppEnvironment/Secret.swift, Core/Core/Features/ActAsUser/ActAsUserViewController.swift, Core/Core/Features/Dashboard/K5/View/K5Preview.swift, Core/Core/Features/Login/APILoginWeb.swift, Core/Core/Features/Login/APIOAuth.swift, Core/Core/Features/Login/GetSSOLogin.swift, Core/Core/Features/Login/LoginSession.swift, Core/Core/Features/Login/LoginStartViewController.swift, Core/Core/Features/Login/LoginWebViewController.swift, Core/Core/Features/Login/OAuthType.swift, Core/Core/Features/Login/PKCE.swift, Core/Core/Features/Profile/UploadAvatar.swift, Core/Core/Features/TokenRefresh/Model/AccessTokenRefreshInteractor.swift, Core/CoreTests/Common/CommonModels/API/APITests.swift, Core/CoreTests/Features/Login/APIOAuthTests.swift, Core/CoreTests/Features/Login/GetSSOLoginTests.swift, Core/CoreTests/Features/Login/LoginStartViewControllerTests.swift, Core/CoreTests/Features/Login/LoginWebViewControllerTests.swift, Core/CoreTests/Features/TokenRefresh/Model/AccessTokenRefreshInteractorTests.swift, Core/CoreTests/Features/TokenRefresh/Model/LoginAgainInteractorTests.swift, Core/CoreTests/Features/TokenRefresh/Model/TokenRefreshInteractorTests.swift, Core/TestsFoundation/Fixtures/Keychain/KeychainEntryFixture.swift, Core/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift, Teacher/Teacher/TeacherAppDelegate.swift
Mobile apps are public clients, which means they cannot securely store a shared secret. [RFC 8252](https://datatracker.ietf.org/doc/html/rfc8252) recommends PKCE, which entirely eliminates the need for a client secret by using a dynamic code verifier and code challenge. This prevents authorization code interception attacks, ensuring only the original client can exchange the code for a token. A couple of relevant excerpts from RFC 8252:
[RFC8252  Section 6] Public native app clients MUST implement the Proof Key for Code Exchange (PKCE [RFC7636]) extension to OAuth, and authorization servers MUST support PKCE for such clients, for the reasons detailed in Section 8.1.
[RFC8252  Section 8.1] Authorization servers SHOULD reject authorization requests from native apps that don't use PKCE by …
=> [Horizon] PKCE Login

Horizon/Horizon/Resources/Localizable.xcstrings, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/ModuleItemSequenceAssembly.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleNavBar/ModuleNavBarView.swift, Horizon/Horizon/Sources/Features/Notebook/Common/Data/CourseNoteLabel.swift, Horizon/Horizon/Sources/Features/Notebook/Common/View/NoteCardFilterButton.swift, Horizon/Horizon/Sources/Features/Notebook/Common/View/NotebookTitleBar.swift, Horizon/Horizon/Sources/Features/Notebook/Note/View/NotebookNoteView.swift, Horizon/Horizon/Sources/Features/Notebook/Note/View/NotebookNoteViewModel.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/NotebookAssembly.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NoteCardView.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift, Horizon/Horizon/Sources/Features/Notification/View/HNotificationView.swift, Horizon/Horizon/Sources/Routing/HorizonRoutes.swift, packages/HorizonUI/Sources/HorizonUI/Sources/Components/Button/HorizonUI.ButtonStyles.swift
1. The close button should have a drop shadow behind it
2. The icon and header look too small
3. The text fields and label buttons should have strokes, not drop shadows
4. There’s a “cancel” button beneath the Save that shouldn’t be there (and if it is, it shouldn’t be white)
5. It looks like I can currently select both the confusing and important labels
6. After saving a note, I should be returned to the learning object and see a success toast. It currently keeps me in the menu, removes the save button, and shows a delete button
I also rolled this ticket into the changes. The styling had changed quite a bit since the previous implementation so it's now been updated to match what's currently designed.
https://instructure.atlassian.net/browse/CLX-1086 …
=> [Horizon] Notebook Design Review Updates

Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetails.swift, Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/View/AssignmentDetailsViewModel.swift
When the submission type is none on an assignment and that's the only submission type, then hide the submit button. I'm guessing quite a bit here on the business rules, so let me know if that's not right.
`    var isSubmitButtonHidden: Bool {
assignment?.submissionTypes.contains(.none) == true && assignment?.submissionTypes.count == 1
}
`
https://github.com/user-attachments/assets/d8ae139f-f037-4607-bf50-a862c07de8a9
=> [Horizon] Hide Submission Button for Submission Type None

Core/Core/Features/Files/View/FileDetails/FileDetailsViewController.swift, Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetails/Domain/HUploadFileManager.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift
I'm unsure this one should be changed. You can see the before and after. I can hide the spinner in the view controller, but then why have it? It would be better to just remove it altogether. But I'm not sure I should do that since it's part of Core. I could also extend the FileDetailsViewController and hide it just for Horizon. But that seems like a lot just to hide a spinner. I personally, would probably just close this defect and not change anything. But I thought I'd let you weigh in @szabinst 
Before and After:
https://github.com/user-attachments/assets/7a0e6f2b-734e-4c56-944a-bf68bbf85a20
https://github.com/user-attachments/assets/c2e137eb-39e7-4d1c-9445-c134acc3ef02
=> [Horizon] File Upload Loading Indicator is Duplicated

Core/Core/Common/CommonModels/AppEnvironment/AppEnvironment.swift, Horizon/Horizon/Resources/Info.plist, Horizon/Horizon/Sources/AppDelegate.swift, Horizon/Horizon/Sources/Features/Splash/View/SplashViewModel.swift
=> [Horizon] Pendo Integration

Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/AssistChatInteractor.swift, Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatView.swift, Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatViewModel.swift, packages/HorizonUI/Sources/HorizonUI/Sources/Components/Controls/Toggle/HorizonUI.Controls.ToggleItem.swift, packages/HorizonUI/Sources/HorizonUI/Sources/Components/ProgressBar/HorizonUI.ProgressBar.swift
1- https://instructure.atlassian.net/browse/CLX-1047
2- https://instructure.atlassian.net/browse/CLX-1083
3- https://instructure.atlassian.net/browse/CLX-1093
https://github.com/user-attachments/assets/16341bf8-9734-4352-912f-2c5519557154
=> [Horizon] Fixed progress bar issues

Core/Core/Features/Grades/GradeListAssembly.swift, Core/Core/Features/Grades/Model/GradeListInteractor.swift, Core/Core/Features/Grades/Model/UseCase/GetAssignmentsByGroup.swift, Core/Core/Features/Grades/ViewModel/GradeListViewModel.swift, Core/CoreTests/Features/Grades/Model/UseCase/GetAssignmentsByGroupTests.swift, Parent/Parent/Courses/CourseDetailsViewController.swift, Student/Student/Routes.swift
refs: MBL-18758
affects: Parent, Student
release note: Fixed grades page showing all observed users' assignments not just the selected observee's.
test plan:
- See ticket for test account.
- Check if assignments are still properly displayed in the student app on the grades page.
=> Fix grades list showing assignments of all observed users

Core/Core/Common/CommonUI/CoreWebView/Model/Features/DarkModeForWebDiscussions.swift, Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift, Core/Core/Common/CommonUI/RichContentEditor/OverrideUserInterfaceStyleManager.swift, Core/Core/Common/CommonUI/RichContentEditor/RichContentEditorViewController.swift, Core/Core/Common/CommonUI/RichContentEditor/RichContentToolbarView.swift, Core/Core/Common/Extensions/UIKit/UIColorExtensions.swift, Core/Core/Features/Discussions/DiscussionHTML.swift, Core/CoreTests/Common/CommonUI/CoreWebView/View/CoreWebViewThemeSwitcherTests.swift, Core/CoreTests/Common/CommonUI/RichContentEditor/OverrideUserInterfaceStyleManagerTests.swift
refs: [MBL-18743](https://instructure.atlassian.net/browse/MBL-18743)
release note: Fixed a dark mode issue on various screens.
- Fixed RCE CSS color handling
- Fixed RCE toolbar borders
- Extracted `OverrideUserInterfaceStyleManager` from `CoreWebViewThemeSwitcher`
- Couldn't find a proper better name, so I gave up and it stayed Manager
- Didn't update CoreWebView and/or it's theme switcher to use the new helper, to reduce code/QA scope
- Didn't try to resolve the whole problem of using white/black colors in light/dark mode
- We've already shown these RCEs in dark mode, now we also show them when the theme is changed on the fly
- See ticket for details and affected screens
- Things should also work properly in forced dark/light modes
<table> …
=> RCE Dark mode issue

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.storyboard, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
refs: MBL-18735
The issue was cause by the space for the attempt picker. When there's no attempt (no submission) then the attempt picker is hidden, so when the submission detail screen is opened and the accessibility font size is set to the largest then the top of the balloon panda from the empty view appears in that "window" where the attempt picker should be (if there were any submission). So the solution was to set the constraints of the view depending on the attempt picker (which depends on the submission). So when there is no attempt picker (no submission) then the top constraint of the content view is set to match the top constraint of the safe area (by default it's set to the bottom constraint of the attempt picker).
=> Student - NewQuizzes submission detail screen has balloon image messing up the layout

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
refs: [MBL-18793](https://instructure.atlassian.net/browse/MBL-18793)
release note: Improved accessibility of submission screen.
Made submission content always focusable, regardless of drawer state (as discussed with UX).
[MBL-18793]: https://instructure.atlassian.net/browse/MBL-18793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make SubmissionDetails content always focusable

Core/Core/Features/Enrollments/Enrollment.swift, Core/Core/Features/Grades/Model/Entities/GradingScheme.swift, Core/Core/Features/Grades/Model/GradeFormatter.swift, Core/CoreTests/Features/Grades/Model/Entities/PercentageBasedGradingSchemeTests.swift, Core/CoreTests/Features/Grades/Model/Entities/PointsBasedGradingSchemeTests.swift
refs: [MBL-18785](https://instructure.atlassian.net/browse/MBL-18785)
release note: Fixed letter grades being displayed incorrectly in some cases.
The problem was that scores ended up being normalized twice after a recent bugfix.
It is now fixed, and the method got a more explicit name.
The `Enrollment` class has multiple unused members, but I didn't remove any of them for now. It may require a deeper look to make it consistent.
- Verify the issue in the ticket is fixed, see details there
- Smoke test letter grades
[MBL-18785]: https://instructure.atlassian.net/browse/MBL-18785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix letter grade conversion

Core/Core/Common/CommonModels/Router/DefaultViewProvider.swift, Core/Core/Common/CommonUI/SwiftUIViews/UIKitSwiftUIBridging/CoreHostingController.swift, Core/Core/Features/Assignments/AssignmentList/View/AssignmentListScreen.swift, Core/Core/Features/Courses/CourseDetails/View/CourseDetailsView.swift, Core/Core/Features/Grades/GradeListAssembly.swift, Core/Core/Features/Modules/ModuleList/ModuleListViewController.swift, Core/CoreTests/Common/CommonModels/Router/DefaultViewProviderTests.swift
refs: MBL-18783
release note: Fixes the issue where empty view is shown on reload (PTR) an assignment detail after appearance switch.
The main cause of the issue is actually due to resetting of `defaultDetailViewRoute` upon Course object update callback on `AssignmentListViewModel`. This triggered by (Pull-to-refresh) on assignment detail page.
This line in particular:
https://github.com/instructure/canvas-ios/blob/3771e0a48ba3e8a1981fe6cd0b4a413626fef813/Core/Core/Features/Assignments/AssignmentList/ViewModel/AssignmentListViewModel.swift#L302
Upon appearance mode switch this would generate different values for route between dark and light mode, as the color is resolved to different hex decimal values between those mode. 
For example: `/empty?contextColor=#C47832` in …
=> Fix the issue where empty view is shown on reload (PTR) an assignment detail after appearance switch

packages/HorizonUI/Sources/HorizonUI/Sources/Foundation/Fonts/HorizonUI.Fonts.swift
There was a typo in the name of Figtree-Regular preventing it from being used correctly.
=> [Horizon] Renaming some font cases 

Core/Core/Common/CommonModels/AppEnvironment/SessionDefaults.swift, Core/Core/Features/Grades/Model/GradeFilterInteractor.swift, Core/Core/Features/Grades/Model/GradeListInteractor.swift, Core/Core/Features/Grades/View/GradeFilterView.swift, Core/Core/Features/Grades/ViewModel/GradeFilterViewModel.swift, Core/Core/Features/Grades/ViewModel/GradeListViewModel.swift, Core/CoreTests/Features/Grades/Model/GradeFilterInteractorLiveTests.swift, Core/CoreTests/Features/Grades/ViewModel/GradeFilterViewModelTests.swift
- Grade Period filter on the Grade List screen now defaults back to the current period.
refs: MBL-18768
release note: Grade Period filter now auto-selects the current period on the Grade List screen.
Test plan:
- Check if Grading Period filter resets to the current period. Previously, the selected option was saved and reloaded.
- Check carefully everything as last time serious bugs went unnoticed. Closing the app, pull-to-refresh, all grading periods, combinations of these.
=> Grade list grading period filter auto selects the current period instead of reloading the last selection

Core/Core/Features/Courses/CourseProgression/GetCoursesProgressionRequest.swift, Core/Core/Features/Courses/CourseProgression/GetDashboardCoursesWithProgressionsUseCase.swift, Horizon/Horizon/Sources/Common/Domain/GetCoursesInteractor.swift
iOS and web were not showing the same list of courses. The GraphQL call to `GetUserCourses` on the web includes the parameter `horizonCourses: true`, which we were not.
=> [Horizon] iOS Course List Discrepancy with Web

Core/CoreTests/Features/Inbox/ComposeMessage/Model/ComposeMessageInteractorLiveTests.swift
Without this, repeating the whole suite failed due to an expectation fulfilled multiple times.
=> Fix test not being torn down correctly

Horizon/Horizon/Sources/Features/Account/AccountView.swift, Horizon/Horizon/Sources/Features/Account/AccountViewModel.swift
Removing the account menu item for the Beta Community and adding a functional link for the account Give Feedback menu item [ignore-commit-lint]
https://github.com/user-attachments/assets/6bc3d899-6de1-41a0-8d99-f74f0fd428e4
=> [Horizon] Account Menu Item Updates

Horizon/Horizon/Sources/Features/LearningObjects/ExternalURL/ExternalURLViewModel.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift, Horizon/Horizon/Sources/Routing/HorizonRoutes.swift
The object ID we store for notes changed from being a module item ID to a page ID. Because of this we now need to pass the `Page` asset type when navigating to the module item sequence.
https://github.com/user-attachments/assets/a3051178-2987-406f-979a-6155c2a54081
=> [Horizon] Notebook not navigating the module item correctly

Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookView.swift, Horizon/Horizon/Sources/Features/Notebook/Notebook/View/NotebookViewModel.swift
If there are no other pages, hide the previous and next page buttons in the notebook.
https://github.com/user-attachments/assets/66444ac4-2658-4d93-9d00-8175898dabf8
=> [Horizon] Hide Previous/Next Page Buttons in Notebook

Core/Core/Common/Extensions/UIKit/UIViewControllerExtensions.swift, Core/Core/Common/Extensions/UIKit/UIViewExtensions.swift, Core/Core/Features/Modules/ModuleItems/ModuleItemSequenceViewController.swift, Core/CoreTests/Common/Extensions/UIKit/UIViewControllerExtensionsTests.swift, Core/CoreTests/Common/Extensions/UIKit/UIViewExtensionsTests.swift, Core/CoreTests/Features/Modules/ModuleItems/ModuleItemSequenceViewControllerTests.swift
I also tried to exit PiP mode by calling `closeAllMediaPresentations` but it kept crashing so I left it out.
refs: MBL-18772
release note: Fixed embedded media playback not getting stopped when switching to another module item.
test plan:
- Go to a module item that has an embedded studio view.
- Start playing the video with sound on.
- Go to next or previous module item.
- Audio should pause.
=> Stop web media playback when switching to a new module item.

Core/Core/Features/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncStudioMediaInteractor.swift, Core/Core/Features/LTI/ExternalTool.swift, Core/Core/Features/Studio/Model/StudioAPIAuthInteractor.swift, Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Features/CourseSync/CourseSyncDownloader/Model/Downloaders/CourseSyncStudioMediaInteractorLiveTests.swift, Core/CoreTests/Features/Studio/Model/StudioAPIAuthInteractorLiveTests.swift
The `accounts/self/lti_apps/launch_definitions` API call failed with 403 for cross shard users so I changed to a different API that seems to work for everyone.
refs: [MBL-18812](https://instructure.atlassian.net/browse/MBL-18812)
release note: Fixed Studio videos not getting downloaded for cross shard users for offline mode.
test plan:
- See ticket for test account.
- Studio offline sync should work when logged in via the root or the 01 instance as well.
- Test a non-shard instance if Studio sync still works on those.
[MBL-18812]: https://instructure.atlassian.net/browse/MBL-18812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Studio videos not getting downloaded 

Core/Core/Common/CommonUI/CoreWebView/Model/Features/DisableLinkPreviews.swift, Core/Core/Common/CommonUI/CoreWebView/Model/Features/DisableLinksOverlayPreviews.swift, Core/Core/Features/Files/View/FileDetails/FileDetailsViewController.swift, Core/Core/Features/LTI/LTITools.swift, Core/Core/Features/Quizzes/QuizDetails/Student/StudentQuizWebViewController.swift, Core/CoreTests/Common/CommonUI/CoreWebView/Model/Features/DisableLinksOverlayPreviewsTests.swift, Teacher/Teacher/SpeedGrader/SubmissionRenderer/View/SubmissionViewer.swift
refs: MBL-18800
release note: Fixes the issue of submission files not showing  in New Quizzes
The issue originally caused by a web script that interrupts clicks/taps to links with "preview_in_overlay" class. 
This class is added to files links when link's **_Display Options_** is set to "Preview in overlay"
It was noticed that this issue doesn't show up for links with Display Options set to "Disable Preview".
Therefore, a possible resolution to it would be to activate a script to tweak HTML content of those failing links to match that generated for working ones. Which is basically: 
1. Replacing "preview_in_overlay" in `class` attribute with "no_preview"
2. Replacing `href` attribute value with that associated for direct file download.
This script was …
=> Fix the issue of submission files not showing  in New Quizzes

Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift
refs: MBL-18804
release note: Fixes issue of WebView not resizing on Dark/Light mode switch
See ticket's description.
We also better check other places that uses WebView in resizable way. Like assignment details (description), notification cards, teacher quiz details.
https://github.com/user-attachments/assets/d0db672f-e438-4ab4-89b0-54402e6562a3
=> Fix issue of WebView not resizing on Dark/Light mode switch

TestPlans/StudentE2E.xctestplan
Offline tests cause a "Lost connection to build agent" abort so we skip these for now.
=> Skip offline tests

Core/Core/Common/CommonUI/InstUI/Views/Cells/RadioButtonCell.swift
refs: [MBL-18855](https://instructure.atlassian.net/browse/MBL-18855)
release note: Improved accessibility on various screens.
Since there is no `isRadioButton` trait and the a11y task asks specifically for these to be read as "Radio Button" I made a workaround.
Verify radio buttons read as expected via VoiceOver. Example screens:
- Add Calendar Event
- Assignment List Preferences
[MBL-18855]: https://instructure.atlassian.net/browse/MBL-18855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility - Radio button

Core/Core/Features/Groups/GetGroups.swift, Core/Core/Features/Groups/Group.swift
refs: MBL-18822
release note: Fixed issue of disappearing groups on dashboard on first refresh after login
The issue occurs after each login, because API request in `GetGroups` use case is made right after the one made by `GetDashboardGroups`. The `GetGroups` instance that is responsible for this is the one living in `TodoListViewController`.  And this interference only occurs after login, if user close the app then relaunch it again it will go away. 
Although, the disappearing group "Education 2" is not marked as favorite _- You can find about that if you go to "All Courses" screen -_, still this interference could cause it to show up as groups fetched in `GetDashboardGroups` are not scoped to ones that were marked as favorite.
Therefore, **_The resolution_** is …
=> Fixed issue of disappearing groups on dashboard on first refresh after login

Parent/ParentUnitTests/Inbox/ParentInboxCoursePicker/Model/ParentInboxCoursePickerInteractorLiveTests.swift, Teacher/Teacher/SpeedGrader/Comments/ViewModel/SubmissionCommentListViewModel.swift, Teacher/Teacher/SpeedGrader/MainLayout/ViewModel/SubmissionGraderViewModel.swift, Teacher/TeacherTests/SpeedGrader/Comments/ViewModel/SubmissionCommentListViewModelTests.swift
- On attempt change in SpeedGrader we fire a notification to update the submission comment list to show comments for the current attempt.
- When a new SpeedGrader page was loaded it automatically sent out this notification but it wasn't filtered to a user.
- All comment lists in memory got the notification and changed the attempt to show comments for the received attempt.
refs: [MBL-18839](https://instructure.atlassian.net/browse/MBL-18839)
test plan:
- Turn on assignment enhancements.
- Have an assignment with multiple submissions from a user. Each submission should have a comment to easily recognise which comment is for which attempt.
- Add another student to the assignment but with only one submission.
- Start SpeedGrader with a filter that has both …
=> Fix swiping to next student changing the current student's attempt

Core/Core/Common/CommonUI/InstUI/Views/Cells/DatePickerCell.swift, Core/Core/Common/CommonUI/InstUI/Views/Cells/RichContentEditorCell.swift, Core/Core/Common/CommonUI/InstUI/Views/Cells/TextEditorCell.swift, Core/Core/Common/CommonUI/InstUI/Views/Cells/TextFieldCell.swift, Core/Core/Common/Extensions/Foundation/String+LocalizedFormats.swift, Core/Core/Features/Planner/CalendarEvent/View/EditCalendarEventScreen.swift, Core/Core/Features/Planner/CalendarToDo/View/EditCalendarToDoScreen.swift, Core/CoreTests/Common/Extensions/Foundation/String+LocalizedFormatsTests.swift, Core/TestsFoundation/UITestHelperNamespaces/CalendarHelper.swift
refs: [MBL-18843](https://instructure.atlassian.net/browse/MBL-18843)
release note: Improved accessibility on various screens.
- cell label itself is no longer focusable
- label is read for the picker component (date or time) which is first focused
- error message is also read for the components
- "Date Picker" & "Time Picker" is read for each component
The main hardship is that the native DatePicker control behaves differently a11y-wise when it is date-time picker than it is date or time picker only. The behaviour is not really customizable and doesn't match a11y requirements.
I ended up composing the Date&Time variant from 2 separate pickers.
Nesting `ViewThatFits` calls caused visible performance issues, so I ended up using one call at the top and flattening …
=> Accessibility - Date Picker

Core/Core/Common/Extensions/Foundation/URLExtensions.swift, Horizon/Horizon/Sources/Features/LearningObjects/Assignment/AssignmentDetailsAssembly.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/Domain/ModuleItemSequenceInteractor.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/Domain/Preview/ModuleItemSequenceInteractorPreview.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/ModuleItemSequenceAssembly.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/ModuleItemSequenceViewModel.swift, Horizon/Horizon/Sources/Features/ModuleItemSequence/Sequence/View/PageDetails/PageDetailsAssembly.swift, Horizon/Horizon/Sources/Features/Notebook/Common/Domain/CourseNoteInteractor.swift, Horizon/Horizon/Sources/Features/Notebook/Common/View/HighlightWebView/HighlightWebView.swift, Horizon/Horizon/Sources/Features/Notebook/Note/View/NotebookNoteViewModel.swift
The gist of the bug is the ModuleItemSequenceInteractor when it's first built asks for the asset type. However, after requesting the module item sequence in the ModuleItemSequenceViewModel, the asset type can change. So when the notebook initially specified a .page asset type, the next asset type in the sequence give back is a .moduleItem.
The resolution is to be able to specify the asset type in the fetchModuleItems method call to ModuleItemSequenceInteractor instead of it remaining constant when the class is first created.
https://github.com/user-attachments/assets/070823d7-9c30-4e8b-b20d-9b43cc188fd0
=> [Horizon] Module Item Sequence Fix

Core/Core/Common/CommonUI/ViewableModels/GradeViewable.swift, Core/CoreTests/Common/CommonUI/ViewableModels/GradeViewableTests.swift
refs: [MBL-18861](https://instructure.atlassian.net/browse/MBL-18861)
release note: Fixed score being rounded on assignment details screen when late penalty was applied.
[MBL-18861]: https://instructure.atlassian.net/browse/MBL-18861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use grade formatter to display score

Core/Core/Common/CommonUI/CoreWebView/Model/CoreWebViewCrossCookieInjection.swift, Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift, Core/Core/Common/Extensions/WebKit/WKHTTPCookieStoreExtensions.swift, Core/CoreTests/Common/CommonUI/CoreWebView/Model/CoreWebViewCrossCookieInjectionTests.swift, Core/CoreTests/Common/Extensions/WebKit/WKHTTPCookieStoreExtensionsTests.swift
- See the linked MBL and RCX tickets for a very detailed analysis on the problem.
- Embedded iframes can't set cookies by default.
- To allow them to set cookies you need to turn on "Allow Cross-Website Tracking" in app settings.
- Another piece is that webkit needs to trust the domain in the iframe and that can be achieved by setting a cookie for the domain before the content load takes place.
refs: [MBL-18806](https://instructure.atlassian.net/browse/MBL-18806)
test plan:
- Turn on "Allow Cross-Website Tracking" in app settings.
- See linked rcx ticket for test account.
- Embedded html content should load.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/7a4e0ecc-64e2-4c8d-a76 …
=> Make embedded html content work

Core/Core/Features/Notifications/UseCase/GetActivities.swift, Core/CoreTests/Features/Notifications/UseCase/GetActivitiesTests.swift, Student/Student/Localizable.xcstrings, Student/Student/Notifications/ActivityStreamViewController.swift
refs: [MBL-18792](https://instructure.atlassian.net/browse/MBL-18792)
release note: Inbox messages are no longer shown on Notifications screen.
[MBL-18792]: https://instructure.atlassian.net/browse/MBL-18792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove conversations from Notifications screen

Parent/Parent/Assignments/Model/ParentSubmissionInteractor.swift, Parent/ParentUnitTests/Assignments/Model/ParentSubmissionInteractorTests.swift
The "Submission & Rubric" screen in the parent app displayed the assignment's details but not the user's submission. Turned out we use the "display=embedded" url query when opening the page and it no longer opens the proper page. Replacing this query with "embedded=true" as on the android client solves the issue.
refs: [MBL-18896](https://instructure.atlassian.net/browse/MBL-18896)
release note: Fixed "Submission & Rubric" page displaying only the assignment's details.
test plan:
- Check submission screen for elementary students.
- Check submission screen for regular students with both assignment enhancements turned on and off.
<table>
<tr><th colspan="2">Assignment Enhancements On</th></tr>
<tr>
<td><img …
=> Fix "Submission & Rubric" page displaying assignment's details in parent app

Core/Core/Features/Discussions/AnnouncementListViewController.swift, Core/CoreTests/Features/Discussions/AnnouncementListViewControllerTests.swift
refs: MBL-18886
release note: Fixed the issue where cross-shard user can not view announcements details.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18886) description.
When using "act as user" as login methodology, modules won't load as expected and user won't be able to preview files.
This issue is caused by an error is returned from the API when `as_user_id` query param is passed along. (Not sure why that happens?)
=> Fix the issue of cross-shard user unable to view announcements details

Teacher/Teacher.xcodeproj/project.pbxproj
- Cleaned up duplicated files.<br/><img width="510" alt="Screenshot 2025-06-16 at 17 24 21" src="https://github.com/user-attachments/assets/59e884fd-ca9e-4584-bd13-24a6164bfbe5" />
- Enabled dSYM generation for release builds.
refs: [MBL-18953](https://instructure.atlassian.net/browse/MBL-18953)
test plan:
- Check if Release mode in Teacher target has the dSYM generation setting on top of DWARF.
- Check if duplicate file compilation warning are gone.
[MBL-18953]: https://instructure.atlassian.net/browse/MBL-18953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix teacher project

Core/Core/Features/People/APIUser.swift, Core/Core/Features/Profile/UserProfile.swift, Core/Core/Resources/Database.xcdatamodeld/Database.xcdatamodel/contents, Horizon/Horizon/Resources/Localizable.xcstrings, Horizon/Horizon/Sources/Common/Domain/GetUserInteractor.swift, Horizon/Horizon/Sources/Common/Domain/GetUserInteractorPreview.swift, Horizon/Horizon/Sources/Features/Account/Profile/View/ProfileView.swift, Horizon/Horizon/Sources/Features/Account/Profile/View/ProfileViewModel.swift
1- Fixed the issue where the mail was not appearing in PD
2- https://instructure.atlassian.net/browse/CLX-1514
=> [Horizon] Add profile disable name fields

Core/Core/Features/Modules/ModuleList/ModuleListViewController.swift, Core/Core/Features/Modules/ModulesAssembly.swift, Core/CoreTests/Features/Modules/ModuleList/ModuleListViewControllerTests.swift, Student/Student/Routes.swift, Teacher/Teacher/Routes.swift
refs: MBL-18871
release note: Fixed the issue where cross-shared user not being able to preview files when added to Modules.
See [ticket's](https://instructure.atlassian.net/browse/MBL-18871) description.
~~When using "act as user" as login methodology, modules won't load as expected and user won't be able to preview files.
This issue is caused by an error is returned from the API when `as_user_id` query param is passed along. (Not sure why that happens?)~~
Just tested this issue today, seems to work normally, same way as the ordinary login way. See recording below:
https://github.com/user-attachments/assets/1e880c00-58fd-45b9-a228-29e269ef4a02
=> Fix the issue of cross-shared user unable to preview files added to Modules

Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListSection.swift, Teacher/TeacherTests/Submissions/SubmissionList/SubmissionListViewModelTests.swift
refs: MBL-18892
release note: Fixed issue with submission list where NotSubmitted ones being sorted under Others section
See [ticket's](https://instructure.atlassian.net/browse/MBL-18892) description.
=> Fix issue with submission list where NotSubmitted ones being sorted under Others section

Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListSection.swift
refs: MBL-18893
release note: Fixed issue of submission list where Re-submitted attempts not being sorted under "Submitted" section
See [ticket's](https://instructure.atlassian.net/browse/MBL-18893) description.
=> Fixed issue of submission list where Re-submitted attempts of assignments not being sorted under "Submitted" section

Core/Core/Common/CommonModels/Store/FetchedResultPublisher.swift
There are crashes when setting up `NSFetchedResultsController` in `FetchedResultPublisher`. I couldn't reproduce the crash but my best guess is that the crash is caused by not setting up the controller on the managed object context's thread. All crashes come from some background thread and the context we use is mainly the view context that is associated with the main thread and this can cause strange crashes. We started investigating this crash because in the latest teacher release we started receiving these in greater numbers but the crash can be found in the Student app as well, although only in previous versions.
Let's test if this causes any unwanted issues and we'll see after releasing it if it actually solves the issue on user's side.
refs: …
=> Move NSFetchedResultsController setup to the context's thread

Core/Core/Features/Enrollments/Enrollment.swift, Core/CoreTests/Features/SubmitAssignmentExtension/Model/FilePreviewProviderTests.swift, Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListInteractorLive.swift, Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListSection.swift, Teacher/Teacher/Submissions/SubmissionsList/ViewModel/SubmissionListViewModel.swift
refs: MBL-18976
release note: Fixed a bug that caused excused submissions to get sorted into two sections.
- Excused submissions were shown in two sections at once, which caused the UI to glitch. Now they should only be shown in the graded section only.
- Submissions with StudentView enrollments are now filtered out from the Submission List screen solving the previous inconsistency between the Assignment Detail and the Submission List screens.
=> Teacher - Excused submission sorted to two sections

Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatView.swift, Horizon/Horizon/Sources/Features/Assist/AssistChat/View/AssistChatViewModel.swift
https://instructure.atlassian.net/browse/CLX-1752
=> [Horizon] Remove SwiftUI code from AssistChatViewModel

Student/Student/Localizable.xcstrings, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.storyboard, Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
- There's now a label over the comment textfield to make it more accessible.
refs: [MBL-18386](https://instructure.atlassian.net/browse/MBL-18386)
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/ed674f37-e65f-4a61-8dad-4a8d2780a2dd" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/ae1617a9-9751-4cac-9b00-ae29176ffcae" maxHeight=500></td>
</tr>
</table>
[MBL-18386]: https://instructure.atlassian.net/browse/MBL-18386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Label for comment field

Core/Core/Features/Planner/CalendarMain/PlannerViewController.swift
refs: MBL-18900
release note: Fixed issue of duplicate rows showing for same event on Planner view on tapping To-do widget day button
The issue primarily caused by internal flaw with legacy `Store` object, by which objects get reported duplicate via `NSFetchedResultsController` delegate method `controllerDidChangeContent`.
Elaborating more on the first point for this context, as per @vargaat request:
Both `CalendarDaysViewController` & `PlannerListViewController` using a store observing `GetPlannables` use case. 
For the natural use case, those refresh on both stores are called subsequently on each navigation to calendar page. So, they both get to reset their objects before dealing with new ones.
While for the case when user tap on a To-do widget button, the following …
=> Fixed issue of duplicate rows showing for same event on Planner view on tapping To-do widget day button

Core/CoreTests/Common/CommonModels/BackgroundActivity/BackgroundActivityTests.swift, Teacher/Teacher.xcodeproj/project.pbxproj, Teacher/Teacher/SpeedGrader/Grading/GradeStatus/Model/GradeStatusInteractor.swift, Teacher/Teacher/SpeedGrader/Grading/GradeStatus/Model/GradeStatusInteractorPreview.swift, Teacher/TeacherTests/SpeedGrader/Grading/GradeStatus/Model/GradeStatusInteractorMock.swift, Teacher/TeacherTests/SpeedGrader/Grading/GradeStatus/Model/GradeStatusInteractorTests.swift
I changed the grade status lookup to always return a value. This fixes the issue when no status is given for a submission and also offers a better fallback in case the lookup fails because the status will show nothing instead of an invalid state.
refs: [MBL-18994](https://instructure.atlassian.net/browse/MBL-18994)
release note: Fixed grade status not being cleared in some cases in SpeedGrader.
test plan:
- In SpeedGrader set a submissions’s grade status to Excused.
- Tap on the “Excused“ grade title and in the alert tap “No Grade“.
- Grade status should clear “Excused“ state.
- I fixed the duplicate file warning in the teacher project.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/10cb06ce-5c3e-4ca0-9b5c-72a45 …
=> Fix grade status not being cleared in SpeedGrader

Core/Core/Common/CommonUI/SwiftUIViews/View+MeasuringSize.swift, Teacher/Teacher.xcodeproj/project.pbxproj, Teacher/Teacher/SpeedGrader/Comments/View/SubmissionCommentListView.swift, Teacher/Teacher/SpeedGrader/SpeedGraderPage/View/DrawerContainer.swift, Teacher/Teacher/SpeedGrader/SpeedGraderPage/View/SpeedGraderPageTabsView.swift, Teacher/Teacher/SpeedGrader/SpeedGraderPage/View/SpeedGraderPageView.swift, Teacher/Teacher/SpeedGrader/SpeedGraderPage/ViewModel/SpeedGraderPageTab.swift
refs: MBL-18907
This is just a chore in preparation for [MBL-18907](https://instructure.atlassian.net/browse/MBL-18907).
- Extracted `SpeedGraderPageTab` model
- Extracted `SpeedGraderPageTabsView`
- it uses the page's viewmodel at the moment, mostly to allow easier rearranging of tab content if needed
- Cleaned up `SpeedGraderPageView`
- Added some helpers to `DrawerState` to make related logic a bit more readable
- Added `onHeightChange()` methods for cases when we only interested in the `height`, not the `size`
- Verify SpeedGrader tab changing, focus, a11y focus, etc. work as before, both in Landscape & Portrait.
- Verify swapping Landscape/Portrait mode works as before, and it keeps the selected tab.
NOTE: Tapping on the selected tab when the …
=> SpeedGrader - Extract Tabs view from Page view

packages/HorizonUI/Sources/HorizonUI/Sources/Components/Inputs/MultiSelect/HorizonUI.MultiSelect.swift
This is fixing a defect where if the user filters the multiselect down to a single result and then taps in the area to add more, it does nothing.
=> [Horizon] Unable to Select Multiple Recipients

Core/Core/Features/Inbox/ComposeMessage/View/WrappingHStack.swift, Horizon/Horizon/Resources/Localizable.xcstrings, Horizon/Horizon/Sources/Features/Assist/AssistChat/Domain/Goal/AssistSelectCourseGoal.swift
This is not perfect, but it is an improvement. It keeps items from overlapping each other, but doesn't allow for vertically centering row items.
=> [Horizon] WrappingHStack Improvement

Core/Core/Features/Submissions/GetSubmissions.swift, Core/CoreTests/Features/Submissions/GetSubmissionsTests.swift
refs: [MBL-19048](https://instructure.atlassian.net/browse/MBL-19048)
release note: Fixed issue with Not-submitted filtering on submissions list
Updated "NotSubmitted" fetching predicate of submissions to match the one used on in `filter` function of `SubmissionListSection.Kind` type, which is also used for list sectioning. 
Mainly this is covering the case where invalid score is being submitted to rubric criteria items on SpeedGrader. Which could yield `workflow_state` to be evaluated as `graded` although no grade value is returned to it. 
See [ticket's](https://instructure.atlassian.net/browse/MBL-19048) description. 
[MBL-19048]: https://instructure.atlassian.net/browse/MBL-19048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> Fix issue of NotSubmitted filtering on Submissions list

Core/Core/Features/Courses/Course.swift, Core/Core/Features/Grades/Model/Entities/GradingScheme.swift, Core/Core/Features/Grades/Model/Entities/GradingSchemes/PercentageBasedGradingScheme.swift, Core/Core/Features/Grades/Model/Entities/GradingSchemes/PointsBasedGradingScheme.swift, Core/Core/Features/Grades/Model/GradeFormatter.swift, Core/CoreTests/Features/Grades/Model/Entities/GradingSchemeTestCase.swift, Core/CoreTests/Features/Grades/Model/Entities/PercentageBasedGradingSchemeTests.swift, Core/CoreTests/Features/Grades/Model/Entities/PointsBasedGradingSchemeTests.swift, Teacher/Teacher/Localizable.xcstrings, Teacher/Teacher/SpeedGrader/Grading/Points/Model/GradeStateInteractor.swift, Teacher/Teacher/SpeedGrader/Grading/Points/ViewModel/SpeedGraderSubmissionGradesViewModel.swift, Teacher/TeacherTests/SpeedGrader/Grading/Points/ViewModel/SpeedGraderSubmissionGradesViewModelTests.swift
refs: [MBL-19074](https://instructure.atlassian.net/browse/MBL-19074)
affects: Teacher, Student, Parent
See ticket for details
Out of scope: GradePicker respecting grading scheme selection in assignment itself (it has it's own task)
(tests will follow in the followup for the main grade input task)
- Set a custom grading scheme in course details
- Do NOT set a different one in the assignment (leave it on default)
- Verify these kinds of grading schemes display and work properly for all kinds of Letter Grade and GPA assignments:
- Percentages based which has decimal values
- Point based matching the assignment's max score
- Point based not matching that
- Point based which also have decimals
- Compare GradePicker subtitles with grading scheme displays in Manage Garding …
=> SpeedGrader - Add support for custom grading schemes

Core/Core/Common/CommonModels/UserName/UserNameModel.swift, Core/Core/Features/Groups/APIGroup.swift, Core/Core/Features/Groups/GetGroups.swift, Core/Core/Features/Submissions/Submission.swift, Teacher/Teacher/SpeedGrader/SpeedGraderPage/ViewModel/SpeedGraderPageHeaderViewModel.swift, Teacher/Teacher/SpeedGrader/SubmissionRenderer/View/SubmissionViewer.swift, Teacher/Teacher/Submissions/SubmissionListViewController.swift, Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListInteractor.swift, Teacher/Teacher/Submissions/SubmissionsList/Model/SubmissionListInteractorLive.swift, Teacher/Teacher/Submissions/SubmissionsList/ViewModel/SubmissionListViewModel.swift, Teacher/TeacherTests/Submissions/SubmissionList/SubmissionListViewModelTests.swift, Teacher/TeacherTests/Submissions/SubmissionList/Utils/MockSubmissionListInteractor.swift
refs: MBL-19071
release note: Fixed issue of groups not showing in submission list when unsubmitted.
Make sure to create an assignment for group set defined on your course.
For proper testing, create multiple groups so to compare between unsubmitted and submitted ones.
After that make a submission for one of them,
Check Teacher > Assignment Details > Submission List screen.
Now you should see unsubmitted group shown as expected.
See [ticket's description](https://instructure.atlassian.net/browse/MBL-19071) for more details.
=> Fix issue of Groups not Showing in Submission List When Unsubmitted

Core/Core/Features/Assignments/Assignment.swift, Core/Core/Features/Assignments/AssignmentDetails/AssignmentSubmissionBreakdownViewModel.swift, Core/CoreTests/Features/Assignments/AssignmentDetails/AssignmentSubmissionBreakdownViewModelTests.swift
refs: MBL-18954
release note: none.
This is to defend against the possible case where a submission with needsGrading or un-submitted status is not being counted as "graded" of submission summary API response. And it is not counted as "unsubmitted" or "ungraded" as well. 
A found use case,
Grade a a student with no submission with "Missing" label, submit that on SpeedGrader, then go back to the same student and assign a custom label to it, then submit again. 
As consequence, Graded count on submissions summary won't include that, it will be also excluded from Ungraded & Un-submitted count. 
Now count for needsGrading and un-submitted upon showing submissions list shouldn't show minus value (-1).
=> Followup: Fix (NeedsGrading & Un-submitted) Counts for Submissions Breakdown for Custom Graded ones

Teacher/Teacher/TeacherAppDelegate.swift
refs: MBL-19166
builds: Teacher
release note: Fixed infinite loading animation upon login.
test plan:
- When logging in make the `users/self` API call to fail.
- The app should present a dialog about the failure with options to retry and log out.
- Test if those actions work properly.
=> Teacher - Handle non-authentication related API errors

Teacher/Teacher/SpeedGrader/SpeedGraderPage/View/SpeedGraderPageView.swift
refs: MBL-19224
builds: Teacher
release note: Updated grade sheet to be opened when opening SpeedGrader.
test plan:
- Check if drawer is in mid position by default.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/e894f387-f1e6-472c-8157-6c2f85e89d73" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/1278b8dc-bcb0-450d-a403-cc4572271c8f" maxHeight=500></td>
</tr>
</table>
=> SpeedGrader - Update drawer default position

Core/Core/Features/Files/View/FileList/FileListViewController.swift, Core/Core/Features/RestrictedStudentAccess/StudentAccessInteractor.swift, Core/CoreTests/Features/Files/View/FileList/FileListViewControllerTests.swift, Student/Student/Routes.swift
refs: PFS-25737
release note: When the restrict_student_access feature flag is enabled in the Student app,
then user will not be able to upload files
test plan:
- Enable the restrict_student_access feature flag
- Launch the Canvas Student app
- Navigate to Files and click on the + icon
- Upload file button should be hidden
- Disable the flag and verify that the Upload file button reappears
=> Disable File Uploads for Students

Core/Core/Features/Grades/View/Header/GradeListFilterButton.swift
refs: MBL-19165
builds: Student
test plan:
- Go to grade screen and check if the filter button is there after the initial load.
=> Fix filter button not realizing that it should appear

Core/Core/Common/CommonUI/CoreWebView/View/CoreWebView.swift, Core/Core/Common/CommonUI/CoreWebView/View/FileViewerWebViewController.swift, Core/CoreTests/Common/CommonUI/CoreWebView/View/CoreWebViewTests.swift
- A html link to a canvas file was added as a link in rich content that didn't point to a regular file resource, rather than pointed to the raw file on the resource server.
- Our app didn't recognize this as a valid path to a file and also the base url didn't match with the one used for login so the app treated this as an external url.
- External urls are opened externally in Safari, but to load this url, a valid session cookie was needed. In case the user didn't have such in the browser, the access was denied.
- To solve the issue, I added a logic that detects such links using their hostname that don't change.
- After this, the link is passed to a modal webview that already has a valid session cookie due to the cookie keep-alive mechanism and the file loads.
refs: …
=> [MBL-19255][All] Fix direct canvas file links not loading from rich content

Core/Core/Common/CommonUI/InstUI/Views/Cells/CheckboxCell.swift, Core/Core/Common/CommonUI/InstUI/Views/Cells/RadioButtonCell.swift, Core/Core/Common/CommonUI/InstUI/Views/Cells/TrailingCheckmarkCell.swift, Core/Core/Common/CommonUI/OptionSelection/Model/OptionItem.swift, Core/Core/Common/CommonUI/OptionSelection/View/MultiSelectionView.swift, Core/Core/Common/CommonUI/OptionSelection/View/SingleSelectionView.swift
We will need a header title to be displayed above checkboxes in the upcoming submission filter changes so I added support for it. While working on this, I noticed that the subtitle support was also inconsistent, so I modified all three selection cells (checkbox, radio, trailing checkmark) to support both header and subtitle labels. There should be no change in the existing behavior and the new layout isn't used yet. The goal of this PR is to make the submission list update PR smaller by merging this easy to review change set.
builds: Student
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/476b5f32-970c-4cb1-b745-d0ad5004ec87" maxHeight=500></td>
<td><img …
=> Update cell layout to support header and subtitle

Canvas.xcworkspace/xcshareddata/swiftpm/Package.resolved, Core/Core/Features/DocViewer/DocViewerViewController.swift, Core/project.yml, Horizon/project.yml, Parent/project-ci.yml, Parent/project.yml, Student/project-ci.yml, Student/project.yml, Teacher/project-ci.yml, Teacher/project.yml
Upgrade Nutrient (PSPDFKit) to version 14.2. Version 26.0 is the newest, but is incompatible with Xcode 16.4. We should upgrade to the newest version when we upgrade to Xcode 26.
Checked all annotation features and they work as expected.
refs: MBL-19292
builds: Student, Parent, Teacher
=> [MBL-19292] Update Nutrient SDK

Core/Core/Common/CommonUI/Formatters/DueDateSummary.swift, Core/Core/Features/Assignments/Assignment/Model/Entities/Assignment.swift, Core/Core/Features/Assignments/Assignment/Model/Entities/CDAssignmentCheckpoint.swift, Core/Core/Features/Assignments/Assignment/Model/Utilities/AssignmentDueDateTextsProvider.swift, Core/Core/Features/Assignments/AssignmentList/Model/StudentAssignmentListItem.swift, Core/Core/Features/Assignments/AssignmentList/Model/TeacherAssignmentListItem.swift, Core/Core/Features/Discussions/DiscussionListViewController.storyboard, Core/Core/Features/Discussions/DiscussionListViewController.swift, Core/Core/Features/Discussions/DiscussionTopic.swift, Core/CoreTests/Common/CommonUI/Formatters/DueDateSummaryTests.swift, Core/CoreTests/Features/Assignments/Assignment/Model/Utilities/AssignmentDueDateTextsProviderMock.swift, Core/CoreTests/Features/Assignments/Assignment/Model/Utilities/AssignmentDueDateTextsProviderTests.swift, Core/CoreTests/Features/Assignments/AssignmentList/Model/StudentAssignmentListItemTests.swift, Core/CoreTests/Features/Assignments/AssignmentList/Model/TeacherAssignmentListItemTests.swift, Core/CoreTests/Features/Discussions/DiscussionListViewControllerTests.swift, Core/CoreTests/Features/Discussions/DiscussionTopicTests.swift, Student/StudentE2ETests/Discussions/DiscussionsTest.swift, Teacher/TeacherE2ETests/Discussions/DiscussionsTests.swift
refs: [MBL-19120](https://instructure.atlassian.net/browse/MBL-19120)
builds: Student, Teacher
release note: Discussion checkpoints are now handled in discussion list.
- Add DCPs support for Discussion List
- Changed due date text priority, now MultipleDueDates priority over AvailabilityClosed (aligned with product)
- Extracted due date text calculation logic to `AssignmentDueDateTextsProvider`
- Verify Discussion List display due dates for both checkpoints if applicable, in both apps
- Smoke test Assignment List in both apps (due dates are still displayed)
<table>
<tr><th>Student Before</th><th>Student After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/7e672dbd-bb28-45c7-8417-5a17e9aa732b" maxHeight=500></td>
<td><img …
=> [MBL-19120] [S/T] DCP - Update Discussion List

Core/Core/Features/DocViewer/DocViewerConstants.swift
refs: MBL-19332
builds: Student, Teacher
release note: Fixed issue of disappearing PDF annotation toolbar in SpeedGrader intermittently
This issue show up consistently when user opens a PDF file for viewing, either from a link or through Files tab. Then after that goes on opening SpeedGrader to view student annotation submission of a student.
What causes the issue is actually the setting of `tintColor` property on global appearance of `AnnotationToolbar` right before showing PDF document at line `FileDetailsViewController:681`
**Note:** You need to use a locally-built build to test this feature. For PSPDFKit currently is **_not_** fully functional on adhoc builds.
- Opened PDF document either via link or through Files tab.
- Showed/Hid annotation toolbar on PDF …
=> [MBL-19332][Teacher] - Fixes issue of disappearing PDF annotation toolbar in SpeedGrader intermittently

packages/HorizonUI/Sources/HorizonUI/Sources/Components/WrappingHStack/HorizonUI.WrappingHStack.Storybook.swift, packages/HorizonUI/Sources/HorizonUI/Sources/Components/WrappingHStack/HorizonUI.WrappingHStack.swift
Adds an HStack that is capable of wrapping its content to a new line when it wouldn't fit into a single line. Additionally it supports filling a single row if there are spacers inside the child views which is not possible using the existing `HFlow`. 
<table>
<tr><th>Examples</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/30830282-d3cf-45a1-abfe-0577ce4333ce" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/1fcba39b-a41f-4672-9191-adf585951c2f" maxHeight=500></td>
</tr>
</table>
builds: Student
=> [HorizonUI] WrappingHStack
