instructure/canvas-ios

rn/Teacher/src/modules/speedgrader/components/Slider.js, rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/GradePicker.test.js.snap, rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/Slider.test.js.snap
Instead of trigging `onLayout` everywhere I used a default value of 1 to avoid `NaN` (and `-NaN`).
=> Fix NaN issue in tests

Student/Student/Student.entitlements
We want these to match old student since the bundle id is the same
and Xcode might try to sync them.
=> Update Reborn entitlements

dangerfile.js, rn/Teacher/i18n/setup.js, rn/Teacher/test/scripts/jestSetup.js
=> Fix jest testing to work in other timeZones

Core/Core/API/APIDocViewer.swift, Core/Core/DocViewer/DocViewerPresenter.swift, Core/Core/DocViewer/DocViewerUseCase.swift, Core/Core/Extensions/OperationQueueExtensions.swift
Properly handle the case where annotation metadata is not returned.
refs: MBL-11927
affects: none
=> Fix anonymous grading in new DocViewer

rn/Teacher/src/modules/address-book/AddressBook.js, rn/Teacher/src/modules/address-book/__tests__/AddressBook.test.js, rn/Teacher/src/modules/inbox/Compose.js
Had to calculate the number of recipient in the top-level group by summing the sub-groups.
refs: MBL-12089
release note: Fixed error when sending messages to 100 or more recipients
=> Auto bulk_message when >= 100 recipients

Core/Core.xcodeproj/project.pbxproj, Core/CoreTests/LTI/LTIToolsTests.swift, scripts/coverage/coverage.js
Also make the `coverage --test` save results to the preferred location.
refs: none
affects: none
=> Add more Core tests

Canvas/Canvas/CanvasAppDelegate.swift, Core/Core/AppEnvironment/AppEnvironment.swift, Core/CoreTests/AppEnvironment/AppEnvironmentTests.swift, Student/Student/AppDelegate.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
This is in prep for moving to the new login views. If login has been saved to the new keychain, switching to the new login flow won't log users out.
refs: none
affects: none
=> Save credentials in new keychain

Core/Core/API/APIOAuth.swift
This was preventing me from logging in in the reborn app.
refs: none
affects: none
=> OAuth doesn't always send email

rn/Teacher/src/modules/speedgrader/SubmissionGrader.js, rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/SubmissionGrader.test.js.snap, rn/Teacher/src/modules/speedgrader/components/CanvadocViewer.js, rn/Teacher/src/modules/speedgrader/components/FilesTab.js, rn/Teacher/src/modules/speedgrader/components/__tests__/CanvadocViewer.test.js, rn/Teacher/src/modules/speedgrader/components/__tests__/FilesTab.test.js, rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/CanvadocViewer.test.js.snap
Also don't close the files tab on wide layout
refs: MBL-12092
release notes: Fixed a bug where switching files on ipad in Speed Grader wouldn't always switch the file
=> Fix file switching on ipad

Canvas/TechDebt/Syllabus/CBISyllabusTabViewModel.m
refs: MBL-4195
release note: Fixed an issue where events with section specific dates would show multiple times for students in the course.
=> Only show events for the section you are in

rn/Teacher/src/modules/users/ContextCard.js, rn/Teacher/src/modules/users/__tests__/__snapshots__/ContextCard.test.js.snap
refs: MBL-12115
release note: Use display name instead of full name on people screens
=> Show display name instead of full name on ContextCard

CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsConstants.swift, CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsPDFDocumentPresenter.swift, CanvasCore/CanvasCore/Annotations/Pre Submission/PreSubmissionPDFDocumentPresenter.swift, Core/Core/DocViewer/DocViewerConstants.swift, Core/CoreTests/DocViewer/DocViewerConstantsTests.swift
refs: MBL-12169
release note: Added an option to give text annotations a transparent background and made that the default
=> Add transparent background to PSPDFKit text tool

Parent/Parent/Thresholds/StudentSettingsViewController.swift, Podfile, Podfile.lock
refs: none
I couldn't find a version of Eureka that builds with Swift 3 so we're
pulling in a Swift 4.2 version. I had to tweak the Podfile in order to
build Eureka with Swift 4.2.
=> Fix installing Eureka pod

Canvas/Canvas/CanvasAppDelegate.swift, CanvasCore/CanvasCore/Media/AudioRecorder.swift, Core/Core/AudioVideo/AudioRecorderViewController.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/AppDelegate.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
This should fix video comment playback after recording an audio comment.
refs: none
affects: none
=> After recording, set session back to playback

Canvas/Canvas/CanvasAppDelegate.swift, Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/Keychain/Keychain.swift, Core/Core/Login/LoginStartPresenter.swift, Core/Core/Views/CoreWebView.swift, Core/CoreTests/Login/LoginStartPresenterTests.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/AppDelegate.swift, Student/Student/Routes.swift, Student/StudentUnitTests/RoutesTests.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
environment.currentSession is the source of truth for logged in state.
Don't have multiple sources of truth, so we don't have to keep them in sync.
extra: align window setup & keychain management
refs: none
affects: none
=> Remove Keychain.currentSession

Core/Core/Store/Store.swift, Student/Student/Courses/CourseNavigation/CourseNavigationPresenter.swift, Student/Student/Groups/GroupNavigation/GroupNavigationPresenter.swift
=> dispatch.main.async call when already on main thread causes small delay that is noticeable when setting navbar colors

Core/Core.xcodeproj/project.pbxproj, Core/Core/Extensions/DispatchExtensions.swift, Core/Core/Store/Store.swift, Core/Core/Store/UseCase.swift, Core/CoreTests/Extensions/DispatchExtensionsTests.swift, Core/CoreTests/Store/StoreTests.swift, rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift
The main issue here was that `UseCase.fetch` callbacks were being
completed in tests that did not initiate them.
- TestA kicks off a request for courses and a request for modules
- TestA waits until courses load then the test would finish
- TestB starts
- TestB mocks modules request
- TestB requests modules
- TestA's request for modules would finish
- **TestA's modules would get written to TestB's db**
- TestB's request for modules would finish
- TestB's modules would get written to TestB's db
- TestB would fail because too many modules were written
This is due to UseCases retaining themselves until the callbacks
complete and not having a way to cancel a UseCase..
We should _probably_ support canceling at some point but in the
meantime, ensuring that we write to the …
=> Fix ModuleListPresenter tests

Core/Core/Store/Store.swift, rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift
refs: none
This is a needed improvement since `getNextPage` might get called a
bunch of times with detecting the end of scroll view. This should also
fix some flaky tests.
=> Fix getNextPage test

rn/Teacher/src/modules/files/ViewFile.js, rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
refs: MBL-12194
release note: Previewing html course files will resolve relative urls to other course files
=> Preview html course files rather than download and embed

Canvas/Canvas.xcodeproj/xcshareddata/xcschemes/Canvas.xcscheme, Core/Core/AppEnvironment/MDMManager.swift, Core/CoreTests/API/APITests.swift, Core/CoreTests/AppEnvironment/MDMManagerTests.swift, Core/CoreTests/Helpers/MockMDMManager.swift, Core/CoreTests/Login/LoginWebPresenterTests.swift, Parent/Parent.xcodeproj/xcshareddata/xcschemes/Parent.xcscheme, README.md, Student/Student.xcodeproj/xcshareddata/xcschemes/Student.xcscheme, rn/Teacher/ios/Teacher.xcodeproj/xcshareddata/xcschemes/Teacher.xcscheme
refs: none
* Always use the one configuration key (I misunderstood how this worked before)
* Move documentation to README
=> Update MDM login flow

Parent/Parent/Airwolf/Model/Student/Student+Network.swift
refs: MBL-12184
release note: Fixed bug with parents who have more than one enrollment type that is not observer
=> fix enrollments call

rn/Teacher/src/modules/courses/CourseNavigation.js, rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
Verified with David that the syllabus should show up on the detail side
of the split view controller. Tapping an assignment pushes onto the
detail.
=> Show syllabus in detail on iPad

Core/Core/Database/CoreData/Models/Rubric.swift, Core/CoreTests/Use Cases/GetAssignmentsTests.swift
=> fix rubric bug with core data

rn/Teacher/src/modules/dashboard/Dashboard.js, rn/Teacher/src/modules/dashboard/__tests__/Dashboard.test.js
refs: MBL-12240
release note: Fixed a bug that would cause an error when a user was invited to a course that had not yet started
=> Fix crash when course invites restricted by date

Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/Database/CoreData/Models/Course.swift, Core/Core/Database/CoreData/Models/File.swift, Core/Core/Database/CoreData/Models/Group.swift, Core/Core/Database/CoreData/Models/LogEvent.swift, Core/Core/Database/CoreData/Models/Submission.swift, Core/Core/Database/CoreData/Models/Tab.swift, Core/Core/Database/Scope.swift, Core/Core/Logger/LogEventList/LogEventListPresenter.swift, Core/Core/Logger/LogEventList/LogEventListViewController.swift, Core/Core/Use Cases/DownloadFile.swift, Core/CoreTests/Database/Models/CourseTests.swift, Core/CoreTests/Database/Models/GroupTests.swift, Core/CoreTests/Database/Models/SubmissionTests.swift, Core/CoreTests/Database/Models/TabTests.swift, Core/CoreTests/Logger/LogEventList/LogEventListPresenterTests.swift
We were not using this much, and it seemed more overhead than help.
Scope is used heavily in UseCases so that remains.
refs: none
affects: none
=> Remove Scoped protocol

rn/Teacher/src/modules/speedgrader/components/RubricItem.js, rn/Teacher/src/modules/speedgrader/components/__tests__/RubricItem.test.js
refs: MBL-11019
release note: Can now enter decimals on custom rubric item scores
test plan: credentials in the ticket
=> Change number pad to decimal pad

Cartfile, Cartfile.resolved
=> Downgrade PSPDFKit to 8.1.3 to avoid breaking speedgrader

CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html, Core/Core/Views/CoreWebView.swift
refs: MBL-12320
release note: Wraps long anchor text to fit in the screen width
=> Wrap long link text in webviews

CanvasCore/CanvasCore/PDF/CanvadocView.swift, Cartfile, Cartfile.resolved
refs: MBL-12335
release note: Fixed scrolling between submissions in speed grader
=> Update PSPDFKit, and check for empty string annotation state

rn/Teacher/src/modules/app/__tests__/index.test.js, rn/Teacher/src/modules/app/index.js, rn/Teacher/src/modules/inbox/CourseSelect.js, rn/Teacher/src/modules/inbox/Inbox.js, rn/Teacher/src/modules/inbox/__tests__/Inbox.test.js, rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Inbox.test.js.snap, rn/Teacher/src/modules/inbox/components/CourseFilter.js
refs: MBL-12311
release note: Fixed a crash in Inbox when a student was enrolled in a past or future course
Fixes the crash on the course filter as well as fixes a related bug in the
`Compose` course picker.
=> Fix crash when course is restricted by date

Student/Student/Submissions/SubmissionFiles/SubmissionFilesViewController.swift, Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift, Student/StudentUITests/Tests/StudentTest.swift
* XCUITest's `isHittable` will only ever be true if the element has `isAccessibilityElement = true` and by default it is `false` for `UIImageView`s
* We have to `.tap()` text inputs before we can `typeText()`
=> Fix tests with XCUITest

rn/Teacher/src/modules/courses/user-prefs/UserCoursePreferences.js, rn/Teacher/src/modules/courses/user-prefs/__tests__/UserCoursePreferences.test.js, rn/Teacher/src/modules/courses/user-prefs/__tests__/__snapshots__/UserCoursePreferences.test.js.snap, rn/Teacher/src/modules/courses/user-prefs/__tests__/map-state-to-props.test.js, rn/Teacher/src/modules/courses/user-prefs/map-state-to-props.js, rn/Teacher/src/modules/profile/Profile.js, rn/Teacher/src/modules/profile/__tests__/Profile.test.js, rn/Teacher/src/modules/profile/__tests__/__snapshots__/Profile.test.js.snap, rn/Teacher/src/modules/userInfo/__tests__/reducer.test.js, rn/Teacher/src/modules/userInfo/reducer.js
refs: MBL-12395
This PR moves the color overlay toggle from the course user preferences to the
profile drawer as it's a global setting, not course specific.
=> Move color overlay toggle into profile drawer

Cartfile.resolved, Student/StudentUITests/Element/Element.swift, Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
We don't want to wait for things that are not visible/enabled to be
not visible/enabled because we end up waiting the entire duration.
Relies on https://github.com/instructure/SwiftUITest/pull/5
=> Optimize UI tests (for xcuitest)

CanvasCore/CanvasCore/Session/NSURLSession+ThreeLegit.swift
I got a `BAD_ACCESS` error here. It originated from trying to set up
push notifications in `getNotificationPreferencesSetup`.
I'm not positive that this will fix the crash but it seems like we
should not strongly retain `self` here.
I tested areas of the app that use this ThreeLegit stuff and they
appear to still be working.
=> Fix a crash on startup

rn/Teacher/src/modules/profile/Profile.js, rn/Teacher/src/modules/profile/__tests__/Profile.test.js
The profile drawer was sticking around on `Change User` and 'Logout`
so VO would focus an invisible drawer on the login screen.
=> Fix VO on logout

Student/Student/Submissions/SubmissionComments/SubmissionCommentFileView.swift
This affects new student
refs: MBL-12456
=> Add submission type to a11y label

Canvas/GradesWidget/Base.lproj/MainInterface.storyboard, Canvas/GradesWidget/GradesTodayWidgetPresenter.swift, Canvas/GradesWidget/GradesTodayWidgetViewController.swift, Core/Core/API/APICourseRequestable.swift, Core/Core/Use Cases/GetCourses.swift, Core/CoreTests/API/APICourseRequestableTests.swift
Also fixes collapsed sizing on iPad
refs: MBL-12392
release note: Fixed the grades widget to work better with iPad and users with more than 10 favorited courses
Test Plan:
- Try the users in the ticket on both iPad and iPhone 8
=> Fix the widget to work with users with more than 10 favorited courses

rn/Teacher/src/common/components/AttachmentView.js
=> Add a11y label to share button in AttachmentView

Canvas/Canvas/Shrug/Router+Canvas.swift
refs: MBL-12458
This was the smallest code change possible to make it work. Don't
_really_ need this route at all so I can remove it and just present the
URL submission view controller if we'd rather do that.
=> Fix routing to url submission

Core/Core/ActAsUser/ActAsUserViewController.storyboard, Core/Core/ActAsUser/ActAsUserViewController.swift
Switching locale prompts a needed alert that would get dismissed. We
don't need to dismiss since we animate to a new root view controller
when we masquerade.
pork: remove auto correct from domain field in masquerade screen.
=> Fix masquerading as user in a different locale

Canvas/CanvasUITests/Inbox/InboxTests.swift, CanvasCore/CanvasCore/Session/Session.swift
One of our [top crashes](https://console.firebase.google.com/u/0/project/delta-essence-114723/crashlytics/app/ios:com.instructure.icanvas/issues/5ce6b9ddf8b88c2963b4a4ec)
in Student is this super awesome stack trace:
```
__51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.182 + 252
```
Gabe has been seeing a crash in `Session.swift` `urlSession(session:task:didCompleteWithError:)`
when running the UI tests. The two look very related.
It's possible that multiple threads
are trying to mutate `completionHandlerByTask`. I'm hoping that by making
copies we can avoid `EXC_BAD_ACCESS` here.
=> Avoid bad access crash in Session

Canvas/CanvasUITests/CanvasUITests.swift, Canvas/CanvasUITests/Dashboard/DashboardTests.swift, rn/Teacher/src/modules/courses/components/CourseCard.js, rn/Teacher/src/modules/courses/components/__tests__/__snapshots__/CourseCard.test.js.snap, rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
Testing the color seemed like fragile code we didn't want to maintain, and the course code is not in the a11y tree, so it only tests the name.
refs: MBL-12570
affects: none
=> Add course card info test

scripts/translations/export.js
This should allow the grades widget and submit assignment extension to be translated.
refs: MBL-12711
=> Allow bundle display name to be translated

Student/Student.xcodeproj/project.pbxproj
This may be what was causing the duplicate PSPDFKit errors.
refs: none
affects: none
=> Unlink PSPDFKit from StudentReborn

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
Since UIRefreshControl uses the size of the scrollView for pull length
refs: none
affects: none
=> Reduce scrollView frame in storyboard

Canvas/Canvas/CanvasAppDelegate.swift, CanvasCore/CanvasCore/React Native Modules/PushNotifications.h, CanvasCore/CanvasCore/React Native Modules/PushNotifications.m
push `userInfo` payload is coming in the launchOptions of appDelegate method.  We are not handling that.
refs: MBL-12702
release note: fix push bug
=> MBL-12702 fix startup manager init

CanvasCore/CanvasCore/Annotations/Pre Submission/SubmitAnnotatedAssignmentViewController.swift
One fewer file system slow leak.
refs: none
=> Use tmpdir for flattened PDF submissions

Podfile.lock, rn/Teacher/.flowconfig, rn/Teacher/package.json, rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneePicker.test.js.snap, rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap, rn/Teacher/src/modules/groups/__tests__/GroupList.test.js, rn/Teacher/src/modules/groups/__tests__/__snapshots__/GroupList.test.js.snap, rn/Teacher/src/modules/people/PeopleList.js, rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/SpeedGrader.test.js.snap, rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/SubmissionGrader.test.js.snap, rn/Teacher/src/routing/__tests__/__snapshots__/index.test.js.snap, rn/Teacher/yarn.lock, yarn.lock
regenerate yarn.lock files to get the latest of transitive dependencies without
updating direct dependencies we care about.
refs: MBL-12850
affects: none
=> Update lodash & transitive dependencies

Student/Student/Submissions/ArcSubmission/ArcSubmissionPresenter.swift, Student/Student/Submissions/ArcSubmission/ArcSubmissionViewController.swift, Student/StudentUnitTests/Submissions/ArcSubmission/ArcSubmissionPresenterTests.swift
refs: MBL-12851
We have to selectively intercept the submit event because
apparently a form element can get submitted before the content loads.
=> Fix Studio submissions with multiple form submits

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
=> MBL-12888 - if assignment details description is empty, show "No Content"

Canvas/Canvas/Modules/ModuleDetailsViewController.swift, Canvas/Canvas/Shrug/Router+Canvas.swift, Canvas/CanvasUITests/Notifications/NotificationsListTests.swift, Canvas/TechDebt/iCanvas/Router.m, CanvasCore/CanvasCore/Files/Model/FileUpload.swift, CanvasCore/CanvasCore/Modules/ModuleItem/ModuleItem+Progress.swift, CanvasCore/CanvasCore/Persistence/So Refreshing/Refresher.swift, CanvasCore/CanvasCore/Session/NSURLSession+ThreeLegit.swift, CanvasCore/CanvasCore/Session/Session.swift, Core/Core.xcodeproj/project.pbxproj, Core/Core/Extensions/NotificationCenterExtensions.swift, Core/Core/Models/ModuleItemCompletionRequirement.swift, Core/Core/Router/Router.swift, Core/Core/Use Cases/CreateSubmission.swift, Core/CoreTests/Extensions/NotificationCenterExtensionsTests.swift, Core/CoreTests/Router/RouterTests.swift, Core/CoreTests/Use Cases/CreateSubmissionTests.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonAlertView.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/Student/Submissions/TextSubmission/TextSubmissionViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
pork: Refactor Session.swift to not use URLSession delegate methods
and to use callbacks instead. This fixes some of the bad access errors
we were getting when accessing the stored completion handlers.
pork: use formSheet for most submission types (per Dave's request)
refs: MBL-12870
=> Post module item completion requirements

Core/Core/AudioVideo/AudioRecorderViewController.swift
refs: MBL-12883
NOTE: This must be tested on device. Simulator does not
have this error
=> Prevent error from audio recording sequence

Canvas/CanvasUITests/Notifications/NotificationsListTests.swift, Canvas/CanvasUITests/Todo/TodoListTests.swift, CanvasCore/CanvasCore/Assignments/Submission/New Submission/ArcVideoPickerViewController.swift, CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift, CanvasCore/CanvasCore/Session/Session.swift, Core/Core.xcodeproj/project.pbxproj, Core/Core/API/API.swift, Core/Core/API/APIActivity.swift, Core/Core/API/APITodo.swift, Core/Core/UITestHelpers/MockDistantURLSession.swift, Core/Core/Use Cases/UploadManager.swift, Core/Core/Use Cases/UploadMedia.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Use Cases/UploadManagerTests.swift, Frameworks/CanvasKit/CanvasKit/Networking/CKIClient.m, Student/StudentUITests/StudentUITestCase.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, TestsFoundation/TestsFoundation/API/MockURLSession.swift, TestsFoundation/TestsFoundation/Fixtures/API/APIActivityFixture.swift, TestsFoundation/TestsFoundation/Fixtures/API/APITodoFixture.swift, TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift, rn/Teacher/index.ios.js, rn/Teacher/src/common/login-verify.js, rn/Teacher/src/redux/actions/async-tracker.js
Makes more api calls mockable (Session.swift, CKIClient).
js api calls are still not mockable, and the login validation is disabled for UI tests.
refs: none
=> Mock Notifications & Todo tests

Core/Core/DocViewer/DocViewerSession.swift, Core/CoreTests/DocViewer/DocViewerSessionTests.swift
This assumes that docviewer always tells us to wait 2 seconds when it sends a 202.
refs: MBL-12877
=> Better handle docviewer retry_after

Student/Student/Submissions/SubmissionDetails/Views/Drawer.swift, Student/Student/Submissions/SubmissionDetails/Views/Drawer.xib
Set the gripper label, and deselect the first segment until content is shown.
refs: MBL-12946
=> Fix initial state of drawer

Canvas/CanvasUITests/Notifications/NotificationsListTests.swift, Canvas/CanvasUITests/Todo/TodoListTests.swift, CanvasCore/CanvasCore.xcodeproj/project.pbxproj, CanvasCore/CanvasCore/React Native Modules/MockHTTPRequestHandler.m, Core/Core/UITestHelpers/MockDistantURLSession.swift, TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift, rn/Teacher/index.ios.js, rn/Teacher/src/common/login-verify.js
Adds another http(s) handler that will use mock data when it there is some in a DEBUG build.
refs: MBL-12943
affects: none
=> Mock React Native requests

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift, Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
=> MBL-12897 - show empty screen for locked assignments

rn/Teacher/src/modules/tabs/TabsList.js
The bad scrolling happens when the initial refresh flashes. By not reporting to be refreshing, the bad scroll never happens.
This does mean however that the spinner won't be accurately shown for the whole time it is refreshing.
refs: MBL-13034
release note: Fixed an issue with Course navigation scrolling
=> Workaround CourseNavigation header issue

Core/Core/AppEnvironment/Keychain.swift
I noticed that my login sessions were not persisting. Turns out I was getting `errSecItemNotFound` from `SecItemAdd` and then `errSecDuplicateItem` from `SecItemUpdate`, identitical to [this SO post](https://stackoverflow.com/questions/22403734/keychain-item-reported-as-errsecitemnotfound-but-receive-errsecduplicateitem-o).
Turns out that we should only query on `kSecClass`, `kSecAttrService` and `kSecAttrAccount` because additional fields (like `kAttrAccessible`) will _"exclude any existing item with the same unique key, but with different attributes."_
The new approach is taken from [this post](https://forums.developer.apple.com/message/259602#259602) from an Apple developer.
=> Fix updating keychain entry

Student/Canvas/Calendar/UI/View/CalendarView.swift
We're getting crash logs on this line. I haven't able to repro but I'm
guessing it's the force unwraps. I doubt `layoutAttributesForItem(at:)`
crashes since it has an optional return value.
=> Remove force unwraps

scripts/coverage/config.json
=> exclude TabBar.swift files from code coverage

Core/Core/Models/Viewable/SubmissionViewable.swift, Core/CoreTests/Models/Viewable/SubmissionViewableTests.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
refs: MBL-13139
release note: Fixed an issue where unsubmitted assignments and quizzes that were graded were saying they were submitted
=> Show proper wording for graded unsubmitted assignments and quizzes

Core/Core/Login/LoginSession.swift, Core/Core/UITestHelpers/UITestHelpers.swift, Core/CoreTests/AppEnvironment/CacheManagerTests.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Login/LoginSessionTests.swift, Core/CoreUITests/CoreUITestCase.swift, Student/StudentUnitTests/PersistenceTestCase.swift, Student/SubmitAssignmentTests/SubmitAssignmentPresenterTests.swift, Student/SubmitAssignmentTests/SubmitAssignmentTests.swift, TestsFoundation/TestsFoundation/Fixtures/Keychain/KeychainEntryFixture.swift, rn/Teacher/ios/TeacherTests/TeacherTestCase.swift
This should prevent tests from messing with the keychain used by the apps.
=> Use separate keychain for login session in tests

Core/Core/Use Cases/UploadManager.swift, Core/CoreTests/Use Cases/UploadManagerTests.swift, Student/Student/CanvasAppDelegate.swift, Student/SubmitAssignment/SubmitAssignmentPresenter.swift, Student/SubmitAssignmentTests/SubmitAssignmentPresenterTests.swift, TestsFoundation/TestsFoundation/Files/MockUploadManager.swift
I'm getting an error uploading from the share extension using the Test Flight build. Based on the logs and error message, I'm guessing that it has to do with the app and the share extension using the same identifier.
I was going off of [this post](https://forums.developer.apple.com/message/225659#225659) by an Apple Staff member:
> The app and the share extension must use the same NSURLSession background session identifier
However, the [official docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) say this:
> Because only one process can use a background session at a time, you need to create a different background session for the containing app and each of its app extensions. 
I wasn't sure which …
=> Use a different background session for share

.gitignore, scripts/apiModelCodegen/Cartfile, scripts/apiModelCodegen/Cartfile.resolved, scripts/apiModelCodegen/CodeGen.swift, scripts/apiModelCodegen/input.json, scripts/apiModelCodegen/setup.sh, scripts/apiModelCodegen/templates/APIModel.mustache, scripts/apiModelCodegen/templates/APIModelFixture.mustache, scripts/apiModelCodegen/templates/GetApiRequestable.mustache, scripts/apiModelCodegen/templates/GetApiRequestableTests.mustache, scripts/apiModelCodegen/templates/GetUseCase.mustache, scripts/apiModelCodegen/templates/GetUseCaseTests.mustache
refs: none
affects: none
Not sure if anyone is interested in this.  I've made new entities for our API so many times that hopefully this will speed up that process.   this will generate the API model, fixture, Requestables, use case and unit tests.
1. Run the `./setup` script which configures dependencies.  
2. You define the entity name and the properties to your API model in `input.json`.  
3. Then run `./GenCode.swift` from the command line. 
The code is generated in an `output` folder and you can add them to the project.  It isn't perfect but it's a faster start than writing it again from scratch or copying files.
4. Add files to project
5. Edit the files as you see fit.
6. sit back and relax
=> code gen for new API entities to fit in our new arch

Parent/Parent/Info.plist, rn/Teacher/ios/Teacher/Info.plist
=> remove no dark mode from plist for parent and teacher

Core/Core/Pages/PageList/PageListPresenter.swift, Core/Core/Pages/PageList/PageListViewController.swift, Core/CoreTests/Pages/PageList/PageListPresenterTests.swift, Student/Canvas/Notifications/ActivityStreamTableViewController.swift, Student/Canvas/Notifications/NotificationsTab.swift, Student/Canvas/To Do/ToDoListViewController.swift, Student/Canvas/To Do/ToDoTab.swift, Student/Student/People/PeopleListPresenter.swift, Student/Student/Quizzes/QuizList/QuizListPresenter.swift, Student/Student/RootViewController.swift, Student/Student/Routes.swift, Student/StudentUnitTests/People/PeopleListPresenterTests.swift, Student/StudentUnitTests/Quizzes/QuizList/QuizListPresenterTests.swift
refs: MBL-13274
Test plan:
- Course and group people lists > user context card
- Notifications Tab > tap notification
- To Do tab > tap to do item
- Quizzes list > tap quiz item
- Pages list > tap page
You can use my normal student user. It has a To Do item and some notifications and all the rest.
=> Fix showing detail views on iPad

Student/TechDebt/People/AboutViewController.m, Student/TechDebt/People/AboutViewController.storyboard
extra: also push Terms instead of modal again
refs: MBL-13299
release note: Fixed the nav bar style in the About screen for iOS 13
=> Use white navbar for About

CanvasCore/CanvasCore/Session/Session.swift, Student/Canvas/Calendar/UI/View Controller/CalendarEventDetailViewController.swift
refs: MBL-13301
I forgot that we store things on Session that need to stay alive so
we shouldn't be creating a new one each time we access `.shared`. This
makes it so that a Session is re-used but the AppEnvironment is always
up to date.
Test plan:
* View a calendar event from syllabus (you can use my student account)
* View a calendar event from calendar
* View other screens that rely on Session (Modules, Notifications, To Do) and make sure they load correctly
=> Fix loading calendar events from syllabus

Student/Student/Routes.swift
The native route handler lost the function props passed by the attachment picker. When there are props passed to an RN route from an RN screen, it has to be handled all in Helm to get the props passed through.
refs: MBL-13309
release note: Fixed an issue with attaching a file from My Files
=> Fix attaching from My Files

CanvasCore/CanvasCore/Helm/Helm.swift, CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift, CanvasCore/CanvasCore/Views/SplitViewController.swift
refs: MBL-13347
release note: Fixed a bug that would cause the app to crash
**Test plan:**
* Please pull this down and tap around on iPad and iPhone and make sure we always show the correct left nav bar items
* Play around with side-by-side on iPad
* Make sure you can always go back from a screen and/or expand it on iPad if the split view changes
I gave it a pretty good run-through but another pair of eyes would be great.
=> Fix infinite loop

Core/Core/Extensions/UINavigationBarExtensions.swift, Core/CoreTests/Extensions/UINavigationBarExtensionsTests.swift
refs: MBL-13293
release note: Fixed calendar title contrast in iOS 13
=> Enforce title color in iOS 13

Core/CoreTests/Pages/PageList/PageListPresenterTests.swift
Somehow missed this in the last PR, and the tests just magically succeeded anyway.
=> fixed fix of PageListPresenterTests

Core/Core/PageViewAnalytics/AppBackgroundHelperProtocol.swift, Core/Core/PageViewAnalytics/PageViewEventRequestManager.swift, Core/CoreTests/PageViewAnalytics/PageViewEventRequestManagerTests.swift, Core/CoreTests/PageViewAnalytics/PageViewEventViewControllerLoggingProtocolTests.swift, Student/Student/CanvasAppDelegate.swift
refs: MBL-13350
release note: Fixed a bug that would cause the app to restart when in the background
Every time we send page view events from the background we create two
background tasks: 1 to get a token and 1 to send the events.
The problem was that we weren't calling `endBackgroundTask` for the
token task because the task was getting replaced with the second task
before we had a chance. And the system terminates apps that don't call
`endBackgroundTask`.
So instead of holding on to one task at a time we can hold on to as many
as we need.
**Test plan:**
- Launch the Student app and tap into a course
- Background the app for 30 seconds
- No need to launch other apps. Just let your phone sit for at least 30 seconds
- Bring the Student app to the foreground by launching it …
=> Fix page view events background task management

Student/Canvas/Modules/Mastery Paths/MasteryPathSelectOptionViewController.swift, Student/Canvas/Modules/Module Items/ModuleItemViewModel.swift, Student/Canvas/Modules/ModuleDetailsViewController.swift
refs: MBL-13287
release note: Fixed a crash when selecting a mastery path
Test plan:
- Log in as `student10` on `narmstrong`
- Dashboard > CS 1400 > Modules > Mastery Paths > Choose option
- App should not crash
- Should have option to dismiss with Cancel button
- Selection view should be in a formsheet on iPad
- Selecting an option should dismiss the modal and make the selection available
=> Fix selecting mastery path

Core/Core/Models/UTI.swift, Core/CoreTests/Models/UTITests.swift, Student/SubmitAssignment/SubmitAssignmentPresenter.swift, Student/SubmitAssignmentTests/SubmitAssignmentPresenterTests.swift
refs: MBL-13354
release note: Fixed submitting screenshots in iOS 13
**Test plan:**
- Take a screenshot and use the share menu to submit it to Student
- Submit a photo from Photos
- Submit a document from the Files app or one similar (Google drive, etc)
=> Support submitting raw images in share extension

CanvasCore/CanvasCore/WhizzyWig/WhizzyWigTableViewCell.swift, Parent/Parent/Details/DetailsDescriptionCell.swift
refs: MBL-13376
**Test plan:**
- Log in as narmstrong > o
- View CS 1400 > Week of Sept 1 > New Event!!
- Details should load, scrolling should be smooth
=> Fix parent calendar event details

Core/Core/Views/HorizontalMenuViewController.swift
student
1. on ipad navigate to syllabus with assignments and syllabus tabs
2. click to go to assignments tab
2. expand ipad to just show details
3. de-expand, it should still be on assignments and display correctly after expansion
=> fix split view bug with horizontal menu

CanvasCore/CanvasCore/WhizzyWig/CanvasWebView.swift
refs: MBL-13418
release note: Fixed a bug that would prevent html 5 content from loading
Test plan:
* See ticket for account and masquerade ID
=> Fix HTML5 content

rn/Teacher/rn-mods.sh
refs: MBL-13420
release note: Fixed issues with media attachments
**Test plan**
Student app:
* Tap Reply on an announcement and/or discussion
* Tap the image icon in the editor toolbar to embed a media
* Tap 'Choose from Library'
* Select a video
* Verify that the video gets uploaded and embeded
* Post the reply and verify that you can play the video from the discussion thread
Teacher app:
* Repeats steps above to embed a video in a discussion reply
* Edit a discussion and embed a video in the description
* Edit an assignment and embed a video in the description
* Edit a page and embed a video in the description
=> Fix media attachments in RN rich content

Core/CoreTests/MetaTests/XCTestCaseTests.swift, TestsFoundation/TestsFoundation/Extensions/XCTestCaseExtensions.swift
There just doesn't seem to be a reliable way to tell if a runloop/dispatch queue is drained. So instead just do the dumb thing.
=> Changed drainMainQueue to be dumber, but less random

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
refs: MBL-13324
release note: fixed bug where lti button was shown when assignment was locked
Test Plan
-----------
see ticket
=> hide show lti button when assignment is locked for user

CanvasCore/CanvasCore/Annotations/Canvadocs/Comments/UITextView+Placeholder.m
refs: MBL-13359
release note: Fixed a bug when adding comment to pin annotations
Test Plan:
- Have a student submit a pdf to an assignment
- In teacher app create a pin annotation and try to
create a comment. It should work.
- Because the fix for this issue depends on ios13
should try in ios12 as well just to make sure it
still works there as well.
=> Fix crash in speedgrader

Core/Core.xcodeproj/project.pbxproj, Core/Core/Login/LoginWebViewController.swift, Core/CoreTests/Login/LoginWebViewControllerTests.swift, TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj, TestsFoundation/TestsFoundation/Extensions/URLAuthenticationChallengeExtensions.swift, rn/Teacher/src/modules/dashboard/GroupRow.js
refs: MBL-13370
release note: Fixed login for some institutions
Test plan:
* Launch student app and log out or change user
* Find My School > mhowe > Go
* Should load a discovery page. Tap ADFS
* Should be shown an alert with username and password fields. Use credentials from jira ticket
* Tap OK you should get logged in
* Tapping cancel should continue the request and show an error
* Make sure regular log in works (twilson, narmstrong, etc)
=> Fix NTLMS and HTTP Basic auth challenges

Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
This reverts commit 191391c5b673ba8a4c79019eeeaaf46c8d130bc1.
refs: MBL-13394
release note: Fixed allowing comments on locked assignments
=> Revert "Disable adding comments while assignment is locked (#684)"

Core/Core/PageViewAnalytics/Persistency.swift, Core/CoreTests/PageViewAnalytics/PageViewEventRequestManagerTests.swift
I was able to get it to fail consistently if I deleted the CoreTester
app before running the test. The changes seemed to have helped.
Hopefully bitrise agrees.
=> Fix flaky testRetrievePandataEndpointInfo

.gitignore, Core/Core/UITestHelpers/MockDistantURLSession.swift, Core/CoreUITests/CoreUITestCase.swift, NightlyTests.xctestplan, scripts/report-failing-tests.sh, scripts/run-nightly-tests.sh
Removes the old in-XCTestCase retry mechanism in favor of a script wrapper that essential re-calls `xcodebuild test` with all the failed tests.
This should be more reliable and flexible. Expect lots of UI test failures, but the failing ones can now be worked on with confidence.
Relevant build:
https://app.bitrise.io/build/78244fed7fc067e1
refs: MBL-13427
affects: none
=> Improved retry mechanism for NightlyTests

rn/Teacher/src/modules/submissions/list/__tests__/submission-entities-reducer.test.js, rn/Teacher/src/modules/submissions/list/submission-entities-reducer.js
refs: MBL-13386
release note: Fixed a bug where grading an assignment where automatic grade posting is set would show the grade as hidden.
Test Plan:
- Create an assignment
- Make sure new gradebook is turned on
- go to the gradebook and turn on automatic grade posting
(cog -> grade posting policy -> automatic)
- Go into speedgrader for the assignment
- Grade the student, when the grade saves it shouldnt
show the red hidden eyeball
=> Record the posted_at timestamp on grade

Student/Student.xcodeproj/project.pbxproj, Student/Student.xcodeproj/xcshareddata/xcschemes/SubmitAssignment.xcscheme, Student/SubmitAssignment/SubmitAssignmentPresenter.swift, Student/SubmitAssignment/SubmitAssignmentViewController.swift, Student/SubmitAssignmentTests/SubmitAssignmentViewControllerTests.swift, TestsFoundation/TestsFoundation/API/MockURLSession.swift
refs: MBL-13312
release note: Fixed a bug where selecting an assignment in the share menu would get reset
Test plan:
* Delete the student app
* Install this build
* Log in as my student (s)
* Dashboard > CS 1400 > Annotate This
* Tap the link `Agenda for UCF Visit.pdf`
* Okay you have to be quick for this next part so read ahead first:
* Tap Share > Student > Tap the assignment row and before the assignments list finishes loading, quickly tap an assignment from the list
* Were you quick enough? You won't know (if it worked)
* The selected assignment should be the one you chose, not the default
* See the video in the ticket for an example of what it used to do
=> Fix selecting assignment in SubmitAssignment

Core/Core/Models/Assignment.swift, Core/CoreTests/Models/AssignmentTests.swift, Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
refs: MBL-13326, MBL-13392
release note: Fixed an issue that would prevent users from viewing feedback on submissions
Test plan:
* External tool submissions that have an associated file should show the file in the submission viewer instead of showing the `Open External Tool` button
* External tool submissions that do not have a linked file should show the `Open External Tool` button
* Use test plan from linked tickets (MBL-13326 and MBL-13392)
* Make sure regular LTI assignments still work
* twilson > student1 > Quizzes Next 2 > Assignments > Planets > Submission & Rubric > Open External Tool
=> Show attachment for online_upload LTI submissions

CanvasCore/CanvasCore/Helm/Helm.swift, rn/Teacher/src/modules/courses/CourseNavigation.js, rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js, rn/Teacher/src/modules/courses/__tests__/__snapshots__/CourseNavigation.test.js.snap, rn/Teacher/src/modules/courses/__tests__/courses-reducer.test.js, rn/Teacher/src/modules/courses/actions.js, rn/Teacher/src/modules/courses/courses-reducer.js
refs: MBL-13399
release note: Fixed a bug with course links
Test plan:
* Link to a public course from a page and tap the link in the student and teacher apps
* Courses details should load in the master on iPad
* Course details should use the course color for nav bar and icons
* See ticket for example
=> Fix linking to course details

CanvasCore/CanvasCore/Helm/Helm.swift, TestsFoundation/TestsFoundation/Router/TestRouter.swift, rn/Teacher/index.ios.js, rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListPresenter.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift, rn/Teacher/ios/TeacherTests/RoutesTests.swift, rn/Teacher/src/routing/Navigator.js, rn/Teacher/src/routing/__tests__/Navigator.test.js
refs: MBL-13381
release note: Fixed a navigation issue when viewing pages and module items on iPad
Test plan:
* Page and module item details should replace the split view details, not do a push
* On iPad in Teacher app, tap into a course and view Page
* Tap several pages, the split view details should get replaced with the page
* Repeat for Modules > tap on module items
* Use my student (s) in course CS 1400 for content
=> Fix showing pages and module items on iPad

Core/Core/LTI/LTITools.swift, Core/Core/Models/Context.swift, Core/CoreTests/LTI/LTIToolsTests.swift, Core/CoreTests/Models/ContextTests.swift
refs: MBL-13323
release note: Fixed an issue with launching certain external tools
Test plan:
* Studio LTI launches should show comments section
* See ticket: https://instructure.atlassian.net/browse/MBL-13323
Look at the modules in that tickets
It has Studio embedded in a few different content types
Launch each of them and make sure they show the comments section
=> Check for context when launching LTI tools

CanvasCore/CanvasCore/Persistence/Table View/TableViewDataSource.swift, Core/Core/Extensions/NotificationCenterExtensions.swift, Student/Canvas/Modules/Module Items/ModuleItemViewModel.swift
refs: MBL-13316
release note: Fixed showing which module item is active on iPad
Test plan:
* Install the Student app on an iPad
* View Modules > tap on an individual module
* Tap on a module item, the module item cell should stay selected
* Use the 'Next and 'Previous' buttons to navigate through the module
* The active module item's cell should become active as expected
You can use my test student (s) and modules in CS 1400.
=> Fix module item selection

CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsPDFDocumentPresenter.swift, Core/Core/DocViewer/DocViewerPresenter.swift, Core/CoreTests/DocViewer/DocViewerPresenterTests.swift
refs: MBL-13463
Test plan:
* Add a text annotation to a document in Teacher SG
* Tap away from the text annotation
* Tap it again to show blue box
* Should not have option to rotate annotation
=> Disable rotating text annotations in Teacher

scripts/build_automation/bitrise_workflows/tests.yml
Aborted builds were reporting nothing to slack, now they'll at least report they were started. Unfortunately, actually updating the slack message would be more work than I feel like doing right now.
refs: MBL-13511
affects: none
=> Add a nightly "build starting" message

Core/CoreTests/DocViewer/DocViewerPresenterTests.swift, Core/CoreTests/RichContentEditor/RichContentEditorViewControllerTests.swift, Core/CoreUITests/CoreUITestCase.swift, Core/CoreUITests/UITestUser.swift, scripts/build_automation/bitrise_workflows/tests.yml, scripts/run-nightly-tests.sh
Apparently the "set -e" flag does less than I thought (it doesn't cause functions to return)
Test plan: this build shouldn't time out:
https://app.bitrise.io/build/45f517fba25b08fc
refs: MBL-13510
affects: none
=> Made nightly runner more robust to xcode errors

Core/CoreTests/API/AssignmentListRequestableTests.swift
refs: MBL-13577
Test Plan
1. set timezone on your machine to tz other than MST.
2. run tests.  
3. Assure they pass.
=> fix timezone issue

Core/Core/API/APIActivity.swift, Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/Core/UITestHelpers/UITestHelpers.swift, Core/CoreTests/API/APIActivityTests.swift, Core/CoreUITests/CoreUITestCase.swift, Student/StudentUITests/Notifications/NotificationsListTests.swift
refs: MBL-13632
Also adds a way to enable experimental features in UI tests.
=> Fix notifications tests

Core/Core/API/APIEnrollment.swift
This should not regress MB-13575 (https://instructure.atlassian.net/browse/MBL-13575)
refs: none
=> Make user on enrollment optional

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/APIDiscussionRequestable.swift, Core/Core/API/APIRequestable.swift, Core/Core/Files/APIFile.swift, Core/Core/Models/Context.swift, Core/Core/UITestHelpers/IPC.swift, Core/Core/UITestHelpers/MockDistantURLSession.swift, Core/CoreTests/API/APIDiscussionRequestableTests.swift, Core/CoreTests/Files/APIFileTests.swift, Core/CoreUITests/CoreUITestCase.swift, Core/CoreUITests/Course Files/CourseFileTests.swift, Core/CoreUITests/Profile/FilesList.swift, Core/CoreUITests/Profile/UserFilesTests.swift, Student/StudentUITests/TestsFromCore.swift, TestsFoundation/TestsFoundation/Element/Element.swift, TestsFoundation/TestsFoundation/Fixtures/API/APIFileFixture.swift, scripts/build_automation/bitrise_workflows/parent.yml, setup.sh
Also, added the capability to dynamically mock data with a closure
test plan: 
https://app.bitrise.io/build/f926ea97d4eafced
will only fail on testNotificationItemsDisplayed and testTodoItemsDisplayed (separate tickets)
refs: MBL-13610
=> Student UI test: C3639562 user files add file

rn/Teacher/src/canvas-api/apis/discussions.js, rn/Teacher/src/modules/discussions/details/DiscussionDetails.js, rn/Teacher/src/modules/discussions/details/__tests__/DiscussionDetails.test.js
refs: MBL-7308
release note: Fixed marking announcements and discussions as read
Test plan:
* Create a new course announcement
* View the course announcements as a student in web
* Notice the new announcement is unread
* View the new announcement as a student in the student app
* On the web, the announcement should be marked as read
You can use my account:
```
narmstrong > s > CS 1400 > Announcements > Push Notifications X
```
=> Mark discussion topics as read

rn/Teacher/src/modules/courses/__tests__/courses-reducer.test.js, rn/Teacher/src/modules/courses/courses-reducer.js
refs: MBL-13589
This issue did not affect production builds because redux state
in production is not frozen where as in debug it is
=> Fix favoriting and unfavoriting courses for the dashboard

CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsConstants.swift, rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher.xcodeproj/xcshareddata/xcschemes/Teacher.xcscheme, rn/Teacher/ios/TeacherTests/Annotations/CanvadocsConstantsTests.swift
refs: MBL-13579
Test plan:
* View a submission in Teacher app
* Draw using the ink tool (probably best to write a sentence)
* Tap Done
* View the submission again
* The annotations should look the same as they did when you drew them
=> Disable natural annotation drawing in Speed Grader

Core/Core/Models/Course.swift, Parent/Parent/Course/CourseDetailsViewController.swift
refs: MBL-13197
Test plan:
in course details:
1. go to a course with a front page set.  Make sure homepage tab is shown but not summary or syllabus.
2. go to a course with a syllabus set as front page.  Make sure syllabus tab and summary loads
3. go to a course with no front page set or syllabus and make sure syllabus or summary tab or homepage do not show.
=> fetch course front page on course details load

rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderTests.swift
refs: MBL-13641
I ran Teacher UI tests locally with a clean install to make sure the tutorial gets dismissed. It also passed on a subsequent run when the tutorial does not appear.
=> Fix SpeedGrader tests

Core/Core/API/APICourseRequestable.swift, Core/CoreTests/API/APICourseRequestableTests.swift, Core/CoreUITests/CoreUITestCase.swift
refs: MBl-13641
I would prefer to always include observed_users so I mocked in in the base class helper so that UI tests still pass.
**Test plan:**
* Log in as narmstrong > `o` in Parent app
* Enable parent3 in experimental features
* Tap a course to view grades
* Assignment and total grades should load
=> Fix Parent grades

Core/Core/Grades/GradesViewController.swift
refs: MBL-13612
getting an empty / faulted core data grading period
```
po print(gp)
<Core.GradingPeriod: 0x600000a30910> (entity: GradingPeriod; id: 0xeffeeed6f1635c1f <x-coredata://B326FF37-AE35-494C-85BF-6738F22883B1/GradingPeriod/p30>; data: {
assignments = "<relationship fault: 0x6000028b3020 'assignments'>";
courseID = 1;
id = nil;
title = nil;
})t``
Test plan:
1. go to grades
2. clear filter
3. filter by a different grading period
4. make sure there are results that can be seen and that it does not crash
=> fix filter by grading period

scripts/run-nightly-tests.sh
Because apparently Xcode needs it
nightly build: https://app.bitrise.io/build/4feb3fd4fbb2afd3
refs: none
affects: none
=> Allow tests runs with no test cases

Core/Core/Router/Route.swift, Parent/Parent/Details/CalendarEventDetailsViewController.swift, Parent/Parent/Routes.swift
refs: MBL-13699
test plan
--------------
1. go to parent app
2. login with observer
3. go to student that has a syllabus and a summary with a calendar event
4. click on the calendar event.  make sure user is show a native detail view and not routed to some web page in core webview.
=> fix calendar event button action from parent summary tab on grades view

Core/Core/Grades/Grades.swift, Core/Core/Models/Enrollment.swift, Core/CoreTests/Grades/GradesTests.swift
refs: MBL-13698
Test plan:
* View the grades list in the Parent app for a student with a visible total score
* Change the grade of an assignment so that the total score will change
* Pull to refresh the grades list
* The total score should update to the new value
See ticket for one user. You can also use
Account: narmstrong
Observer: o
Student: student8
=> [Parent] Fix refreshing total score on grades page

Core/Core/Grades/GradesCell.xib
refs: MBL-13713
Test plan:
Tap on a course in the Parent app to view the Grades list.
The icons and space around the icons should be the correct size.
=> Fix Grades list icons

Core/Core/Pages/PageList/PageListViewController.storyboard, Core/Core/Pages/PageList/PageListViewController.swift, Core/CoreTests/Pages/PageList/PageListViewControllerTests.swift
refs: MBL-13537
test plan
-----------------
did replace front page view tapGesture with a UIButton.  So also test student that able to to navigate to front page via pages.
=> render tests for pages list

Student/Canvas/Calendar/UI/View/CalendarDaysOfWeekView.swift, Student/Canvas/Calendar/UI/View/CalendarView.swift, Student/StudentUnitTests/Calendar/CalendarMonthViewControllerTests.swift
refs: MBL-12428
Test plan:
* Navigate the student calendar with Voice Over on
* Use header navigation to swipe up and down between months (note you have to scroll with three fingers once to get more calendars to load. I don't know why. Might be a collection view optimization or something)
* Week day symbols at the top should read the full week day
* The year 2020 should not read "twentieth twenty"
=> Fix Calendar a11y

Core/Core/Views/CoreWebView.swift
properly encodes the localized launch text so translations can't break the js.
refs: MBL-13733
release note: Fixed an issue with assignment descriptions in French
=> Fix French web view resizing

Core/Core/Profile/ProfilePresenter.swift
Presenter used to be in apps, but moved to Core. The strings were still being looked up in the main bundle instead of in Core.
refs: MBL-13734
release note: Fixed an issue with translations in global menu
=> Fix translations on global nav

Parent/Parent/Course/CourseDetailsViewController.swift, Parent/ParentUnitTests/.swiftlint.yml, Parent/ParentUnitTests/Course/CourseDetailsViewControllerTests.swift, Parent/ParentUnitTests/ParentTestCase.swift, Student/StudentUnitTests/StudentTestCase.swift
refs: MBl-13778
release note: Fixed a bug that would cause the syllabus to show when it should not be shown
Test plan:
* Log in to Parent app as `o` on narmstrong
* Select Student Two
* _Fight Club_ should not show syllabus
* _Modules_ course should show the Syllabus
* _CS 1400_ should not show the syllabus but should show Front Page
=> Hide syllabus if it's not Home and disabled

rn/Teacher/src/modules/inbox/__tests__/reducer.test.js, rn/Teacher/src/modules/inbox/components/ConversationMessageRow.js, rn/Teacher/src/modules/inbox/components/__tests__/ConversationMessageRow.test.js, rn/Teacher/src/modules/inbox/reducer.js
refs: MBL-13754
release note: Fixed a bug when tapping on user avatars in Inbox
Test plan: See [ticket](https://instructure.atlassian.net/browse/MBL-13754)
Apparently we can't trust the `context_code` in the conversation payload because in this case the ID was completely wrong.
=> Fix context cards from Inbox

Core/Core/Grades/Grades.swift
There was timing issue where the main thread might access a Store that hasn't performed a fetch yet. This should make the operation synchronous so to avoid the crash.
Test plan:
View a course in Parent then immediately tap the Reply icon to compose a message. The app should not crash.
=> Fix a crash in GradesViewController

Core/Core/Models/Course.swift, Core/Core/Use Cases/GetConversationCourses.swift, Core/CoreTests/Login/LoginWebViewControllerTests.swift, Core/CoreTests/Models/CourseTests.swift, TestsFoundation/TestsFoundation/Fixtures/API/APICourseFixture.swift
refs: MBL-13788
Test Plan: see ticket for credentials
- In the inbox for the user the course CS1400
should show up multiple times.
- Ignore blank CS 2810 student name, this is
just bad data from the api
=> Fix course action sheet from showing same course twice

Student/StudentUITests/Modules/ModulesTests.swift
Ticket to re-enable: MBL-13814
refs: none
=> disable testUnlockModuleItemWithPrerequisiteModule

CanvasCore/CanvasCore/Persistence/Table View/ColorfulTableViewCell.swift, Core/Core/Router/Router.swift, Core/CoreTests/Router/RouterTests.swift, Student/StudentUITests/Modules/ModulesTests.swift
refs: MBL-13783, MBL-13814
[run-nightly]
Adds a check for accessing locked module items to cover case C3647962.
```swift
XCTAssertFalse(ModulesDetail.moduleItem(index: 0).isEnabled)
```
Also fixes the flakiness by mocking `GetModulesRequest` after tapping
into the module item. This is necessary because the item locked status
will depend on the `state` of the parent module.
=> Fix and enhance Modules UI test

Core/Core/Grades/GradesViewController.storyboard, Core/Core/Grades/GradesViewController.swift, Core/Core/Views/HorizontalMenuViewController.swift, Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift, Core/CoreTests/Grades/GradesViewControllerTests.swift, Core/CoreTests/Views/HorizontalMenuViewControllerTests.swift
refs: MBL-13821
release note: Fixed bug where loading spinners would stop animating while loading
Test Plan:
- Open a course with a syllabus
- While the grades list is loading quickly swipe to
the syllabus and then back to the grades list
- The activity indicator should continue to animate
- Pull to refresh
- Quickly switch to the syllabus view and back
- The refresh control should still be animating
=> Resume activity indicator animations after page change

Parent/Parent/Dashboard/Alerts/AlertsListViewController.swift, Parent/Parent/Details/AccountNotificationViewController.swift, Parent/Parent/Details/AnnouncementDetailsViewController.swift, Parent/Parent/Details/AssignmentDetailsViewController.swift, Parent/Parent/Details/CalendarEventDetailsViewController.swift
refs: MBL-13822
release note: Better display details about alerts
test plan:
- Go to the list of alerts for a student
- Tap on alerts, they should all push instead of modal
=> Push alert detail screens and not modal

Core/Core.xcodeproj/project.pbxproj, Core/Core/Profile/ProfilePresenter.swift, Core/Core/Profile/ProfileViewController.swift, Core/CoreTests/Profile/ProfileViewControllerTests.swift, Parent/Parent/Dashboard/DashboardViewController.swift
Ensured badge in profile drawer is electric
- if it were used in Teacher or Student it would match branding
Set alert tab bar item to use context badge color
Menu icon badge was already correct
refs: MBL-13801
=> Polish badge colors in Parent

Core/Core/Views/HorizontalScrollingStackview.swift, Parent/Parent/Conversations/ConversationDetailCell.swift, Parent/Parent/Conversations/ConversationDetailViewController.storyboard, Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift
refs: MBL-13774
Test plan
---------------
Messages with 1 or 2 attachments should layout correctly.  Before this fix, if there was 2 attachments, there was a big space in between attachments.  No longer!
=> Fix attachments layout on message details when there are 1 or 2 attachments

Core/Core/Conversations/APIConversation.swift, Core/Core/Conversations/CreateConversation.swift, Core/CoreTests/Conversations/CreateConversationTests.swift
refs: MBL-13862
test plan:
- When you compose a new message from the conversation
list
- when you land back on the conversation list with the
new message, that message should have the course name
in the cell as the gray secondary text in the cell
=> Attach contextName on conversation creation

Core/Core/LTI/LTITools.swift, Core/CoreTests/LTI/LTIToolsTests.swift, TestsFoundation/TestsFoundation/Router/TestRouter.swift
refs: none
Test plan:
* On an iPad running iOS 13
* narmstrong : s
* Dashboard > CS 1400 > Assignments > Clear filter > Google Cloud Assignment
* Launch External Tool
* Should be full screen
=> Make Google LTIs full screen on iPadOS

Core/Core/AudioVideo/AudioPlayerViewController.swift, Core/Core/Files/File.swift, Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/Models/FileTests.swift, Core/CoreTests/Models/SubmissionTests.swift, Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/Conversations/ConversationDetailCell.swift, Parent/Parent/Conversations/ConversationDetailViewController.storyboard, Parent/Parent/Conversations/ConversationDetailViewController.swift, Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift, Student/SubmitAssignmentTests/SubmitAssignmentPresenterTests.swift
Audio comments & attachments look like other files, but open a fullscreen AVPlayer when you tap.
Video comments & attachments get an inline AVPlayer that automatically goes fullscreen when you tap to play.
refs: MBL-13773
=> Show media comments in conversation messages

Core/Core/Profile/ProfileViewController.swift, Parent/Parent/Conversations/ComposeRecipientsView.swift, Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
refs: MBL-13787
test plan:
- tapping in the recipients view should expand and collapse it
- If there are more than one recipients and the view is collapsed
it will show the additional number of recipients label
=> Expand and collapse recipients view

Core/Core/API/APISearchRecipient.swift, Core/Core/Conversations/APIConversationRecipient.swift, Core/Core/Conversations/ConversationMessage.swift, Core/Core/Conversations/ConversationParticipant.swift, Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Models/SearchRecipient.swift, Parent/Parent/Airwolf/Model/Airwolf.xcdatamodeld/Airwolf.xcdatamodel/contents, Parent/Parent/Airwolf/Model/Student/Student.swift, Parent/Parent/Conversations/ComposeRecipientsView.swift, Parent/Parent/Conversations/ComposeReplyViewController.swift, Parent/Parent/Conversations/ConversationCoursesActionSheet.swift, Parent/Parent/Conversations/ConversationDetailCell.swift, Parent/Parent/Conversations/EditComposeRecipientsViewController.swift, Parent/Parent/Dashboard/DashboardViewController.swift, Parent/Parent/Settings/SettingsObserveeCellViewModel.swift, Parent/Parent/Thresholds/StudentSettingsViewController.swift, Parent/ParentUnitTests/Conversations/ComposeReplyViewControllerTests.swift, Parent/ParentUnitTests/Conversations/ConversationCoursesActionSheetTests.swift, Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift, Parent/ParentUnitTests/Conversations/EditComposeRecipientsViewControllerTests.swift, TestsFoundation/TestsFoundation/Fixtures/API/APISearchRecipientFixture.swift
refs: MBL-13764
release note: Added support for user pronouns
Test plan:
* Log in to Parent > narmstrong > o
* Pronouns should show for Student 1 in the following places:
- Dashboard: Student Picker and Nav title
- Manage Children > Children list
- Manage Children > tap Student1 > Nav title
- Inbox > Tap Conversation ("Test Push Notification") > to and from labels
- Inbox > Compose > Course picker > Student name below course
- Compose > Edit recipients > Should show in the picker > Select Student 1 > Should show in the recipient pills
=> Add pronouns to Parent

Core/Core/Conversations/APIConversationRecipient.swift, Parent/Parent/Conversations/ComposeRecipientsView.swift, Parent/Parent/Conversations/ComposeReplyViewController.swift, Parent/Parent/Conversations/ComposeViewController.storyboard, Parent/Parent/Conversations/ComposeViewController.swift, Parent/Parent/Conversations/ConversationDetailCell.swift, Parent/Parent/Conversations/ConversationDetailViewController.storyboard, Parent/Parent/Conversations/ConversationListCell.swift, Parent/Parent/Conversations/ConversationListViewController.storyboard, Parent/Parent/Conversations/ConversationListViewController.swift, Parent/ParentUnitTests/Conversations/ConversationListViewControllerTests.swift
Make each text field a heading on compose to easily navigate
Text fields have proper a11y labels
Recipients field is auto expanded when VO is on
Close edit recipients focuses edit button
Made compose button a header for easier navigation
Made reply button a header for easier navigation
Made the message cells on a conversation have better a11y text
refs: MBL-13864
=> Improve accessibility in inbox

Parent/Parent/Conversations/ComposeViewController.swift, Parent/Parent/Conversations/ConversationCoursesActionSheet.swift, Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
refs: MBL-13820
* Added course name as subheader to Compose
* Centered spinner in Compose > course picker
=> Inbox polish

Parent/Parent/Conversations/ComposeViewController.swift, Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
refs: none
Test plan:
* Compose a new message in Inbox
* Don't add a body
* Attach a file
* While the file is uploading, type some text
* Send button should be enabled after the file uploads
=> Fix updating Send button with attachments

Core/Core/Conversations/APIConversation.swift, Core/Core/Conversations/CreateConversation.swift, Core/CoreTests/Conversations/APIConversationTests.swift, Core/CoreTests/Conversations/CreateConversationTests.swift, Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
=> Fix attaching to new conversation

Core/Core.xcodeproj/project.pbxproj, Core/Core/Conversations/APIConversationRecipient.swift, Core/Core/Conversations/SearchRecipient.swift, Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
Since the whole API object equality/hashing was used, we needed both name & fullname to be persisted in CoreData. Also the display name should always be used rather than the full name.
refs: MBL-13942
=> Fix mismatch in recipients selected

Core/Core/Use Cases/GetConversationCourses.swift
It does not look like any actual observed student enrollments are missing
refs: MBL-13940
=> Remove blank course

Core/Core/Extensions/NSPredicateExtensions.swift, Core/Core/Store/Scope.swift, Core/Core/Use Cases/GetCourses.swift, Core/CoreTests/Use Cases/GetCoursesTest.swift
Ordering only by name caused the course picker in the share extension to
appear to switch courses randomly.
refs: MBL-13933
release note: Fixed a bug that would cause the course selection to change in the share extension
Test plan: See [ticket](https://instructure.atlassian.net/browse/MBL-13933)
=> Order courses by name and ID

rn/Teacher/src/modules/submissions/list/__tests__/get-submissions-props.test.js, rn/Teacher/src/modules/submissions/list/get-submissions-props.js
refs: MBL-13922
release note: Fixed an issue with loading submissions with inactive enrollments
Test plan:
* See [ticket](https://instructure.atlassian.net/browse/MBL-13922)
* Eugene Barnes should load when you tap Ethal Boone from the submissions list
=> Exclude inactive enrollments in Speed Grader

Core/Core/API/AssignmentListRequestable.swift, Core/Core/Extensions/UIImageInstIconsExtensions.swift, Core/Core/Models/Assignment.swift, Core/Core/Models/Submission.swift, Core/Core/Models/SubmissionType.swift, Core/CoreTests/Models/AssignmentTests.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
Page assignments are new to me. I don't think this should be a thing but the
web does display this page in the assignments list so /shrug.
The assignment object has no reference to the page so we have no way of knowing to
direct to the page or to load the page body so we load a weird assignment details
screen for assignment pages /shrug.
refs: MBL-13880
release note: Fixed a bug that would prevent the assignments list from loading after unlocking a mastery path
Test plan:
* Log in as the user in [the ticket](https://instructure.atlassian.net/browse/MBL-13880) and follow the steps to get to the Assignments page
* The Assignments page should load
=> Handle page assignments

rn/Teacher/src/modules/speedgrader/components/Header.js, rn/Teacher/src/modules/speedgrader/components/__tests__/Header.test.js, rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/Header.test.js.snap, rn/Teacher/src/modules/submissions/list/SubmissionRow.js, rn/Teacher/src/modules/submissions/list/__tests__/SubmissionRow.test.js, rn/Teacher/src/modules/submissions/list/__tests__/__snapshots__/SubmissionRow.test.js.snap
refs: MBL-13893
release note: Fixed a bug that could allow viewing users when grading anonymously
Test plan: Steps in [ticket](https://instructure.atlassian.net/browse/MBL-13893)
=> Disable avatar presses when anonymous

rn/Teacher/src/modules/submissions/list/SubmissionList.js, rn/Teacher/src/modules/submissions/list/__tests__/SubmissionList.test.js
refs: MBL-13889
release note: Fixed a but that would cause the wrong submissiont to load in Speed Grader
Test plan:
* See steps in [ticket](https://instructure.atlassian.net/browse/MBL-13889)
* Submissions list should now be ordered from lowest number to highest
* Tapping any submission row should load the correct on in SG
=> Fix sort order of submissions list

Core/Core/AppEnvironment/SessionDefaults.swift, Core/Core/People/APIUser.swift, Core/Core/Views/CoreWebView.swift, Core/CoreTests/Views/CoreWebViewTests.swift, Parent/Parent/ParentAppDelegate.swift, TestsFoundation/TestsFoundation/Fixtures/API/APIUserFixture.swift
refs: MBL-13884
release note: Disables links in web views if the setting is set in Canvas
Test plan:
* narmstrong.beta.instructure.com > s
* CS 1400 > Front Page > Tap 'Modules' link
* URL should load modally in a web view controller
* Try to tap a link to a module item or use course navigation to get around
* Links should not work
* twilson.beta.instructure.com > Observer1
* Assignment Overrides > Syllabus
* Tap 'Assignments' link
* URL should open in SFSafari
* Links should be tappable
=> Limit web access in Parent if flag set

Parent/Parent/Dashboard/Calendar/CalendarDaysViewController.swift, Parent/Parent/Dashboard/Calendar/CalendarViewController.swift, Parent/ParentUnitTests/Dashboard/Calendar/CalendarDaysViewControllerTests.swift, Parent/ParentUnitTests/Dashboard/Calendar/CalendarViewControllerTests.swift
try to keep the same selected date if possible in expanded calendar
otherwise pick same day of month, or same day of week in collapsed.
refs: MBL-13902
=> Select a day immediately when paging the calendar

rn/Teacher/src/canvas-api/apis/submissions.js, rn/Teacher/src/modules/speedgrader/comments/CommentInput.js, rn/Teacher/src/modules/speedgrader/comments/CommentsTab.js, rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentInput.test.js, rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentsTab.test.js, rn/Teacher/src/modules/speedgrader/comments/__tests__/pending-comments-reducer.test.js, rn/Teacher/src/modules/speedgrader/comments/pending-comments-reducer.js
refs: MBL-13966
release note: Fixed adding comments in Speed Grader
Test plan:
* Add a new comment in Speed Grader, ensure it does not Whoops out
* Add a new media comment and make sure it all works
* narmstrong > s
* CS 1400 > Assignments > File Upload > Student 1 > Comments > Add a new text, audio, and video comment
=> Fix adding new comments in Speed Grader

Core/Core/Use Cases/GetPage.swift, Core/CoreTests/Pages/PageDetails/PageDetailsViewControllerTests.swift, Core/CoreTests/Use Cases/GetPage.swift
refs: MBL-13960
release note: Fixed loading the course Home page
Test plan:
* Turn on new_page_details feature flag and make sure a course Home page loads when it is set to Front page
* See [ticket](https://instructure.atlassian.net/browse/MBL-13960)
* Or narmstrong > s > CS 1400 > Home
=> Fix Home when front page

CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
I've added this to the list of future UI tests. I don't think it's worth
adding a unit test for this right now.
refs: MBL-13970
release note: Fixed submitting quizzes with unanswered questions
Test plan:
* See [ticket](https://instructure.atlassian.net/browse/MBL-13970)
=> Fix non-native quizzes with unanswered questions

Parent/Parent/Dashboard/Calendar/CalendarViewController.swift
=> Improve animation in calendar

.gitattributes, scripts/build_automation/suggest-lint-fix.swift
For some reason the old version was throwing an error about JSON fragments only on bitrise
refs: none
affects: none
=> Maybe fix lint fix script. Also make pbxproj merging better

Parent/Parent/Routes.swift, Parent/ParentUnitTests/RoutesTests.swift
test plan:
twilson > Assignment Overrides has a link to the calendar in the syllabus body.
Clicking that should open the new calendar if the flag is enabled, same as other links there work.
Deep links to /calendar should work as well, opening a modal as is typical.
refs: MBL-13906
=> Add calendar deep link

Core/Core/AppEnvironment/Clock.swift, Core/Core/Extensions/DateExtensions.swift, Core/CoreTests/Extensions/DateExtensionsTests.swift
=> Add endOfMonth and startOfMonth helpers

Core/Core/Models/SubmissionType.swift, Core/Core/Models/UTI.swift, Core/CoreTests/Models/SubmissionTypeTests.swift, Core/CoreTests/Models/UTITests.swift
refs: MBL-13975
release note: Fixed a bug with submitting iWork files
Test plan:
* Install Pages, Numbers, and Keynote on your device
* Create a new file for each app
* Use the Files app to copy the files from iCloud Drive to On My Device
* Submit to an assignment that restricts file extensions to iWork
extensions (see [ticket](https://instructure.atlassian.net/browse/MBL-13975) and
also narmstrong > s > CS 1400 > Assignments > iWork
* Verify that you can select the iWork files from both On My Device and
iCloud Drive
=> Fix submitting iWork from device

Student/Canvas/Modules/ModuleViewModel.swift, Student/StudentE2ETests/Modules/ModulesE2ETests.swift
[run-nightly]
refs: MBL-14024
release note: Fixed "locked until date" message appearing on unlocked modules
=> Remove "locked until date" message from unlocked modules

Core/Core/Planner/PlannerListViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift
Don't modify contentInset while dragging, instead add a bottom inset to ensure you can scroll up to collapse calendar.
refs: MBL-14029
=> Fix push to collapse bugs

Core/Core/Planner/CalendarDaysViewController.swift, Core/Core/Planner/CalendarViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/CoreTests/Planner/CalendarDaysViewControllerTests.swift, Core/CoreTests/Planner/CalendarViewControllerTests.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift
[run-nightly]
Also, dims days in other months.
refs: MBL-14061
Test plan:
* Swipe around in Calendar, expanding and collapsing the month view
along the way
* Selecting a day in a different month should transition to that month
* Select January 31
* Collapse to week view
* Select February 1
* Expand to month view
* The month of February should be shown
* Days in other months should be dimmed
=> Always show month of selected day in Planner

Core/Core/Planner/PlannerViewController.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift
refs: MBL-14072
Test plan:
* Delete the app
* Log in as twilson > observer1
* February 20 should show 3 events
* Tap Calendars to filter
* Remove all `AG` calendars
* Feb 20 should only show 2 events
* Add back `AG` calendars
* Feb 20 should show all 3 events again
=> Fix planner filtering

Core/Core/AppEnvironment/SessionDefaults.swift, Parent/Parent/Dashboard/DashboardViewController.swift, Parent/Parent/ParentAppDelegate.swift, Parent/Parent/UserDefaults/ColorScheme.swift, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
refs: MBL-14059
Test plan
1. Login with twilson: observer1
2. set student to something other than 1st default student
3. force kill the app, restart
4. default user selected should be the user selected in step 2
=> Persist current student

Core/Core/API/APIGraphQLRequestable.swift, Core/Core/API/APIPostPolicyRequestable.swift, Core/Core/API/AssignmentListRequestable.swift, Core/CoreTests/.swiftlint.yml, Core/CoreTests/API/APIGraphQLRequestableTests.swift, Core/CoreTests/API/APIPostPolicyRequestableTests.swift, Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift, Student/StudentUITests/Assignments/IPadAssignmentsTests.swift, Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift, TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift, rn/Teacher/ios/Submissions/PostGradesPresenter.swift, rn/Teacher/ios/TeacherUITests/Submissions/AssignmentPostPolicyTests.swift
variables are now passed as graphQL variables, for easier mocking
[run-nightly] [run-ipad-tests]
refs: none
affects: none
=> Force GraphQL requests to have a static query

rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleItemCell.swift, rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.storyboard, rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.swift, rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleSectionHeaderView.xib, rn/Teacher/ios/TeacherTests/Modules/ModuleListViewControllerTests.swift
refs: MBL-14035
Test plan:
* Turn on VO in Teacher modules
* VO should say published and expanded states
* Published icons should all be aligned
=> Fix a11y in Teacher modules and align icons

Core/Core/API/AssignmentListRequestable.swift, Core/CoreTests/API/AssignmentListRequestableTests.swift
(Though really this means that the graphql schema has the wrong types...)
refs: none
affects: none
=> Fix AssignmentFilter for graphQL

Core/Core/Grades/GradesViewController.swift, Parent/Parent/Course/CourseDetailsViewController.swift
refs: MBL-14100
release note: Fix quiz icon always showing locked
Testing
quiz icons in grades on parent should not show locked.
=> Show quiz icon in parent grades list, assignments come back as `lockedForUser` in parent

Core/Core/Views/CircleProgressView.swift, Core/CoreTests/Views/CircleProgressViewTests.swift, Parent/Parent/Conversations/ComposeReplyViewController.swift, Parent/Parent/Conversations/ComposeViewController.swift, Parent/ParentUnitTests/Conversations/ComposeReplyViewControllerTests.swift, Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
Also fixed a bug where CircleProgressView wouldn't animate.
refs: MBL-14082
release note: Fixed an issue where you could accidentally send duplicate messages
=> Make sure you can't hit send more than once

Core/CoreUITests/Profile/UserFilesTests.swift, Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift, Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift, scripts/build_automation/bitrise_workflows/tests.yml
Bitrise is currently having problems with SIP on our xcode stack, so disable the tests that need a microphone.
Will add ticket to re-enable
[ignore-commit-lint] [run-nightly]
=> disable microphone-related tests

Core/Core/Planner/CalendarViewController.swift, Core/Core/Planner/GetPlannerCourses.swift, Core/Core/Planner/PlannerFilterViewController.storyboard, Core/Core/Planner/PlannerFilterViewController.swift, Core/Core/en.lproj/Localizable.stringsdict, Core/CoreTests/Planner/CalendarViewControllerTests.swift, Core/CoreTests/Planner/PlannerFilterViewControllerTests.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift, Core/CoreUITests/Planner/Planner.swift, Parent/ParentE2ETests/PlannerTests.swift, Student/Student.xcodeproj/xcshareddata/xcschemes/NightlyTests.xcscheme, scripts/build_automation/bitrise_workflows/tests.yml
Displays course name instead of code to match Android & other parts of the app
[run nightly]
refs: MBL-14079
=> Add a11y & ui tests for planner filter

Core/Core/Planner/GetPlannables.swift, Core/Core/Planner/Plannable.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/Store/UseCase.swift, Core/CoreTests/Planner/GetPlannablesTests.swift, Core/CoreTests/Use Cases/UploadManagerTests.swift, TestsFoundation/TestsFoundation/Database/TestPersistence.swift, TestsFoundation/TestsFoundation/Fixtures/Model/PlannableFixture.swift
refs: MBl-14117
affects: parent, student
Test plan:
- Pull to refresh on a day that has one or more events
- Do it many many times (10 or more)
- You should not see any duplicate events
=> Prevent duplicate events in Planner

Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/Core/Login/LoginQRCodeTutorialViewController.storyboard, Core/Core/Login/LoginStartViewController.swift, Core/CoreTests/Login/LoginStartViewControllerTests.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/CanvasAppDelegate.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-14134
Test plan:
* Log into Firebase Console > Remote Config
* qr_code_login_enabled should be set to `false`
* Install the Student app and launch and logout
* QR Login button should be hidden
* Change the default value for qr_code_login_enabled remote config to `true` and `Publish Changes`
* Relaunch the Student app
* QR Login button should be visible and functional
* Change the default value for qr_code_login_enabled back to `false`
* QR Login button should no longer be visible
=> Remote config for QR Login

Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift, Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift
refs: MBL-14153
release note: Fixed a crash in Assignments
Test plan:
* On iPad, view Assignments in a course with lots of assignments
* Try to tap Back before the initial load finishes
* The should not crash
* Do it lots of times
* Try really hard to go back before the initial load
=> Fix a crash in assignments

Core/Core/DocViewer/DocViewerViewController.swift, Core/CoreTests/DocViewer/DocViewerViewControllerTests.swift
refs: none
release note: Fixed a crash when trying to share a pdf before it has loaded
=> Fix crash in trying to share before pdf is loaded

scripts/build_automation/bitrise_workflows/tests.yml
=> Put beta tests in the same timezone as nightly

Student/Canvas/Modules/Module Items/ModuleItemViewModel.swift
You can still go into the assignment details, which will also tell you it is locked.
refs: MBL-14185
release note: Fixed missing icon for locked assignments in a module
=> Still show lock icon for locked assignments

Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
=> Fix PSPDFKit upgrade regressions

Core/Core/Conferences/APIConference.swift
refs: MBL-14221
release note: Fixed a bug that would prevent conferences from loading
Test plan: see ticket https://instructure.atlassian.net/browse/MBL-14221
=> Handle null conference recording length

scripts/build_automation/bitrise_workflows/parent.yml, scripts/build_automation/bitrise_workflows/student.yml, scripts/build_automation/bitrise_workflows/teacher.yml, scripts/build_automation/build-link.swift
Adds permanent links and QR codes to the last successful master build, so that installing from master is as easy as installing from a PR.
Links can be found at https://instructure.atlassian.net/wiki/spaces/MOBILE/pages/822378551/Latest+master+QR+install+links
(teacher won't work properly because I retriggered a build too early, but just ignore that)
=> Master build QR links

Student/Student/Routes.swift, rn/Teacher/src/modules/dashboard/LiveConferenceRow.js, rn/Teacher/src/modules/dashboard/__tests__/LiveConferenceRow.test.js, rn/Teacher/src/routing/register-screens.js
refs: MBL-14224
Test plan:
* narmstrong.beta.instructure.com > s > Dashboard > Tap live conference
* Should go directly to live conference in safari, not conference details
=> Launch directly to live conference from dashboard

Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
refs: MBL-14225
release note: Fixed crash in quizzes when uploading a file.
testing
1. go to twilson 
2. in quizzes questions course
3. assignments > Geometry (last assignment)
4. click resume quiz
5. Resume quiz again
6. on first question, click "Choose a File"
If this is fixed it should show a little action sheet for selecting an upload, if it's broken, it will crash at this point.
=> Fix crasher with quiz file upload questions

Core/Core/Extensions/UIImageViewExtensions.swift, Core/CoreTests/Extensions/UIImageViewExtensionsTests.swift, Core/CoreTests/Grades/GradeListViewControllerTests.swift
Use mocked network to make most things synchronous.
Only one svg test waits for a snapshot, to ensure that works properly
refs: MBL-13827
affects: none
=> Fix ImageViewExtensionTests

Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
This no longer tries to assert that the webview finishes loading, but we probably don't need to test that WKWebView updates estimatedProgress correctly anyway.
That seemed like a better compromise than simply extending the wait time past 5 seconds.
refs: MBL-13825
affects: none
=> Remove waiting for webview from testSVG

rn/Teacher/src/modules/discussions/details/DiscussionDetails.js, rn/Teacher/src/modules/discussions/details/__tests__/DiscussionDetails.test.js
RN 0.62.2 [broke requestIdleCallback](https://github.com/facebook/react-native/issues/28602).
refs: MBL-14307
Test plan:
* Viewing discussion details should automatically mark replies as read
=> Fix marking discussions as read on scroll

Parent/ParentUITests/InboxTests.swift
The signal before showRoot is gone now. I'm not sure about the prior CoreData issue, but the tests ran successfully on my machine many times.
[run-nightly]
refs: MBL-14180
affects: none
=> Re-enable testReplyWithAttachments

Core/Core/Router/Router.swift, Core/CoreTests/Router/RouterTests.swift, Student/Student/CanvasAppDelegate.swift, Student/Student/Routes.swift
refs: MBL-14220, MBL-14325
release note: Fixed a bug that could cause push notifications to open up in Safari
Test plan:
* Check out the changes locally (so you can simulate a push notification)
* Log in as narmstrong > s
* Drag the attached `push.apns` file over the simulator and tap the notification
* Should launch the course details
=> Fix push notifications for vanity domain users

CanvasCore/CanvasCore/PDF/CanvadocView.swift
refs: MBL-14345
release note: Fixed a bug that could cause Speed Grader to close when swiping between submissions
Something in PSPDFKit changed to cause this little hack to do very bad
things. Swiping between submissions where one or more submission uses
PSDFKit would cause Speed Grader to get dismissed.
I couldn't get any orphaned popovers to hang around so.. i dunno.
Test plan:
I was able to repro consistently with this:
- narmstrong > t
- CS 1400 > Assignments > Annotate This > All Submissions
- Tap the first user, swipe left 6+ times
- Speed Grader should not close all on its own
=> Fix a bug in SpeedGrader

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/APIModule.swift, Core/Core/API/APIModuleRequestable.swift, Core/Core/Models/Assignment.swift, Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Models/MasteryPath.swift, Core/Core/Models/ModuleItem.swift, Core/Core/Modules/Mastery Paths/MasteryPathAssignmentCell.xib, Core/Core/Modules/Mastery Paths/MasteryPathAssignmentSetDivider.xib, Core/Core/Modules/Mastery Paths/MasteryPathViewController.storyboard, Core/Core/Modules/Mastery Paths/MasteryPathViewController.swift, Core/Core/Modules/ModuleList/ModuleListViewController.swift, Core/Core/Modules/ModuleList/ModuleStore.swift, Core/CoreTests/Modules/MasteryPathViewControllerTests.swift, Core/CoreTests/Modules/ModuleListViewControllerTests.swift, Podfile.lock, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, TestsFoundation/TestsFoundation/Fixtures/API/APIModuleFixture.swift, TestsFoundation/TestsFoundation/Router/TestRouter.swift
refs: MBL-14157
Test plan:
* narmstrong > student15 > CS 1400 > Modules > Mastery Path
* Select a path > Tap Back
* Module list should reload with the selected path available
* **Note:** your position in the list might get messed up after
selecting a list due to the list reloading. I will retain the scroll
position in a separate commit
=> Add selecting mastery paths

Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Models/ModuleItem.swift, Core/Core/Modules/ModuleList/ModuleListViewController.storyboard, Core/CoreTests/Modules/ModuleItems/ModuleItemDetailsViewControllerTests.swift
refs: MBL-14347
release note: Fixed a bug in Modules that would cause the screen to refresh infinitely
Test plan:
* View a module item in Teacher app with a `must_view` completion requirement
* narmstrong > t > CS 1400 > Modules > Michael J Scott > Demo 1 (Discussion)
* The module item details screen should not refresh infinitely
=> Fix refresh cycle in Teacher modules

CanvasCore/CanvasCore/Quizzes/Quiz Details/Controllers/QuizTakeabilityController.swift
refs: MBL-14308
release note: Fixed uploading files in quizzes by showing quizzes with file-upload questions in a web view
Test plan:
- see ticket
- quiz should launch in a web view
=> Remove native support for file upload questions

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/APICalendarEvent.swift, Core/Core/API/APICalendarRequestable.swift, Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/Courses/APICourse.swift, Core/Core/Planner/APIPlannable.swift, Core/Core/Planner/CreatePlannerNote.swift, Core/Core/Planner/GetPlannables.swift, Core/Core/Planner/GetPlannerCourses.swift, Core/Core/Planner/Plannable.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/Store/UseCase.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Planner/CalendarDaysViewControllerTests.swift, Core/CoreTests/Planner/GetPlannablesTests.swift, Core/CoreTests/Planner/PlannerFilterViewControllerTests.swift, Core/CoreTests/Planner/PlannerListViewControllerTests.swift, Core/CoreTests/Planner/PlannerNoteDetailViewControllerTests.swift, Core/CoreTests/Planner/PlannerViewControllerTests.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/CanvasAppDelegate.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-14321
release note: Fixed Calendar for manually enrolled observers
Test plan:
* Log in as user from [KNO-403](https://instructure.atlassian.net/browse/KNO-403)
* April 10 and 11 should show planner items
* Use the Calendar filter to remove the only calendar
* April 10 and 11 events should be removed
=> Fix Planner for manually enrolled observers

CanvasCore/CanvasCore.xcodeproj/project.pbxproj, CanvasCore/CanvasCore/React Native Modules/NativeUserDefaults.m, CanvasCore/CanvasCore/React Native Modules/NativeUserDefaults.swift, Core/Core/AppEnvironment/CacheManager.swift, Core/Core/Extensions/NSPersistentContainerExtensions.swift, Core/Core/Extensions/URLExtensions.swift, Core/Core/Profile/ProfileViewController.swift, Core/CoreTests/AppEnvironment/CacheManagerTests.swift, Core/CoreTests/Extensions/URLExtensionsTests.swift, Core/CoreTests/Profile/ProfileViewControllerTests.swift, rn/Teacher/src/modules/dashboard/Dashboard.js, rn/Teacher/test/scripts/jestSetup.js, scripts/coverage/config.json
I had to update the CacheManager to not blow away everything in the
`Bundle.main.appGroupID()` container because that includes shared
UserDefaults which is where `SessionDefault`s are stored including this
flag.
Instead, CacheManager only deletes the newly added `caches/` directory
in the App Group. Core Data files are now stored in that caches
directory instead of at the root.
refs: MBL-14332
release note: Fixed a bug that would cause the 'Show Grades' option to reset
Test plan:
- Checkout the changes locally
- Build and run the app
- From the global nav, toggle 'Show Grades' to On
- Change the build number of Student in Xcode
- Build and run again
- Grades on dashboard should still be shown
=> Fix 'Show Grades' option

Core/Core/Views/CoreWebView.swift
refs: MBL-14354
affects: teacher, student
release notes: Fixed a but that could prevent Studio videos from playing
Test plan:
* Log in to Student as siteadmin
* Masquerade as user 13716 on `jcatibog.instructure.com`
* Course > Pages > new rce test
* Studio video should be playable
=> Fix Studio videos embedded in RCE for non-US

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
=> Show submission on submission details when user has submitted and assignment is locked.

Core/Core/Views/CoreWebView.swift
This hack lives on, unfortunately.
refs: MBL-14360
release note: Fixed loading html files in Pages
=> Fix loading canvas files in iframes in pages

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift
refs: MBL-14392
release note: Fixed file upload status on assignment details page
Test plan:
- narmstrong > s
- Use the Photos app and the Student share extension to submit a photo to the CS 1400 > iWork assignment
- View the iWork assignment in the Student app
- It should display a submission error
=> Fix showing upload status on assignment details

Core/Core.xcodeproj/project.pbxproj, Core/Core/Views/ActivityIndicatorButton.swift, Core/CoreTests/Views/ActivtyIndicatorButtonTests.swift, Parent/Parent/Create Account/CreateAccountViewController.storyboard, Parent/Parent/Create Account/CreateAccountViewController.swift
refs: MBL-14413
Test plan
1. enable parent qr code flag, enable student qr code
2. scan student qr code so it opens parent app create account screen
3. when you click on the `create account` button you should see an activity indicator.
=> Add activity indicator to create account button.

Parent/Parent/Create Account/CreateAccountViewController.swift, Parent/ParentUnitTests/CreateAccount/CreateAccountViewControllerTests.swift
refs: MBL-14413
Test plan
1. when on parent create account screen, click `Already have account, sign in`
2. it should dismiss the modal and take you to the institution login page
=> Show institution login screen when user clicks `Already have account,Sign In` on CreateAccount view

Core/Core/Login/LoginDelegate.swift, Core/Core/Login/LoginStartViewController.swift, Core/CoreTests/Login/LoginStartViewControllerTests.swift, Parent/Parent/ParentAppDelegate.swift
refs: MBL-14413
Test plan:
1. make sure you can still login with qr code from web using the qr code scanner in parent app
2. bring up the parent create account screen using the qr code scanner in parent app
=> Support create account in parent from qr scanner

Core/Core/AppEnvironment/CacheManager.swift, Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/AppEnvironment/CacheManagerTests.swift, Student/Student/CanvasAppDelegate.swift, rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-14258
release note: Optimized storage
Test plan:
* In Student app, view a PDF in course files and add annotations to it.
* Background the app (to trigger `viewWillDisappear`) then force-quit and
relaunch the app
* View the same pdf again, annotations should still be there
Aside from print debugging, it's difficult to tell if the bloat actually
gets removed. For one, you will need [this
build](https://app.bitrise.io/artifact/36705347/p/fe2588d5cd3365e27ac8f4e168a319fc)
or older, then download a file and install this build over it in order
for bloated files to get removed. But even then it's difficult to
verify that the files were removed. The numbers in Storage settings are
not consistent enough.
=> Remove storage bloat

Core/Core/Views/ScannerViewController.swift, Parent/Parent.xcodeproj/project.pbxproj, Parent/Parent/Dashboard/DashboardViewController.swift, Parent/Parent/Dashboard/SelectAddStudentMethodViewController.swift, Parent/Parent/ParentAppDelegate.swift, Parent/Parent/Students/AddStudentController.swift, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
refs: MBL-14174
test plan
---------------
1. login to parent
2. click the add student button on dashboard
3. make sure modal menu is shown and that is shows 2 options, test both
4. disable flag `parentQRCodePairing` and make sure old behavior is still there where just the pairing alert comes up when you click add student
=> Add qr code pairing to parent dashboard

Core/Core/LTI/LTITools.swift, Core/CoreTests/LTI/LTIToolsTests.swift
refs: MBL-14425
Test plan:
- If the builds pass I think we are good
- There won't be any noticeable difference yet. This won't fix the issue
until Quizzes checks for the query param
=> Append platform param to LTI launches

Core/Core/Files/File.swift, Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Use Cases/UploadManager.swift, Core/CoreTests/Conversations/AttachmentCardsViewControllerTests.swift, Core/CoreTests/Files/FilePicker/FilePickerViewControllerTests.swift, Core/CoreTests/Models/FileTests.swift, Core/CoreTests/Use Cases/UploadManagerTests.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift, TestsFoundation/TestsFoundation/API/MockURLSession.swift, TestsFoundation/TestsFoundation/Fixtures/Model/FileFixture.swift
`URLSessionTask.taskIdentifier` is only unique to the URLSession so they are not a reliable
way to uniquely identify a file upload in progress. This will hopefully
prevent issues with files being submitted to the wrong assignments
refs: none
release note: Improved stability of file upload submissions
Test plan:
- Submit to an assignment using a file upload both within the app and
with the share extension
- narmstrong > s > CS 1400 > Assignments > File Upload
=> Use UUID for file uploads

Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
TIL: sometimes an assignment.submission can be `nil`. I didn't think
that was allowed to happen anymore.
refs: MBL-14419
release note: Fixed launching some quizzes from the assignment page
Test plan:
- Log into qa-syd.instructure.com > narmstrong
- course > assignments > assignment > Launch External Tool
- Quiz should launch in SFSafari
=> Fix launching LTI tools without a submission

Core/Core/API/APIURL.swift, Core/Core/Files/APIFile.swift, Core/CoreTests/API/APIURLTests.swift, Core/CoreTests/Files/APIFileTests.swift
refs: MBL-14448
release note: Fixed an issue with loading the To Do list
Test plan: See ticket. To Do list should load without error.
=> Fix To Do list when thumbnail_url is empty string

Core/Core/Discussions/DiscussionDetailsViewController.swift
refs: MBL-14468
Test plan:
- View a discussion item through modules
- It should not reload infinitely
- narmstrong > CS 1400 > Modules > pick any discussion
=> Fix discussion module items in teacher

rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-14461
release note: Fixed launching the app with canvas-teacher://
Test plan:
Go to canvas-teacher:// in safari. Should launch the app without error.
=> Fix deep linking to canvas-teacher://

scripts/build_automation/bitrise_workflows/parent.yml, scripts/build_automation/bitrise_workflows/student.yml, scripts/build_automation/bitrise_workflows/teacher.yml, scripts/build_automation/bitrise_workflows/tests.yml, scripts/coverage/export-coverage.swift
Also, cache carthage HEAD install
test plan: nightly runs normally and coverage information shows up at https://codecov.io/gh/instructure/canvas-ios/branch/MBL-14456
[run-nightly]
refs: MBL-14456
affects: none
=> Merge coverage of nightly builds

scripts/build_automation/bitrise_workflows/tests.yml
test plan: this should trigger nightly on this PR, but not once this PR gets merged, so I guess the testing has to happen after approval... but it's a small change.
=> disable the [run-nightly] hook on master

Core/Core/Files/FilePicker/FilePickerViewController.swift, Core/CoreTests/Files/FilePicker/FilePickerViewControllerTests.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
refs: none
release note: Added the option to submit scanned documents
Test plan:
- Submit to an assignment that accepts image file upload submissions
- Choose the Scanner option from the file picker
- Scan one or more documents
- Submit
- The scanned images should submit successfully
=> Scanned document submissions

Core/Core/Discussions/DiscussionHTML.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
refs: MBL-14500
release note: Fixed discussions for some schools
Test plan:
- Ticket has users that you can masquerade as
- When an account has custom javascript files, the API inserts those
scripts into every discussion reply
- Discussion replies with script tags should load
- For now we strip out the scripts. We can try to load them in the
future
=> Fix discussions with script tags

Parent/Parent/Extensions/CalendarEvent+Submissions.swift
refs: MBL-13430
release note: Fixed label for paper assignments to be "On Paper" instead of "In-Class"
=> Change label from In-Class to On Paper

Core/Core/Modules/ModuleList/ModuleListViewController.swift, Core/CoreTests/Modules/ModuleListViewControllerTests.swift
refs: MBL-14511
Test plan:
- narmstrong > s > CS 1400 > Modules > Empty Module
- Verify you can tap select `This module is empty.` row
=> Disable user interaction on empty module cells

Core/Core.xcodeproj/project.pbxproj, Core/Core/Conversations/APIConversation.swift, Core/Core/Conversations/APISearchRecipient.swift, Core/Core/Conversations/CommonCourse.swift, Core/Core/Conversations/ComposeReplyViewController.swift, Core/Core/Conversations/ConversationParticipant.swift, Core/Core/Conversations/SearchRecipient.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Conversations/ComposeReplyViewControllerTests.swift
Prevents parents from messaging students that they are not observing.
refs: MBL-14389
release note: Inbox privacy improvements
Test plan:
- As a teacher, start a conversation with an observer, the observed user, and
another student (not being observed by observer)
- As the observer, reply-all to the conversation in the parent app
- The message should only be sent to the teacher and the observed child
- You can use the most recent conversation as `o` on `narmstrong`
=> Fix Parent reply-all

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Discussions/DiscussionHTML.swift, Core/Core/Groups/GetGroups.swift, Core/Core/Groups/Group.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
The API returns all course groups when we ask for them, even if the
current user isn't in the group. And all the group topics are included
in the discussion, even those that are not for the current user.
So for child group topics we should only request the groups for the
current user so that we can accurately narrow down which child topic to
show.
refs: MBL-14543
release note: Fixed loading discussions
Test plan:
- Install student from master or prod
- Masquerade as users in ticket
- View the linked discussions
- They should load
=> Fix loading some group discussions

Core/Core/Views/HorizontalMenuViewController.swift, Core/CoreTests/Views/HorizontalMenuViewControllerTests.swift
refs: MBL-14554
release note: Fixed a crash when accessing courses
Test plan:
I couldn't reliably repro on device but I did verify that the test threw
the exception without the fix applied.
=> Fix crash in HorizontalMenuViewController

CanvasCore/CanvasCore/React Native Modules/LTITools.m, Core/Core/Assignments/APIAssignment.swift, Core/Core/Assignments/Assignment.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/LTI/LTITools.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift, rn/Teacher/src/common/LTITools.js, rn/Teacher/src/common/__tests__/LTITools.test.js, rn/Teacher/src/modules/assignment-details/AssignmentDetails.js, rn/Teacher/src/modules/assignment-details/__tests__/AssignmentDetails.test.js
refs: MBL-14482
release note: Fixed launching some LTI tools
Release plan:
- View the assignments from the ticket as a student and a teacher (in
the respective apps)
- Each assignment should launch the correct youtube video (you have to
tap the button to show in a new window)
=> Fix launching LTI assignments when URL re-used

Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
refs: MBL-14581
release note: Fixed a bug when sharing files with annotations
Test plan:
- Annotate on a file
- Tap share > Markdown
- Markdown should have the recent annotations
=> Save pdf document before share

Core/Core/Modules/APIModule.swift, Core/Core/Modules/MasteryPath.swift
refs: MBL-14585
release note: Fixed loading modules in the case that there were Mastery Paths without any assignments linked
Test plan:
- Masquerade as the student from the ticket
- View modules in the course from the ticket
- The second module, _Unit 2: Creative mind_, should load
=> Fix loading certain modules

Core/Core/UIViews/HorizontalMenuViewController.swift, Core/CoreTests/Views/HorizontalMenuViewControllerTests.swift
refs: MBL-14615
release note: Fixed a crash when viewing syllabus
Test plan:
Couldn't repro locally but crash report was pretty obvious.
The test did throw an exception without the fix.
Logs made it clear that it would happen when viewing a course syllabus.
- View a course syllabus
- App should not crash
=> Fix a crash in HorizontalMenu

Core/Core/Files/UploadManager.swift, Core/CoreTests/Files/UploadManagerTests.swift, Core/CoreTests/RichContentEditor/RichContentEditorViewControllerTests.swift
refs: MBL-14573
release note: Fixed uploading videos in Rich Content Editor
Test plan:
- Use the image picker to insert video into rich content for discussions
and text submissions
- Videos should embed without error
=> Fix uploading videos in RCE

Core/Core/Login/LoginWebViewController.swift, Core/CoreTests/Login/LoginWebViewControllerTests.swift
Some auth providers send `?error=false` which would trigger our error
handler.
refs: MBL-14646
release note: Fixed logging in for some institutions
Test plan:
- see ticket for account and credentials
- should login without error
=> Fix login error check

rn/Teacher/src/modules/speedgrader/comments/CommentInput.js
refs: MBL-14590
release note: Fix SpeedGrader comment field sometimes not being cleared
test plan: On a device enable dictation
settings > general > keyboard > "Enable Dictation"
In teacher, go to an assignment, and click on the add comment field
tap the microphone, say something, then without stopping dictation hit send
It should send the message and clear the field
=> Clear comment field after dictating a comment

rn/Teacher/src/modules/courses/user-prefs/UserCoursePreferences.js
truthiness strikes again
refs: MBL-14644
release note: Fix a crash when attempting to change course preferences
=> Fix course preferences if image url is empty string

Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
refs: MBL-14624
release note: Fixed a bug that would appear to allow Edit and Delete buttons for discussion replies when those permissions were disabled
=> Honor discussion permissions for replies

Core/Core/Planner/GetPlannables.swift, Core/Core/Planner/PlannerListViewController.swift, Core/Core/Planner/PlannerViewController.swift, Core/Core/Store/UseCase.swift
The syncContext was added to remove these kinds of races, but pagination re-broke it.
Rather than try to sync the two requests, this exhausts the pagination at request level,
so when each finish they immediately restore anything they reset.
refs: MBL-14610
release note: Fixed an issue with missing events in the planner
=> Fix planner intermittent missing events

Core/Core/AppEnvironment/CacheManager.swift, Core/CoreTests/AppEnvironment/CacheManagerTests.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
The FileDetailsViewController has been using tmp for a while now, and only
annotated pdf are moved to documents. There should be nothing else putting
new files in the documents folder, so the cleanup should no longer be
necessary.
refs: MBL-14415
=> Remove file cleanup at startup

Core/Core/Modules/ModuleItemType.swift
refs: MBL-14675
release note: Fixed an issue preventing some modules with LTI tools from appearing
=> Fix URL parsing for external module urls

Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift, Student/Student/Routes.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/src/modules/speedgrader/SubmissionViewer.js, rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/SubmissionViewer.test.js.snap, rn/Teacher/src/routing/register-screens.js
This also makes links in submissions way more consistent across speedgrader.
refs: MBL-14661
release note: Fixed an issue loading some links inside a submission
=> Fix no-context file links & file details modal from speedgrader

CanvasCore/CanvasCore/ReactNativeModules/DocViewerWrapper.swift
even though a new previewURL was set, the view didn't realize it needed to layoutSubviews() which handles making sure the right document is displayed.
refs: MBL-14702
=> Fix rerendering of new document

Core/Core/Login/LoginFindSchoolViewController.swift, Core/Core/Login/LoginWebViewController.swift, Core/CoreTests/Login/LoginWebViewControllerTests.swift
refs: MBL-14726
release note: Fixed logging in for some institutions
test plan:
- Find My School > search for "mit" > tap Massachusetts Institute of Technology
- Tap MIT Students, Faculty, and Staff
- It should load the next login page within the web view
- A back button should appear at the bottom
- Tapping the back button should take you back in the web view and the back button should disappear
=> Support navigating within login web view

rn/Teacher/ios/TeacherE2ETests/ContextCardE2ETests.swift, rn/Teacher/src/canvas-api-v2/queries/ContextCard.js, rn/Teacher/src/modules/users/ContextCard.js
very surprisingly, no snapshots needed updating
This is now how android does it.
Test plan: [run-nightly] succeeds
refs: MBL-14698
release note: fix submitted assignment count on context card
=> Fix student context card submission count

Core/Core/Modules/ModuleList/ModuleListViewController.swift, Core/CoreTests/Modules/ModuleListViewControllerTests.swift
refs: MBL-14712
release note: Fixed a bug that would allow access to the modules list when it was disabled
test plan:
- see ticket for an example of modules being disabled
- narmstrong > s > CS 1400 > Should be able to access modules from Home page
- Should be able to access Modules from a regular course tab
=> Support disabled modules list

Core/Core/Planner/APICalendarEvent.swift, Core/Core/Planner/GetPlannables.swift, Core/CoreTests/Planner/GetPlannablesTests.swift
refs: MBL-14737
release note: Fixed a bug that could cause duplicate calendar events to show.
test plan:
- see ticket for creds
- sept 18 should only show one event
- it should be the event with "(Parent App Duplicate Test)"
=> Hide hidden calendar events

Parent/Parent/Info.plist, Student/Student/Info.plist, rn/Teacher/ios/Teacher/Info.plist
refs: MBL-14793
release note: Added an option to Settings to allow cross-website tracking to temporarily fix images not loading in rich content
test plan:
- Go to iOS Settings > Settings for the app > Enable `Allow Cross-Website Tracking`
- Repro steps in ticket
- Images should load
=> Add option to allow cross-website tracking

Core/Core/Assignments/Assignment.swift, Core/CoreTests/Assignments/AssignmentTests.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
refs: MBL-14797
release note: Hide attempts section, when not applicable
=> Assignments: show attempts section only if it makes sense

Core/Core/Contexts/APITab.swift, Core/Core/Contexts/Tab.swift
refs: MBL-14820
I decided to do this now since I don't want to have to hotfix
again with another unknown visibility type.
=> Make APITab.visibility a String

Core/Core/DocViewer/DocViewerViewController.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
refs: MBL-14809
release note: Fixed a bug with annotating documents with 3rd party annotations
test plan:
- see ticket
- new annotations should be applied and saved above all others
In case this causes issues in the future, here's some additional context:
- https://github.com/instructure/ios/pull/1678
- https://github.com/instructure/ios/commit/0343ef9cd6aa55aa072609dd59f010d5d6f79bf5#diff-e6097e3aee4336373b57d5b73007dfadR127
=> Append our pdf provider instead of insert

Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/Core/Login/LoginDelegate.swift, Core/Core/Login/LoginStartViewController.swift, Core/Core/Login/LoginWebViewController.swift, Core/Core/Profile/Settings/PairWithObserverViewController.storyboard, Core/Core/Profile/Settings/PairWithObserverViewController.swift, Core/CoreTests/Login/LoginStartViewControllerTests.swift, Core/CoreTests/Profile/Settings/PairWithObserverViewControllerTests.swift, Parent/Parent/ParentAppDelegate.swift, Parent/Parent/Students/AddStudentController.swift, Parent/ParentE2ETests/LoginTests.swift, Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift, Parent/ParentUnitTests/Students/AddStudentControllerTests.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
Also removes QR feature flags.
refs: MBL-14722
release note: Added a message for parents that try to create an account using the QR code pairing feature when self registration is not allowed
test plan:
1. On web, go to account settings > Authentication
2. Set `Self registration` to `All account types`
3. Parent app > QR Login > I don't have an account > Scan student QR code
4. You should get the self registration form
5. Set `Self registration` to `Observer accounts only`
6. Repeat step 3
7. You should get the self registration form
8. Set `Self registration` to `Disabled`
9. Repeat step 3
10. You should get an error alert
=> Show error if self registration is not allowed

Core/Core.xcodeproj/project.pbxproj, Core/Core/People/PeopleListViewController.swift, Core/CoreTests/People/GroupPeopleListViewControllerTests.swift
refs: MBL-14825
release note: Remove unwanted header on Group People list.
test plan:
- Go to Dashboard.
- Select a group.
- Enter People list.
- Grey, empty section header shouldn't be visible above cells.
=> Remove unwanted header on Group People list, add UI test for it.

Student/Student/Submissions/SubmissionFiles/SubmissionFilesViewController.swift
refs: MBL-14831
release note: Make file submission list checkmark color reflect course color.
test plan:
- Submit a file upload.
- View the submission.
- In the drawer tap the files tab.
- The checkmark that appears on the file row should be the course color.
=> Make file submission list checkmark color reflect course color.

Core/Core/Grades/GetAssignmentsByGroup.swift, Core/CoreTests/Grades/GetAssignmentsByGroupTests.swift
refs: MBL-14827
release note: Fix assignment groups not being displayed correctly in specific cases.
test plan:
- Create three Assignment groups - two with the same name, and one with a different name between them.
- Add published assignments to each of the assignment groups.
- In the Parent app, as the observer, navigate to the course then away from the course, and then back again.
- In the Student app, navigate to Dashboard > Course > Grades, go back, then visit the page again.
- Assignment groups should be displayed and in the same order as on the site.
=> Fix CoreData predicate not to cause an exception during fetch. Add tests for the faulty scenario.

Core/Core/UIViews/GradeCircleView.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
refs: MBL-14830
release note: Make grade circle color reflect the course color.
test plan:
- Have a graded submission as a student on a points assignment.
- View the assignment as the student.
- The colored portion of the grade circle should be the course color.
=> Make grade circle color reflect the course color.

Student/Student/Submissions/TextSubmission/TextSubmissionViewController.swift
refs: MBL-14833
release note: Display more appropriate placeholder text when entering a text submission.
test plan:
- Open the text entry dialog on a text assignment by clicking "Submit assignment" button.
- Editor placeholder text should display "Write..." instead of "Enter submission".
=> Modify text submission dialog placeholder text.

rn/Teacher/src/modules/address-book/AddressBook.js, rn/Teacher/src/modules/address-book/__tests__/AddressBook.test.js, rn/Teacher/src/modules/address-book/__tests__/__snapshots__/AddressBook.test.js.snap
refs: MBL-10466
release note: Remove unnecessary cancel button from new message recipient picker.
test plan:
- Bring up the add new message dialog.
- Select a course.
- Start adding recipients.
- The navigation bar in the recipient picker should show a single done button.
=> Remove unnecessary cancel button from new message recipient picker.

rn/Teacher/src/modules/address-book/AddressBook.js, rn/Teacher/src/modules/address-book/__tests__/AddressBook.test.js, rn/Teacher/src/modules/address-book/__tests__/__snapshots__/AddressBook.test.js.snap, rn/Teacher/src/modules/inbox/Compose.js, rn/Teacher/src/modules/inbox/CourseSelect.js, rn/Teacher/src/modules/inbox/__tests__/Compose.test.js, rn/Teacher/src/modules/inbox/__tests__/CourseSelect.test.js, rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Compose.test.js.snap
refs: MBL-10467
release note: Apply color theme to new message dialog navigation bar.
test plan:
- Enter Inbox.
- Start compose a new message.
- Nav bar should reflect the account's theme.
- Enter Select a Course screen.
- Nav bar should reflect the account's theme.
- Select course.
- Tap + sign on the To field.
- Nav bar should reflect the account's theme.
=> Fix new message navigation bar style

Core/Core/AppEnvironment/ExperimentalFeature.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/ios/TeacherTests/RoutesTests.swift, rn/Teacher/src/common/ExperimentalFeature.js, rn/Teacher/src/modules/courses/CourseNavigation.js, rn/Teacher/src/routing/register-screens.js
refs: MBL-14814
test plan:
* turn on experimental feature: native_teacher_syllabus
* check a course, that has a syllabus
* native syllabus page should open
=> Add native syllabus routes

Core/Core/RichContentEditor/RichContentEditorViewController.swift, Core/CoreTests/RichContentEditor/RichContentEditorViewControllerTests.swift
refs: MBL-14868
release note: Editing a url in a rich text input now populates link text and url properly in the edit link dialog.
test plan:
- In the teacher app, go to your course, create an announcement/page/assignment/etc.
- In the rich content editor, write some text. Highlight the text and tap the link icon to add a link to the text.
- In the pop up, notice that your text has been moved to the URL field, and you have to re-enter the text in the right field.
=> Invert link text and url prefill logic in rich content's link editor dialog.

rn/Teacher/src/modules/announcements/edit/AnnouncementEdit.js, rn/Teacher/src/modules/announcements/edit/__tests__/AnnouncementEdit.test.js
refs: MBL-14869
release note: Date picker for delayed announcement now offers time selection as well.
test plan:
- Enter course / announcements.
- Tap on + to add a new announcement.
- Switch on "Delay Posting" option.
- Tap "Post at..." row.
- Tap on the date row which appeared.
- Date picker should show the option to specify time.
=> Add time to delayed announcement date picker.

rn/Teacher/src/modules/inbox/Compose.js, rn/Teacher/src/modules/inbox/CourseSelect.js, rn/Teacher/src/modules/inbox/__tests__/CourseSelect.test.js, rn/Teacher/src/modules/inbox/__tests__/__snapshots__/CourseSelect.test.js.snap
refs: MBL-10465
release note: The previously selected course is now indicated in the course list when composing a new message.
test plan:
- Go to Inbox tab.
- Start composing a new message.
- Select a Course.
- Tap the course line again.
- Course list should indicate the previously selected course with a checkmark.
- The first group should be called "Favorited Courses"
=> Add checkmark to previously selected course in course list when composing a new message

Core/Core.xcodeproj/project.pbxproj, Core/Core/Syllabus/SyllabusTabViewController.swift, Core/CoreTests/Syllabus/SyllabusTabViewControllerTests.swift, Student/Student.xcodeproj/project.pbxproj, Student/Student/Routes.swift, Student/StudentUnitTests/RoutesTests.swift, rn/Teacher/ios/Teacher/Routes.swift, rn/Teacher/ios/TeacherTests/RoutesTests.swift
refs: MBL-14872
test plan:
student: no change, should check, that syllabus still works the same
teacher:
* turn on experimental feature: native_teacher_syllabus
* check a course, that has a syllabus
* native syllabus page should open with summary tabbed, same is in student
=> Rename StudentSyllabus View and move to Core, use it in teacher

Core/Core/Submissions/APISubmission.swift, Core/Core/Submissions/Submission.swift, Core/CoreTests/Submissions/APISubmissionTests.swift
refs: MBL-14937
release note: Fixed viewing grades for some courses
test plan:
- Masquerade as user and observer of user in ticket
- View grades in student and parent app
- View similarity scores from To Do in teacher app as `turnitin.instructure.com` user in 1Password (search for `turnitin`)
=> Fix decoding TurnItIn data

rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
refs: MBL-14955
release note: Fixed crash when opening telephone links from help menu
test plan: see ticket (add a tel link to the help menu)
=> Fix non-http link handling

Core/Core/Profile/Help/View/HelpItemView.swift
refs: MBL-14959
test plan:
- Setup long help menu titles and subtitles.
- Open help menu on a device running iOS 13.0.
- All text should be displayed on multiple lines, instead of being cropped on one line.
=> Fix long help menu item text being cropped on iOS 13.0.

Core/Core/DocViewer/DocViewerViewController.swift
refs: MBL-14967
release note: Fixes point annotation position error after scrolling
test plan: as a teacher open an assignment with a submitted pdf in speedgrader
*place some point annotations
*scroll/zoom
*place new annotations: they shouldn't be shifted
=> Fix annotation place calculation

Core/Core/Todos/TodoListViewController.swift, rn/Teacher/ios/TeacherUITests/Todo/TodoUITests.swift
Fix test expectations based on modified speedgrader behavior.
test plan:
- Start Teacher app.
- Todo tab should display badge based on the number of todo items.
=> Fix To-do tab bar not getting notification badges after app start. 

Student/StudentE2ETests/ActAsUser/ActAsUserE2ETests.swift
Remove waiting step failing on bitrise, it's unnecessary for the test.
affects: none
test plan:
- Act as user E2E test should pass
=> Fix ActAsUser E2E test

Core/Core/Files/APIFile.swift, Core/CoreTests/Files/APIFileTests.swift
refs: MBL-14979
release note: Fix files not getting correctly uploaded during a submission.
test plan:
- See ticket.
=> Fix file name parameter in API response being case sensitive.

Core/Core/People/ContextCard/ContextCardHeaderView.swift, Student/StudentE2ETests/People/PeopleE2ETests.swift
refs: MBL-15072
test plan:
- Context card shouldn't display an empty line below username.
=> Student Context Card email display fix

Core/Core/Login/GetSSOLogin.swift, Core/CoreTests/.swiftlint.yml, Student/StudentE2ETests/Dashboard/DashboardE2ETests.swift
affects: none
test plan:
- Swiftlint warnings shouldn't appear during pull requests
=> Fix Swiftlint 0.42.0 warnings. Fix core tests yaml file overriding parent swiftlint config.

Core/Core/SwiftUIViews/CircleProgress.swift
Disable spinner animation on iOS versions where it causes glitches. Fix timer not getting stopped after CircleProgress UI removed from screen.
refs: MBL-15013
test plan:
- SpeedGrader shouldn't produce strange repeating animations on iOS 13 and 14.0 when grading submissions loaded in WebView.
=>  Fix SpeedGrader animation glitches

rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift, rn/Teacher/ios/Teacher/SpeedGrader/Drawer.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
test plan:
SpeedGrader comment editor keyboard should hide on
* drawer close
* drawer tab switch
* submit pressed
=> End edititing thus hide keyboard, when it's not needed anymore

CanvasCore/CanvasCore/Helm/HelmViewController.swift
test plan:
Open a course, navigation bar should be normal
=> Fix white navbar on course navigation for ios 13

Core/Core.xcodeproj/project.pbxproj, Core/Core/Discussions/DiscussionHTML.swift, Core/CoreTests/Discussions/DiscussionHTMLTests.swift
refs: MBL-15047
release note: Fixed attachments being visible on deleted discussion entries.
test plan:
- Attachment icon shouldn't be visible on a deleted discussion entry.
- See ticket for test environment.
=> Remove attachment from deleted discussion entries.

Core/Core/Discussions/DiscussionDetailsViewController.swift
refs: MBL-15028
release note: Fix group discussion redirection
test plan: see ticket, make sure to test with an empty cache
=> Fix groups not downloading on initial load

Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
refs: MBL-15027
release note: Show rubric comments
test plan: see ticket, original sandbox is unavailable, use balintbartok / s / assignments->rubric
=> Always show comments, when present

Core/Core/API/APIError.swift, Core/Core/Files/FileDetails/FileDetailsViewController.swift, Core/CoreTests/API/APIErrorTests.swift
refs: MBL-15056
test plan: addition to the ticket, change language to a non-English one, files should open from
- global announcements ( MBL-14931 )
- discussions( MBL-15056)
- anywhere (?)
=> Fix user file open logic being language dependent

Core/Core/Discussions/AnnouncementListViewController.swift
refs: MBL-15211
test plan:
- Go to Course/Announcements, note + button is visible in the top right corner
- Go back to Dashboard, pull to refresh
- Go back to Course/Announcements
- "+" button should still be visible
=> Fix GetCourses API call overwriting permissions CoreData information.

Core/Core/Planner/CalendarEvent.swift
refs: MBL-15214
test plan:
- Have a course in which there's an assignment with workflowState = unpublished
- Go to course syllabus summary
- Assignments should be listed
=> Fix syllabus summary not displaying assignments if there's one with unpublished workflowstate

Core/Core/Groups/Group.swift
refs: MBL-15215
test plan:
- Log into an account which is added to a group without a Course
- Tap on Edit and Hamburger buttons
- Dashboard edit page and side menu opens
=> Fix navigation bar buttons not working on dashboard due to infinite refresh cycle

scripts/build_automation/bitrise_workflows/tests.yml
refs: none
affects: none
test plan:
- Nightly test runs shouldn't fail
=> Remove xcbeautify brew dependency from test yml as it's already pre-installed on Bitrise stack.

Core/Core/Grades/GradeFormatter.swift, Core/Core/Grades/GradeListViewController.swift, Core/CoreTests/Grades/GradeFormatterTests.swift, Core/CoreTests/Grades/GradeListViewControllerTests.swift
refs: MBL-15005
affects: Parent, Student
test plan:
- Go to grades list with VoiceOver enabled and tap on a row.
- VoiceOver should announce grades as: "grade, five out of ten" instead of "five slash ten"
=> Improve VoiceOver announcement for grades on the grades list.

Core/Core/Discussions/DiscussionHTML.swift
refs: MBL-15004
test plan:
- Go to a discussion with replies with VoiceOver activated.
- Notice each reply button just says "reply" and doesn't indicate if you are replying to the main discussion or a thread.
=> Improve discussion reply button's accessibility label.

Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
refs: MBL-15104
test plan: submissions->open drawer to max, navigation to date is no longer possible
=> hide a11y label for pickerbutton, when drawer is fully open

rn/Teacher/src/common/components/PickerPage.js, rn/Teacher/src/common/components/__tests__/__snapshots__/PickerPage.test.js.snap, rn/Teacher/src/common/components/rows/Row.js, rn/Teacher/src/common/components/rows/RowWithSwitch.js, rn/Teacher/src/common/components/rows/__tests__/RowWithSwitch.test.js, rn/Teacher/src/common/components/rows/__tests__/__snapshots__/Row.test.js.snap, rn/Teacher/src/common/components/rows/__tests__/__snapshots__/RowWithDetail.test.js.snap, rn/Teacher/src/common/components/rows/__tests__/__snapshots__/RowWithSwitch.test.js.snap, rn/Teacher/src/modules/assignments/__tests__/__snapshots__/AssignmentListRow.test.js.snap, rn/Teacher/src/modules/attachments/__tests__/__snapshots__/AttachmentRow.test.js.snap, rn/Teacher/src/modules/filter/Filter.js, rn/Teacher/src/modules/filter/__tests__/__snapshots__/Filter.test.js.snap, rn/Teacher/src/modules/inbox/__tests__/__snapshots__/CourseSelect.test.js.snap, rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap
refs: MBL-14991
test plan:
- Enable voice over and navigate to the course navigation menu.
- When swiping to each item VoiceOver should announce that the item is a button.
=> Fix course navigation a11y announcement

Core/Core/Conversations/APISearchRecipient.swift, Core/Core/Conversations/SearchRecipient.swift
refs: MBL-15226
test plan:
- Go to Course > People
- Note what roles people have
- Tap filter
- Filter offers roles currently available in the course and not all possible roles
<table>
<th>Before</th>
<th>After</th>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix search recipient API response parsing failure

Student/StudentUITests/Discussions/DiscussionReplyTests.swift
refs: MBL-15004
affects: none
test plan:
- Related UI tests shouldn't fail
=> Update UI test according to new a11y behaviour

Core/Core/People/PeopleListViewController.swift, Core/CoreTests/People/PeopleListViewControllerTests.swift
refs: MBL-15227
test plan:
- Assign an observer both to a course and to a user inside the course
- Go to Course > People
- The role "Observer" under the user's name should be written once
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/108716105-fcc0e980-751b-11eb-8d6c-810c81fe8657.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/108716117-ffbbda00-751b-11eb-90e3-3f9d127ef12f.png"></td>
</tr>
</table>
=> Filter people list cell's role to show a role only one time

Core/Core/Dashboard/CourseCard.swift
refs: MBL-15233
release note: Fixed dashboard not opening the appropriate course in some cases.
test plan:
See ticket.
=> Fix big course image blocking tap action

rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
refs: MBL-15238
release note: Fixed SpeedGrader annotations not working correctly on iPad landscape mode.
test plan:
See ticket.
=> Move docviewer and annotations view to the front to prevent overlapping.

Core/Core/DocViewer/DocViewer.swift, Core/Core/DocViewer/DocViewerViewController.swift, rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionViewer.swift
refs: MBL-15230
release note: Fixed SpeedGrader not scrolling to next submission while an annotation button is active.
test plan:
- Launch the app on an iPad in landscape mode
- Enter SpeedGrader
- Select an annotation type, pen for example
- Try to scroll to the next submission by initiating the scroll from the right grade panel
=> Fix SpeedGrader not scrolling while there's an annotation button selected.

Core/Core.xcodeproj/project.pbxproj, Core/Core/Accessibility/UIAccessibilityAnnouncement.swift, Core/Core/Discussions/DiscussionDetailsViewController.swift, Core/Core/Discussions/DiscussionReplyViewController.swift, Core/CoreTests/Accessibility/UIAccessibilityAnnouncementTests.swift, Core/CoreTests/Discussions/DiscussionDetailsViewControllerTests.swift
refs: MBL-15074
release note: Discussion screen now scrolls to your new reply if you add one.
test plan:
- Add a new reply to a discussion with VoiceOver enabled.
- App should announce "reply sent" on successful posting.
- Discussion list should scroll to the new reply.
=> Add a11y announcement on successful reply post. Scroll discussion view to the new reply after posting.

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Files/File.swift, Core/CoreTests/Files/FileTests.swift
refs: MBL-15253
release note: Fixed submissions not appearing correctly in SpeedGrader for group assignments with individuals grades option turned on.
test plan: See second part of the ticket.
=> MBL-15253 Fix group submission file not appearing

Core/Core/Submissions/APISubmission.swift, Core/Core/Submissions/Submission.swift, Core/CoreTests/Submissions/APISubmissionTests.swift, rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionHeader.swift, rn/Teacher/ios/TeacherTests/SpeedGrader/SubmissionHeaderTests.swift
refs: MBL-15253
release note: Fixed SpeedGrader displaying the submitter's name instead of the group name in case of group submissions.
test plan: See first part of the ticket.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/110642982-dfdf1400-81b3-11eb-8363-4ee5242a7742.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/110642996-e40b3180-81b3-11eb-921a-723ff60120c1.png"></td>
</tr>
</table>
=> MBL-15253 Fix group submission display

Core/Core/UIViews/GradeCircleView.swift, Core/CoreTests/UIViews/GradeCircleViewTests.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard, Student/StudentUITests/Assignments/AssignmentDetailsTests.swift, TestsFoundation/TestsFoundation/CoreUIElements/Assignments/Assignments.swift, TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
Fix progress circle for incomplete submissions, hide attempts section for unlimited attempts on the assignment details page.
refs: MBL-15081
release note: Fix submission status for incomplete assignments
test plan:
- set up an assignment with the grade display set to complete/incomplete
- set the submission attempts to unlimited
- save and publish the assignment
- in the Student app find the assignment and open its details
- attempts section should not be visible
- after submission and an incomplete grade a gray X and the "Incomplete" should be visible in the grade section
=> Not submitted indication discrepancy

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/SpeedGrader/GradeSlider.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift
Extract grade slider, make it tappable along the Slider track, align Slider min/max value Texts vertically, only show bottom divider when the rubrics section is available.
refs: MBL-15250
release note: Improved Grade Slider
=> Add Grade Slider tap feature

Core/Core/Files/FilePicker/FilePickerViewController.swift, Core/Core/Files/UploadManager.swift, Core/Core/Profile/ProfileViewController.swift, Core/CoreTests/Files/FilePicker/FilePickerViewControllerTests.swift, Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
refs: MBL-15258
release note: Added file upload warning when logging out
test plan: Have a file upload assignment, upload a large file
* on submission, the dialog should not dismiss automatically
* while the file is still uplaoding in the background, navigate to the menu and try to log out
* a warning message should appear
=> Add alert for logout, while file is uploading in background

Core/Core.xcodeproj/project.pbxproj, Core/Core/Assignments/APIRubric.swift, Core/Core/Assignments/Rubric.swift, Core/Core/Submissions/GradeSubmission.swift, Core/Core/SwiftUIViews/ChangeObserver.swift, Core/Core/SwiftUIViews/CircleProgress.swift, Core/CoreTests/Submissions/GradeSubmissionTests.swift, rn/Teacher/ios/Teacher/SpeedGrader/RubricAssessor.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift
refs: MBL-15252
release note: Fixed grading issues when using rubrics in SpeedGrader.
test plan:
- See ticket.
In addition to that:
- Grade a submission with rubrics.
- Scroll two submissions away, then scroll back.
- Submission should still show your selected rubrics.
--
- Select a rubric on a submission, then de-select it.
- Close SpeedGrader, then re-open it.
- Rubric selection should be empty.
--
- Progress indicator circle should animate even if it's shown for less than 1 second.
--
- Rubric selection and comment should save upon adding them and not when the view is closed or the user scrolls to another submission.
=> Rubric fixes

rn/Teacher/ios/Teacher/SpeedGrader/SubmissionHeader.swift, rn/Teacher/ios/TeacherTests/SpeedGrader/SubmissionHeaderTests.swift
refs: MBL-15253
test plan:
- See ticket for account details on group submissions.
- Submission in SpeedGrader created by an individual should show the user's profile picture, tapping on it should open his/her context card
- In case a group submitted the assignment then the name of the group should show with the group logo, tapping on it should do nothing as it isn't supported yet
- In case a group submitted the assignment but individual grades is turned on then the user's profile picture should show with the context card on tap
=> Fix profile image in SpeedGrader when grading a submission from an individual

Core/Core/Submissions/GetSubmissions.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift
refs: MBL-15288
release note: Fixed submission order changing while grading group submissions in SpeedGrader.
=> Make submission order deterministic in case of group submissions.

Core/Core/Submissions/GetSubmissions.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift, rn/Teacher/ios/TeacherTests/Submissions/SubmissionListViewControllerTests.swift
release note: Hide inactive students on the Submissions page
=> Fix inactive students are listed in the not submitted tab

Core/Core/Submissions/GetSubmissions.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift
refs: MBL-15304
release note: Fixed empty submissions appearing in SpeedGrader next to a real submission.
test plan:
- Create a submission with students assigned.
- Start the app and go to the new assignment's detail page.
- Make a submission with a student via web or app.
- Go back to teacher app, refresh assignment page. 1 need grading should appear.
- Tap on the need grading circle and then on the submission.
- There should be only one submission in the SpeedGrader.
=> Delete old submissions after a fresh list is fetched from API.

rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj, rn/Teacher/ios/Teacher/SpeedGrader/GradeSlider.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift, rn/Teacher/ios/TeacherTests/SpeedGrader/GradeSliderTests.swift
refs: MBL-15292
release note: Fixed grade slider decimal value and hold features.
test plan:
- set up an assignment with decimal grade points (eg. 10.5)
- add a student submission
- move the grade slider to the maximum on the submission grading pane
- the slider should be able to take up even values and then the maximal decimal value
- the slider should support holding the slider button on the min/max values and toggle no mark/excused states accordingly.
=> Grade slider can give incorrect score if assignment is worth a decimal number

Core/Core/Dashboard/CourseCard.swift, Core/Core/Dashboard/DashboardCard.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Dashboard/DashboardCardTests.swift
refs: MBL-15320
release note: Fixed dashboard freezing on older iOS versions.
test plan:
- Start the app on an iPad (or simulator) running iOS 14.0 or 14.1 in portrait mode.
- Switch to Inbox tab.
- Rotate to landscape.
- Switch back to dashboard.
- App shouldn't freeze.
=> Fix infinite refresh cycle of dashboard card.

Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
refs: MBL-15221
release note: Assignment locked screen now respects the phone's timezone setting.
test plan:
- Create an assignment which will unlock in the future.
- In the app, observe the date on assignment details page.
- Go to iOS Settings, change timezone.
- Restart app, go to assignment details again.
- Unlock date should be updated based on the new timezone.
=> Make assignment locked screen respect phone's timezone setting.

Core/Core/SwiftUIViews/TextEditor.swift, rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentList.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift, rn/Teacher/ios/TeacherUITests/SpeedGrader/SpeedGraderCommentUITests.swift
refs: MBL-15291
release note: Fixed long comments in SpeedGrader pushing send button out of screen.
test plan:
- Start SpeedGrader on a submission where free form rubric comments are enabled.
- Enter a long text (or 1 character and new lines).
- Text box shouldn't grow so large that it pushes the send button out of screen, scrolling should work in text box.
- Repeat the same on the submission comments tab.
=> Limit comment box size and enable scrolling.

Core/Core/Notifications/APIActivity.swift, Core/CoreTests/Notifications/APIActivityTests.swift
refs: MBL-13735
release note: Fixed activity stream showing unplublished courses.
=> Addonly_active_users parameter

rn/Teacher/ios/Teacher/SpeedGrader/SubmissionHeader.swift
refs: MBL-15124
test plan: See ticket ( submission header eye icon identifier)
=> Add a11y identifier for eye icon

Core/Core/Assignments/APIAssignment.swift, Core/Core/Assignments/Assignment.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/Assignments/APIAssignmentTests.swift, Parent/Parent/Assignments/AssignmentDetailsViewController.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift, Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
Use can_submit parameter for getAssigmnents as default
use observed_users only in parent app
refs: MBL-14703
release note: Fixed submit button availability for soft concluded enrollments.
test plan:
see ticket, check parent, if assignments are valid
=> Use can_submit parameter for getAssigmnents as default

Core/Core/Planner/CreateTodoViewController.swift
refs: MBL-15329
release note: Fixed date picker for iOS 14 on the Calendar's new todo page.
test plan:
see ticket
=> Fix iOS 14 datepicker on the calendar's new to do page

rn/Teacher/ios/Teacher/SpeedGrader/SpeedGraderViewController.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
refs: MBL-15095
test plan: Overlapped elements in SpeedGrader shouldn't be accessible to VoiceOver.
=> SpeedGrader a11y fixes

rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrades.swift
Add tap and long press gesture grading actions on min/max value texts on the grade slider.
refs: MBL-15349
release note: Speedgrader slider now supports grading by tapping on the min and max value numbers and no mark / excused on long press.
test plan:
see ticket
try tapping an long press on the min/max values of the slider
=> Add tap action for numbers at the ends of the Speedgrader slider

scripts/build_automation/bitrise_workflows/tests.yml
refs: none
affects: none
test plan: Nightly tests shouldn't fail while setting up dependencies.
=> Remove unused brew tap.

Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift, Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift, Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
refs: MBL-15312
release note: Disabled scanner for media recordings
test plan: see ticket (balintbartok sandbox has a media recording upload type assignment)
* scanner should not be available, when user selects media recording
* it should be available for file uploads as before
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/117808083-bcd8eb00-b25c-11eb-92ce-329bc1c8e40d.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/117807960-9ca92c00-b25c-11eb-815a-ddaf1719487f.png"></td>
</tr>
</table>
=> Remove scanner for media recordings

Core/Core/Assignments/Assignment.swift, Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
refs: MBL-15414
release note: Fixed External tools button not showing
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/117959500-5fa46e80-b31c-11eb-86fc-e0f9c26745a6.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/117959528-66cb7c80-b31c-11eb-9c93-adc5bd80eac9.png"></td>
</tr>
</table>
=> Don't check can_submit in case of LTI tools

Core/Core.xcodeproj/project.pbxproj, Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/Core/AppEnvironment/FeatureFlags/Environment/API/APIEnvironmentFeatureFlags.swift, Core/Core/AppEnvironment/FeatureFlags/Environment/API/GetEnvironmentFeatureFlagsRequest.swift, Core/Core/AppEnvironment/FeatureFlags/Environment/CoreData/EnvironmentFeatureFlags.swift, Core/Core/AppEnvironment/FeatureFlags/Environment/CoreData/GetEnvironmentFeatureFlags.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/CoreTests/AppEnvironment/AppEnvironmentTests.swift, Core/CoreTests/AppEnvironment/FeatureFlags/Environment/API/GetEnvironmentFeatureFlagsRequestTests.swift, Core/CoreTests/AppEnvironment/FeatureFlags/Environment/CoreData/GetEnvironmentFeatureFlagsTests.swift, Student/Student/StudentAppDelegate.swift, Student/Student/StudentTabBarController.swift
refs: MBL-15371
affects: none
release note: Student
test plan: K5 dashboard should show for environments where canvas for elementary is enabled and the K5 experimental feature flag is turned on.
=> K5 feature flag

Core/Core/Courses/CourseListView.swift
refs: MBL-14908
release note: Improved accessibility features.
test plan:
- Enter edit Dashboard menu.
- Turn on VoiceOver.
- Toggle a course's favourite state.
- VoiceOver should announce the actual state correctly.
=> Improve dashboard favourite button's a11y announcements

Core/Core.xcodeproj/project.pbxproj, Core/Core/SwiftUIViews/CompatibleScrollViewReader.swift, Core/Core/SwiftUIViews/ScrollViewWithReader.swift, Core/Core/SwiftUIViews/TopBar/View/TopBarView.swift
refs: MBL-15374
test plan: Items should scroll to screen on iOS 14 when selected if a part of them is off-screen.
=> Make K5 top navbar scroll to the selected item

Core/Core/DocViewer/DocViewerAnnotationProvider.swift, Core/Core/DocViewer/DocViewerViewController.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
refs: MBL-15223
release note: Fixed annotation orientation on rotated submissions
test plan: see ticket, only new annotations will save correctly (check green arrows at bottom)
=> Move FileAnnotations inside DocViewerAnnotataionProvider

Core/Core/Groups/GetGroups.swift, Core/CoreTests/Groups/GetGroupsTests.swift, TestsFoundation/TestsFoundation/Fixtures/Model/GroupFixture.swift
refs: MBL-15336
release note: Hide concluded course groups on the dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/121877299-c39ac800-cd0a-11eb-80fe-2f8ba8688121.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/121877313-c5fd2200-cd0a-11eb-8b64-98cdbfa9cab7.png"></td>
</tr>
</table>
=> Groups in soft-concluded courses show up on dashboard and give error

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/TypeSafeCodable.swift, Core/Core/Dashboard/K5/Model/DueItems/GetK5HomeroomDueItemCount.swift, Core/Core/Planner/APIPlannable.swift, Core/CoreTests/API/TypeSafeCodableTests.swift
=> Add entity to be able to decode two different data types in APIPlannable response.

Core/Core/People/PeopleListViewController.swift, Core/Core/People/User.swift, Core/CoreTests/People/PeopleListViewControllerTests.swift
refs: MBL-15435
release note: Fix roles display on the People page. 
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/122892737-f1ed5880-d345-11eb-99a4-c2fe968116d9.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/122892686-e437d300-d345-11eb-8745-2553013785df.png"></td>
</tr>
</table>
=> User viewing people in a course shows their enrollment roles from other courses

Core/Core/People/ContextCard/Course/ContextCardViewModel.swift
refs: MBL-15361
release note: Fixed context cards not loading in case of more than 100 students
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/122900315-de91bb80-d34c-11eb-9d81-2cc496c8da76.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/122900376-ebaeaa80-d34c-11eb-8780-6d4d9e2d283b.png"></td>
</tr>
</table>
=> Exhaust enrollments and submissions

rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift, rn/Teacher/ios/TeacherTests/Submissions/SubmissionListViewControllerTests.swift
refs: MBL-15382
release note: Fix assignment filter for custom roles.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/123268256-2d328780-d4fe-11eb-861a-489d38dc1e19.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/123268310-37548600-d4fe-11eb-8cb7-b86ece25be31.png"></td>
</tr>
</table>
=> Custom roles do not work with section filters

Core/Core/Submissions/GetSubmissions.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift
refs: MBL-15406
release note: Fixed invited but not accepted users showing up in submissions list.
test plan:
- Invite a user to a course which has an active assignment but don't accept the invitation with it.
- Start teacher app, enter the assignment's submissions list.
- Invited user shouldn't be visible in this list.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/123277019-037d5e80-d506-11eb-8f82-ca9eed9f249c.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/123276905-e779bd00-d505-11eb-98ba-b1aca4889c91.png"></td>
</tr>
</table>
=> Filter out invited only users from submissions list.

Core/Core/Discussions/DiscussionTopic.swift, Core/Core/Discussions/GetDiscussions.swift, Core/CoreTests/Discussions/DiscussionTopicTests.swift
refs: MBL-15324
release note: Fix imported Announcement ordering
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72031065/123276933-eea0cb00-d505-11eb-8711-ebe11f75d68b.png"></td>
<td><img src="https://user-images.githubusercontent.com/72031065/123276212-3ffc8a80-d505-11eb-9717-66079b2ca2ab.png"></td>
</tr>
</table>
=> Use API order for announcements

Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/AppEnvironment/ExperimentalFeature.swift, Core/CoreTests/AppEnvironment/AppEnvironmentTests.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Courses/CourseTests.swift, Core/CoreTests/Planner/PlannableTests.swift, Student/Student/StudentAppDelegate.swift
refs: MBL-15511
test plan: K5 mode should be turned on only if the account is K5 capable and the experimental feature flag is on.
=> Add K5 feature flag.

Core/Core/Submissions/APISubmission.swift, Core/CoreTests/Submissions/APISubmissionTests.swift
refs: MBL-15466
release note: Fixed submission file comments visibility
test plan: see ticket, it's a bit hard to understand: attach a file to a submission as a comment, then check on the web, if the file is visible
=> Use empty comment instead of nil

Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift, Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift, rn/Teacher/src/modules/assignment-due-dates/AssignmentDueDates.js, rn/Teacher/src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js
refs: MBL-15479
release note: Fix navigation bar buttons on the assignment editor screen.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/124758930-61ab3800-df2f-11eb-97e0-bb81ca9affab.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/124758890-548e4900-df2f-11eb-8b0f-61551ad36188.png"></td>
</tr>
</table>
=> Confused action buttons on edit assignment dialog

Core/Core/SwiftUIViews/OptionalDatePicker.swift
refs: MBL-15445
test plan:
- As the teacher edit an assignment.
- Turn on VoiceOver.
- Focus on Due, Available from and Available until buttons and observe that it now announces that there is no date selected.
=> Add empty state announcement to date picker cell.

CanvasCore/CanvasCore/ReactNativeModules/NativeLoginManager.swift, Core/Core.xcodeproj/project.pbxproj, Core/Core/AppEnvironment/AppEnvironment.swift, Core/Core/AppEnvironment/K5State.swift, Core/Core/AppEnvironment/SessionDefaults.swift, Core/Core/Courses/Course.swift, Core/Core/Extensions/UIFontExtensions.swift, Core/Core/Extensions/UINavigationBarExtensions.swift, Core/Core/Planner/Plannable.swift, Core/Core/Profile/Settings/ProfileSettingsViewController.swift, Core/Core/RichContentEditor/RichContentEditorViewController.swift, Core/Core/UIViews/CoreWebView.swift, Core/CoreTests/AppEnvironment/AppEnvironmentTests.swift, Core/CoreTests/AppEnvironment/K5StateTests.swift, Core/CoreTests/AppEnvironment/SessionDefaultsTests.swift, Core/CoreTests/CoreTestCase.swift, Core/CoreTests/Courses/CourseTests.swift, Core/CoreTests/Planner/PlannableTests.swift, Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift, Student/Student/Routes.swift, Student/Student/StudentAppDelegate.swift, Student/Student/StudentTabBarController.swift
refs: MBL-15526
test plan: K5 mode should be controlled by the switch in the settings menu on K5 accounts. The switch shouldn't be visible for non-k5 users or teachers or when the K5 remote/experimental feature flag is turned off.
=> K5 dashboard toggle in settings

Core/Core/Quizzes/QuizListViewController.swift, Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/src/modules/assignments/AssignmentList.js, rn/Teacher/src/modules/assignments/__tests__/AssignmentList.test.js
refs: MBL-15535
test plan: See linked ticket. Detail pages listed in MBL-15305 (except files) should open. New quiz won't launch on that test account since the LTI tool is broken there but the detail page should open.
=> Revert manual route constructing and use html url instead.

Core/Core/Discussions/DiscussionDetailsViewController.swift
refs: MBL-15543
test plan:
- Create a new discussion or enter one where all comments plus your upcoming one fits the screen
- Add a new reply
- Screen shouldn't scroll
=> Fix discussion scroll to new comment

rn/Teacher/ios/Teacher/Submissions/SubmissionListViewController.swift
refs: MBL-15521
test plan: The mail button on the assignment submission list screen should have a valid a11y identifier.
=> Add a11y label to mail button.

Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomMySubjectsView.swift, Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomView.swift, Core/Core/Dashboard/K5/View/K5DashboardView.swift, Core/Core/Dashboard/K5/View/Schedule/K5ScheduleSubjectView.swift, Core/Core/SwiftUIViews/UIKitSwiftUIBridging/EnvironmentValues.swift
refs: MBL-15566
test plan: No new functionality, only refactoring. K5 homeroom should work as before.
=> Move scrollview from K5 skeleton to child page to support more generic page contents

Core/Core/Profile/Settings/ProfileSettingsViewController.swift
refs: MBL-15557
test plan: Elementary View switch in Setting menu should read Homeroom View from now on.
=> Change Elementary View switch in Setting menu to Homeroom View.

Core/Core/Dashboard/K5/View/Schedule/K5ScheduleWeekView.swift
refs: MBL-15137
test plan:
- Open schedule tab in homeroom.
- Note that screen scrolled to today section.
- Scroll away from today and open a course from a todo item.
- Close the dialog.
- Schedule screen scroll should stay at the same position it was when you opened the course.
=> Fix schedule week view scrolling to Today multiple times.

rn/Teacher/src/canvas-api/apis/quizzes.js
refs: MBL-15560
release note: Fixed error on saving quiz details.
test plan: Editing a quiz should no longer return an error.
=> Remove unsupported quiz field from update request.

Core/Core/AppEnvironment/K5State.swift, Core/Core/Profile/SideMenu/SideMenuView.swift
refs: MBL-15462
test plan: Show grades and color overlay switches should not be visible in the side menu in K5 mode.
=> Remove options from side menu in K5 mode.

Core/Core/Profile/Settings/ProfileSettingsViewController.swift, Core/Core/TermsOfService/APIAccountTermsOfService.swift, Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift
refs: MBL-15532
test plan: See ticket. Pairing option in settings should only be visible if self registration is set to all or observer on the canvas account.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/130920407-22702b53-7734-4970-8708-a4117f4ae84e.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/130920418-045073f6-ef51-4d29-80ea-a9a5d033fdfe.png"></td>
</tr>
</table>
=> Disable pairing if self registration is disallowed

CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift, CanvasCore/CanvasCore/Helm/HelmViewController.swift, Core/Core.xcodeproj/project.pbxproj, Core/Core/Assignments/AssignmentDetails/AssignmentDetailsView.swift, Core/Core/Assignments/AssignmentEditor/AssignmentEditorView.swift, Core/Core/SwiftUIViews/CompatibleScrollViewReader.swift, Core/Core/ViewModifiers/CompatibleNavBarItems.swift, rn/Teacher/src/modules/assignment-due-dates/AssignmentDueDates.js, rn/Teacher/src/modules/assignment-due-dates/__tests__/AssignmentDueDates.test.js
refs: MBL-15585
release note: Fixed edit assignment dialog navigation issues.
test plan:
- Open assignment details
- Tap on edit
- Close the edit dialog either with cancel or done
- Edit button should work again from assignment details
---
- Open assignment details
- Tap on due dates section
- Tap on edit
- Edit dialog should have a cancel and done button
---
- Open assignment details on a big enough iPhone to support master-detail split view
- Tap on edit
- Rotate the phone to landscape
- Layout should still be usable
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/130790982-d027474d-e45f-4fff-94a1-263af5ca7b20.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/130791070-6148e19f …
=> Fix add assignee screen buttons

Core/Core/Discussions/DiscussionSectionsPicker.swift
refs: MBL-15556
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/130811838-1f9dbc5d-b452-483b-93b2-035792d3ebdd.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/130811849-ce4dcc54-6d67-4dd6-9ae1-125ac71444a6.png"></td>
</tr>
</table>
=> Add custom back button to discussion sections picker.

Core/Core/Notifications/GetActivities.swift, Core/CoreTests/Notifications/GetActivitiesTests.swift, Student/Student/Notifications/ActivityStreamViewController.swift, Student/Student/Routes.swift
refs: MBL-15594
release note: Show course related recent activities.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/131867768-2008cd3e-7275-448d-a415-9cb335bd41c5.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/131867755-92a5087b-076c-4ce9-8373-66e18e77edd4.png"></td>
</tr>
</table>
=> Recent Activity page in course filters all courses' activities

CanvasCore/CanvasCore/Helm/FullScreenPrimaryHelmSplitViewController.swift
refs: MBL-15553
test plan:
- Launch the app on iPad or a landscape capable iPhone with a K5 account.
- Enter Course > Assignment.
- Note that assignment details are visible on the right side of the split view.
- Tap on the Homeroom icon on the bottom tab bar.
- K5 dashboard should resize to full screen.
=> Fix K5 dashboard not resizing to full screen when tab bar icon is tapped

Core/Core/Dashboard/K5/View/Schedule/K5ScheduleView.swift, Core/Core/Dashboard/K5/View/Schedule/K5ScheduleWeekView.swift, Core/Core/SwiftUIViews/HorizontalPager/HorizontalPager.swift, Core/Core/SwiftUIViews/HorizontalPager/HorizontalPagerProxy.swift
refs: MBL-15608
test plan: Today button should be visible on all week pages of the schedule tab, not just on the current week.
=> Make today button visible on all schedule pages

TestPlans/NightlyTests.xctestplan
refs: MBL-15468
affects: none
test plan:
=> Fix NightlyB build error by switching ParentUITests and ParentUnitTests test order.

rn/Teacher/ios/Teacher/en.lproj/InfoPlist.strings
refs: MBL-15468
test plan: Export translations script should complete without errors.
=> Remove unused file which caused export-translations to fail

Core/Core/Dashboard/K5/View/Resources/K5ResourcesView.swift, Core/Core/Dashboard/K5/ViewModel/Resources/K5ResourcesViewModel.swift
refs: MBL-15574
test plan:
- set up a user with a single homeroom enrollment
- homeroom name should not show on the resources page
- set up a user with multiple homeroom enrollments
- all homeroom syllabuses should be presented
- homeroom names should show as titles
=> Resources screen - Important Info section

Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
refs: MBL-15630
release note: Fixed app getting frozen after a successful media submission.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/133631765-8bf280a2-9911-425a-b45e-b6f6e4011921.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/133631778-22665dda-3f14-4e43-8000-7485d93a16a3.PNG"></td>
</tr>
</table>
=> Fix nil self being used for alert dismissal.

Core/Core/Discussions/DiscussionTopic.swift
refs: MBL-15631
release note: Fixed announcements list getting out of order after reading one.
test plan:
Student App:
- Go to announcements
- Open an announcements which is not at the bottom of the list
- Do a pull to refresh on the announcement detail page
- Go back to announcements list
- Announcements order shouldn't have changed
Teacher App:
- Go to announcements
- Open an announcements which is not at the bottom of the list
- Go back to announcements list
- Announcements order shouldn't have changed
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/135054113-384fe6d5-52be-4aa9-aff9-ba8b3f9eddd9.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/135054127-7c31afc6-3a12 …
=> Fix announcement position being reset when updating a single announcement.

Core/Core/Submissions/GetSubmissions.swift, Core/CoreTests/Submissions/GetSubmissionsTests.swift
refs: MBL-15632
release note: Show inactive students' submissions while they are inactive in another course section.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/135981963-f4932939-a08f-4fb0-97e9-2370be33af7d.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/135981973-6cb3c6f4-d4ed-45f5-9094-08599b1e6506.png"></td>
</tr>
</table>
=> Student won't display in assignment list of students when inactive in another section

Core/Core/DocViewer/APIDocViewer.swift, Core/Core/DocViewer/DocViewerAnnotationProvider.swift, Core/CoreTests/DocViewer/APIDocViewerTests.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
refs: MBL-15225
release note: Fixed annotation saving error not getting displayed in case of poor network connection.
test plan:
- Setup Charles proxy.
- Add a breakpoint in Breakpoints Settings... menu to this path /2018-03-07/sessions/* check only the request checkbox.
- Log in to the teacher app, go to an assignment which can be annotated.
- Draw a line.
- Charles proxy will pop up a dialog, ignore it yet.
- Draw a second line.
- In Charles, abort the first request and execute the second.
- Go back to app, SpeedGrader should display the annotation save failed message.
- Disable breakpoints in Charles.
- Hit try again in the app, wait until save finishes.
- Close and re-open the assignment.
- Both lines should be visible.
<table> …
=> Fix annotation saving error not getting displayed in case of poor network connection

Core/Core.xcodeproj/project.pbxproj, Core/Core/SwiftUIViews/DynamicHeightTextEditor.swift, Core/Core/SwiftUIViews/ViewPreferences/Bounds.swift, Core/Core/ViewModifiers/AvoidKeyboardArea.swift, Core/CoreTests/ViewModifiers/AvoidKeyboardAreaTests.swift, rn/Teacher/ios/Teacher/SpeedGrader/CommentEditor.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionCommentList.swift, rn/Teacher/ios/Teacher/SpeedGrader/SubmissionGrader.swift
refs: MBL-15689
release note: Fixed entered submission comment disappearing upon rotation on iPads.
test plan:
- On iPad go to SpeedGrader.
- Enter a comment into the text field but don't send it, keep the keyboard on screen.
- Put the app into background then move it to foreground.
- Entered text shouldn't disappear.
- Repeat this for the other interface orientation as well.
---
- On iPad go to SpeedGrader.
- Enter a comment into the text field but don't send it, keep the keyboard on screen..
- Rotate the device to the other orientation.
- Entered text shouldn't disappear.
- Keyboard should disappear, its are should be filled back with our content.
---
- On iPad go to SpeedGrader on a submission which can be annotated.
- Put the app into background then move it to …
=> Fix SpeedGrader comment field content disappearing and other layout issues

Core/Core/Pages/GetPage.swift, Core/CoreTests/Pages/GetPageTests.swift
refs: MBL-15710
release note: Fixed Hebrew character handling in page titles.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/141808293-0e9d60bd-0655-4933-98d4-7f2cf771e575.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/141808287-c0c2eeeb-394c-411d-b2ce-7e1a4a9580ab.png"></td>
</tr>
</table>
=> Hebrew character ע will prevent updating pages

Core/Core.xcodeproj/project.pbxproj, Core/Core/DocViewer/DocViewerAnnotationContextMenuModel.swift, Core/Core/DocViewer/DocViewerAnnotationProvider.swift, Core/Core/DocViewer/DocViewerViewController.swift, Core/Core/DocViewer/PSPDFAnnotationExtension.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift, Core/CoreTests/DocViewer/DocViewerViewControllerTests.swift, Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift
refs: MBL-15685
release note: Fixed annotations being editable on a read-only document.
test plan: 
- As a student, create a file submission with a pdf file that has 3rd party annotations (use Preview app on macOS to create such).
- As a teacher start annotating the document. 3rd party annotations shouldn't be editable (move, style, delete, comment). Add some annotations. Add a comment to one of your annotations.
- As a student go to Submission & Rubric and load your uploaded file.
- Teacher and 3rd party annotations should be visible.
- Neither teacher's nor 3rd party annotations should be editable (move, style, delete).
- Comment menu should display on the annotation where the teacher left a comment.
=> Fix annotation menu on read only documents

rn/Teacher/src/modules/assignment-details/components/AssignmentDatesEditor.js, rn/Teacher/src/modules/quizzes/edit/QuizEdit.js, rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap
refs: MBL-15714
release note: Added time picker for date related rows in edit quiz details screen.
test plan:
- As a teacher go to Quizzes and select a quiz.
- Tap edit in the top right corner.
- Check "Show correct answers at", "Hide correct answers at", "Available From" and "Available Until" fields if they allow time selection in their date picker. 
- Add time to those fields. Save changes.
- Check quiz details on web if they have time set.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/142615048-7510eb25-e59e-4cca-ba88-ba9cfba5ded4.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/142615234-a5f2310f-74eb-41b9-897e-c275f76dfb66.png"></td>
</tr>
</table>
=> Change date picker mode to datetime in quiz edit screen.

Core/Core/Courses/K5/View/Subject/K5SubjectView.swift, Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift, Core/Core/Dashboard/K5/ViewModel/Grades/K5GradeCellViewModel.swift, Core/Core/SwiftUIViews/TopBar/View/TopBarView.swift, Core/CoreTests/Dashboard/K5/ViewModel/Grades/K5GradeCellViewModelTests.swift, Core/CoreTests/Dashboard/K5/ViewModel/K5SubjectViewModelTests.swift, Student/Student/Routes.swift
refs: MBL-15756
test plan:
- Login to a K5 account as student
- On the K5 homeroom, go to grades tab
- Tap on a subject
- Elementary subject page should load with the grades tab selected
=> Update grades routing in K5 homeroom.

scripts/build_automation/bitrise_workflows/common.yml
=> Use app-store distribution method instead of auto-detect during archiving

Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomSubjectCardViewModel.swift, Core/CoreTests/Dashboard/K5/ViewModel/Homeroom/K5HomeroomSubjectCardViewModelTests.swift, Core/CoreTests/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModelTests.swift
refs: MBL-15653
test plan:
- Create a course announcement and an overdue assignment on an elementary account.
- Log in to the student app.
- Elementary dashboard card for the above course should display that 1 item is missing and the course announcement title.
- Tap on the announcement.
- App should route to the subject home where the announcement is fully displayed.
- Go back.
- Tap on the missing item text.
- App should route to the subject schedule page.
=> Update routes from K5 homeroom card.

Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomSubjectCardView.swift
refs: none
test plan: pull to refresh on K5 homeroom like there's no tomorrow, try after opening an announcement previously
=> fix crash on homescreen

Core/Core/Dashboard/K5/Model/Schedule/K5ScheduleItemInfo.swift, Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleWeekViewModel.swift, Core/CoreTests/Dashboard/K5/Model/Schedule/K5ScheduleItemInfoTests.swift
refs: none
test plan:
- Create an announcement in a homeroom course
- Log in as a student and go to schedule page
- Find the announcement item
- Homeroom name shouldn't be tappable, only the announcement
=> Disable tap action in homeroom schedule screen in case the to-do item is from a homeroom course.

Core/Core/Dashboard/K5/View/Schedule/K5ScheduleEntryView.swift, Core/Core/Dashboard/K5/View/Schedule/K5ScheduleSubjectView.swift, Core/Core/Profile/Help/View/HelpItemView.swift
refs: none
test plan:
- Open help menu where long item names are present.
- Go to homeroom schedule page with long subject and assignment names.
- Text alignment should be leading and not centered.
=> Set multi line text alignment to leading.

Parent/Parent/Courses/CourseListViewController.swift, Parent/ParentUnitTests/Courses/CourseListViewControllerTests.swift
refs: MBL-15775
release note: Fixed courses not being displayed on dashboard after visiting the calendar filter screen.
test plan:
- Start the parent app and log in with a parent observing a student with an active course
- Go to Calendar Tab
- Tap Calendars button
- Tap Done
- Go to courses tab
- Observed student's courses should be displayed
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/143855328-7c1e3186-e668-4784-b98d-f23cc4d0c72c.jpeg"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/143855341-0425644b-0b0e-4cad-b130-eb1e1dcf68f6.png"></td>
</tr>
</table>
=> Force refresh dashboard each time it appears.

Core/Core.xcodeproj/project.pbxproj, Core/Core/Conferences/Conference.swift, Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomView.swift, Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift, Core/Core/Dashboard/View/DashboardCardView.swift, Core/Core/Dashboard/ViewModel/DashboardConferencesViewModel.swift, Core/CoreTests/Dashboard/ViewModel/DashboardConferencesViewModelTests.swift
refs: MBL-15694
release note: Added conference banner to homeroom view.
test plan:
- Create conferences both for a K5 and a non-K5 account and start them.
- Log in with the K5 user.
- Conference banner should be visible, tapping on it should launch it in a browser, tapping on X should hide it.
- Log in with the non-K5 user and check the same.
=> Add conference banner to homeroom view

Core/Core/Modules/APIModule.swift, Core/Core/Modules/MasteryPath.swift
refs: MBL-15750
release note: Fixed the assignment titles not appearing with conditional mastery path selection
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/143442414-add140ee-f9f0-4d76-befd-600e1eaeedf8.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/143442487-37698d24-8d47-469c-a4e0-ca6910870993.png"></td>
</tr>
</table>
=> Fix conditional mastery path selection UI issue

Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift, Core/Core/Dashboard/K5/ViewModel/Schedule/K5ScheduleWeekViewModel.swift
refs: MBL-15737
release note: Fixed homeroom showing only 10 missing items.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144073634-bc7fb7ee-8b07-4d0c-9a47-1406a99844ac.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/144073602-78df20f2-b202-4e09-b7dd-4761a06bfa79.png"></td>
</tr>
</table>
=> Add paging to missing items fetch.

Core/Core.xcodeproj/project.pbxproj, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListRequest.swift, Core/Core/SubmitAssignmentExtension/Model/API/AssignmentPickerListResponse.swift, Core/Core/SubmitAssignmentExtension/View/AssignmentPickerView.swift, Core/Core/SubmitAssignmentExtension/View/AttachmentPreviewView.swift, Core/Core/SubmitAssignmentExtension/View/CoursePickerView.swift, Core/Core/SubmitAssignmentExtension/View/SubmitAssignmentExtensionView.swift, Core/Core/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModel.swift, Core/Core/SubmitAssignmentExtension/ViewModel/CoursePickerViewModel.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/AssignmentPickerViewModelTests.swift, Core/CoreTests/SubmitAssignmentExtension/ViewModel/CoursePickerViewModelTests.swift
refs: MBL-15784
release note: Fixed file share extension not showing all assignments in a course. Fixed file share extension pre-selecting course and assignment only on the first attempt.
test plan: See ticket, assignments above number 100 should also be displayed in the app. I added a preview icon for pdf files, fixed text alignments in case of long course and assignment names and I also modified the course and assignment pre-select logic not to work only for the first time. The REST API call was replaced with an equivalent GraphQL one to make assignment list load faster in case of courses with a lot of assignments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144637763-3d9b2dda-94fd-44fc-92c2-18dd52d …
=> Share extension fixes

Core/Core/Dashboard/K5/View/Homeroom/K5HomeroomView.swift, Core/Core/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModel.swift, Core/CoreTests/Dashboard/K5/ViewModel/Homeroom/K5HomeroomViewModelTests.swift
refs: MBL-15694
release note: Added account announcements to homeroom view.
test plan:
- Create an account announcement.
- Log in with a K5 user to the student app.
- Announcement should be visible on the homeroom screen.
- Check if opening, collapsing and dismissing works.
=> Add account announcements to homeroom view

Core/Core/Discussions/GetDiscussions.swift, Core/Core/Extensions/URLComponentsExtensions.swift, Core/CoreTests/Discussions/GetDiscussionsTests.swift, Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift
refs: MBL-15732
release note: Fixed announcements getting out of order if there were more than 100.
=> Fix announcement order when paging is active

Core/Core.xcodeproj/project.pbxproj, Core/Core/Dashboard/View/CourseCard.swift, Core/Core/Dashboard/View/DashboardCardView.swift, Core/Core/Dashboard/View/DashboardGrid.swift
refs: MBL-15726
release note: Updated dashboard card layout to allow large course titles to be displayed.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/145379165-e9d47182-27ab-442d-85c8-bd1d7d496ce1.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/145379219-0eaa5702-4920-46e6-9211-06379b1457fc.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/145379496-1ee93629-9fbf-465c-a416-4e9bbbe16a8a.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/145379545-ab89d1e3-2446-42f2-95b5-207d549eec56.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/145379596-7af4 …
=> Update dashboard card layout to allow large course titles to be displayed

Core/Core/Grades/GetAssignmentsByGroup.swift, Core/CoreTests/Grades/GetAssignmentsByGroupTests.swift
refs: MBL-15730
release note: Fixed assignments not being ordered by due date on the grades page.
test plan: see ticket.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/145426273-6f38d6f3-d1da-4a15-ac70-4948cfcfaae1.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/145426265-e29b0bcd-1949-4b3e-8f06-deea5af4b71a.png"></td>
</tr>
</table>
=> Grades page ordering by due date descending

Core/Core/Grades/GradeListViewController.swift, Core/CoreTests/Grades/GradeListViewControllerTests.swift
refs: MBL-15736
release note: Fixed Late and Missing labels not showing for 'on paper' and 'no submission' assignments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/145228244-ea4c11d8-1ecd-4b4e-ad52-03e7fd35a4da.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/145228238-b4dd39d1-9f27-4e22-8ceb-866627f783c9.png"></td>
</tr>
</table>
=> Late and Missing labels do not show for on page and no submission assignments

Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/ObserverAlerts/APIObserverAlert.swift, Core/Core/ObserverAlerts/ObserverAlert.swift, Core/CoreTests/ObserverAlerts/ObserverAlertTests.swift, Parent/Parent/ObserverAlerts/ObserverAlertListViewController.swift, Parent/ParentUnitTests/ObserverAlerts/ObserverAlertListViewControllerTests.swift
refs: MBL-15735
release note: Fixed handling of missing assignment alerts where the course is no longer available.
test plan: See ticket and its comments. There's a new API field which indicates if the alert is from a no longer available course. This field only works if the course is deleted but doesn't if the course is concluded. If the API team fixes this we'll need no client side modifications.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144847259-e5441e06-5840-4246-9932-30a1dfe44f6b.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/144847248-e3eb6b5d-7f9e-43d9-872e-780faf219ee1.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/144847346 …
=> Add support for locked parent alerts

Core/Core/Discussions/AnnouncementListViewController.swift
refs: MBL-15794
test plan: See ticket and its comment for details.
=> Allow announcement list to select the first announcement after a force refresh.

Core/Core/Courses/K5/View/Subject/K5SubjectView.swift, Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift, Core/Core/SwiftUIViews/WebView.swift, Core/CoreTests/Dashboard/K5/ViewModel/K5SubjectViewModelTests.swift
Make K5 subject page reload upon module item completion. Add support for SwiftUI webview to perform a reload.
refs: MBL-15798
release note: Fixed module item progress not being updated on homeroom module page.
test plan:
- Create a module with a few items (page view for convenience) and enable sequential requirement order on a K5 account.
- Log in to the student app.
- Go to subject home and enter Modules tab.
- Complete the first module item then close the page.
- Subject home page should be updated and the module item should be marked as completed.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/148403162-b731baf6-4e61-49f0-b674-efdaa778ae66.PNG"></td>
<td><img …
=> Fix module progress not updating

Core/Core/Dashboard/K5/Model/MissingSubmissions/GetMissingSubmissionsRequest.swift
refs: MBL-15814
release note: Fixed homeroom view showing missing items from closed grading periods.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/148797150-a5fd33f7-c773-435c-adab-039adaacc438.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/148797196-d9d5e90d-eb2a-49aa-a908-f3e3c12a49fc.png"></td>
</tr>
</table>
=> Filter missing items to current grading period in homeroom

Core/Core/People/PeopleListViewController.swift, Core/CoreTests/People/PeopleListViewControllerTests.swift
Add time for the table view to display the loading cell before triggering next page load.
refs: MBL-15808
release note: Fixed a crash on people list screen.
=> Fix crash on people list screen

Core/Core/Dashboard/K5/Model/MissingSubmissions/GetMissingSubmissionsRequest.swift
refs: MBL-15814
test plan:
- Log in to a K5 account on web, go to homeroom, check in Charles the missing_submissions API call's parameters, it includes the submittable filter.
- Do the same with the android client.
- iOS version should match the filtering behaviour of the above 2 platforms.
The hard way:
- Create a grading period which ends today.
- Add an assignment to it.
- Wait until the grading period ends.
- Missing items count in the homeroom view shouldn't include the above -now locked- assignment.
=> Make missing submissions count in homeroom exclude locked assignments.

scripts/generate-release-notes.js
refs: MBL-15831
affects: none
test plan: run the release script, it should not fail on issues with refs containing tags
=> Fix release notes script commit tag issue

Core/Core/DocViewer/DocViewerAnnotationProvider.swift, Core/CoreTests/DocViewer/DocViewerAnnotationProviderTests.swift
refs: MBL-15825
release note: Fixed annotations made in iOS not appearing on submissions.
test plan:
- Create an assignment with a pdf file attached.
- As a student, download the pdf file to iOS Files.
- Open the pdf in iOS Files and add annotations.
- Submit the annotated file to the assignment.
- As a student check your submission in Submission & Rubric.
- As a teacher go to SpeedGrader and check the file.
- Annotations added in Files app should appear.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/149745368-58b97042-60da-4008-a7a6-f1ccbdbffabe.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/149745454-e944e398-81e0-4c20-8d4e-4c23cc9186f7.png"></td>
</tr>
</table>
=> Disable using customData dictionary on annotations.

Core/Core/Extensions/UITableViewExtensions.swift, Core/CoreTests/Extensions/UITableViewExtensionsTests.swift, Parent/Parent/ParentAppDelegate.swift, Student/Student/StudentAppDelegate.swift, rn/Teacher/ios/Teacher/TeacherAppDelegate.swift
refs: MBL-15827
test plan: Check screens where a native tableview is used.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/150993480-54d262bd-a97e-446d-a29a-e9793b46bd21.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/150993490-517407a2-7456-4008-b5bd-2a0c611d4474.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/150993616-51c14865-3f2a-48fa-a4d0-02c822a3306f.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/150993670-eee77d67-fb84-4f99-bd0e-aa316c9ff23a.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/150993725-a7699bcf-cb07-46c2-ba71-2204560 …
=> Set the default section header top padding to 0.

Core/Core/Courses/K5/ViewModel/K5SubjectViewModel.swift
refs: MBL-15863
release note: Fixed a crash upon assignment submission in homeroom view.
test plan:
- Log in to a K5 account which has a course with a file upload assignment in a module.
- Go to subject page, modules tab.
- Tap on the assignment and submit a file to it.
- App shouldn't crash.
=> Move webview reload call to main thread.

Core/Core.xcodeproj/project.pbxproj, Core/Core/Courses/Course.swift, Core/Core/Dashboard/Model/DashboardCard.swift, Core/Core/Dashboard/View/DashboardCardView.swift, Core/Core/Database.xcdatamodeld/Database.xcdatamodel/contents, Core/Core/Groups/Group.swift, Core/CoreTests/Courses/CourseTests.swift, Core/CoreTests/Dashboard/Model/DashboardCardTests.swift, Core/CoreTests/Groups/GroupTests.swift
Change course property on DashboardCard from a dynamic lookup to a stored property to avoid managed object context access during SwiftUI rendering.
refs: MBL-15888
release note: Fixed a crash on dashboard.
test plan: All dashboard functions should work without crashing.
=> Fix dashboard rendering crash

Core/Core/Modules/ModuleList/ModuleListViewController.swift
Move global variable to instance one to prevent tableview state synchronization issues on modules screen.
refs: MBL-15898
release note: Fixed a crash on the modules screen.
test plan:
- Setup a course with multiple modules and the module page as the course home.
- On a split view capable device enter the course, modules list load on the detail view.
- Enter modules page as well on the course navigation panel.
- Collapse the first module on the left list.
- Collapse the second module on the right list.
- App shouldn't crash.
=> Fix crash on the modules screen

Core/Core/Grades/GradeListViewController.swift, Core/CoreTests/Grades/GradeListViewControllerTests.swift
refs: MBL-15854
release note: Fixed grades page showing letter grade for the total score instead of the current one.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153601792-f255372b-9ec3-4113-ba12-b23defb234dc.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153601801-8914c900-9294-4047-bd9f-5669788bb289.png"></td>
</tr>
</table>
=> Fix letter grade display

Core/Core/Dashboard/View/NotificationCard.swift
refs: MBL-15854
test plan:
- Create an account announcement with a long title.
- Go to dashboard, check the invitation box's text alignment.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153604836-f72be6d3-b33a-4874-838e-5555b8792c52.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153604851-0d65cc68-2618-47d1-b311-97988253eaad.png"></td>
</tr>
</table>
=> Fix announcement text alignment.

Core/Core/Planner/GetPlannerCourses.swift
refs: MBL-15842
test plan:
- Have a student invited to a course.
- Log in to the Student app as the student
- Tap on Calendar on the bottom tab bar.
- Tap on Calendars in the top right corner.
- The invited course shouldn’t show up.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153613241-6087bb7b-ef25-4da6-bd2d-b7a9ff24c418.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153613259-259cd5b2-4d56-443b-bf94-59ec7431a848.png"></td>
</tr>
</table>
=> Filter out invited courses from calendar filter

Core/Core.xcodeproj/project.pbxproj, Core/Core/API/SafeURL.swift, Core/Core/Submissions/APISubmission.swift, Core/CoreTests/API/SafeURLTests.swift
refs: MBL-15855
release note: Fixed grades and assignments pages not loading in some cases.
test plan: See ticket. Test account in comments.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153458693-a3b7a566-6b75-473f-951e-213a20a56027.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153458712-53848104-41bb-48fc-8779-fb540a6fa077.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153458787-e94dd4cb-a629-405c-bbfb-239e179e5edd.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153458830-7d3d20cc-0627-48f9-b6c7-5b390fc5cf86.PNG"></td>
</tr>
</table>
=> Add property wrapper to decode urls with unsafe characters.

Core/Core/People/ContextCard/Course/ContextCardSubmissionRow.swift, Core/Core/Submissions/GetSubmissions.swift
release note: Fixed people page not showing missing submissions.
test plan:
- Create an assignment with due date in the past.
- Login with a student assigned to that assignment.
- Check Grades → Assignment is shown as “Missing”.
- Check People page → No missing label.
- Do the same in the teacher app with a teacher account in the same course.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/153844929-d4bea451-2cb0-4664-9fbc-ea54f9df6a3f.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/153844942-31599778-c18e-4cce-9480-a9a376fad65d.png"></td>
</tr>
</table>
=> Fix people page not showing missing submissions

Student/GradesWidget/GradesWidgetViewController.swift
refs: MBL-15885
test plan:
- Add the old grades widget to the home screen.
- Expand its layout with the arrow at the top right corner.
- Course grades should be visible.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/154084858-ce02287f-30bd-4900-bfff-579d934b2195.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/154084878-e25b5503-317f-414d-a3eb-7cc36a2e38aa.PNG"></td>
</tr>
</table>
=> Fix table view section spacing.

Core/Core/Pages/PageList/PageListViewController.swift, Core/CoreTests/Pages/PageList/PageListViewControllerTests.swift
refs: MBL-15906
test plan:
- Remove all pages from a course
- Add a new Page that is Published and is Front Page
- Go to course > pages in both apps
- Check the front page header cell if “Front Page” text and the title of the page is visible
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/154287633-5e3d21d6-216e-4abb-bb17-3ae112e3d9d6.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/154287667-70939bb5-4712-4a5f-89cc-33532fd20d96.png"></td>
</tr>
</table>
=> Fix front page header cell height.

Core/Core/Dashboard/ViewModel/DashboardCardsViewModel.swift
refs: MBL-15931
release note: Fixed an occasional crash on the dashboard in case of a network error.
=> Use generic network error message instead of non thread safe error property on Store.

rn/Teacher/src/modules/inbox/Inbox.js
refs: MBL-15927
release note: Fixed inbox not loading in case there are locked courses.
=> Fixed undefined return statement causing Inbox to fail to load.

Core/Core/Groups/Group.swift, Core/CoreTests/Groups/GroupTests.swift
refs: MBL-15839
release note: Fixed groups for concluded courses showing up on dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/157059974-1283eac1-7c94-4d9c-82c7-565021a64448.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/157059991-64d93bb3-84d4-45ed-a2a3-22d5f9233337.png"></td>
</tr>
</table>
=> Check if course is concluded when checking whether a course's group is active

Core/Core/Dashboard/View/DashboardCardView.swift
refs: MBL-15921
release note: It’s now easier to touch the dashboard menu and layout toggle buttons.
=> Dashboard layout switcher button is too small

Core/Core/Dashboard/View/NotificationCard.swift, Core/Core/SwiftUIViews/WebView.swift
refs: MBL-15944
release note: Fixed global announcements cannot be expanded on the dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/79920680/160798997-971cf6d3-1ff8-44f7-8199-86febd040c1b.png"></td>
<td><img src="https://user-images.githubusercontent.com/79920680/160799006-79d4e38e-bd68-4810-a7f8-a25ac392152f.png"></td>
</tr>
</table>
=> Global announcements cannot be expanded

Core/Core/Dashboard/View/DashboardCardView.swift, Core/Core/Dashboard/ViewModel/DashboardCardsViewModel.swift, Core/Core/Dashboard/ViewModel/DashboardInvitationsViewModel.swift, Core/Core/SwiftUIViews/Pandas/InteractivePanda.swift, Core/Core/SwiftUIViews/Pandas/PandaGallery.swift, Core/Core/SwiftUIViews/Pandas/Scenes/SharedLayers/BouncyImage.swift, Core/CoreTests/Dashboard/ViewModel/DashboardCardsViewModelTests.swift, Core/CoreTests/Dashboard/ViewModel/DashboardInvitationsViewModelTests.swift
refs: MBL-15962
release note: Fixed missing edit dashboard button in case there were no active courses on the dashboard.
test plan: 
- Edit dashboard button should be visible even if there are no courses.
- Layout selector button should be hidden in case there are no course cards.
- Interactive empty panda!
- User's groups should be visible even if there are no active courses.
- Empty panda shouldn't be visible for a second upon first login before course cards are displayed.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/161516409-c086f0ed-4ca1-499e-8890-939da9aca2a8.png"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/161516427-d192e73e-59af-4ee9-ab11-296e12f14814.png"></td> …
=> Add edit courses button on empty dashboard

scripts/build_automation/automateVersioning.sh, scripts/build_automation/bitrise_workflows/common.yml, scripts/coverage/config.json
refs: MBL-15704
test plan: Release script shouldn't try to update the non-existing plist file.
=> Remove script reference pointing to the old grades widget plist file.

Core/Core/ActAsUser/ActAsUserWindow.swift, Core/Core/SwiftUIViews/Pandas/InteractivePanda.swift
refs: MBL-16010
test plan:
- Check if empty panda is focusable via VoiceOver.
- Check VoiceOver focus rectangle on stop masquerade button.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/162755152-5931ddc7-765a-4e5c-b9c1-1bdeebbe2223.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/162755202-1984a7e6-0299-46ca-b943-ea0c8a635610.PNG"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/72396990/162755291-3f554db4-6a6a-4910-ae8d-9d497228de5a.PNG"></td>
<td><img src="https://user-images.githubusercontent.com/72396990/162755351-ac14b6c4-3563-4146-89b5-b41a44e2263d.PNG"></td>
</tr>
</table>
=> Fix a11y issues.

Core/Core/Profile/SideMenu/SideMenuBottomSection.swift, Core/Core/Profile/SideMenu/SideMenuItem.swift, Core/Core/Profile/SideMenu/SideMenuMainSection.swift
refs: MBL-16008
release note: Fixed side menu items have no visual selection feedback
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/36445038/164477017-864ec9bb-f720-4332-b2bd-c036f663e6a6.png"></td>
<td><img src="https://user-images.githubusercontent.com/36445038/164477026-ab56e94f-4a92-498e-8c3b-7505b9d7d5ac.png"></td>
</tr>
</table>
=> Add selection indicator to side menu
