instructure/canvas-ios

- Core/CoreTests/Store/UseCaseTests.swift
- dangerfile.js
- package.json
- scripts/coverage/dangerfile-teacher.js
- scripts/coverage/dangerfile-utils.js
- scripts/update-headers.js
- yarn.lock
Aligns React Native coverage report to XCTest coverage reports
Checks license headers for changed & added files
refsx: none
affects: invalid
release notez: none
> Clean up danger reporting

- rn/Teacher/src/common/feature-flags.js
- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
- rn/Teacher/src/routing/register-screens.js
We don't want to accidentally release them.
> Place teacher modules behind a feature flag

- .gitignore
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher.xcodeproj/xcshareddata/xcschemes/Teacher.xcscheme
- rn/Teacher/ios/TeacherTests/Extensions/CKIClientExtensionsTests.swift
- rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift
- rn/Teacher/ios/TeacherTests/RoutesTests.swift
- scripts/coverage/config.json
- scripts/coverage/coverage.js
ignore Pods and AppDelegate extensions
test remaining files
refs: none
affects: none
> Fix TeacherTest coverage

- rn/Teacher/src/__templates__/enrollments.js
- rn/Teacher/src/canvas-api-v2/queries/ContextCard.js
- rn/Teacher/src/canvas-api-v2/queries/__templates__/ContextCard.js
- rn/Teacher/src/canvas-api/flow/enrollment.js
- rn/Teacher/src/common/text.js
- rn/Teacher/src/modules/users/ContextCard.js
refs: MBL-11710
release note: Show grade override and original grade for students
> Show grade overrides

- Core/Core.xcodeproj/project.pbxproj
> Don't copy PSPDFKit into Core, only the apps

- Core/Core.xcodeproj/xcshareddata/xcschemes/Core.xcscheme
- Student/Student.xcodeproj/xcshareddata/xcschemes/Student.xcscheme
- Student/Student.xcodeproj/xcshareddata/xcschemes/StudentHostDistantObjectCategories.xcscheme
- Student/Student.xcodeproj/xcshareddata/xcschemes/StudentUITests.xcscheme
> fix warnings

- Canvas/TechDebt/Assignments/Submissions/CBIStudentSubmissionViewController.m
- Frameworks/CanvasKit/CanvasKit/Networking/CKIClient+CKISubmissionComment.h
- Frameworks/CanvasKit/CanvasKit/Networking/CKIClient+CKISubmissionComment.m
refs: MBL-12084
release note: Fixed commenting on group assignment submissions
> Add group_comment flag to comments on group submission

- Core/Core/Database/CoreData/Models/Assignment.swift
- Core/CoreTests/Database/Models/AssignmentTests.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
> handle on paper submissions

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/Database/Models/FileTests.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
> Fix File coverage & nitpick

- Canvas/TechDebt/MyLittleViewController/MLVCCollectionViewCellViewModel.h
- Canvas/TechDebt/MyLittleViewController/MLVCCollectionViewController.m
> Fixes error from app store connect

- Core/Core/Extensions/UITabBarExtensions.swift
- Core/CoreTests/Extensions/UITabBarExtensionsTests.swift
> Update the tabbar to match the latest designs

- Canvas/Canvas/CanvasAppDelegate+Helm.swift
ref: MBL-12134
release note: fix modules links with numbers
> fix modules with pages with numbers in the title

- Core/Core/DocViewer/Comments/CommentListViewController.swift
- Core/Core/DocViewer/DocViewerViewController.swift
- Core/Core/Extensions/BundleExtensions.swift
- Core/Core/Extensions/UIViewExtensions.swift
- Core/Core/Logger/LogEventList/LogEventListViewController.swift
- Core/Core/Login/LoginFindSchoolViewController.swift
- Core/Core/Login/LoginManualOAuthViewController.swift
- Core/Core/Login/LoginStartViewController.swift
- Core/Core/Views/AccessIconView.swift
- Core/Core/Views/EmptyView.swift
- Core/Core/Views/LoadingViewController.swift
- Core/Core/Views/TitleSubtitleView.swift
- Core/CoreTests/Extensions/BundleExtensionsTests.swift
- Core/CoreTests/Extensions/UIViewExtensionsTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/Student/Courses/CourseList/CourseListViewController.swift
- Student/Student/Dashboard/DashboardViewController.swift
- Student/Student/FilePicker/FilePickerViewController.swift
- Student/Student/Quizzes/QuizList/QuizListViewController.swift
- Student/Student/Submissions/SubmissionDetails/ExternalToolSubmissionContentViewController.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/Student/Submissions/SubmissionDetails/UrlSubmissionContentViewController.swift
- Student/Student/Submissions/SubmissionDetails/Views/Drawer.swift
- Student/Student/Submissions/SubmissionDetails/Views/SubmissionDetailsEmptyView.swift
- Student/Student/Submissions/urlSubmission/UrlSubmissionViewController.swift
- rn/Teacher/ios/Teacher/Modules/ModuleItemList/ModuleItemListViewController.swift
- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.swift
> Use view & controller extensions instead of Bundle.load

- Canvas/Settings.bundle/Root.plist
- Parent/Settings.bundle/Root.plist
- rn/Teacher/ios/Settings.bundle/Root.plist
refs: MBL-12170
affects: student, parent, teacher
> Fix title casing in settings

- Core/Core/API/APIFile+Requestable.swift
- Core/CoreTests/API/APIFile+Requestable+Tests.swift
> Fix seeding file uploads

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/Canvas/Canvas.entitlements
- Canvas/Canvas/CanvasAppDelegate.swift
- Canvas/Canvas/Info.plist
- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/React Native Modules/SiriShortcutManager.m
- CanvasCore/CanvasCore/React Native Modules/SiriShortcutManager.swift
- rn/Teacher/src/modules/assignments/AssignmentList.js
- rn/Teacher/src/modules/assignments/map-state-to-props.js
- rn/Teacher/src/modules/grades/GradesList.js
- rn/Teacher/src/modules/grades/__tests__/GradesList.test.js
refs: MBL-12171
release note: Added siri shortcuts to support Grades
> add siri shortcuts that support grades

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsPDFDocumentPresenter.swift
- Cartfile
- Cartfile.resolved
- Core/Core/DocViewer/DocViewerPresenter.swift
> update pspdf kit to 8.2.2 ( to support apple pencle 2nd gen double click )

- Frameworks/CanvasKit/CanvasKit/Models/Rubric/CKIRubric.h
- Frameworks/CanvasKit/CanvasKit/Models/Rubric/CKIRubric.m
refs: MBL-11613
release note: Added support for hiding rubric points
> Fix hiding rubric points

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIModule.swift
- Core/Core/API/APIModuleRequestable.swift
- Core/Core/API/APIRequestable.swift
- Core/Core/Models/ModuleItemType.swift
- Core/CoreTests/API/APIModuleRequestableTests.swift
- Core/CoreTests/API/APIModuleTests.swift
- Core/CoreTests/API/APIRequestable+Tests.swift
- Core/CoreTests/Database/Models/ModuleItemTypeTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/Api/APIModuleFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/ModuleItemTypeFixture.swift
- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.storyboard
> Add APIModuleItem

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Store/Store.swift
- Core/Core/Store/UseCase.swift
- Core/Core/Use Cases/CreateTextComment.swift
- Core/CoreTests/CoreTestCase.swift
- Core/CoreTests/Store/StoreTests.swift
- Core/CoreTests/Use Cases/CreateTextCommentTests.swift
- Student/Student/Submissions/SubmissionComments/SubmissionCommentsPresenter.swift
- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUITests/Element/Element.swift
- Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift
- Student/StudentUITests/Tests/StudentTest.swift
- Student/StudentUnitTests/Submissions/SubmissionComments/SubmissionCommentsPresenterTests.swift
refs: MBL-12199, MBL-11319
affects: none
> Add text and video comments

- rn/Teacher/src/__templates__/rubric.js
- rn/Teacher/src/canvas-api/flow/assignments.js
- rn/Teacher/src/common/components/CircleToggle.js
- rn/Teacher/src/common/components/__tests__/CircleToggle.test.js
- rn/Teacher/src/modules/speedgrader/GradeTab.js
- rn/Teacher/src/modules/speedgrader/__tests__/GradeTab.test.js
- rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/GradeTab.test.js.snap
- rn/Teacher/src/modules/speedgrader/components/RubricItem.js
- rn/Teacher/src/modules/speedgrader/components/__tests__/RubricItem.test.js
refs: MBL-12054
release note: Fixed incorrect display of rubrics with multiple ratings sharing a point value
> Key rubric ratings on rating id

- Core/CoreTests/AppEnvironment/MDMManagerTests.swift
> Fix MDMManager test names

- Core/Core/Store/Store.swift
- Student/StudentUITests/Tests/AssignmentDetailsPageTest.swift
File upload ui test is still flaky.. I think it has to do with presenting a view modally (even though it passes 100% locally) so I will keep digging into that.
In the meantime, here's a fix to a flaky unit test.
> Fix flaky unit test

- Student/Student/FilePicker/FilePickerViewController.swift
- Student/StudentUITests/Pages/FilePickerPage.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUITests/Tests/AssignmentDetailsPageTest.swift
- Student/StudentUITests/Tests/FilePickerPageTests.swift
> Fix flaky UI tests

- Student/StudentHostDistantObjectCategories/TestHost.swift
- rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift
> Fix StudentUITests build

- Canvas/TechDebt/Files and Folders/FileViewController.m
refs: MBL-12194
release note: Previewing html course files will resolve relative urls to other course files
> Render preview of html files

- Canvas/TechDebt/Files and Folders/FileViewController.h
- Canvas/TechDebt/Files and Folders/FileViewController.m
> Fix viewing PDF files

- Core/Core/Views/HorizontalMenuView.swift
- Core/Core/Views/HorizontalMenuViewCell.swift
- Student/Student/Courses/Syllabus/SyllabusViewController.swift
> Fix syllabus in high contrast mode

- CanvasCore/CanvasCore/Push Notifications/Services/RemoteService.swift
refs: MBL-12178
release note: Fixed a bug that would cause registering for push notifications to fail
> Retry registering for push notifications

- Core/Core/Views/HorizontalMenuView.swift
- Core/Core/Views/HorizontalMenuViewCell.xib
> animate underline on horizontal menu

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> fix assignment details submission type action sheet on ipad

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIAssignment.swift
- Core/Core/API/APIRubric.swift
- Core/Core/Database/CoreData/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Database/CoreData/Models/Assignment.swift
- Core/Core/Database/CoreData/Models/Rubric.swift
- Core/CoreTests/Use Cases/GetAssignmentsTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/Api/APIRubricFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/RubricFixture.swift
> add rubric entities

- rn/Teacher/src/modules/files/ViewFile.js
- rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
refs: MBL-12213, MBL-12239
release note: Fixed previewing files with certain characters in the filename
> Fix previewing files with special characters

- Canvas/TechDebt/Files and Folders/FileViewController.m
- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/React Native Modules/QLPreviewManager.h
- CanvasCore/CanvasCore/React Native Modules/QLPreviewManager.m
- rn/Teacher/src/modules/files/ViewFile.js
- rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
- rn/Teacher/test/scripts/jestSetup.js
refs: MBL-12207
release note: Adds preview ability for usdz files
> Add AR preview for usdz files

- rn/Teacher/src/common/feature-flags.js
- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
- rn/Teacher/src/routing/register-screens.js
> Remove Modules Feature Flag

- rn/Teacher/index.ios.js
> Fix routing to module item after multiple logins

- rn/Teacher/src/common/components/AttachmentView.js
- rn/Teacher/src/common/components/__tests__/AttachmentView.test.js
- rn/Teacher/src/modules/files/ViewFile.js
- rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
- rn/Teacher/src/modules/speedgrader/comments/AudioComment.js
refs: MBL-12261
release note: Local storage improvements
> Store Teacher files in temporary directory

- AllTheThings.xcworkspace/contents.xcworkspacedata
- Canvas.xcworkspace/contents.xcworkspacedata
- Canvas/Canvas.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/AppEnvironment/Secret.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Student/Student.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
> Cleanup framework references

- Core/Core/Database/CoreData/Models/Assignment.swift
- Core/Core/LTI/LTITools.swift
- Core/Core/Router/Router.swift
- Core/CoreTests/Database/Models/AssignmentTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
- TestsFoundation/TestsFoundation/Router/TestRouter.swift
> Launch external tool type assignments

- Student/Student.xcodeproj/project.pbxproj
> Remove recovered obsolete reference

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/Extensions/UITableViewCellExtensionsTests.swift
> Add UITableViewCellExtensions tests

- rn/Teacher/index.ios.js
- rn/Teacher/src/utils/__tests__/clear-cache.test.js
- rn/Teacher/src/utils/clear-cache.js
refs: MBL-12261
affects: teacher, student
> Clear caches directory

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsAnnotationService.swift
- CanvasCore/CanvasCore/PDF/CanvadocView.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/AppEnvironment/CacheManager.swift
- Core/Core/DocViewer/DocViewerSession.swift
- Core/Core/Extensions/URLExtensions.swift
- Core/CoreTests/AppEnvironment/CacheManagerTests.swift
- Core/CoreTests/Extensions/URLExtensionsTests.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Delete SpeedGrader Cache

- Canvas/Canvas/Shrug/Router+Canvas.swift
- Core/Core/Views/HorizontalMenuView.swift
- Student/Student/Courses/Syllabus/SyllabusPresenter.swift
- Student/Student/Courses/Syllabus/SyllabusViewController.storyboard
- Student/Student/Courses/Syllabus/SyllabusViewController.swift
- Student/StudentUnitTests/Courses/Syllabus/SyllabusPresenterTests.swift
> only show actionable items on syllabus if there is not hmtl body

- README.md
> Add docs about connecting to a portal instance

- Cartfile.resolved
- Student/StudentUITests/StudentUITests.swift
- Student/StudentUITests/Tests/StudentTest.swift
> Use new SwiftUITest

- Student/Student/RouterViewController.swift
- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
> make each rubric circle it's own button

- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Submissions/SubmissionRubric/RubricCollectionViewCell.xib
- Student/Student/Submissions/SubmissionRubric/RubricLongDescriptionViewController.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
> Open long description of rubric

- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizDetailsViewController.swift
- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigTemplate.html
- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigView.swift
Fixes media playing in old quizzes
extra: remove ugly selection on padding cells
extra: use newer content size change detection
refs: MBL-12256
release note: Fixed playing audio and video in quizzes
> Convert WhizzyWigView to WKWebView

- Canvas/CanvasKit1/API Classes/CKCanvasAPI.h
- Canvas/CanvasKit1/API Classes/CKCanvasAPI.m
- Canvas/CanvasKit1/Models/CKAttachment.h
- Canvas/CanvasKit1/Models/CKAttachment.m
- Canvas/TechDebt/People/ProfileViewController.m
refs: MBL-12264
release note: Fixed an issue with updating user avatars
This bug only affected users in accounts with vanity urls. I verified
that it works on both vanity urls and regular canvas domains.
> Fix updating avatar

- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.storyboard
refs: MBL-12321
release note: Fixed module headers to wrap instead of truncate
> Wrap module header text

- Core/Core/AppEnvironment/CacheManager.swift
- Core/CoreTests/AppEnvironment/CacheManagerTests.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Fix running TeacherTests on device

- rn/Teacher/src/canvas-api/flow/assignments.js
- rn/Teacher/src/modules/submissions/list/get-submissions-props.js
refs: MBL-12341
release note: Fixed an error when grading a section assignment
> Fix fatal error in section assignment

- rn/Teacher/ios/Teacher/AppDelegate.swift
> Avoid TeacherTests sadness on bitrise

- Core/Core/en.lproj/Localizable.stringsdict
- Core/CoreTests/Models/Viewable/GradeViewableTests.swift
- Core/CoreTests/Views/GradeCircleViewTests.swift
- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
- Student/StudentUITests/Tests/AssignmentDetailsPageTest.swift
- Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
refs: MBL-12303
releast note: none
> Ensure rubric view is accessible

- rn/Teacher/src/modules/submissions/list/__tests__/map-state-to-props.test.js
- rn/Teacher/src/modules/submissions/list/get-submissions-props.js
refs: MBL-12342
release note: Sort submissions by the user's sortable name
> Use sortable_name not name

- rn/Teacher/src/modules/pages/edit/PageEdit.js
- rn/Teacher/src/modules/pages/edit/__tests__/__snapshots__/PageEdit.test.js.snap
refs: MBL-12346
release note: Fix issue causing error when creating and editing pages
> Fix create/edit pages

- Canvas/Canvas/CanvasAppDelegate+Helm.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Fix accidental login start shown

- Core/Core/WrongApp/WrongAppViewController.swift
- Parent/Parent/Router/Router+Routes.swift
> Use LoginDelegate instead of WrongAppViewControllerDelegate

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> Use button title instead of external label

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
> Make submission picker button opaque when disabled

- Core/Core/Views/TitleSubtitleView.xib
> Make nav title a heading for VO

- Parent/Parent/Airwolf/Canvas/CalendarEvents.swift
- Parent/Parent/Dashboard/Calendar/CalendarEventCellViewModel.swift
- Parent/Parent/Dashboard/Calendar/CalendarEventListViewController.swift
refs: MBL-12138
release note: Fixed a bug that would prevent status labels from showing
Now that the bug has been fixed by MBL-11071, this removes the special
case code that was hiding status labels.
> Fix missing status labels in Parent

- Core/Core/API/APIDiscussion.swift
- Core/Core/API/APIRubric.swift
- Core/Core/Database/CoreData/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Database/CoreData/Models/DiscussionTopic.swift
- Core/Core/Database/CoreData/Models/Rubric.swift
- Core/CoreTests/Database/Models/DiscussionTopicTests.swift
- Student/Student/Courses/Syllabus/SyllabusActionableItemsPresenter.swift
- Student/Student/Courses/Syllabus/SyllabusActionableItemsViewController.swift
> Fix syllabus loading assignments

- Core/Core/Login/LoginFindSchoolViewController.storyboard
> Disable auto-correct on domain picker

- Core/Core/ActAsUser/ActAsUserViewController.storyboard
> Disable selection on masquerade cell

- Student/Student/Courses/Syllabus/SyllabusPresenter.swift
- Student/Student/Courses/Syllabus/SyllabusViewController.swift
- Student/StudentUnitTests/Courses/Syllabus/SyllabusPresenterTests.swift
refs: MBL-12344
release note: Fixed links in Syllabus
> Handle deep links in Syllabus

- rn/Teacher/flow/app-state.js
- rn/Teacher/src/canvas-api/apis/users.js
- rn/Teacher/src/canvas-api/flow/user.js
- rn/Teacher/src/modules/courses/components/CourseCard.js
- rn/Teacher/src/modules/courses/components/__tests__/CourseCard.test.js
- rn/Teacher/src/modules/courses/components/__tests__/__snapshots__/CourseCard.test.js.snap
- rn/Teacher/src/modules/dashboard/Dashboard.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
- rn/Teacher/src/modules/dashboard/__tests__/map-state-to-props.test.js
- rn/Teacher/src/modules/userInfo/__tests__/actions.test.js
- rn/Teacher/src/modules/userInfo/__tests__/reducer.test.js
- rn/Teacher/src/modules/userInfo/actions.js
- rn/Teacher/src/modules/userInfo/reducer.js
- rn/Teacher/src/redux/__templates__/app-state.js
refs: MBL-12388
release note: Respect the color overlays user setting
> Respect hide overlay setting on dashboard

- Student/Student/Submissions/SubmissionRubric/RubricViewController.storyboard
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
> Rubric empty state

- rn/Teacher/src/common/__tests__/show-color-overlay-for-course.test.js
- rn/Teacher/src/common/show-color-overlay-for-course.js
- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
- rn/Teacher/src/modules/courses/__tests__/__snapshots__/CourseNavigation.test.js.snap
- rn/Teacher/src/modules/tabs/TabsList.js
refs: MBL-12390
This PR only addresses the course details part of this ticket
> Respect hide overlay setting on course details

- rn/Teacher/src/canvas-api/apis/users.js
- rn/Teacher/src/modules/courses/user-prefs/UserCoursePreferences.js
- rn/Teacher/src/modules/courses/user-prefs/__tests__/UserCoursePreferences.test.js
- rn/Teacher/src/modules/courses/user-prefs/__tests__/__snapshots__/UserCoursePreferences.test.js.snap
- rn/Teacher/src/modules/courses/user-prefs/__tests__/map-state-to-props.test.js
- rn/Teacher/src/modules/courses/user-prefs/map-state-to-props.js
- rn/Teacher/src/modules/userInfo/__tests__/actions.test.js
- rn/Teacher/src/modules/userInfo/__tests__/reducer.test.js
- rn/Teacher/src/modules/userInfo/actions.js
- rn/Teacher/src/modules/userInfo/reducer.js
> Respect color overlay settings in course preferences and allow editing

- Core/Core/API/APIBrandVariables.swift
refs: MBL-12396
release note: Fixed a crash during login
> Make sure we don't crash if APIBrand is missing stuff

- Core/Core/Login/LoginFindSchoolPresenter.swift
- Core/Core/Login/LoginFindSchoolViewController.swift
- Core/CoreTests/Login/LoginFindSchoolPresenterTests.swift
refs: MBL-12397
release note: Fixed a bug preventing SAML login
> Fix SAML login when there are multiple entries

- scripts/generate-release-notes.js
> Fix the generate-release-notes script

- Canvas/Canvas/Canvas.entitlements
- Canvas/Canvas/CanvasAppDelegate.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Use Cases/GetSSOLogin.swift
- Core/CoreTests/CoreTestCase.swift
- Core/CoreTests/Use Cases/GetSSOLoginTests.swift
- Student/Student/AppDelegate.swift
- Student/Student/Student.entitlements
refs: MBL-12292
release note: Allow SSO login from other apps
> Handle SSO universal links

- rn/Teacher/src/modules/courses/components/CourseCard.js
- rn/Teacher/src/modules/courses/components/__tests__/__snapshots__/CourseCard.test.js.snap
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
refs: MBL-12380
release note: Fix Voice Over focus on the dashboard course card
> Fix course card a11y

- rn/Teacher/src/redux/middleware/persist.js
refs: MBL-12419
affects: student,teacher
release note: Fixed a bug where the dashboard would have an error
> Bump store version

- Core/Core/Views/HorizontalMenuViewCell.swift
> MBL-12443 add selected to accessibility label on syllabus

- Canvas/GradesWidget/GradesTodayWidgetViewController.swift
refs: MBL-12307
release note: Fix layout edge cases for the grade widget
> Fix empty states and errors

- CanvasCore/CanvasCore/People/Backdrop/BackdropPickerViewController.swift
> MBL-12426 add some accessibility to cover images

- Canvas/Canvas/Info.plist
- rn/Teacher/ios/Teacher/Info.plist
> MBL-12440 add app spoken name

- CanvasCore/CanvasCore/People/Pandatar/InfinitePagedImagesView.swift
> Make panda builder accessible

- rn/Teacher/src/common/__tests__/__snapshots__/text.test.js.snap
- rn/Teacher/src/common/text.js
- rn/Teacher/src/modules/discussions/list/DiscussionsRow.js
- rn/Teacher/src/modules/discussions/list/__tests__/__snapshots__/DiscussionsList.test.js.snap
- rn/Teacher/src/modules/discussions/list/__tests__/__snapshots__/DiscussionsRow.test.js.snap
- rn/Teacher/src/modules/quizzes/list/__tests__/__snapshots__/QuizRow.test.js.snap
- rn/Teacher/src/modules/quizzes/list/__tests__/__snapshots__/QuizzesList.test.js.snap
> Fix VO on discussions list

- rn/Teacher/src/modules/discussions/details/Reply.js
refs: MBL-12436
release note: Fixed discussion thread  unread indicator missing in Voice Over
> Add VO label to unread dot

- Core/Core/Profile/ProfileViewController.swift
- Parent/Parent/Profile/ProfilePresenter.swift
refs: MBL-12402
release note: Fixed a crash when accessing the Help menu on iPad
> [Parent] Fix Help menu crash on iPad

- rn/Teacher/src/modules/courses/user-prefs/UserCoursePreferences.js
- rn/Teacher/src/modules/courses/user-prefs/__tests__/UserCoursePreferences.test.js
- rn/Teacher/src/modules/courses/user-prefs/__tests__/__snapshots__/UserCoursePreferences.test.js.snap
- rn/Teacher/src/modules/courses/user-prefs/components/ColorButton.js
- rn/Teacher/src/modules/courses/user-prefs/components/__tests__/__snapshots__/ColorButton.test.js.snap
> Align course card colors to web & add a11y names

- rn/Teacher/src/common/components/rich-text-editor/ColorPicker.js
- rn/Teacher/src/common/components/rich-text-editor/__tests__/ColorPicker.test.js
- rn/Teacher/src/common/components/rich-text-editor/__tests__/__snapshots__/ColorPicker.test.js.snap
> Port colors (& names) from new RCE to old

- package.json
- scripts/svg2pdf.js
> Fix svg2pdf doc

- rn/Teacher/src/common/components/Avatar.js
- rn/Teacher/src/modules/groups/__tests__/__snapshots__/GroupList.test.js.snap
- rn/Teacher/src/modules/speedgrader/comments/__tests__/__snapshots__/CommentsTab.test.js.snap
- rn/Teacher/src/modules/submissions/list/__tests__/__snapshots__/SubmissionList.test.js.snap
> Add context to Avatar button

- Canvas/Canvas/Modules/Module Items/ModuleItemDetailViewController.swift
- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/Extensions/NSObject+Reactive.swift
refs: MBL-12381
Removes the next/prev buttons from the accessibility tree Switch Control is enabled and the button is disabled.
> Improve next/prev experience for switch control

- Core/Core/Views/HorizontalMenuView.swift
- Core/Core/Views/HorizontalMenuViewCell.swift
- Student/Student/Courses/Syllabus/SyllabusViewController.swift
> Improve a11y of syllabus menu

- rn/Teacher/src/common/components/Avatar.js
- rn/Teacher/src/common/components/__tests__/__snapshots__/Avatar.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneePicker.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneeRow.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneeSearch.test.js.snap
> MBL-12441 people screen avatar should not be accessible

- Student/Student/Submissions/SubmissionButton/SubmissionButtonAlertView.swift
- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
> Fix popovers on iPad

- Canvas/TechDebt/Files and Folders/FileViewController.m
refs: MBL-12423
This was only an issue when VO setting for "Native Images" is set to
"With descriptions".
> Fix VO to image files

- Canvas/Canvas/Shrug/Router+Canvas.swift
- CanvasCore/CanvasCore/FeatureFlags/FeatureFlags.swift
- rn/Teacher/src/common/feature-flags.js
- rn/Teacher/src/routing/register-screens.js
It never worked anyway
refs: MBL-12429
> Remove newGroupNavigation flag

- rn/Teacher/src/common/components/AccessIcon.js
- rn/Teacher/src/common/components/__tests__/AccessIcon.test.js
refs: MBL-12437 MBL-12439 MBL-12442
> MBL-12437 MBL-12439 MBL-12442 turn off published unpublished label when in student app

- rn/Teacher/src/modules/courses/edit-favorites/EditFavorites.js
- rn/Teacher/src/modules/courses/edit-favorites/__tests__/__snapshots__/EditFavorites.test.js.snap
- rn/Teacher/src/modules/dashboard/Dashboard.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
> MBL-12427 add more context to edit favorites

- Canvas/Canvas/Settings/LandingPageViewController.swift
refs: MBL-12382
release note: Fixed landing page settings to match names in nav
> Align landing page settings to tab labels

- rn/Teacher/src/modules/address-book/AddressBook.js
> Fix address book a11y labels

- README.md
> Update example script in README

- CanvasCore/CanvasCore/React Native Modules/A11yGroupManager.m
- rn/Teacher/src/modules/speedgrader/SpeedGrader.js
- rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/SpeedGrader.test.js.snap
- rn/Teacher/test/scripts/jestSetup.js
> Fix VO in Speed Grader

- rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Inbox.test.js.snap
- rn/Teacher/src/modules/inbox/components/ConversationRow.js
- rn/Teacher/src/modules/inbox/components/__tests__/__snapshots__/ConversationRow.test.js.snap
refs: MBL-12431
This mimicks the web by only reading off the subject line, date,
starred, and unread status of the conversation rows.
> Simplify inbox conversation a11y labels

- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
This affects NEW student assignment submissions
refs: MBL-12454
> Add media button a11y label

- rn/Teacher/src/modules/files/ViewFile.js
- rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
refs: MBL-12463
release note: Improved accessibility while viewing a file
> Announce file url copied

- Frameworks/CanvasKeymaster/CanvasKeymaster/SupportTicket/ImpactTableViewController.m
- Frameworks/CanvasKeymaster/CanvasKeymaster/SupportTicket/SupportTicketViewController.m
refs: MBL-12462
affects: student,teacher
release note: Improved accessibility on report a problem
> Fix report a problem a11y labels

- Core/Core/Use Cases/UploadBatch.swift
- Core/Core/Use Cases/UploadFileComment.swift
- Core/CoreTests/Use Cases/UploadBatchTests.swift
- Core/CoreTests/Use Cases/UploadFileCommentTests.swift
> Fix submitting a file upload more than once

- rn/Teacher/src/common/components/Avatar.js
- rn/Teacher/src/common/components/__tests__/__snapshots__/Avatar.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneePicker.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneeRow.test.js.snap
- rn/Teacher/src/modules/assignee-picker/__tests__/__snapshots__/AssigneeSearch.test.js.snap
> Remove redundant accessible=false

- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
> Read rubric circles as text in Student

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUnitTests/Submissions/ArcSubmission/ArcSubmissionPresenterTests.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
> Support viewing Arc submissions

- CanvasCore/CanvasCore/LTI/ExternalToolManager.swift
> Use session baseURL for LTI launches

- CanvasCore/CanvasCore/Push Notifications/View Controller/NotificationPreferencesTableViewCell.swift
- CanvasCore/CanvasCore/Push Notifications/View Controller/NotificationPreferencesViewController.swift
> Fix a11y in notification preferences

- Core/Core/Use Cases/UploadFileComment.swift
The UploadFileCommentTests were flaky because of occasional merge conflicts here. I hope this helps. 🤞
> Fix merge conflict in file upload comments

- rn/Teacher/src/modules/discussions/details/Reply.js
> Fix discussion ratings a11y

- rn/Teacher/src/common/components/rows/RowWithDateInput.js
- rn/Teacher/src/common/components/rows/__tests__/__snapshots__/RowWithDateInput.test.js.snap
- rn/Teacher/src/modules/assignment-details/AssignmentDetailsEdit.js
- rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDatesEditor.test.js.snap
- rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDetailsEdit.test.js.snap
- rn/Teacher/src/modules/assignment-details/components/AssignmentDatesEditor.js
- rn/Teacher/src/modules/assignment-details/components/__tests__/__snapshots__/AssignmentDatesEditor.test.js.snap
- rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap
refs: MBL-12478
release note: Improved accessibility for assignment, discussion, and announcement editing
> Add button traits to several buttons

- Core/Core/Login/LoginWebPresenter.swift
- Core/Core/Login/LoginWebViewController.swift
- Core/CoreTests/Login/LoginWebPresenterTests.swift
refs: MBL-12493
release note: Fixed a login bug with 3rd party providers
> Fix 3rd party signin

- Student/StudentUnitTests/Courses/CourseNavigation/CourseNavigationPresenterTests.swift
> Fix flaky unit tests

- rn/Teacher/src/common/components/rows/RowWithTextInput.js
- rn/Teacher/src/common/components/rows/__tests__/__snapshots__/RowWithTextInput.test.js.snap
- rn/Teacher/src/modules/announcements/edit/__tests__/__snapshots__/AnnouncementEdit.test.js.snap
- rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDetailsEdit.test.js.snap
- rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap
refs: MBL-12480, MBL-12481, MBL-12482
> Fix RowWithTextInput accessibility

- CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html
- Core/Core/Views/CoreWebView.swift
refs: MBL-12464
release note: Fixed a bug with discussion content white space
> Prevent loops in checkSize

- rn/Teacher/src/modules/profile/Profile.js
- rn/Teacher/src/modules/profile/__tests__/Profile.test.js
refs: MBL-12492
release note: Fixed a bug in settings
> Fix displaying ToU

- rn/Teacher/src/modules/quizzes/submissions/__tests__/__snapshots__/QuizSubmissionList.test.js.snap
- rn/Teacher/src/modules/submissions/SubmissionsHeader.js
- rn/Teacher/src/modules/submissions/__tests__/__snapshots__/SubmissionsHeader.test.js.snap
- rn/Teacher/src/modules/submissions/list/__tests__/__snapshots__/SubmissionList.test.js.snap
refs: MBL-12483
release note: Improve accessibility for submission list filtering
> Add accessibility label to filter button

- rn/Teacher/src/modules/speedgrader/comments/CommentsTab.js
- rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentsTab.test.js
refs: MBL-12486
release note: Improve accessibility
> Fix comments empty tab a11y

- CanvasCore/CanvasCore/LTI/ExternalToolManager.swift
- CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html
- CanvasCore/CanvasCore/WhizzyWig/CanvasWebView.swift
- Core/Core/Extensions/URLComponentsExtensions.swift
- Core/Core/LTI/LTITools.swift
- Core/Core/Views/CoreWebView.swift
- Core/Core/Views/CoreWebViewController.swift
- Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift
- Core/CoreTests/LTI/LTIToolsTests.swift
- Core/CoreTests/Views/CoreWebViewTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/Student/Courses/Syllabus/SyllabusViewController.swift
- Student/Student/Submissions/SubmissionDetails/ExternalToolSubmissionContentViewController.storyboard
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
> Handle external tool links in CoreWebView

- rn/Teacher/src/modules/speedgrader/components/GradePicker.js
- rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/GradePicker.test.js.snap
refs: MBL-12484
release note: Improve speedgrader accessibility
> Fix speedgrader grade a11y

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/Canvas.xcodeproj/xcshareddata/xcschemes/Canvas.xcscheme
- Canvas/Canvas.xcodeproj/xcshareddata/xcschemes/GradesWidget.xcscheme
- Canvas/CanvasUITests/CanvasUITests.swift
- Canvas/CanvasUITests/Info.plist
> Add CanvasUITests target

- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.storyboard
refs: MBL-12465
release note: Fixed module items names not always being displayed
> Fix module item names sometimes not displaying

- Core/Core/WrongApp/WrongAppLinkView.swift
- Core/Core/WrongApp/WrongAppLinkView.xib
- Core/Core/WrongApp/WrongAppViewController.storyboard
- Core/Core/WrongApp/WrongAppViewController.swift
refs: MBL-12513
affects: Teacher, Parent
> Fix WrongApp app buttons

- CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html
- Core/Core/Views/CoreWebView.swift
> Fix sizing issue in discussions

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIQuiz.swift
- Core/Core/API/APIQuizRequestable.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Quiz.swift
- Core/Core/Models/QuizSubmission.swift
- Core/Core/Models/QuizSubmissionWorkflowState.swift
- Core/Core/Router/Route.swift
- Core/Core/Use Cases/GetQuiz.swift
- Core/CoreTests/API/APIQuizRequestableTests.swift
- Core/CoreTests/Models/QuizSubmissionTests.swift
- Core/CoreTests/Router/RouteTests.swift
- Core/CoreTests/Use Cases/GetQuizTests.swift
- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
- Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
- TestsFoundation/TestsFoundation/API/APIQuiz.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIQuizFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/QuizFixture.swift
Adds resume & retake quiz logic. Makes the button go to old details page, instead of doing nothing.
refs: MBL-10185
affects: none
> Handle quiz takability

- Student/StudentUnitTests/Groups/GroupNavigation/GroupNavigationPresenterTests.swift
> Fix flaky GroupNavigationPresenterTests

- rn/Teacher/src/modules/courses/__tests__/courses-reducer.test.js
- rn/Teacher/src/modules/courses/courses-reducer.js
refs: MBL-12491
affects: Teacher,Student
release note: Fixed an issue where you might not be able to create a discussion
> Fix permissions reducer

- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsSectionContainerView.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsSectionContainerView.xib
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> MBL-10246 add section view to help with hiding views when locked

- Canvas/CanvasUITests/Login/LoginTests.swift
> Added LDAP test

- Canvas/CanvasUITests/Login/LoginTests.swift
> Added test for school search up

- rn/Teacher/src/modules/groups/__tests__/group-entities-reducer.test.js
- rn/Teacher/src/modules/groups/group-entities-reducer.js
refs: MBL-12533
release note: Fixed issue with deep linking to group discussions
> Fix issue deeplinking to group discussions

- Canvas/CanvasUITests/CanvasUITests.swift
- Canvas/CanvasUITests/Login/LoginTests.swift
> Fixed all login UI tests succeed when run at once

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
- Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
> Fix quiz detail when quiz submission doesn't load

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Announcement/AnnouncementTests.swift
> UI test for announcements list matching web order

- Canvas/Canvas/CanvasAppDelegate.swift
- Canvas/CanvasKit1/Models/CKAttachment.h
- Canvas/TechDebt/Assignments/CKRichTextInputView.m
- Canvas/TechDebt/Files and Folders/FileViewController.h
- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigView.swift
- Frameworks/CanvasKeymaster/CanvasKeymaster/SupportTicket/SupportTicketViewController.h
- Frameworks/CanvasKit/CanvasKit/Networking/CKIClient.h
- Student/Student/Submissions/SubmissionRubric/RubricViewController.storyboard
> Fix lots of warnings

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/Student/RouterViewController.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetails.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetailsTests.swift
> MBL-10246 fix lock section panda appearing and moving all around and doing panda things when it shouldn't

- Core/Core/ActAsUser/ActAsUserViewController.swift
> Dismiss keyboard before masquerade

- Canvas/Canvas/Modules/Module Items/ModuleItemViewModel.swift
- CanvasCore/CanvasCore/Helm/Helm.swift
refs: MBL-12514
release note: Fixed a bug that would cause external tools to launch automatically within modules
> Fix LTI tools auto launching in modules

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Dashboard/CourseInvitation.swift
- Canvas/CanvasUITests/Dashboard/DashboardTests.swift
- Canvas/CanvasUITests/Dashboard/GlobalAnnouncement.swift
- TestsFoundation/TestsFoundation/Element/Element.swift
- TestsFoundation/TestsFoundation/Element/ElementWrapper.swift
- rn/Teacher/src/modules/dashboard/CourseInvite.js
- rn/Teacher/src/modules/dashboard/GlobalAnnouncementRow.js
- rn/Teacher/src/modules/dashboard/__tests__/CourseInvite.test.js
- rn/Teacher/src/modules/dashboard/__tests__/Dashboard.test.js
- rn/Teacher/src/modules/dashboard/__tests__/GlobalAnnouncementRow.test.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/CourseInvite.test.js.snap
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/GlobalAnnouncementRow.test.js.snap
refs: MBL-12583, MBL-12584
affects: none
> Add UI tests for global announcements

- rn/Teacher/src/modules/speedgrader/comments/CommentInput.js
> Fix empty space above keyboard in SG comments

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/ShareSubmission/Base.lproj/MainInterface.storyboard
- Canvas/ShareSubmission/Info.plist
- Canvas/ShareSubmission/ShareViewController.swift
This just adds the empty target. Wanted to get this in to avoid merge
conflicts.
> Add SubmitAssignment share extension target

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Announcements/AnnouncementTests.swift
- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/Course Files/CourseFileTests.swift
- Canvas/CanvasUITests/Courses/CourseNavigation.swift
- Canvas/CanvasUITests/Dashboard/Dashboard.swift
- Canvas/CanvasUITests/Dashboard/DashboardTests.swift
- Canvas/CanvasUITests/Login/LoginTests.swift
- Canvas/CanvasUITests/People/PeopleTests.swift
- Canvas/CanvasUITests/Profile/Profile.swift
- Canvas/CanvasUITests/Profile/ProfileTests.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Profile/ProfileViewController.xib
- TestsFoundation/TestsFoundation/Element/Element.swift
- TestsFoundation/TestsFoundation/Element/ElementWrapper.swift
- rn/Teacher/src/common/components/rows/RowWithSwitch.js
- rn/Teacher/src/modules/assignment-details/__tests__/__snapshots__/AssignmentDetailsEdit.test.js.snap
- rn/Teacher/src/modules/profile/Profile.js
- rn/Teacher/src/modules/profile/__tests__/Profile.test.js
- rn/Teacher/src/modules/profile/__tests__/__snapshots__/Profile.test.js.snap
- rn/Teacher/src/modules/quizzes/edit/__tests__/__snapshots__/QuizEdit.test.js.snap
extra: move some test elements out of test files
refs: MBL-12571
affects: none
> Add Show Grades UI test

- Canvas/CanvasUITests/Announcements/AnnouncementTests.swift
- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/Calendar/CalendarTests.swift
- Canvas/CanvasUITests/CanvasUITests.swift
- Canvas/CanvasUITests/Course Files/CourseFileTests.swift
- Canvas/CanvasUITests/Dashboard/DashboardTests.swift
- Canvas/CanvasUITests/Login/LoginTests.swift
- Canvas/CanvasUITests/People/PeopleTests.swift
- Canvas/CanvasUITests/Profile/ProfileTests.swift
- Core/Core/AppEnvironment/Secret.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- Student/Student.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Element/Element.swift
- TestsFoundation/TestsFoundation/Element/LoginFindSchool.swift
- TestsFoundation/TestsFoundation/Element/LoginStart.swift
- TestsFoundation/TestsFoundation/Element/LoginWeb.swift
- TestsFoundation/TestsFoundation/Extensions/XCUIApplicationExtensions.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestUser.swift
Also keep around the keychain entry to skip login flow on subsequent logins
refs: MBL-12540
affects: none
> Keep test users secret

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Discussions/DiscussionList.swift
- Canvas/CanvasUITests/Discussions/DiscussionListTests.swift
- TestsFoundation/TestsFoundation/Element/LoginWeb.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift
refs: MBL-12579, MBL-12580
affects: none
> Add DiscussionList tests

- CanvasCore/CanvasCore/Localization/LocalizationManager.swift
- Core/Core/AppEnvironment/LocalizationManager.swift
- scripts/translations/import.js
refs: MBL-12675
release note: Fixed a custom language pack
> Handle unimelb custom language pack

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Dashboard/DashboardTests.swift
- Canvas/CanvasUITests/Discussions/DiscussionDetails.swift
- Canvas/CanvasUITests/Discussions/DiscussionDetailsTests.swift
- Canvas/CanvasUITests/Profile/Profile.swift
- Canvas/CanvasUITests/Profile/ProfileTests.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- TestsFoundation/TestsFoundation/Element/Element.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift
- rn/Teacher/src/common/components/AttachmentView.js
- rn/Teacher/src/modules/discussions/details/DiscussionDetails.js
> Add test to preview discussion attachment

- Canvas/CanvasUITests/Discussions/DiscussionDetailsTests.swift
- Canvas/CanvasUITests/Discussions/DiscussionList.swift
- Canvas/CanvasUITests/Discussions/DiscussionListTests.swift
- Student/Student.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Element/NavBar.swift
- rn/Teacher/src/modules/discussions/list/DiscussionsRow.js
- rn/Teacher/src/modules/discussions/list/__tests__/DiscussionsList.test.js
- rn/Teacher/src/modules/discussions/list/__tests__/DiscussionsRow.test.js
- rn/Teacher/src/modules/discussions/list/__tests__/__snapshots__/DiscussionsList.test.js.snap
- rn/Teacher/src/modules/discussions/list/__tests__/__snapshots__/DiscussionsRow.test.js.snap
> Add tests for Discussion links

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/Canvas/Calendar/CalendarTabViewController.swift
- Canvas/Canvas/Notifications/NotificationsTab.swift
- Canvas/Canvas/RootViewController.swift
- Canvas/Canvas/To Do/ToDoTab.swift
- Canvas/CanvasUITests/Calendar/CalendarTests.swift
- Canvas/CanvasUITests/Dashboard/Dashboard.swift
- Canvas/CanvasUITests/Inbox/InboxTests.swift
- Canvas/CanvasUITests/Login/LoginTests.swift
- Canvas/CanvasUITests/Notifications/NotificationsListTests.swift
- CanvasCore/CanvasCore/Inbox/inboxTab.swift
- Student/Student/RootViewController.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Element/TabBar.swift
- rn/Teacher/ios/Teacher/RootTabBarController.swift
extra: Updates teacher tabs & adds ids to tabs
refs: MBL-12614
release note: Improve navigation accessibility
> Add Notifications test

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Announcements/AnnouncementTests.swift
- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/Calendar/CalendarTests.swift
- Canvas/CanvasUITests/Course Files/CourseFileTests.swift
- Canvas/CanvasUITests/Course Groups/CourseGroupTests.swift
- Canvas/CanvasUITests/Courses/CourseNavigation.swift
- Canvas/CanvasUITests/Dashboard/Dashboard.swift
- Canvas/CanvasUITests/Inbox/InboxTests.swift
- Canvas/CanvasUITests/Pages/PageTests.swift
- Canvas/CanvasUITests/Pages/Pages.swift
- Canvas/CanvasUITests/People/PeopleTests.swift
refs: MBL-12573, MBL-12615, MBL-12576, MBL-12574
> UI tests for groups, pages, and links

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/CanvasUITests.swift
- Canvas/CanvasUITests/Modules/ModulesTests.swift
- Canvas/CanvasUITests/Profile/ProfileTests.swift
- Canvas/CanvasUITests/Todo/TodoListTests.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestCase.swift
- rn/Teacher/src/common/components/RichContent.js
- rn/Teacher/src/common/components/__tests__/RichContent.test.js
- rn/Teacher/src/common/components/__tests__/__snapshots__/RichContent.test.js.snap
- rn/Teacher/src/common/feature-flags.js
> Add todo list tests

- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/Dashboard/DashboardTests.swift
- Canvas/CanvasUITests/Modules/ModulesTests.swift
> UI tests for grades and dashboard

- Student/Student/Submissions/SubmissionRubric/RubricLongDescriptionViewController.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
> Render rich text for rubric long descriptions

- Core/Core/UITestHelpers/UITestHelpers.swift
> fix UI tests in X, XS, & XR

- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
> MBL-12695 - display rubric even when there is no assessment

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/Extensions/ProcessInfoExtensionsTests.swift
> Improve coverage of ProcessInfoExtensions.swift

- Canvas/Canvas/Profile/UserPreferences.swift
- Canvas/Canvas/Settings/Base.lproj/Settings.storyboard
- Canvas/Canvas/Settings/LandingPageViewController.swift
- Canvas/CanvasUITests/Profile/Profile.swift
- Canvas/CanvasUITests/Profile/ProfileTests.swift
- TestsFoundation/TestsFoundation/Element/LoginStart.swift
extra: remove padding around settings list & use safe area
extra: use same model for setting & using landing page
refs: MBL-12700
release note: Fixed setting To Do or Inbox as landing page
> Fix landing page setting

- rn/Teacher/src/modules/courses/edit-favorites/EditFavorites.js
- rn/Teacher/src/modules/courses/edit-favorites/__tests__/__snapshots__/EditFavorites.test.js.snap
refs: MBL-12712
release note: Fixed a layout bug in the favorite courses list
> Fix Edit favorites overflow

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIAssignment.swift
- Core/Core/API/APIAssignmentRequestable.swift
- Core/Core/API/APIList.swift
- Core/Core/Models/Assignment.swift
- Core/CoreTests/API/APIAssignmentRequestableTests.swift
- Core/CoreTests/API/APIListTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIAssignmentFixture.swift
> Fix assignment details grades for observers

- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigTemplate.html
- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigView.swift
refs: MBL-12710
release note: Fixed external tools in quiz content
> Fixed rich content in quizzes

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Courses/CourseNavigation.swift
- Canvas/CanvasUITests/Modules/ModulesTests.swift
- Canvas/CanvasUITests/Quizzes/Quiz.swift
- Canvas/CanvasUITests/Quizzes/QuizTests.swift
refs: MBL-12662, MBL-12663, MBL-12664, MBL-12665
> Quiz UI tests for student

- rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-12702
release note: fix push notification bug
> MBL-12702 [Teacher] handle push that comes in as launch options

- Student/Student/Courses/Syllabus/SyllabusViewController.swift
> MBL-12819 Change label on syllabus from `Assignments` to `Summary`

- Canvas/CanvasUITests/Quizzes/Quiz.swift
- Canvas/CanvasUITests/Quizzes/QuizTests.swift
> Fix header on new files

- Canvas/CanvasUITests/Login/LoginTests.swift
- Core/Core/AppEnvironment/MDMManager.swift
- Core/Core/Login/LoginStartPresenter.swift
- Core/Core/Login/LoginStartViewController.storyboard
- Core/Core/Login/LoginStartViewController.swift
- Core/CoreTests/AppEnvironment/MDMManagerTests.swift
- Core/CoreTests/Helpers/MockMDMManager.swift
- Core/CoreTests/Login/LoginStartPresenterTests.swift
refs: MBL-12821
release note: Allowed schools to prefill the host for login
> Allow MDM to set login host & auth provider

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Settings/SettingsAPIClient.swift
- Parent/Parent/Settings/SettingsViewController.swift
- Parent/Parent/Settings/StudentsListViewController.swift
refs: MBL-11041
affects: MBL-11041
release note: Users can now add multiple students
> MBL-11041 - give user ability to add student to observe

- Canvas/SubmitAssignment/SubmitAssignmentPresenter.swift
- Core/Core/API/API.swift
- Core/Core/Constants/HTTPHeaderConstants.swift
- Core/Core/Extensions/UIImageExtensions.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/File.swift
- Core/Core/Use Cases/UploadManager.swift
- Core/CoreTests/Use Cases/UploadManagerTests.swift
- TestsFoundation/TestsFoundation/API/MockURLSession.swift
> Fix file uploads

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIAccount.swift
- Core/Core/API/APILoginWebRequestable.swift
- Core/Core/Login/LoginFindSchoolPresenter.swift
- Core/CoreTests/API/APIAccountResultTests.swift
- Core/CoreTests/API/APILoginWebRequestableTests.swift
- Core/CoreTests/Login/LoginWebPresenterTests.swift
refs: MBL-12816
release note: Fixed an issue with logging in for some accounts
> Handle bad authentication providers

- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
> MBL-12709 - improve a11y on rubrics

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/Announcements/AnnouncementTests.swift
- Canvas/CanvasUITests/Deep Links/DeepLinkTests.swift
refs: MBL-12628, MBL-12641, MBL-12640
> UI tests for announcements and deep links

- Canvas/Canvas/Calendar/UI/View Controller/CalendarDayListViewController.swift
refs: MBL-12719
release note: Fixed calendar bug
> MBL-12719 - prevent assignments from disappearing when on cusp of new day

- Core/Core/API/APIAssignment.swift
- Core/Core/API/APIRubric.swift
- Core/Core/Models/Assignment.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/CoreTests/Models/AssignmentTests.swift
- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
- Student/StudentUnitTests/Submissions/SubmissionRubric/RubricPresenterTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIAssignmentFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIRubricFixture.swift
> MBL-12818 - hide rubric points when setting is true

- Core/Core/LTI/LTITools.swift
- Core/CoreTests/LTI/LTIToolsTests.swift
- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListPresenter.swift
- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.swift
- rn/Teacher/ios/TeacherTests/Modules/ModuleListPresenterTests.swift
refs: MBL-12822
release note: Fixed launching some external tools from modules
> Fix launching LTIs from modules

- Canvas/CanvasUITests/Inbox/InboxTests.swift
- Canvas/CanvasUITests/Quizzes/QuizTests.swift
refs: MBL-12658, MBL-12660, MBL-12661
> UI tests for quizzes

- CanvasCore/CanvasCore/FeatureFlags/FeatureFlags.swift
- rn/Teacher/src/common/__tests__/feature-flags.test.js
- rn/Teacher/src/common/feature-flags.js
> Enable new assignment details

- Canvas/CanvasUITests/Assignments/Assignments.swift
- Canvas/CanvasUITests/Assignments/AssignmentsTests.swift
- Canvas/CanvasUITests/Courses/CourseNavigation.swift
> Test launching Quizzes.NEXT

- rn/Teacher/package.json
- rn/Teacher/yarn.lock
> Pin hyntax to fix RN bundling

- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
> show formsheet modal on ipad when rubric has long desc

- Core/Core/FilePicker/FilePickerViewController.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> Fix picking from library on iPad in landscape

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
> center loading spinner on assignment details on ipad

- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
> dismiss keyboard on scroll on submission comments

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> Fix incorrectly showing upload progress button

- Student/Student/Submissions/SubmissionRubric/RubricCircleView.swift
> add exclusive touch to rubric buttons

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
> get userid even if there is no submission, allowing user to view `Submission & Rubric`

- Core/Core/Profile/ProfileViewController.swift
- Core/Core/Profile/ProfileViewController.xib
> MBL-12832 fix parent version for release

- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizIntroViewController.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIQuizRequestable.swift
- Core/Core/Models/QuizSubmission.swift
- Core/Core/Use Cases/GetQuiz.swift
- Core/Core/Use Cases/GetQuizSubmission.swift
- Core/Core/Use Cases/GetQuizSubmissions.swift
- Core/CoreTests/API/APIQuizRequestableTests.swift
- Core/CoreTests/Use Cases/GetQuizSubmissionTests.swift
- Core/CoreTests/Use Cases/GetQuizSubmissionsTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
API no longer returns question_types in quiz submission included quiz, only in the quiz api.
refs: MBL-12867
> Fix launching native quizzes

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
> MBL-12849 - Add page view tracking for assignment details submissions

- Canvas/Canvas/Modules/Module Items/ModuleItemDetailViewController.swift
- Canvas/Canvas/Modules/Module Items/ModuleItemViewModel.swift
- Canvas/Canvas/Modules/ModulesTableViewController.swift
pork: restore module details loading in master view on iPad
refs: MBL-12906
Test plan:
* View a page through modules
* Change user to a different user
* You should not get an error about "Page not found"
> Fix memory leak in modules

- Core/Core/Models/File.swift
- Core/CoreTests/Models/FileTests.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
> Fix media & non-docviewer file uploads

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> MBL-12875 - always show submissions & rubric button

- Canvas/CanvasUITests/Notifications/NotificationsListTests.swift
- Canvas/CanvasUITests/Todo/TodoListTests.swift
> Skip flaky tests

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
> MBL-12879 - fix locked text when it has mucho HTML

- Core/Core/Models/Viewable/SubmissionViewable.swift
- Core/CoreTests/Models/Viewable/SubmissionViewableTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetailsTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
> Remove submission buttons when assignment is not graded

- Student/Student/Submissions/SubmissionButton/SubmissionButtonAlertView.swift
> MBL-12908 - Change Arc to Studio

- Canvas/SubmitAssignment/Courses/CoursesPresenter.swift
- Canvas/SubmitAssignment/SubmitAssignmentPresenter.swift
- Core/Core/API/APICourseRequestable.swift
- Core/Core/Use Cases/GetCourses.swift
- Core/CoreTests/API/APICourseRequestableTests.swift
- Core/CoreTests/Store/StoreTests.swift
- Core/CoreTests/Store/UseCaseTests.swift
- Core/CoreTests/Use Cases/GetCoursesTest.swift
> Exclude concluded courses in Submit Assignment

- Core/Core/Views/GradeCircleView.swift
- Core/Core/Views/GradeCircleView.xib
- Core/CoreTests/Views/GradeCircleViewTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetails.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetailsTests.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
> Show the grade circle for excused assignments

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
> Fix flickering while files upload

- Core/Core/Models/Submission.swift
- Core/CoreTests/Models/SubmissionTests.swift
- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
> Show submit buttons/labels for unsubmitted graded submissions

- Core/Core/AudioVideo/AudioRecorderViewController.swift
> Pause preview when clearing an audio recording

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/StudentUITests/Assignments/AssignmentDetails/AssignmentDetailsTests.swift
> Tap grade cell to view submission

- Core/Core/DocViewer/DocViewerPresenter.swift
- Core/CoreTests/DocViewer/DocViewerPresenterTests.swift
> Remove highlight annotation from text selection menu

- Canvas/SubmitAssignment/SubmitAssignmentViewController.swift
> Change share extension button to be Submit

- CanvasCore/CanvasCore/Extensions/UINavigationController+Core.swift
- CanvasCore/CanvasCore/Helm/HelmSplitViewController.swift
- CanvasCore/CanvasCore/Helm/HelmViewController.swift
- Core/Core/Views/TitleSubtitleView.swift
> Fix janky subtitle views on iPad with side-by-side

- Student/Student/Submissions/SubmissionDetails/UrlSubmissionContentViewController.storyboard
- Student/Student/Submissions/SubmissionDetails/UrlSubmissionContentViewController.swift
- Student/Student/Submissions/urlSubmission/UrlSubmissionPresenter.swift
> MBL-12890 disable preview button unless there submission has an attachment

- Canvas/Canvas/CanvasAppDelegate.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Extensions/BundleExtensions.swift
- Core/Core/PageViewAnalytics/AppBackgroundHelperProtocol.swift
- Core/Core/PageViewAnalytics/PageViewEventController.swift
- Core/Core/PageViewAnalytics/PageViewEventRequestManager.swift
- Core/CoreTests/PageViewAnalytics/PageViewEventRequestManagerTests.swift
- Core/CoreTests/PageViewAnalytics/PageViewEventViewControllerLoggingProtocolTests.swift
> MBL-12901 - make core safe for extensions

- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
refs: MBL-12892
release note: Fixed placement of conferences unsupported message
> Always show conferences unsupported in detail

- Student/Student/Submissions/SubmissionFiles/SubmissionFilesViewController.swift
> Disable checkview a11y for switch control

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
> Improve a11y in submission viewer

- Student/Student.xcodeproj/project.pbxproj
- Student/Student/RouterViewController.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.storyboard
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/Student/Submissions/SubmissionDetails/Views/SubmissionDetailsLockedEmptyView.swift
- Student/Student/Submissions/SubmissionDetails/Views/SubmissionDetailsLockedEmptyView.xib
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
> MBL-12897 - show empty locked state in submission details on quizzes

- Core/Core/Views/GradeCircleView.swift
> MBL-12950 - add accessibility help to letter grades with a "minus sign"

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/CanvasUITests/ActAsUser/ActAsUserTests.swift
- Core/Core/ActAsUser/ActAsUserPresenter.swift
- Core/Core/ActAsUser/ActAsUserViewController.storyboard
- Core/Core/ActAsUser/ActAsUserViewController.swift
- Core/Core/ActAsUser/ActAsUserWindow.swift
- Core/Core/AppEnvironment/Secret.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Element/ActAsUser.swift
- TestsFoundation/TestsFoundation/UITestCase/UITestUser.swift
refs: MBL-12649, MBL-12650
affects: none
> Add masquerading tests

- Canvas/CanvasUITests/Deep Links/DeepLinkTests.swift
> MBL-12653 - UI tests - deep link to public course page

- Canvas/Canvas.xcodeproj/project.pbxproj
- Canvas/Canvas/Calendar/UI/View Controller/CalendarDayDetailViewController.swift
- Canvas/Canvas/Calendar/UI/View Controller/CalendarWeekDayViewController.swift
- Canvas/Canvas/Modules/Mastery Paths/MasteryPathSelectOptionViewController.swift
> fix all warnings in canvas target

- Student/StudentUnitTests/Pages/PageList/PageListPresenterTests.swift
> Fix testLoadPages()

- README.md
> Update connecting to local canvas docs

- Frameworks/CanvasKeymaster/CanvasKeymaster.xcodeproj/project.pbxproj
> MBL-12967 fix all warnings in KeyMaster

- Student/CanvasKit1/CanvasKit1.h
- Student/TechDebt/TechDebt.h
> MBL-12967 fix missing headers warnings in Student

- Student/CanvasUITests/Announcements/AnnouncementTests.swift
- Student/CanvasUITests/CanvasUITests.swift
> Fix first test being flaky in CanvasUITests

- Frameworks/CanvasKit/CanvasKit.xcodeproj/project.pbxproj
- Student/CanvasKit1/UI Classes/CKActionSheetWithBlocks.h
- Student/CanvasKit1/UI Classes/CKActionSheetWithBlocks.m
- Student/CanvasKit1/UI Classes/CKCommentViewController.m
- Student/TechDebt/Assignments/CKAttachmentManager.m
- Student/TechDebt/Assignments/Submissions/ReceivedFilesViewController.m
- Student/TechDebt/Assignments/Submissions/SubmissionWorkflowController.m
- Student/TechDebt/People/ProfileViewController.m
- Student/TechDebt/Web Browser/WebBrowserViewController.m
> MBL-12967 fix all warnings in CanvasKit

- CanvasCore/CanvasCore/Push Notifications/Model/CommunicationChannel.swift
> MBL-13023 add communication channel types

- Core/Core/API/APICourse.swift
- Core/Core/API/APIExternalTool.swift
- Core/Core/Models/Course.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APICourseFixture.swift
> fixed decoding issues with some models

- Core/Core/Extensions/NSPersistentContainerExtensions.swift
> Destroy cache on failed db migrations

- scripts/coverage/coverage.js
> Sort list of files in folder coverage page

- Student/CanvasUITests/Login/LoginTests.swift
> Disable broken LDAP tests

- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizDetailsViewController.swift
refs: MBL-13068
release note: Fixed a crash when viewing a quiz
> Fix crash in quiz details

- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- Frameworks/CanvasKeymaster/CanvasKeymaster.xcodeproj/project.pbxproj
- Frameworks/CanvasKit/CanvasKit.xcodeproj/project.pbxproj
> Fix duplicate module build error

- Core/Core/Use Cases/UploadManager.swift
> Avoid invalid background session

- Core/Core/DocViewer/DocViewerPresenter.swift
- Core/Core/Extensions/URLComponentsExtensions.swift
- Core/Core/Router/RouteHandler.swift
- Core/CoreTests/DocViewer/DocViewerPresenterTests.swift
- Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift
- Core/CoreTests/Extensions/URLExtensionsTests.swift
- Core/CoreTests/Router/RouteHandlerTests.swift
- Core/CoreTests/Router/RouterTests.swift
- Student/Student/Courses/Syllabus/SyllabusPresenter.swift
- Student/StudentUITests/Quizzes/QuizTests.swift
- Student/StudentUnitTests/Courses/Syllabus/SyllabusPresenterTests.swift
- rn/Teacher/src/modules/profile/Profile.js
refs: MBL-13074
release note: Fixed an issue with annotations while acting as another user
> Fix previewing doc viewer while masquerading

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/Controllers/QuizSubmissionTimerController.swift
refs: MBL-13083
release note: Fixed a crash in quizzes
> Fix crash in quiz submissions

- CanvasCore/CanvasCore/Quizzes/Quiz Details/Controllers/QuizController.swift
- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizDetailsViewController.swift
- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizIntroViewController.swift
refs: MBL-9908
release note: Fixed an issue that would cause a spike in page views for quiz submissions
> Replace timer with pull-to-refresh on quiz details

- Core/CoreUITests/CoreUITestCase.swift
- Core/CoreUITests/Dashboard/AccountNotifications/AccountNotificationsTests.swift
> Fix error alerts on AccountNotificationsTests

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsAnnotation.swift
- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsConstants.swift
- Core/Core/DocViewer/DocViewerConstants.swift
- Core/Core/DocViewer/PSPDFAnnotationExtension.swift
- Core/CoreTests/DocViewer/PSPDFAnnotationExtensionTests.swift
refs: MBL-13058
release note: Improved quality of pen annotations
> Support ink annotation widths

- Core/CoreUITests/Dashboard/AccountNotifications/AccountNotificationsTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
> Added UI Test for dismissing account notification

- Core/Core/API/APIFileRequestable.swift
- Core/Core/Models/FileUploadTarget.swift
- Core/Core/Use Cases/UploadManager.swift
refs: MBL-13061
release note: Fixed an issue with submitting Keynote and Pages documents
> Fix uploading of files with null inferred content-type

- CanvasCore/CanvasCore/Annotations/Pre Submission/PreSubmissionPDFDocumentPresenter.swift
> Flatten pre-submission annotations

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
- rn/Teacher/src/modules/speedgrader/SubmissionViewer.js
- rn/Teacher/src/modules/speedgrader/__tests__/SubmissionViewer.test.js
- rn/Teacher/src/modules/speedgrader/submission-viewers/ImageSubmissionViewer.js
- rn/Teacher/src/modules/speedgrader/submission-viewers/__tests__/__snapshots__/ImageSubmissionViewer.test.js.snap
refs: MBL-13075
release note: Added support for viewing heic file submissions
> Support viewing heic file submissions

- Core/Core/API/APICourseRequestable.swift
- Core/Core/Extensions/BundleExtensions.swift
- Core/Core/Use Cases/GetCourses.swift
- Core/CoreTests/API/APICourseRequestableTests.swift
- rn/Teacher/src/canvas-api/apis/courses.js
> Exclude unpublished courses

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/RichContentEditor/RichContentToolbarView.xib
- Core/CoreUITests/RichContentEditor/RichContentToolbar.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUITests/Submissions/TextSubmission/TextSubmissionTests.swift
> Add test for online_text_entry submission

- Core/Core/FilePicker/FilePickerViewController.swift
- Core/Core/UITestHelpers/MockDistantURLSession.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUITests/FilePicker/FilePicker.swift
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
> Add file upload test

- Core/Core/Extensions/UIFontExtensions.swift
- Core/Core/Extensions/UITableViewExtensions.swift
- Core/CoreTests/Extensions/UITableViewExtensionsTests.swift
- rn/Teacher/ios/Localizable.stringsdict
- rn/Teacher/ios/Submissions/HideGradesViewController.storyboard
- rn/Teacher/ios/Submissions/HideGradesViewController.swift
- rn/Teacher/ios/Submissions/PostGradesViewController.storyboard
- rn/Teacher/ios/Submissions/PostGradesViewController.swift
- rn/Teacher/ios/Submissions/PostSettingsViewController.storyboard
- rn/Teacher/ios/Submissions/PostSettingsViewController.swift
- rn/Teacher/ios/Submissions/PostToVisibilitySelectionViewController.storyboard
- rn/Teacher/ios/Submissions/PostToVisibilitySelectionViewController.swift
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
> MBL-11702 - UI for manual post grades screen

- Cartfile
- Cartfile.resolved
- Core/Core/DocViewer/Comments/CommentListViewController.swift
- Core/Core/Models/Submission.swift
- Parent/Parent/Info.plist
- Podfile
- Podfile.lock
- Student/Student/Info.plist
- rn/Teacher/ios/Teacher/Info.plist
> MBL-13117 - ios13 support

- rn/Teacher/src/modules/quizzes/submissions/QuizSubmissionList.js
- rn/Teacher/src/modules/quizzes/submissions/__tests__/QuizSubmissionList.test.js
- rn/Teacher/src/modules/quizzes/submissions/__tests__/__snapshots__/QuizSubmissionList.test.js.snap
refs: MBL-12972
release note: Made it more clear that you can not get to speed grader for practice quizzes and surveys
> Show practice quiz/survey message in submission list

- Parent/Parent/Thresholds/StudentSettingsViewController.swift
> Add label to threshold rows

- Core/Core/Use Cases/GetAssignments.swift
- Core/CoreTests/Use Cases/GetAssignmentsTests.swift
- Student/SubmitAssignment/Assignments/AssignmentsPresenter.swift
- Student/SubmitAssignment/SubmitAssignmentPresenter.swift
refs: MBL-13152
release note: Removed unavailable assignments from Submit Assignment extension
> Only list unlocked assignments in share

- CanvasCore/CanvasCore/OSSAttribution/components.plist
- Podfile
- Podfile.lock
> Remove SVProgressHUD

- Core/Core/Login/LoginFindSchoolViewController.swift
- Parent/Parent/Details/DatePickerViewController.swift
extra: fix deprecation warning.
refs: MBL-12403
> Don't auto focus the school search field for VO users

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Observer Alerts/Model/AlertThreshold/AlertThreshold.swift
- Parent/Parent/Router/Router+Routes.swift
- Parent/Parent/Thresholds/Base.lproj/StudentSettingsHeaderView.xib
- Parent/Parent/Thresholds/StudentSettingsHeaderView.swift
- Parent/Parent/Thresholds/StudentSettingsViewController.storyboard
- Parent/Parent/Thresholds/StudentSettingsViewController.swift
- Podfile
- Podfile.lock
> get rid of Eureka dependency

- Student/Student/Courses/Syllabus/SyllabusActionableItemsPresenter.swift
refs: MBL-13142
release note: Fixed start time of syllabus calendar event
> MBL-13142 fix start time of syllabus calendar event

- Student/Canvas/Calendar/UI/View Controller/CalendarEventDetailViewController.swift
refs: MBL-13145
release note: Added location to calendar event details
> MBL-13145 - show location on calendar event details

- Student/Student.xcodeproj/xcshareddata/xcschemes/NightlyTests.xcscheme
> add nightly UI Test scheme, change CITests to run only unit tests

- rn/Teacher/launchPackager.command
> try to speed up ui test time by not busting the cache

- rn/Teacher/ios/Teacher/Modules/ModuleList/ModuleListViewController.swift
> Fix launching LTI module items in Teacher

- dangerfile.js
> Use PR body for Danger linting

- Student/Student/CanvasAppDelegate.swift
> Fix deep linking modal to have done button

- Core/Core/Pages/PageList/PageListCell.swift
refs: MBL-13187
release note: Fixed a crash when viewing pages
> Fix crash in pages list

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/ParentAppDelegate.swift
> Remove CanvasKit from Parent

- Core/Core/Logger/Logger.swift
- Core/Core/UITestHelpers/MockDistantURLSession.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- Student/StudentUITests/Assignments/AssignmentDetailsTests.swift
- Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift
> Fix legit ui test failures

- rn/Teacher/i18n/locales/en.json
> Update English source strings

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APISearchRecipient.swift
- Core/Core/API/APISearchRecipientsRequestable.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/SearchRecipient.swift
- Core/Core/Router/Route.swift
- Core/Core/Use Cases/GetSearchRecipients.swift
- Core/CoreTests/API/APISearchRecipientsRequestableTests.swift
- Core/CoreTests/Models/SearchRecipientTests.swift
- Core/CoreTests/Router/RouteTests.swift
- Core/CoreTests/Use Cases/GetSearchRecipientsTests.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/Student/People/PeopleListCell.swift
- Student/Student/People/PeopleListPresenter.swift
- Student/Student/People/PeopleListViewController.storyboard
- Student/Student/People/PeopleListViewController.swift
- Student/Student/Routes.swift
- Student/StudentUnitTests/People/PeopleListPresenterTests.swift
- Student/StudentUnitTests/RoutesTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/API/APISearchRecipientFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/SearchRecipientFixture.swift
- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/routing/register-screens.js
> Refactor PeopleList for both courses and groups

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Extensions/UITableViewExtensions.swift
- Core/Core/Grades/GradesViewController.storyboard
- Core/Core/Grades/GradesViewController.swift
- Core/Core/Views/SectionHeaderView.swift
- Core/CoreTests/Extensions/UITableViewExtensionsTests.swift
refs:MBL-11243
no need for feature flag yet, no way to navigate here.
> MBL-11243 grades list

- Student/Student/Quizzes/QuizList/QuizListViewController.storyboard
- rn/Teacher/src/modules/quizzes/list/QuizRow.js
- rn/Teacher/src/modules/quizzes/list/__tests__/__snapshots__/QuizRow.test.js.snap
- rn/Teacher/src/modules/quizzes/list/__tests__/__snapshots__/QuizzesList.test.js.snap
- rn/Teacher/src/modules/tabs/TabRow.js
- rn/Teacher/src/modules/tabs/__tests__/__snapshots__/TabRow.test.js.snap
> Fix a few more minor font bugs

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/QuizPresentingViewController.swift
refs: MBL-13161
release note: Fixed an issue with resuming a quiz
> Force refresh quiz & submission when exiting quiz

- rn/Teacher/src/modules/quizzes/list/QuizzesList.js
- rn/Teacher/src/modules/quizzes/list/__tests__/__snapshots__/QuizzesList.test.js.snap
> Fix sort instability in Quizzes List

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIDiscussion.swift
- Core/Core/API/APIDiscussionRequestable.swift
- Core/Core/API/ID.swift
- Core/CoreUITests/CoreUITestCase.swift
- Core/CoreUITests/Deep Links/DeepLinkTests.swift
- Core/CoreUITests/Discussions/DiscussionEditReply.swift
- Core/CoreUITests/Discussions/DiscussionEditTests.swift
- Core/CoreUITests/Discussions/DiscussionReply.swift
- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Student/StudentUITests/People/PeopleTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUITests/TestsFromCore.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APICourseFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionEntryFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionTopicFixture.swift
- rn/Teacher/ios/TeacherUITests/TestsFromCore.swift
- rn/Teacher/src/modules/discussions/details/EditReply.js
- rn/Teacher/src/modules/discussions/details/Reply.js
- rn/Teacher/src/modules/discussions/details/__tests__/EditReply.test.js
- rn/Teacher/src/modules/discussions/details/__tests__/Reply.test.js
- rn/Teacher/src/modules/discussions/details/__tests__/__snapshots__/DiscussionDetails.test.js.snap
- rn/Teacher/src/modules/discussions/details/__tests__/__snapshots__/EditReply.test.js.snap
- rn/Teacher/src/modules/discussions/details/__tests__/__snapshots__/Reply.test.js.snap
This revealed several bugs (I think) one of which is preventing me from finishing the "with attachment" test.
The broken tests are disabled here (xtest...)
refs: MBL-12751
affects: none
> Added UI tests for discussion replies

- Core/Core/Use Cases/GetAssignments.swift
refs: MBL-13156
release note: Fixed order of assignments in Submit Assignment to be by due date
> Sort assignments in ext by due date

- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/React Native Modules/HTTPRequestHandler.m
- CanvasCore/CanvasCore/React Native Modules/HTTPRequestHandler.swift
- Core/Core/API/APIRequestable.swift
- Core/CoreTests/API/APIRequestableTests.swift
- rn/Teacher/src/canvas-api/__tests__/httpClient.test.js
- rn/Teacher/src/canvas-api/httpClient.js
- rn/Teacher/src/routing/__tests__/__snapshots__/index.test.js.snap
- rn/Teacher/src/routing/index.js
> Use API for RN requests

- Core/Core/AppEnvironment/Secret.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- Core/CoreUITests/CoreUITestCase.swift
- Core/CoreUITests/Login/LoginTests.swift
- Core/CoreUITests/UITestUser.swift
> Add SAML login test

- Core/Core/Analytics/Analytics.swift
- Core/Core/AppEnvironment/SessionDefaults.swift
- Core/CoreTests/Analytics/AnalyticsTests.swift
- Parent/Parent/ParentAppDelegate.swift
- Student/Student/CanvasAppDelegate.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Log analytics around refresh tokens

- Core/Core/Grades/GradesCell.xib
- Core/Core/Grades/GradesPresenter.swift
- Core/Core/Grades/GradesViewController.storyboard
- Core/Core/Grades/GradesViewController.swift
- Core/Core/Router/Route.swift
- Parent/Parent/Routes.swift
> MBL-11243 make grade cell look like mocks

- Student/Student/Submissions/SubmissionRubric/RubricViewController.swift
refs: MBL-13210
release note: Fixed a bug where viewing a description of a rubric item would show the incorrect description
> Show the proper rubric description

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIFile.swift
- Core/Core/API/APIFileRequestable.swift
- Core/Core/API/APIUserRequestable.swift
- Core/Core/Profile/ProfileViewController.storyboard
- Core/Core/Profile/ProfileViewController.swift
- Core/Core/Profile/UploadAvatar.swift
- Core/CoreTests/API/APIFileRequestableTests.swift
- Core/CoreTests/CoreTestCase.swift
- Core/CoreTests/Profile/UploadAvatarTests.swift
- TestsFoundation/TestsFoundation/API/MockURLSession.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIFileFixture.swift
refs: MBL-13191
release note: Added uploading a new avatar picture from the profile drawer
> Allow updating avatar by tapping it in drawer

- Parent/Parent/ParentAppDelegate.swift
> remove whats new link on parent

- Core/Core/Grades/GradesViewController.swift
- Core/Core/Models/Assignment.swift
- Core/CoreTests/Models/AssignmentTests.swift
refs:MBL-11243
to view this:
Developer Menu > enter route `/courses/<courseID/grades` > push
> MBL-11243 fix grade cell grade formatting

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Course/CourseDetailsViewController.storyboard
- Parent/Parent/Course/CourseDetailsViewController.swift
> MBL-11243 - add horizontal menu that holds grades

- Core/Core/AppEnvironment/AppEnvironment.swift
- Parent/Parent/ParentAppDelegate.swift
- Parent/Parent/Routes.swift
- Student/Student/Routes.swift
- Student/StudentUnitTests/.swiftlint.yml
- Student/StudentUnitTests/RoutesTests.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
- rn/Teacher/src/routing/Navigator.js
- rn/Teacher/src/routing/__tests__/Navigator.test.js
> Open links in Safari

- .gitignore
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIGradingPeriod.swift
- Core/Core/API/GradingPeriodRequestables.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/GradingPeriod.swift
- Core/Core/Use Cases/GradingPeriodUseCase.swift
- Core/CoreTests/API/GradingPeriodRequestableTests.swift
- Core/CoreTests/Use Cases/GradingPeriodUseCaseTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/API/APIGradingPeriodFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/GradingPeriodFixture.swift
> MBL-13195 - add multiple grading period API entity and requestable and Core Data model and UseCase

- Core/Core/API/API.swift
- Core/CoreTests/API/APITests.swift
> Fix downloading from DocViewer in SpeedGrader

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsAnnotationProvider.swift
- Cartfile
- Cartfile.resolved
- Core/Core/DocViewer/DocViewerAnnotationProvider.swift
refs: MBL-13213
release note: Fixed a bug that caused documents to not respect grader rotations
> Fix document orientations

- Core/Core/Extensions/UIViewControllerExtensions.swift
- Core/Core/Router/Router.swift
- Core/CoreTests/Extensions/UIViewControllerExtensionsTests.swift
- Core/CoreTests/Router/RouterTests.swift
- Student/Canvas/Modules/ModuleDetailsViewController.swift
- Student/Canvas/Modules/ModulesTableViewController.swift
- Student/Student/Routes.swift
> Add option for routing to detail

- Core/Core/Models/Assignment.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/CoreTests/Models/AssignmentTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIAssignmentFixture.swift
> MBL-13195 - add submissions set to assignment to so observer role can get multiple students submissions on assignments

- Student/Student/Routes.swift
> Fix conferences crash

- rn/Teacher/src/modules/graphql-speed-grader/SubmissionGrader.js
- rn/Teacher/src/modules/graphql-speed-grader/components/SubmissionPicker.js
> Graphql-ify SubmissionPicker

- Parent/Parent/Info.plist
- rn/Teacher/ios/Teacher/Info.plist
> add no dark mode flags for parent and teacher

- Core/Core.xcodeproj/project.pbxproj
- Parent/Parent.xcodeproj/project.pbxproj
- Student/Student.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- scripts/runSwiftLint.sh
> remove swift lint in xcode build phases, add script to run on CI servers

- Podfile
- Podfile.lock
- rn/Teacher/package.json
- rn/Teacher/yarn.lock
refs: MBL-13294
release note: Fixed a crash in Files
> Update RNSearchBar to support iOS 13

- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
refs: MBL-13289
release note: Fix for rubrics with custom assessments
> MBL-13289 - fix rubric with custom assessments and same ids

- Core/Core/Extensions/DateExtensions.swift
- Core/CoreTests/Use Cases/GetRecentlyGradedSubmissionsTests.swift
> fix unit tests with Xcode 11

- Core/Core/PageViewAnalytics/PageViewEventController.swift
refs: MBL-13295, MBL-13296, MBL-13297
> Fix crashes in release on iOS 12

- scripts/runSwiftLint.sh
fail on swiftlint errors so ci build fails
refs: none
affects: none
> fail on swiftlint errors so ci build fails

- CanvasCore/CanvasCore/React Native Modules/HTTPRequestHandler.swift
refs: MBL-13298
release note: Fixed attachment uploading to show correct file size sent
> Send complete progress for RN

- Core/Core/Router/Router.swift
- Core/CoreTests/Router/RouterTests.swift
> Hide split view buttons from modals

- rn/Teacher/src/modules/users/ContextCard.js
refs: MBL-13303
release note: Only show unposted grades when they differ from the posted grade
> If unposted grade is the same, don't show it

- CanvasCore/CanvasCore/Views/TokenLabelView.swift
- Core/Core/Extensions/UIFontExtensions.swift
> fix serif font

- rn/Teacher/src/modules/speedgrader/components/Header.js
- rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/Header.test.js.snap
refs: MBL-13320
release note: Fixed an issue with long names in speedgrader
> Fix name truncation in speedgrader header

- Core/Core/Router/Router.swift
- Core/CoreTests/Router/RouterTests.swift
Fixes deep linking to RN views.
refs: MBL-13325
> Place modal done button on left side

- Core/Core/Extensions/BundleExtensions.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- Core/CoreTests/Use Cases/GetContextUsersTests.swift
- Core/CoreUITests/CoreUITestCase.swift
- Student/StudentUITests/Assignments/AssignmentDetailsTests.swift
- Student/StudentUITests/StudentUITestCase.swift
> Fix some automation bugs

- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Core/CoreUITests/Login/LoginTests.swift
- Student/Student.xcodeproj/xcshareddata/xcschemes/Student.xcscheme
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- TestsFoundation/TestsFoundation/Element/LoginFindSchool.swift
> Fix some automation stuff

- Core/Core/Extensions/URLExtensions.swift
- Core/Core/FilePicker/FilePickerViewController.swift
- Core/CoreTests/Extensions/URLExtensionsTests.swift
refs: MBL-13322
release note: Fixed submitting videos from library
> Fix submitting videos from library in iOS 13

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Core/Core/DeveloperMenu/DeveloperMenuViewController.swift
- Core/Core/Views/SwitchTableViewCell.swift
- Parent/Parent/Course/CourseDetailsViewController.storyboard
- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/Parent/Dashboard/Calendar/CourseListViewController.swift
> add feature flag for parent 3.0 features

- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
For some reason Xcode thinks none of these attributes are syncable now. :shrug:
> Fix NSSecureUnarchiveFromData warnings in CoreData

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Syllabus/SyllabusPresenter.swift
- Core/Core/Syllabus/SyllabusViewController.storyboard
- Core/Core/Syllabus/SyllabusViewController.swift
- Core/CoreTests/Syllabus/SyllabusPresenterTests.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Courses/Syllabus/StudentSyllabusPresenter.swift
- Student/Student/Courses/Syllabus/StudentSyllabusViewController.storyboard
- Student/Student/Courses/Syllabus/StudentSyllabusViewController.swift
- Student/Student/Routes.swift
- Student/StudentUnitTests/Courses/Syllabus/StudentSyllabusPresenterTests.swift
> Add syllabus to parent

- rn/Teacher/src/modules/speedgrader/comments/CommentsTab.js
- rn/Teacher/src/modules/speedgrader/comments/__tests__/CommentsTab.test.js
refs: MBL-13327
release note: Fixed a bug that would cause an error when viewing quiz attempts
> Fix viewing quiz attempts in Teacher

- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
refs: MBL-13279
release note: Fixed add comments appearing when assignment is locked
> Disable adding comments while assignment is locked

- Student/Student/Routes.swift
- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
- rn/Teacher/src/routing/register-screens.js
refs: MBL-13280
release note: Fixed a crash when viewing Conferences
**Test plan:**
* View conferences in Student and Teacher app. It should launch to Safari in Student and SFSafariViewController in Teacher.
> Fix conferences

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.storyboard
refs: MBL-13348
release note: Fixed a flash of grey on locked assignment details
> Fix lock description background color

- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Submission.swift
- Core/Core/Models/SubmissionComment.swift
- Core/Core/Use Cases/CreateTextComment.swift
- Core/Core/Use Cases/GetSubmissionComments.swift
- Core/Core/Use Cases/UploadFileComment.swift
- Core/Core/Use Cases/UploadMediaComment.swift
- Core/CoreTests/Models/SubmissionTests.swift
- Core/CoreTests/Use Cases/GetSubmissionCommentsTests.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/SubmissionCommentFixture.swift
refs: MBL-13321
release note: Fixed quiz submission comments not appearing
> Fix quiz submission comments

- Core/CoreTests/Pages/PageList/PageListPresenterTests.swift
- Core/CoreTests/Profile/ProfilePresenterTests.swift
- Student/StudentUnitTests/People/PeopleListPresenterTests.swift
- Student/StudentUnitTests/Submissions/SubmissionButton/SubmissionButtonPresenterTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Extensions/XCTestCaseExtensions.swift
- scripts/coverage/coverage.js
> Fix some flaky unit tests

- scripts/coverage/coverage.js
> Fix coverage script (again) for Xcode 11

- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigTableViewCell.swift
refs: MBL-13305
release note: Fixed an issue with quizzes cutting off question text
> Fix reused whizzywig cells not updating height

- Core/Core.xcodeproj/project.pbxproj
- Parent/Parent.xcodeproj/project.pbxproj
- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUnitTests/People/PeopleListPresenterTests.swift
- TestsFoundation/TestsFoundation/Extensions/XCTestCaseExtensions.swift
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- scripts/carthage-copy-frameworks.swift
- scripts/coverage/coverage.js
- scripts/find-flaky-pairs-of-tests.sh
> Build fixes

- scripts/carthage-copy-frameworks.swift
Lock will now timeout while building instead of waiting forever
Lock will no longer be able to outlive the build process, which would
result in a permanent deadlock requiring a clean build.
> Made Carthage locking mechanism more robust

- rn/Teacher/src/common/formatters.js
refs: MBL-13353
release note: Fixed bad rounding for quiz grades
> Fix Student points grade

- rn/Teacher/src/modules/submissions/list/SubmissionStatusLabel.js
- rn/Teacher/src/modules/submissions/list/__tests__/SubmissionStatus.test.js
refs: MBL-13365
release note: Fixed an issue where grades list would show "Not Submitted" for a submitted assignment
> Fixed submitted at in snake case

- CanvasCore/CanvasCore/WhizzyWig/WhizzyWigTableViewCell.swift
refs: MBL-13318
release note: Fixed text being cut off on a quiz
Test Plan:
- Creds and affected quiz is in the ticket
> Don't cut off the body of quiz details on iPad

- rn/Teacher/src/modules/courses/CourseNavigation.js
- rn/Teacher/src/modules/courses/__tests__/CourseNavigation.test.js
refs: MBL-13378
release note: Fixed viewing Outcomes
**Test plan:**
- Student App > narmstrong > s > CS 1400 > Outcomes
- Should launch in Safari
> Fix Outcomes tab

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Views/ItemPickerViewController.swift
- Core/CoreUITests/ItemPicker/ItemPickerElement.swift
- Core/CoreUITests/Profile/Profile.swift
> Fix profile landing page ui test

- Core/Core/Views/HorizontalMenuViewController.swift
- TestsFoundation/TestsFoundation/Element/Element.swift
- TestsFoundation/TestsFoundation/Extensions/XCUIApplicationExtensions.swift
- TestsFoundation/TestsFoundation/TestsFoundation.h
[run nightly]
nightly build with _only_ 2 test failures: https://app.bitrise.io/build/045ab5943d59c069
> Fix UI tests failing to get snapshots and crashing (again)

- Core/Core/DeveloperMenu/DeveloperMenuViewController.swift
- Core/Core/Router/Router.swift
> improve native dev menu

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Views/HorizontalMenuViewController.swift
- Core/CoreTests/MetaTests/XCTestCaseTests.swift
- scripts/report-failing-tests.sh
- scripts/runSwiftLint.sh
- setup.sh
...and some miscellaneous cleanup/testing
> Add script for flaky test reporting

- Parent/Parent/ParentAppDelegate.swift
refs: MBL-13414
release note: Fixed a bug that could cause the app to hand when logging in
> Fix logging in to Parent

- TESTING-CONVENTIONS.md
> Testing docs

- CanvasCore/CanvasCore/Views/TokenLabelView.swift
refs: MBL-13382
Test plan
------------
see ticket
> uppercase token view

- rn/Teacher/src/modules/submissions/list/SubmissionList.js
- rn/Teacher/src/modules/submissions/list/__tests__/SubmissionList.test.js
refs: MBL-13385
release note: Fixed filtering by section in speedgrader
Test Plan: See ticket for credentials and assignment
> Fix speed grader section filtering

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIUserRequestable.swift
- Core/Core/Views/AlertAction.swift
- Core/CoreTests/API/APIUserRequestableTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent.xcodeproj/xcshareddata/xcschemes/Parent.xcscheme
- Parent/Parent/Settings/SettingsViewController.swift
- Parent/ParentUnitTests/ParentTestCase.swift
- Parent/ParentUnitTests/Settings/SettingsViewControllerTests.swift
- TestsFoundation/TestsFoundation/Router/TestRouter.swift
refs: MBL-13428
release note: Fixed adding children with pairing code
> Fix adding users via pairing code

- Student/Student/Submissions/SubmissionComments/SubmissionCommentsPresenter.swift
- Student/StudentUnitTests/Submissions/SubmissionComments/SubmissionCommentsPresenterTests.swift
refs: MBL-13377
Test plan
------------
see ticket
> add done button to submission comments modal that shows File

- rn/Teacher/src/canvas-api-v2/queries/ContextCard.js
- rn/Teacher/src/canvas-api-v2/queries/SubmissionList.js
- rn/Teacher/src/common/__tests__/formatters.test.js
- rn/Teacher/src/common/formatters.js
- rn/Teacher/src/modules/quizzes/submissions/map-state-to-props.js
- rn/Teacher/src/modules/speedgrader/components/GradePicker.js
- rn/Teacher/src/modules/submissions/list/OldSubmissionRow.js
- rn/Teacher/src/modules/submissions/list/SubmissionRow.js
- rn/Teacher/src/modules/users/UserSubmissionRow.js
refs: MBL-13353
release note: Fixed bad rounding in some quiz grades
> Use score for grade text in teacher

- CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html
- Core/Core/Views/CoreWebView.swift
refs: MBL-13401
release note: Fixed alignment of equations
> Fix alignment of equations

- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizDetailsViewController.swift
refs: MBL-13319
Test plan
------------
https://instructure.atlassian.net/browse/MBL-13319
> fix content under navbar on quiz details screen

- rn/Teacher/src/modules/speedgrader/components/Header.js
- rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/Header.test.js.snap
refs: MBL-13384
release note: Fixed a bug where submitted assignments would show as not submitted in speed grader
Test Plan:
- See ticket for creds and assignment to check
> Fix not submitted label on submitted assignments

- CanvasCore/CanvasCore/Quizzes/Quiz Details/QuizIntroViewController.swift
refs: MBL-13402
release note: fixed bug resuming quiz
Test plan
------------
see ticket
> refresh takeability when view will appear resuming quiz

- rn/Teacher/src/modules/submissions/list/SubmissionList.js
- rn/Teacher/src/modules/submissions/list/__tests__/SubmissionList.test.js
refs: MBL-13380
release note: Fixed a bug where grades in submission list would not match grades given in speedgrader
Test Plan:
- go into speedgrader and give a grade
- Go back to submission list and see that the grade is correct
> Refresh submissions list after speedgrader dismiss

- Student/TechDebt/Files and Folders/FileViewController.m
refs: MBL-13307
release note: Fixed an issue with status bar color when viewing a file
> Fix status bar in FileViewController

- Core/Core/Pages/PageList/PageListCell.swift
refs: MBL-13404
release note: Fixed an issue with page updated date being displayed incorrectly
> Correctly display the page updated date

- Core/Core/ActAsUser/ActAsUserWindow.swift
- Core/CoreTester/Info.plist
> Don't override rootViewController

- CanvasCore/CanvasCore/Modules/ModuleItem/ModuleItem.swift
- Student/Canvas/Modules/Module Items/ModuleItemViewModel.swift
refs: MBL-13315
release note: Fix useless selection of module headers
> Make text subheaders unselectable

- CanvasCore/CanvasCore/Todo/Model/TodoKit.xcdatamodeld/TodoKit.xcdatamodel/contents
- CanvasCore/CanvasCore/Todo/Network/TodoAPI.swift
- CanvasCore/CanvasCore/Todo/Todo/Todo.swift
refs: MBL-13362
release note: Fixed marking To Do items as done
Test plan:
* Log in as student6 on narmstrong
* View To Do list and swipe to mark the item as done
* The item should not re-appear
> Fix marking To Do items as done

- Student/StudentUITests/Login/LoginFindSchoolTests.swift
> Fix LoginFIndSchoolTests

- rn/Teacher/src/modules/files/FilesList.js
- rn/Teacher/src/modules/files/__tests__/FilesList.test.js
refs: MBL-13306
Test plan
------------
https://instructure.atlassian.net/browse/MBL-13306
> refresh file list after deletion

- scripts/run-nightly-tests.sh
refs: MBL-13450
affects: none
Nightly tests will currently not retry a test if it isn't run for some xcode reason. Change to skipping passing tests instead of retrying failing tests to be sure we pass all tests before declaring success.
> Change nightly test retry to blacklist instead of whitelist

- Core/Core/Views/ItemPickerViewController.swift
- rn/Teacher/ios/Submissions/PostGradesViewController.swift
- rn/Teacher/ios/TeacherUITests/Submissions/AssignmentPostPolicyTests.swift
> Move read-write testPostPolicySettings to be isolated in its own course

- Core/Core/UITestHelpers/MockDistantURLSession.swift
- Core/CoreUITests/ActAsUser/ActAsUserTests.swift
- Core/CoreUITests/CoreUITestCase.swift
- Student/StudentUITests/Assignments/AssignmentDetailsTests.swift
- Student/StudentUITests/Course/Syllabus/SyllabusTests.swift
- Student/StudentUITests/Login/LoginStartTests.swift
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
- Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUITests/Submissions/SubmissionFiles/SubmissionFilesTests.swift
- TestsFoundation/TestsFoundation/Element/Element.swift
- scripts/run-nightly-tests.sh
refs: MBL-13437 MBL-13440 MBL-13441 MBL-13442 MBL-13444 MBL-13445 MBL-13446 MBL-13447 MBL-13448
affects: none
relevant build: 
~https://app.bitrise.io/build/3fcd9c0be051946d~
~https://app.bitrise.io/build/4554e5a2c3ae398b~
https://app.bitrise.io/build/54aaff8ec0360b73
> Fix all the broken nightly tests

- Core/Core/Extensions/URLComponentsExtensions.swift
- Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift
- Student/Student/CanvasAppDelegate.swift
- Student/Student/Routes.swift
refs: MBL-13272
Test plan
------------
https://instructure.atlassian.net/browse/MBL-13272
> route graded submission deep links to assignment details so user can see a grade

- CanvasCore/CanvasCore/Pages/UI/Rendering/PageTemplate.html
- Core/Core/Views/CoreWebView.swift
> Fix equation rendering with tex only

- Core/Core/ActAsUser/ActAsUserWindow.swift
- Core/Core/Profile/ProfilePresenter.swift
- Core/Core/Profile/ProfileViewController.swift
- Core/CoreTests/Profile/ProfilePresenterTests.swift
refs: MBL-13256
release note: Fixed a memory leak when changing users
> Dismiss profile before login changes

- Parent/Parent/ParentAppDelegate.swift
- Student/Student/CanvasAppDelegate.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Only delete the token on logout

- Core/Core/Login/LoginStartViewController.storyboard
- Core/Core/Login/LoginStartViewController.swift
refs: MBL-13460
release note: Fixed an issue with Previous Logins remaining visible after all logins have been removed
> Fix Previous Logins not hiding

- CanvasCore/CanvasCore/Helm/Helm.swift
- rn/Teacher/src/modules/discussions/details/DiscussionDetails.js
- rn/Teacher/src/modules/discussions/details/Reply.js
- rn/Teacher/src/modules/discussions/details/__tests__/DiscussionDetails.test.js
- rn/Teacher/src/modules/discussions/details/__tests__/Reply.test.js
- rn/Teacher/src/routing/Navigator.js
- rn/Teacher/src/routing/__tests__/Navigator.test.js
refs: MBL-13349
Test plan
------------
https://instructure.atlassian.net/browse/MBL-13349
> do not allow helm modals to be dismissed by swipe in ios13

- Core/Core/Extensions/UIColorInstColorsExtensions.swift
- Student/TechDebt/Files and Folders/FileViewController.m
- scripts/build-colors.js
refs: MBL-13465
release note: Fixed a bug when viewing submission comment attachments
Test plan:
* Student App > narmstrong > s > Dashboard > CS 1400 > Assignments > Annotate this > Submission & Rubric > Comments > jpg attachment
* Modal animation should not be transparent
* Go back to Dashboard > Drawer > Files
* Tap around a few different file types to makes sure file viewer is all good
> Fix submission comment animation

- rn/Teacher/src/routing/Navigator.js
- rn/Teacher/src/routing/__tests__/Navigator.test.js
> fix speedgrader fullscreen bug

- .github/workflows/citest.yml
- .gitignore
- scripts/build_automation/bitrise_workflows/tests.yml
Use GitHub actions to run CITests on PR using the same workflow as Bitrise (temporary)
refs: none
affects: none
> Add github action to run bitrise

- .github/workflows/citest.yml
- scripts/build_automation/bitrise_workflows/tests.yml
Should work for a little while...
> super-hacky-temp-carthage-cache

- Parent/Parent/Dashboard/Base.lproj/DashboardViewController.storyboard
- Parent/Parent/Dashboard/DashboardViewController.swift
refs: MBL-12400
release note: Accessibility Improvements
> Fix a11y of Parent header

- Student/StudentUITests/Assignments/AssignmentDetailsTests.swift
refs: MBL-13509
Test plan: [This build](https://app.bitrise.io/build/c7f6ea95eae9ca78#?tab=log) should pass.
> Fix UI tests for assignment grades

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift
> render tests for assignment details

- Student/Student.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Helpers/TestEnvironment.swift
> Move TestEnvironment and TestStore into TestsFoundation

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsPDFDocumentPresenter.swift
- CanvasCore/CanvasCore/Annotations/Canvadocs/Comments/CanvadocsCommentAnnotation.swift
- CanvasCore/CanvasCore/Annotations/Pre Submission/PreSubmissionPDFDocumentPresenter.swift
- Cartfile
- Cartfile.resolved
- Core/Core/DocViewer/DocViewerConstants.swift
- Core/Core/DocViewer/DocViewerPointAnnotation.swift
- Core/Core/DocViewer/DocViewerViewController.swift
- Core/CoreTests/DocViewer/DocViewerConstantsTests.swift
- Core/CoreTests/DocViewer/DocViewerPointAnnotationTests.swift
- Student/TechDebt/Files and Folders/FileViewController.m
- scripts/build_automation/bitrise_workflows/tests.yml
refs: MBL-13383
release note: Fixed a crash that would sometimes occur when changing annotation colors on iPad
Test plan:
* Test PSPDFKit in Student (annotate on a pdf file, try out all the annotation tools, share, etc)
* Test PSPDFKit in Teacher (annotate on a pdf submission, all the annotation tools, comments, etc)
* Follow steps in ticket: https://instructure.atlassian.net/browse/MBL-13383
> Upgrade PSPDFKit to 9.0.2

- Core/CoreTests/MetaTests/XCTestCaseTests.swift
- dangerfile.js
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/coverage/dangerfile-utils.js
> Test failures as comment on PR

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIURL.swift
- Core/Core/API/APIUser.swift
- Core/Core/ActAsUser/ActAsUserPresenter.swift
- Core/Core/Extensions/URLComponentsExtensions.swift
- Core/Core/Login/LoginStartPresenter.swift
- Core/Core/Models/User.swift
- Core/Core/Profile/UploadAvatar.swift
- Core/Core/Profile/UserProfile.swift
- Core/CoreTests/API/APIURLTests.swift
- Student/Student/CanvasAppDelegate.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIUserFixture.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-13515
release note: Fixed a bug that would prevent users from logging in if their avatar URL contained spaces
Test plan:
See [ticket](https://instructure.atlassian.net/browse/MBL-13515)
> Add APIURL and use it in APIProfile

- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Rubric.swift
- Student/Student/Submissions/SubmissionRubric/RubricPresenter.swift
refs: MBL-13550
release note: Fixed an issue with partially graded rubrics
> Don't assume 0 for assessment rating

- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
- scripts/build_automation/bitrise_workflows/tests.yml
> move slack notifications to #ios-bots

- Core/CoreUITests/Login/LoginTests.swift
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
- Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/build_automation/set-mtime.sh
- scripts/run-nightly-tests.sh
- re-enable some interaction tests
- added virtual audio input/output so audio recording tests can do their thing
- harden mtime script against git errors a little
Test plan: https://app.bitrise.io/build/ce6bdf49dcbafe85 will pass
refs: MBL-13134 MBL-13452
affects: none
> re-enable some interaction tests

- Core/Core/UITestHelpers/UITestHelpers.swift
- Core/CoreUITests/CoreUITestCase.swift
- Student/Canvas/Calendar/UI/View Controller/CalendarDayDetailViewController.swift
- Student/Canvas/Calendar/UI/View Controller/CalendarDayPageViewController.swift
- Student/Canvas/Calendar/UI/View Controller/CalendarMonthViewController.swift
- Student/Canvas/Calendar/UI/View/CalendarView.swift
- Student/Canvas/Calendar/UI/View/CalendarWeekView.swift
- Student/StudentUITests/Calendar/CalendarTests.swift
> Add a helper for mocking now in UI tests

- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Student/Student/CanvasAppDelegate.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
> Fix crash when coredata migration is needed

- Core/Core/API/APICalendarEvent.swift
- Core/CoreUITests/CoreUITestCase.swift
- Student/StudentUITests/Calendar/CalendarTests.swift
- TestsFoundation/TestsFoundation/Extensions/DateExtensions.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APICalendarEventFixture.swift
Also made days much shorter in certain instances
refs: MBL-12732
affects: none
> Add UI test for viewing calendar events by day

- Core/Core/AppEnvironment/AppEnvironment.swift
- Core/Core/PageViewAnalytics/PageViewEventController.swift
- Core/Core/Pages/PageList/PageListCell.swift
- Core/Core/Profile/ProfileViewController.swift
- Student/Student/Submissions/SubmissionComments/SubmissionCommentTextCell.swift
- rn/Teacher/index.ios.js
- rn/Teacher/src/common/login-verify.js
refs: MBL-13557
release note: Fixed a crash after logout
> Add more logging to prevent logged out crashes

- Core/Core/Extensions/NSPersistentContainerExtensions.swift
> Fix migration crash

- Student/Student/Routes.swift
> Fix pageViewEventName not set in legacy file view

- CanvasCore/CanvasCore/Activity Stream/Activity+Collections.swift
- CanvasCore/CanvasCore/Activity Stream/Activity.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIActivity.swift
- Core/Core/Models/Activity.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Use Cases/GetActivities.swift
- Core/CoreTests/Models/ActivityTests.swift
- Core/CoreTests/Use Cases/GetActivitiesTests.swift
- Student/Canvas/Notifications/ActivityStreamTableViewController.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/API/APIActivityFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/ActivityFixture.swift
> add activity stream core data / use case pieces

- Core/Core/UITestHelpers/IPC.swift
- Core/Core/UITestHelpers/MockDistantURLSession.swift
- Core/Core/UITestHelpers/MockMessage.swift
- Core/Core/UITestHelpers/UITestHelpers.swift
- Core/CoreUITests/CoreUITestCase.swift
- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Student/StudentUITests/StudentUITestCase.swift
- Student/StudentUITests/Submissions/SubmissionComments/SubmissionCommentsTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUITests/Submissions/SubmissionFiles/SubmissionFilesTests.swift
- scripts/run-nightly-tests.sh
> moved mocks from testee-app to tester-app

- Core/Core/UITestHelpers/IPC.swift
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
- TestsFoundation/TestsFoundation/Element/Element.swift
- rn/Teacher/ios/TeacherUITests/Submissions/AssignmentPostPolicyTests.swift
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/run-nightly-tests.sh
refs: MBL-13578
affects: none
test plan: https://app.bitrise.io/build/816681c5949f4f73 will succeed
>  nightly: fix testMediaRecording and deflake testPostPolicySettings 

- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
refs: MBL-13566
release note: Fixed an issue with reporting submission upload progress
> Fix file upload progress

- Cartfile
- Cartfile.resolved
> Upgrade pspdfkit to version 9.0.3

- Core/CoreTests/ErrorReports/APIErrorReportTests.swift
> Fix experimental features test

- Core/Core/Extensions/DateExtensions.swift
- Core/CoreTests/Extensions/DateExtensionsTests.swift
- Student/StudentUnitTests/Notifications/ActivityStreamViewControllerTests.swift
- scripts/build_automation/bitrise_workflows/tests.yml
> fix tz issues with activity Stream

- Core/CoreUITests/Todo/TodoListTests.swift
> Fix Student Todo List UI tests

- Parent/Parent.xcodeproj/xcshareddata/xcschemes/Parent.xcscheme
- Student/Student.xcodeproj/xcshareddata/xcschemes/Student.xcscheme
- rn/Teacher/ios/Teacher.xcodeproj/xcshareddata/xcschemes/Teacher.xcscheme
> Include CoreTests with app unit tests

- rn/Teacher/src/modules/speedgrader/components/SubmissionPicker.js
- rn/Teacher/src/modules/speedgrader/components/__tests__/SubmissionPicker.test.js
refs: none
release note: Fixed a crash in Speed Grader
Test plan:
* View a submission in Speed Grader
* I saw the crash in narmstrong > t > CS 1400 > Assignments > Annotation This > narmstrong+s
> Fix crash in Speed Grader

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
- Student/Student/Routes.swift
- Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift
- Student/StudentUnitTests/RoutesTests.swift
refs: MBL-13585
use account listed in https://instructure.atlassian.net/browse/MBL-13585 to test, this has a good amount of assignments to test paging.
> remove feature flag for new assignment list, fix bumpy scrolling when paging

- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
> remove empty rows from tableview on assignmentlist

- Core/Core/API/APICourseRequestable.swift
- Core/CoreTests/API/APICourseRequestableTests.swift
- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
- Student/StudentUITests/Submissions/SubmissionButton/SubmissionButtonTests.swift
Fixes many of the nightly tests (all but speedgrader)
Test plan: https://app.bitrise.io/build/294646f22579703c#?tab=log will only have 1 failed test (testSubmissionCommentAttachments)
> Fix nightly tests

- scripts/run-nightly-tests.sh
refs: MBL-13521
affects: none
See https://app.bitrise.io/build/faa843621bf774ec#?tab=artifacts for an example
> Record video of failing tests

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/Profile/ProfileViewControllerTests.swift
- TestsFoundation/TestsFoundation/Fixtures/Keychain/KeychainEntryFixture.swift
> render tests for global nav

- Parent/Parent/Course/CourseDetailsViewController.swift
> show syllabus if it exists when front page is set to something other than page or syllabus

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Parent/Parent/Dashboard/Calendar/CourseListViewController.swift
- Parent/Parent/Routes.swift
- Parent/ParentUnitTests/RoutesTests.swift
> remove feature flag for parent

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/Syllabus/SyllabusViewControllerTests.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUnitTests/Courses/Syllabus/StudentSyllabusViewControllerTests.swift
> render tests for student syllabus

- scripts/build_automation/bitrise_workflows/tests.yml
> Move from sumo to splunk

- Core/Core/Grades/Grades.swift
- Core/Core/Grades/GradesViewController.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
Also fixes a bug in the GradesViewController with sorting assignment groups
refs: MBL-13650
release note: Fixed some copy and a bug with sorting assignment groups
> Change Frontpage to Front Page

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Login/LoginManualOAuthViewController.storyboard
- Core/Core/Login/LoginManualOAuthViewController.swift
- Core/CoreTests/Login/LoginManualOAuthViewControllerTests.swift
- Core/CoreTests/Login/LoginNavigationControllerTests.swift
> Add Login ManualOAuth & Navigation tests

- Core/Core/UITestHelpers/MockDistantURLSession.swift
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/run-nightly-tests.sh
This is the reason testUrlSubmission was failing.
refs: MBL-13688
affects: none
> fix problem with non-main queue running on main thread

- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUnitTests/People/PeopleListViewControllerTests.swift
> render tests for people

- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsViewController.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsViewControllerTests.swift
refs: MBL-13660
release note: Fixed a bug where the keyboard hides the submission comment text field
> Open drawer all the way when keyboard is shown

- Parent/Parent/Extensions/CalendarEvent+Submissions.swift
refs: MBL-13629
release note: Fixed an issue where graded missing assignments were not marked missing
> Graded does not necessarily mean submitted

- Parent/Parent/Dashboard/Alerts/AlertsListViewController.swift
refs: MBL-13701
test plan
--------------
follow steps in ticket https://instructure.atlassian.net/browse/MBL-13701
> route to grades list on course grade high/low alert

- Parent/Parent/Discussions/DiscussionTopic/DiscussionTopic.swift
- Parent/Parent/Discussions/Model/DiscussionKit.xcdatamodeld/DiscussionKit.xcdatamodel/contents
refs: MBL-13702
Test plan: View Parent announcement in ticket
> Fix viewing discussion topics without an author

- Core/Core.xcodeproj/project.pbxproj
- Core/CoreTests/API/APIDashboardTests.swift
> Add test for APIDashboard

- Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
- Core/CoreTests/Login/LoginWebViewControllerTests.swift
> Improve flaky webview test

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Syllabus/SyllabusActionableItemsCell.xib
- Core/Core/Syllabus/SyllabusActionableItemsViewController.swift
- Student/StudentUnitTests/Courses/Syllabus/StudentSyllabusViewControllerTests.swift
> fix syllabus summary actionable item cells

- Core/Core/Profile/Settings/ProfileSettingsViewController.swift
- Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift
> render tests for settings

- Parent/Parent/Extensions/CalendarEvent+Submissions.swift
refs: MBL-13709
test plan, follow ticket
> fix floating point grade

- Core/CoreTests/Login/LoginWebViewControllerTests.swift
> Try to fix testOpenTab moar better

- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/React Native Modules/NativeUtils.m
- Core/Core/API/APIDiscussion.swift
- Core/CoreUITests/Discussions/DiscussionReply.swift
- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Student/StudentUITests/Modules/ModulesTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionEntryFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionTopicFixture.swift
- rn/Teacher/src/modules/discussions/details/DiscussionDetails.js
- rn/Teacher/src/modules/discussions/details/Reply.js
- rn/Teacher/src/modules/discussions/details/__tests__/DiscussionDetails.test.js
- rn/Teacher/src/modules/discussions/details/__tests__/Reply.test.js
- rn/Teacher/src/modules/discussions/details/__tests__/__snapshots__/DiscussionDetails.test.js.snap
- rn/Teacher/src/modules/discussions/details/__tests__/__snapshots__/Reply.test.js.snap
- scripts/build_automation/bitrise_workflows/tests.yml
Also, lots of testID cleanup
refs: MBL-13691
> Add test for rating discussion replies

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conversations/APIConversation.swift
- Core/Core/Conversations/Conversation.swift
- Core/Core/Conversations/ConversationMessage.swift
- Core/Core/Conversations/ConversationParticipant.swift
- Core/Core/Conversations/GetConversations.swift
- Core/Core/Extensions/DateExtensions.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Router/Route.swift
- Core/CoreTests/Conversations/APIConversationTests.swift
- Core/CoreTests/Conversations/ConversationMessageTests.swift
- Core/CoreTests/Conversations/ConversationParticipantTests.swift
- Core/CoreTests/Conversations/ConversationTests.swift
- Core/CoreTests/Extensions/DateExtensionsTests.swift
- Core/CoreTests/Router/RouteTests.swift
- Core/CoreUITests/Inbox/InboxTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ConversationListCell.swift
- Parent/Parent/Conversations/ConversationListViewController.storyboard
- Parent/Parent/Conversations/ConversationListViewController.swift
- Parent/ParentUnitTests/Conversations/ConversationListViewControllerTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/Model/ConversationFixture.swift
> Finish ConversationList in Parent

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conversations/APIConversation.swift
- Core/Core/Conversations/Conversation.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Views/AvatarGroupView.swift
- Core/CoreTests/Conversations/ConversationTests.swift
- Core/CoreTests/Views/AvatarGroupViewTests.swift
- Parent/Parent/Conversations/ConversationListCell.swift
- Parent/Parent/Conversations/ConversationListViewController.storyboard
- Parent/Parent/IBDesignables/IBDesignables.swift
> Add conversation audience avatars

- Core/Core/Conversations/APIConversation.swift
- Core/Core/Conversations/Conversation.swift
- Core/Core/Conversations/ConversationMessage.swift
- Core/Core/Conversations/GetConversations.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/en.lproj/Localizable.stringsdict
- Core/CoreTests/Conversations/ConversationMessageTests.swift
- Core/CoreTests/Conversations/ConversationParticipantTests.swift
- Core/CoreTests/Conversations/ConversationTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ConversationDetailViewController.storyboard
- Parent/Parent/Conversations/ConversationDetailViewController.swift
- Parent/Parent/Routes.swift
- Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift
> inbox message detail

- Core/Core/Login/LoginStartViewController.storyboard
- Core/Core/Views/LoadingViewController.storyboard
> Fix the logo size in loading & login start screen

- CanvasCore/CanvasCore/Persistence/Core Data/NSManagedObjectContext+SoPersistent.swift
- CanvasCore/CanvasCore/Persistence/So Refreshing/Refresher.swift
- CanvasCore/CanvasCore/Persistence/Sync/SyncOperation.swift
- CanvasCore/CanvasCore/Persistence/SynchronizedModel.swift
- CanvasCore/CanvasCore/Session/Session.swift
- Core/Core/en.lproj/Localizable.stringsdict
- Student/Canvas/Calendar/UI/View/CalendarDayCell.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/StudentUnitTests/Calendar/CalendarMonthViewControllerTests.swift
- Student/StudentUnitTests/StudentTestCase.swift
- TestsFoundation/TestsFoundation/API/MockURLSession.swift
- TestsFoundation/TestsFoundation/Extensions/URLResponseExtensions.swift
refs: MBL-12428
Test plan:
* Log in to Student app. Account: narmstrong, User: s
* Go to Calendar tab and turn on Voice Over
* Dec 9, 2019 should say "2 events"
* Dec 13, 2019 should say "1 event"
> Improve calendar a11y

- Parent/Parent/Routes.swift
- Student/Student/Routes.swift
> Fix flaky route tests

- Student/StudentUITests/Calendar/CalendarTests.swift
- scripts/build_automation/bitrise_workflows/tests.yml
> Fix nightly build

- Student/StudentUITests/Dashboard/DashboardTests.swift
MBL-13748 created to re-enable test
> disable flaky testEditFavorites

- scripts/build_automation/bitrise_workflows/tests.yml
> Fix github slack bot

- Core/Core/API/APIGraphQLRequestable.swift
- Core/Core/API/APIPostPolicyInfo.swift
- Core/Core/API/APIPostPolicyRequestable.swift
- Core/Core/API/AssignmentListRequestable.swift
- Core/Core/UITestHelpers/IPC.swift
- Core/Core/UITestHelpers/MockDistantURLSession.swift
- Core/Core/UITestHelpers/MockMessage.swift
- Core/CoreTests/API/APIGraphQLRequestableTests.swift
- Core/CoreTests/API/APIPostPolicyRequestableTests.swift
- Core/CoreUITests/Profile/UserFilesTests.swift
- Student/StudentUITests/Course/Syllabus/SyllabusTests.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/API/APIPostPolicyInfoFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/GraphQL/SubmissionListFixture.swift
- TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
- rn/Teacher/ios/TeacherUITests/SpeedGrader/IPadSpeedGraderTests.swift
- rn/Teacher/ios/TeacherUITests/Submissions/AssignmentPostPolicyTests.swift
> Mock post policy UI test

- .gitignore
- Core/Core.xcodeproj/project.pbxproj
- Core/CoreUITests/SpringBoard/SpringBoard.swift
- Core/CoreUITests/SpringBoard/SpringBoardTests.swift
- Student/Student.xcodeproj/xcshareddata/xcschemes/IPadTests.xcscheme
- Student/Student.xcodeproj/xcshareddata/xcschemes/NightlyTests.xcscheme
- TestPlans/IPadTests.xctestplan
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/nightly-blame-bot.sh
- scripts/run-ui-tests.sh
renamed "nightly" to "ui test" in many cases, since they are no longer
all nightly.
[run-nightly] [run-ipad-tests]
refs: MBL-13726
affects: none
> Add bitrise job for iPad tests

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conversations/APIConversationRecipient.swift
- Core/Core/Router/Route.swift
- Core/CoreTests/Conversations/APIConversationRecipientTests.swift
- Core/CoreTests/ErrorReports/APIErrorReportTests.swift
- Core/CoreTests/Router/RouteTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ComposeRecipientsView.swift
- Parent/Parent/Conversations/ComposeViewController.storyboard
- Parent/Parent/Conversations/ComposeViewController.swift
- Parent/Parent/Conversations/ConversationListViewController.swift
- Parent/Parent/Routes.swift
- Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
> Add recipient pills to compose view 

- rn/Teacher/src/modules/inbox/components/AddressBookToken.js
- rn/Teacher/src/modules/inbox/components/__tests__/__snapshots__/AddressBookToken.test.js.snap
refs: MBL-13728
release note: Accessibility improvement
> Increase touch area & accessibility box for remove address book token

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/Answer Cells/TextAnswerCell.swift
refs: MBL-13750
release note: Improved accessibility in a resumed quiz
> Add a11y selected state to multiple choice

- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
refs: MBL-13736
release note: Fix iOS 13 crash when using Studio files
> fix ios 13 web crasher when displaying UIDocumentViewController

- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
Version mismatches between cache push and pull were causing teacher to never use the cache
> Fix teacher caching

- Parent/Parent.xcodeproj/project.pbxproj
- Student/Student.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
> Upload dsyms on app store builds from bitrise

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ComposeReplyViewController.storyboard
- Parent/Parent/Conversations/ComposeReplyViewController.swift
- Parent/Parent/Conversations/ConversationDetailViewController.swift
- Parent/ParentUnitTests/Conversations/ComposeReplyViewControllerTests.swift
- Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift
extra: remove sticky headers in conversation details
refs: MBL-13770
> Add reply composition

- CanvasCore/CanvasCore/Helm/Helm.swift
- Core/Core/Router/Router.swift
- Core/CoreTests/Router/RouterTests.swift
- Parent/Parent/Dashboard/DashboardPresenter.swift
- rn/Teacher/src/modules/dashboard/Dashboard.js
- rn/Teacher/src/modules/dashboard/__tests__/Dashboard.test.js
refs: MBL-13707
affects: teacher, parent
Test plan:
* Log in as student2 on narmstrong in Teacher and Parent
* Wrong app screen should not be dismissable
> Prevent dismissing Wrong App alert

- Core/Core/Grades/Grades.swift
- Core/Core/Grades/GradesViewController.swift
- Core/Core/Models/Course.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Enrollment.swift
- Core/CoreTests/Grades/GradesViewControllerTests.swift
- Core/CoreTests/Models/EnrollmentTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIEnrollmentFixture.swift
refs: MBL-13777
release note: Fixed a bug that caused the total grade for a course to show when it should not
Test plan:
* Log in as `o` on `narmstrong.instructure.com`
* Student Two > Modules > Total Grade should be `N/A`
* Student Two > Fight Club > Total Grade should not be `N/A`
> Fix hiding total grades in Parent

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/QuizPresentingViewController.swift
- Core/Core/Use Cases/GetQuiz.swift
- Core/CoreTests/Use Cases/GetQuizTests.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
> Fix race condition when saving quiz and submission

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conversations/APIConversation.swift
- Core/Core/Conversations/AddMessage.swift
- Core/Core/Conversations/Conversation.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/CoreTests/Conversations/APIConversationTests.swift
- Core/CoreTests/Conversations/AddMessageTests.swift
- Core/CoreUITests/Inbox/InboxTests.swift
- Parent/Parent/Conversations/ComposeReplyViewController.swift
- Parent/Parent/Conversations/ConversationListCell.swift
- Parent/ParentUnitTests/Conversations/ComposeReplyViewControllerTests.swift
> Add reply sending

- Core/Core/Extensions/BundleExtensions.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/ParentAppDelegate.swift
- Parent/ParentUITests/ExampleTests.swift
- Parent/ParentUITests/Info.plist
- Parent/ParentUITests/ParentUITestCase.swift
- Parent/ParentUITests/ParentUITests.swift
- Student/Student.xcodeproj/xcshareddata/xcschemes/NightlyTests.xcscheme
- TestPlans/NightlyTests.xctestplan
- TestsFoundation/TestsFoundation/Element/TabBar.swift
- TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
> Parent UI test skeleton

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APISearchRecipientsRequestable.swift
- Core/Core/Conversations/APIConversationRecipient.swift
- Core/Core/Use Cases/GetSearchRecipients.swift
- Core/Core/Views/HorizontalMenuViewController.swift
- Core/CoreTests/API/APISearchRecipientsRequestableTests.swift
- Core/CoreTests/Conversations/APIConversationRecipientTests.swift
- Core/CoreTests/Views/HorizontalMenuViewControllerTests.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/ParentUnitTests/Course/CourseDetailsViewControllerTests.swift
refs: MBL-12995
Test plan
1. go to course grades, select a course with multiple different types of tabs
2. click reply, the subject should say students name and the tab title they are on.
> Message teachers from syllabus

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIEnrollment.swift
- Core/Core/API/APIEnrollmentRequestable.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Enrollment.swift
- Core/Core/Router/Route.swift
- Core/Core/Use Cases/GetConversationCourses.swift
- Core/CoreTests/API/APIEnrollmentRequestableTests.swift
- Core/CoreTests/Models/EnrollmentTests.swift
- Core/CoreTests/Router/RouteTests.swift
- Core/CoreTests/Use Cases/GetConversationCoursesTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ActionSheetTransitioning.swift
- Parent/Parent/Conversations/ComposeViewController.swift
- Parent/Parent/Conversations/ConversationCoursesActionSheet.swift
- Parent/Parent/Conversations/ConversationListViewController.swift
- Parent/Parent/Routes.swift
- Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
- Parent/ParentUnitTests/Conversations/ConversationCoursesActionSheetTests.swift
- Parent/ParentUnitTests/Conversations/ConversationListViewControllerTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIEnrollmentFixture.swift
refs: MBL-12997
test plan:
- Compose a message from the conversation list (make sure the
experimental feature is on)
- user in the ticket
> Compose message from conversation list

- scripts/build_automation/bitrise_workflows/tests.yml
[ignore-commit-lint] [run-nightly]
> upgrade awscli dependency to python3 to match bitrise

- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/run-ui-tests.sh
example (approximate): https://app.bitrise.io/build/4173f64e1c9952af
refs: MBL-13781
affects: none
> MBL-13781 trigger nightly build from release automation

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/People/GetContextUsers.swift
- Core/Core/People/PeopleListViewController.storyboard
- Core/Core/People/PeopleListViewController.swift
- Core/Core/Views/FilterHeaderView.swift
- Core/Core/Views/ListFormatter.swift
- Core/CoreTests/People/PeopleListViewControllerTests.swift
refs: MBL-13642
release note: Added filtering People by base enrollment type
> Add filtering to PeopleList

- scripts/build_automation/bitrise_workflows/tests.yml
Bitrise's go templates are horrible and poorly documented.
[ignore-commit-lint] [run-nightly]
> Fix nightly

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Pages/PageList/PageListPresenter.swift
- Core/Core/Pages/PageList/PageListViewController.swift
- Core/Core/Pages/PageList/Pages.swift
- Core/CoreTests/Pages/PageList/PageListPresenterTests.swift
- Core/CoreTests/Pages/PageList/PageListViewControllerTests.swift
> Attempt at fixing pages crash

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Details/AssignmentDetailsViewController.swift
- Parent/ParentUnitTests/Details/AssignmentDetailsViewControllerTests.swift
> Message instructor from assignment details

- Student/Student/Submissions/SubmissionButton/SubmissionButtonPresenter.swift
> Fix modal quiz presentation from assignments

- Core/Core/People/PeopleListViewController.swift
- Core/Core/Views/FilterHeaderView.swift
Fixed the search bar not consistently starting out hidden.
Changed the filter button to always use linkColor.
refs: MBL-13642
> Fix minor issues with PeopleList

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/QuizPresentingViewController.swift
> Fix quiz modals in iOS 13 #2

- Core/Core/Store/Store.swift
- Core/CoreTests/Store/StoreTests.swift
refs: MBL-13762
affects: parent, student, teacher
> Fix crash in store referencing non existant objects

- Core/Core/API/APIUser.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/People/PeopleListViewController.swift
- Core/Core/People/User.swift
- Core/Core/Profile/ProfilePresenter.swift
- Core/Core/Profile/ProfileViewController.swift
- Core/Core/Profile/UserProfile.swift
- Core/CoreTests/People/PeopleListViewControllerTests.swift
- Core/CoreTests/Profile/ProfileViewControllerTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIUserFixture.swift
refs: MBL-13762
Test plan:
* narmstrong > s > CS 1400 > People > Student1 Armstrong should have pronouns
* Open Profile drawer, should see pronouns
> Add pronouns to People list and Profile

- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
refs: MBL-13759
test plan
---------------
page some assignments, make sure this does not break anything and is still smooth scrolling
> Attempt to fix mutation crash perhaps on different threads

- Core/Core/People/PeopleListViewController.swift
> Fix PeopleList filter for iPad

- Student/Canvas/Calendar/UI/View/CalendarView.swift
refs: MBL-13794
Test plan
make sure calendar still works
> Fix force unwrapped crasher in calendar

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conversations/GetConversations.swift
- Core/CoreTests/Conversations/GetConversationsTests.swift
- Parent/Parent/Conversations/ConversationListViewController.swift
refs: MBL-13795
test plan:
- Creds in the ticket
- The user should have more than one conversation listed
in inbox
- Sending a new message should show up in the top of the list
> Include sent messages in conversation list

- Core/Core/API/APIDiscussion.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionEntryFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIDiscussionTopicFixture.swift
[run-nightly]
refs: MBL-13838
release note: Fixed an issue with loading graded discussions
Test plan: See [ticket](https://instructure.atlassian.net/browse/MBL-13838)
> Fix loading graded discussions with nil ratings

- Core/Core/Conversations/APIConversation.swift
- Core/Core/Conversations/Conversation.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
refs: none
test plan:
- twilson.instructure.com / observer1
- inbox should load with no errors
> Fix some optional values

- Core/Core/People/APIUser.swift
- Core/Core/Profile/ProfileViewController.swift
- Core/CoreTests/Profile/ProfileViewControllerTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIUserFixture.swift
refs: MBL-13841
release note: Fixed a bug with updating profile pictures
> Check permissions for updating avatar

- rn/Teacher/src/modules/files/ViewFile.js
- rn/Teacher/src/modules/files/__tests__/ViewFile.test.js
refs: MBL-13792
release note: Fixed loading previews for files with some special characters
> Fix ?# in loading files

- Parent/Parent/Conversations/ConversationDetailCell.swift
> Fix border color on attachments

- Core/Core/Files/FileDetails/FileDetailsViewController.swift
refs: MBL-13861
release note: Fixed an issue with image placement on file details
> Fix initial placement of images in file details

- CanvasCore/CanvasCore.xcodeproj/project.pbxproj
- CanvasCore/CanvasCore/Modules/ModuleItem/ModuleItem+Progress.swift
- Core/Core.xcodeproj/project.pbxproj
- Core/Core/LTI/LTITools.swift
- Core/Core/LTI/LTIViewController.swift
- Core/CoreTests/LTI/LTIToolsTests.swift
- Core/CoreTests/LTI/LTIViewControllerTests.swift
- Student/Canvas/Modules/Module Items/ModuleItemViewModel.swift
refs: MBL-13840
release note: Fixed marking LTI module items as viewed
Test plan:
* narmstrong.instructure.com : student2
* Dashboard > Modules > Modules > Sequential
* The items should require to be viewed but are not viewed
* Tap the items then tap Launch External Tool
* Module items should be marked as viewed when you go back to the items list
> Fix marking LTI module items viewed

- Parent/Parent/ParentAppDelegate.swift
- Student/Student/CanvasAppDelegate.swift
- rn/Teacher/ios/Teacher/AppDelegate.swift
affects: parent, teacher, student
refs: MBL-13854
> Set user properties for feature flags

- rn/Teacher/src/canvas-api-v2/queries/ContextCard.js
- rn/Teacher/src/modules/users/ContextCard.js
- rn/Teacher/src/modules/users/UserSubmissionRow.js
- rn/Teacher/src/modules/users/__tests__/ContextCard.test.js
refs: MBL-13763
Test plan:
* Teacher app > narmstrong : t
* CS 1400 > People > Student1 Armstrong
* Context card should display pronouns
> Add user pronouns to Context Card

- CanvasCore/CanvasCore/Assignments/Assignment/Assignment.swift
- CanvasCore/CanvasCore/Assignments/Model/AssignmentKit.xcdatamodeld/AssignmentKit v1.xcdatamodel/contents
- CanvasCore/CanvasCore/Calendar/CalendarEvent/CalendarEvent.swift
- CanvasCore/CanvasCore/Calendar/Model/CalendarKit.xcdatamodeld/CalendarKit.xcdatamodel/contents
- Parent/Parent/Extensions/CalendarEvent+Submissions.swift
refs: MBL-13839
release note: Fixed a bug causing on paper assignments to show as missing
test plan:
- Ticket has credentials
- Check grades list, assignment details, and calendar (got to go back a week)
> On paper assignments should not be missing

- Canvas.xcworkspace/contents.xcworkspacedata
- Core/Core/API/APIOAuth.swift
- Student/Student.xcodeproj/xcshareddata/xcschemes/Beta E2E.xcscheme
- TestPlans/Beta.xctestplan
- TestPlans/IPadTests.xctestplan
- TestsFoundation/TestsFoundation/UITests/UITestUser.swift
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/run-ui-tests.sh
build: ~https://app.bitrise.io/build/9e6b84ff51364b35~
https://app.bitrise.io/build/1d92b8894e5a2b74
refs: MBL-12853
affects: none
> Add beta test plan and bitrise workflow

- Core/Core/API/APIOAuth.swift
- Core/Core/AppEnvironment/Secret.swift
- Core/CoreE2ETests/Login/LoginE2ETests.swift
- Student/Student.xcodeproj/xcshareddata/xcschemes/Beta E2E.xcscheme
- TestPlans/Beta.xctestplan
- TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
- TestsFoundation/TestsFoundation/UITests/UITestUser.swift
- scripts/run-ui-tests.sh
[run-nightly]
depends on https://github.com/instructure/steps-canvas-ios-secrets/pull/25
refs: MBL-13887
affects: none
> Test mobile verify

- Core/Core/AppEnvironment/Secret.swift
- Core/Core/Extensions/BundleExtensions.swift
- Core/CoreUITests/Dashboard/Dashboard.swift
- Core/CoreUITests/Profile/Profile.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ComposeReplyViewController.storyboard
- Parent/Parent/Conversations/ConversationDetailViewController.storyboard
- Parent/Parent/Conversations/ConversationListViewController.storyboard
- Parent/Parent/Dashboard/Base.lproj/DashboardViewController.storyboard
- Parent/Parent/Details/AssignmentDetailsViewController.swift
- Parent/Parent/Settings/StudentsListViewController.swift
- Parent/ParentE2ETests/Conversations/ComposeReply.swift
- Parent/ParentE2ETests/Conversations/ConversationDetail.swift
- Parent/ParentE2ETests/Conversations/ConversationList.swift
- Parent/ParentE2ETests/InboxTests.swift
- Parent/ParentE2ETests/Info.plist
- TestPlans/Beta.xctestplan
- TestPlans/NightlyTests.xctestplan
- TestsFoundation/TestsFoundation/Element/ElementWrapper.swift
- TestsFoundation/TestsFoundation/UITests/CoreUITestCase.swift
- TestsFoundation/TestsFoundation/UITests/UITestUser.swift
- rn/Teacher/src/modules/dashboard/Dashboard.js
- rn/Teacher/src/modules/dashboard/__tests__/Dashboard.test.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
> Add E2E test target for parent with reply test

- Core/Core/API/API.swift
- Core/Core/API/APIMediaCommentRequestable.swift
- Core/Core/API/APIRequestable.swift
- Core/Core/Files/APIFile.swift
- Core/Core/Use Cases/UploadManager.swift
- Core/CoreTests/API/APIMediaCommentRequestableTests.swift
- Core/CoreTests/API/APIRequestableTests.swift
- Core/CoreTests/Files/APIFileTests.swift
- Core/CoreTests/Use Cases/UploadManagerTests.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsViewController.swift
- Student/Student/Info.plist
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsPresenterTests.swift
- Student/StudentUnitTests/Assignments/AssignmentDetails/AssignmentDetailsViewControllerTests.swift
- Student/SubmitAssignment/SubmitAssignment.entitlements
- Student/SubmitAssignment/SubmitAssignmentPresenter.swift
- Student/SubmitAssignmentTests/SubmitAssignmentPresenterTests.swift
- TestsFoundation/TestsFoundation/Files/MockUploadManager.swift
refs: MBL-13875
Test plan:
**With inst-fs disabled:**
_narmstrong.instructure.com has the inst-fs plugin disabled_
* Log into narmstrong : student2
* CS 1400 > Assignments > File Upload > Resubmit > File Upload
* Choose a file (or two) and make sure it submits successfully
* Submit a file from the share extension from another app to the same course
**With inst-fs enabled:**
_twilson.instructure.com has the inst-fs plugin enabled_
* twilson : student1
* Assignment Grades > Assignments > file upload
* Submit a file and make sure it completes
* Submit from the share extension from another app to make sure it completes as well
> Fix uploading files to s3

- Podfile
- Podfile.lock
- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
> Fix dsym upload

- Core/Core/Grades/GradesViewController.swift
- Core/CoreUITests/Assignments/Assignments.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/ComposeRecipientsView.swift
- Parent/Parent/Conversations/ComposeViewController.storyboard
- Parent/Parent/Dashboard/Courses/CourseCellViewModel.swift
- Parent/ParentE2ETests/GradesListTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/Compose.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/ComposeReply.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/ConversationDetail.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/ConversationList.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Courses.swift
> Add E2E test for parents messaging from assignment details

- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/Parent/Details/AssignmentDetailsViewController.swift
refs: none
Test plan:
* View Grades > compose icon should be comment, not reply
* View Assignment Details > compose icon should be comment, not reply
> Use the comment icon for context compose

- Parent/Parent/Dashboard/DashboardViewController.swift
> Fix for nightly

- Core/Core/DocViewer/DocViewerViewController.swift
- Core/Core/Files/FileDetails/FileDetailsViewController.swift
- Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
- Parent/Parent/Conversations/ComposeRecipientsView.swift
- Parent/Parent/Conversations/EditComposeRecipientsViewController.swift
- fix padding & hit box for recipients
- fix pdf crash
- fix selected property of edit recipients
> Polish inbox

- Core/Core/Profile/ProfilePresenter.swift
- Core/Core/Router/Route.swift
- Core/CoreTests/Profile/ProfilePresenterTests.swift
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/Routes.swift
- Parent/Parent/Settings/SettingsViewController.swift
- Parent/Parent/View/CustomNavbarProtocol.swift
refs: MBL-13895
1. click add student button
2. should show add pairing code popup
> Add "add student" button 

- Core/Core/en.lproj/Localizable.stringsdict
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/View/CustomNavbarProtocol.swift
refs: MBL-13863
Test Plan
1. test VO on dashboard menu
> Dashboard Polish Accessibility

- CanvasCore/CanvasCore/React Native Modules/NativeUtils.m
- rn/Teacher/src/modules/inbox/Compose.js
- rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Compose.test.js.snap
refs: MBL-13899
release note: Fixed an issue with scrolling while composing long messages
> Fix scroll weirdness in Teacher & Student Compose

- Core/Core/Extensions/UIBarButtonItemExtensions.swift
- Core/Core/Extensions/UINavigationBarExtensions.swift
- Core/Core/Syllabus/SyllabusViewController.swift
- Core/CoreTests/Extensions/UIBarButtonItemExtensionTests.swift
- Core/CoreTests/Extensions/UINavigationBarExtensionsTests.swift
- Core/CoreTests/Presenter/ColoredNavViewProtocol.swift
- Parent/Parent/Conversations/ConversationListViewController.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/Parent/Dashboard/Base.lproj/DashboardViewController.storyboard
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/Info.plist
- Parent/Parent/View/CustomNavbarProtocol.swift
- Parent/ParentUnitTests/Conversations/ConversationListViewControllerTests.swift
- Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
- Parent/ParentUnitTests/View/CustomNavbarProtocolTests.swift
- Student/StudentUnitTests/Groups/GroupNavigation/GroupNavigationViewControllerTests.swift
refs: MBL-13941
fixes:
- webview bg
- floating button on grades
- changed inbox to white navbar
> Polish Parent inbox and dashboard

- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
refs: MBL-13837
Test plan:
1. use ticket to test https://instructure.atlassian.net/browse/MBL-13837
2. also, assignment list where there are many assignments and/or assignment groups
3. https://instructure.atlassian.net/browse/MBL-13585 this has a good account w/ mucho assignments to use to test
> Fix grading period filter where count is close to paging limit

- scripts/build_automation/bitrise_workflows/parent.yml
- scripts/build_automation/bitrise_workflows/student.yml
- scripts/build_automation/bitrise_workflows/teacher.yml
- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/build_automation/build-link.swift
> Add links and QR codes to builds

- Core/Core/Files/FileDetails/FileDetailsViewController.swift
- Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
refs: MBL-13959
release note: Fixed a bug that could cause annotations to not be saved
Test plan: Follow steps in [ticket](https://instructure.atlassian.net/browse/MBL-13959)
> Save annotations on viewWillDisappear

- Core/CoreE2ETests/Profile/ProfileE2ETests.swift
- Student/StudentE2ETests/Assignments/AssignmentsE2ETests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/CoreUIElements/Filles/FileDetails.swift
- scripts/build_automation/bitrise_workflows/tests.yml
> Nightly fix

- Core/Core/Login/LoginDelegate.swift
- Core/Core/Login/LoginStartViewController.swift
- Core/Core/Profile/ProfilePresenter.swift
- Parent/Parent/Conversations/ComposeViewController.swift
- Parent/Parent/Conversations/ConversationCoursesActionSheet.swift
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/ParentAppDelegate.swift
- Parent/Parent/Settings/SettingsObserveeCellViewModel.swift
- Parent/Parent/Settings/SettingsViewController.swift
- Parent/Parent/Thresholds/StudentSettingsViewController.swift
- Parent/ParentUnitTests/Conversations/ComposeViewControllerTests.swift
- Parent/ParentUnitTests/Conversations/ConversationCoursesActionSheetTests.swift
- Parent/ParentUnitTests/Dashboard/DashboardViewControllerTests.swift
refs: MBL-13967
* Change find school button title in parent
* Change Manage Children to Manage Students
* Show all students in switcher
* Use short name in navbar
* Use short name in all the places
* Course code as nav subtitle
> Parent 3.1 Polish

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Plannable.swift
- Core/Core/Planner/APIPlannable.swift
- Core/Core/Planner/GetPlannablesUseCase.swift
- Core/Core/Planner/PlannablesRequestable.swift
- Core/CoreTests/Planner/GetPlannablesUseCaseTests.swift
- Core/CoreTests/Planner/PlannableRequestablesTests.swift
- Core/CoreTests/Planner/PlannableTests.swift
- TestsFoundation/TestsFoundation.xcodeproj/project.pbxproj
- TestsFoundation/TestsFoundation/Fixtures/Model/PlannableFixture.swift
> Plannable models

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/Settings/AddStudentController.swift
- Parent/Parent/Settings/SettingsViewController.swift
- Parent/ParentUnitTests/Settings/AddStudentControllerTests.swift
- Parent/ParentUnitTests/Settings/SettingsViewControllerTests.swift
refs: MBL-13963
Test plan:
1. make sure you can add(pair) a student on both the dashboard and the manage children screen
> Add add student alert to dashboard

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/AppEnvironment/Clock.swift
- Core/Core/Extensions/DateExtensions.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/Plannable.swift
- Core/Core/Planner/APIPlannable.swift
- Core/Core/Planner/GetPlannablesUseCase.swift
- Core/Core/Planner/PlannerListViewController.storyboard
- Core/Core/Planner/PlannerListViewController.swift
- Core/CoreTests/Extensions/DateExtensionsTests.swift
- Core/CoreTests/Planner/GetPlannablesUseCaseTests.swift
- Core/CoreTests/Planner/PlannableTests.swift
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Dashboard/Calendar/CalendarContainerViewController.swift
- Parent/Parent/Dashboard/Calendar/CalendarViewController.swift
- Parent/Parent/Dashboard/DashboardViewController.swift
- TestsFoundation/TestsFoundation/Extensions/DateExtensions.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/PlannableFixture.swift
> Plalender list initial implementation

- Core/Core/Files/FileDetails/FileDetailsViewController.swift
- Core/Core/Files/GetFile.swift
- Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
- Student/Student/Routes.swift
refs: MBL-13981
release note: Fixed a bug that could prevent files from loading
Test plan:
* Make sure file loads from [ticket](https://instructure.atlassian.net/browse/MBL-13981)
* Course and user files should also load (use narmstrong > s)
> Remove context restriction from file details

- Core/Core/Views/HorizontalMenuViewController.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/Parent/Details/AssignmentDetailsViewController.swift
- Parent/ParentUnitTests/Course/CourseDetailsViewControllerTests.swift
- Parent/ParentUnitTests/Details/AssignmentDetailsViewControllerTests.swift
> Inbox String polish

- Core/Core/Todos/Todo.swift
- Core/CoreTests/Todos/TodoTests.swift
- Core/CoreUITests/Todo/TodoListTests.swift
- Student/StudentUITests/Course/Syllabus/SyllabusTests.swift
[run-nightly]
refs: MBL-13968
release note: Added weekday to To Do list due dates
Test plan:
* Due dates on To Do list should show the weekday
* See [ticket](https://instructure.atlassian.net/browse/MBL-13968)
> Show weekday in to-do list cells

- Core/Core/Planner/PlannerListViewController.storyboard
- Core/Core/Planner/PlannerListViewController.swift
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
refs: MBL-13988
test plan
- click on a cal day w/ no events, should show empty state
> Empty state for planner list

- scripts/build_automation/automateVersioning.sh
> sort tags by version number instead of lexicographically

- Parent/ParentE2ETests/GradesListTests.swift
> Fix nightly test

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Core/Core/Conversations/APIConversation.swift
- Core/Core/Profile/ProfilePresenter.swift
- Core/CoreTests/Profile/ProfilePresenterTests.swift
- Core/CoreTests/RichContentEditor/RichContentEditorViewControllerTests.swift
- Parent/Parent/Course/CourseDetailsViewController.swift
- Parent/Parent/Dashboard/DashboardViewController.swift
- Parent/Parent/Details/AssignmentDetailsViewController.swift
- Parent/Parent/Routes.swift
- Parent/ParentE2ETests/GradesListTests.swift
- Parent/ParentE2ETests/InboxTests.swift
- Parent/ParentUITests/ParentUITestCase.swift
- Parent/ParentUnitTests/Course/CourseDetailsViewControllerTests.swift
- Parent/ParentUnitTests/Details/AssignmentDetailsViewControllerTests.swift
- Parent/ParentUnitTests/RoutesTests.swift
> Remove Parent Inbox feature flag

- scripts/build_automation/bitrise_workflows/tests.yml
- scripts/delete-extra-checkmarx-comments.swift
> Add script to remove checkmarx comments

- Core/Core/Router/Router.swift
- Core/CoreTests/Extensions/URLComponentsExtensionsTests.swift
- Core/CoreTests/Router/RouterTests.swift
refs: MBL-14002
release note: Fixed an issue launching Studio videos from quizzes.
> Fix launching studio from quizzes

- Core/Core/API/APIExternalTool.swift
- Core/Core/Files/FileDetails/FileDetailsViewController.swift
- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/Conversations/AttachmentCardsViewController.swift
- Parent/Parent/Conversations/ComposeReplyViewController.swift
- Parent/Parent/Conversations/ConversationDetailCell.swift
- Parent/ParentUITests/.swiftlint.yml
- Parent/ParentUITests/InboxTests.swift
- Parent/ParentUITests/ParentUITestCase.swift
- TestsFoundation/TestsFoundation/CoreUIElements/Filles/FileDetails.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/ComposeReply.swift
- TestsFoundation/TestsFoundation/ParentUIElements/Conversations/ConversationDetail.swift
> Add mocked UI test for Inbox

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Planner/APIPlannable.swift
- Core/Core/Planner/Plannable.swift
- Core/Core/Planner/PlannerListViewController.storyboard
- Core/Core/Planner/PlannerListViewController.swift
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
- Parent/Parent/Routes.swift
- Parent/ParentUnitTests/RoutesTests.swift
> Route to plannable details from calendar

- Core/Core/Planner/CalendarDaysViewController.swift
- Core/Core/Planner/CalendarViewController.swift
- Core/Core/Planner/PlannerListViewController.storyboard
- Core/Core/Planner/PlannerListViewController.swift
- Core/Core/Planner/PlannerViewController.swift
- Core/Core/Views/CircleProgressView.swift
- Core/Core/Views/CircleRefreshControl.swift
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
- Core/CoreTests/Planner/PlannerViewControllerTests.swift
- Core/CoreTests/Views/CircleProgressViewTests.swift
- Core/CoreTests/Views/CircleRefreshControlTests.swift
- Parent/Parent/Routes.swift
> Add pull to refresh to Planner

- Core/Core/Planner/PlannerListViewController.storyboard
- Parent/Parent/Dashboard/DashboardViewController.swift
refs: MBL-13907
Test
use a smaller phone, click on calendar day w/ no events so you can see placeholder, placeholder should be below calendar, not overlapping
> Fix placeholder

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Planner/PlannerListViewController.storyboard
- Core/Core/Planner/PlannerListViewController.swift
- Core/Core/Views/CircleRefreshControl.swift
- Core/Core/Views/ListBackgroundView.swift
- Core/Core/Views/ListErrorView.swift
- Core/Core/Views/ListErrorView.xib
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
> Update the planner list error state

- Parent/ParentE2ETests/PlannerTests.swift
[run-nightly]
refs: MBL-14015
affects: none
> Add swipe tests to planner

- Parent/Parent/Conversations/EditComposeRecipientsViewController.swift
refs: MBL-14076
Test plan, follow ticket: https://instructure.atlassian.net/browse/MBL-14076
> Layout selected view so it shows selected checkmark

- rn/Teacher/src/common/__tests__/__snapshots__/buttons.test.js.snap
- rn/Teacher/src/common/buttons.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
- rn/Teacher/src/modules/discussions/details/DiscussionDetails.js
- rn/Teacher/src/modules/discussions/details/Reply.js
- rn/Teacher/src/modules/inbox/__tests__/__snapshots__/Inbox.test.js.snap
- rn/Teacher/src/modules/inbox/components/__tests__/__snapshots__/CourseFilter.test.js.snap
- rn/Teacher/src/modules/quizzes/submissions/__tests__/__snapshots__/QuizSubmissionList.test.js.snap
- rn/Teacher/src/modules/speedgrader/__tests__/__snapshots__/GradeTab.test.js.snap
- rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/RubricItem.test.js.snap
- rn/Teacher/src/modules/speedgrader/components/__tests__/__snapshots__/Tutorial.test.js.snap
- rn/Teacher/src/modules/speedgrader/submission-viewers/__tests__/__snapshots__/URLSubmissionViewer.test.js.snap
- rn/Teacher/src/modules/submissions/__tests__/__snapshots__/SubmissionsHeader.test.js.snap
- rn/Teacher/src/modules/submissions/list/__tests__/__snapshots__/SubmissionList.test.js.snap
refs: MBL-14033
release note: Improve accessibility in discussions
> Fix reply button a11y

- rn/Teacher/src/modules/courses/settings/CourseSettings.js
- rn/Teacher/src/modules/courses/settings/__tests__/__snapshots__/CourseSettings.test.js.snap
refs: MBL-14034
release note: Fixed an issue with course settings hiding the name
> Fix invisible Course name setting

- Parent/Parent/Conversations/ConversationDetailViewController.swift
- Parent/ParentUnitTests/Conversations/ConversationDetailViewControllerTests.swift
> Require reply all on messages from me

- rn/Teacher/src/modules/speedgrader/GradeTab.js
- rn/Teacher/src/modules/speedgrader/__tests__/GradeTab.test.js
refs: MBL-14039
release note: Fixed creating free-form rubric comments
Test plan:
* Add a rubric comment using repro steps in [ticket](https://instructure.atlassian.net/browse/MBL-14039)
> Fix creating free-form rubric comments

- Parent/ParentE2ETests/InboxTests.swift
- Parent/ParentUnitTests/UserDefaults/ColorSchemeTests.swift
> Fix Inbox e2e test

- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
> Fix testExternalToolSubmission

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Planner/CalendarDaysViewController.swift
- Core/Core/Planner/CalendarViewController.swift
- Core/Core/Planner/Plannable.swift
- Core/Core/Planner/PlannerNoteDetailViewController.swift
- Core/Core/Planner/PlannerViewController.swift
- Core/Core/Views/PagesViewController.swift
- Core/CoreTests/Planner/CalendarViewControllerTests.swift
- Core/CoreTests/Views/PagesViewControllerTests.swift
- Parent/ParentE2ETests/PlannerTests.swift
Also makes plannable date optional to avoid another crash.
[run-nightly]
refs: MBL-14036
> Use custom paging for calendar to avoid crashes

- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
- Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift
> Fix crash when clearing filter on assignments

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Core/Core/Planner/APIPlannable.swift
- Core/Core/Planner/CreatePlannerNote.swift
- Core/Core/Planner/CreateTodoViewController.storyboard
- Core/Core/Planner/CreateTodoViewController.swift
- Core/CoreTests/Planner/APIPlannableTests.swift
- Core/CoreTests/Planner/CreateTodoViewControllerTests.swift
- Student/Canvas/Calendar/UI/View Controller/CalendarMonthViewController.swift
> Create new calendar event details view

- Core/Core/Planner/CalendarViewController.swift
- Core/Core/Planner/PlannerListViewController.swift
- Core/Core/Planner/PlannerViewController.swift
- Core/CoreTests/Planner/CalendarViewControllerTests.swift
refs: MBL-14073
- adjust up down arrow on calendar month
- tighten up spacing in planner list
- animate month title change
- avoid updating planner list if date has not changed.
> Parent Polish 3.2

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APICourseRequestable.swift
- Core/Core/Planner/GetPlannerCourses.swift
- Core/CoreTests/API/GetCoursesRequestTests.swift
- Core/CoreTests/Planner/PlannerViewControllerTests.swift
refs: MBL-14098
follow ticket https://instructure.atlassian.net/browse/MBL-14098
> Change getCourses request on parent course plannables to use student id

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
refs: MBL-14094
release note: Fixed a bug with links to other questions in a quiz
> Fix OQAAT links to stay in webview

- Core/Core/API/APIPageRequestable.swift
- Core/CoreTests/API/APIPageRequestableTests.swift
refs: MBL-14095
release note: Fix error fetching page
testplan
1. follow ticket https://instructure.atlassian.net/browse/MBL-14095
> Fix url encoding for GetPage requestable

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Conferences/APIConference.swift
- Core/Core/Conferences/Conference.swift
- Core/Core/Conferences/ConferenceDetailsViewController.storyboard
- Core/Core/Conferences/ConferenceDetailsViewController.swift
- Core/Core/Conferences/ConferenceListViewController.storyboard
- Core/Core/Conferences/ConferenceListViewController.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/People/PeopleListViewController.swift
- Core/CoreTests/Conferences/ConferenceDetailsViewControllerTests.swift
- Core/CoreTests/Conferences/ConferenceListViewControllerTests.swift
- Core/CoreTests/Conferences/ConferenceTests.swift
> Add native conference details

- Core/Core/Conferences/Conference.swift
- Core/Core/Conferences/ConferenceDetailsViewController.swift
- Core/CoreTests/Conferences/ConferenceDetailsViewControllerTests.swift
- Core/CoreTests/Conferences/ConferenceTests.swift
> Update In Progress status

- Core/Core/Planner/PlannerViewController.swift
- Core/CoreTests/Planner/PlannerViewControllerTests.swift
> Use PagesViewController for list for a11y

- Parent/Parent.xcodeproj/project.pbxproj
- Parent/Parent/ParentAppDelegate.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/Student/CanvasAppDelegate.swift
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher/AppDelegate.swift
refs: MBL-14113
affects: Student Parent Teacher
> Refine changes related to crashlytics

- Core/Core/API/APIOAuth.swift
- Core/Core/Use Cases/GetSSOLogin.swift
- Core/CoreTests/Use Cases/GetSSOLoginTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIOAuthTokenFixture.swift
refs: MBL-14110
Test plan:
- Act as a student on beta
- Generate a QR code for mobile login
- Scan the QR code on the device
- Should get logged and be masquerading as the user
> Masquerading QR codes

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Student/Student/Routes.swift
- rn/Teacher/src/common/ExperimentalFeature.js
refs: none
Test plan: Conferences should be native.
> Remove conferences feature flag

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/PageViewAnalytics/Persistency.swift
- Core/Core/Profile/Settings/APIPairingCode.swift
- Core/Core/Profile/Settings/PairWithObserverViewController.storyboard
- Core/Core/Profile/Settings/PairWithObserverViewController.swift
- Core/Core/Profile/Settings/ProfileSettingsViewController.swift
- Core/Core/Views/CoreWebViewController.swift
- Core/Core/Views/NotificationView.swift
- Core/CoreTests/Profile/Settings/APIPairingCodeTests.swift
- Core/CoreTests/Profile/Settings/PairWithObserverViewControllerTests.swift
- Core/CoreTests/Profile/Settings/ProfileSettingsViewControllerTests.swift
> Generate observer pairing code

- Core/Core/Views/CircleRefreshControl.swift
- Core/CoreTests/Views/CircleRefreshControlTests.swift
refs: MBL-14119
release note: Fixed a crash related to pull to refresh
> Fix crash in CircleRefreshControl

- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
- Student/StudentUITests/Submissions/SubmissionDetails/SubmissionDetailsTests.swift
- Student/StudentUnitTests/Submissions/SubmissionDetails/SubmissionDetailsPresenterTests.swift
- TestsFoundation/TestsFoundation/Database/TestPersistence.swift
> Fix Nightly testRubric

- Core/Core/Router/Router.swift
- Core/CoreTests/CoreTestCase.swift
- Core/CoreTests/Router/RouterTests.swift
> Log router events

- Core/Core/Conferences/ConferenceListViewController.swift
- Core/CoreTests/Conferences/ConferenceListViewControllerTests.swift
- Student/Student/Routes.swift
- rn/Teacher/src/__templates__/account-notification.js
- rn/Teacher/src/canvas-api/apis/account.js
- rn/Teacher/src/modules/dashboard/Dashboard.js
- rn/Teacher/src/modules/dashboard/LiveConferenceRow.js
- rn/Teacher/src/modules/dashboard/__tests__/Dashboard.test.js
- rn/Teacher/src/modules/dashboard/__tests__/LiveConferenceRow.test.js
- rn/Teacher/src/modules/dashboard/__tests__/__snapshots__/Dashboard.test.js.snap
- rn/Teacher/src/modules/dashboard/__tests__/account-notification-actions.test.js
- rn/Teacher/src/modules/dashboard/__tests__/account-notification-reducer.test.js
- rn/Teacher/src/modules/dashboard/account-notification-actions.js
- rn/Teacher/src/modules/dashboard/account-notification-reducer.js
- rn/Teacher/src/routing/register-screens.js
refs: MBL-14125
release note: Added a banner for live conferences to the dashboard
> Show announcement for live conference

- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsAnnotation.swift
- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsConstants.swift
- CanvasCore/CanvasCore/Annotations/Canvadocs/CanvadocsPDFDocumentPresenter.swift
- CanvasCore/CanvasCore/Annotations/Canvadocs/Comments/CanvadocsCommentAnnotation.swift
- CanvasCore/CanvasCore/Annotations/Pre Submission/PreSubmissionPDFDocumentPresenter.swift
- CanvasCore/CanvasCore/PDF/PSPDFView.swift
- Core/Core/AppEnvironment/SessionDefaults.swift
- Core/Core/DocViewer/DocViewerConstants.swift
- Core/Core/DocViewer/DocViewerViewController.swift
- Core/CoreTests/AppEnvironment/SessionDefaultsTests.swift
refs: MBL-14140
release note: Fixed an issue with annotation preferences being lost
> Don't reset last used annotation values until app reset

- Core/Core/Files/FileDetails/FileDetailsViewController.swift
- Core/CoreTests/Files/FileDetails/FileDetailsViewControllerTests.swift
refs: MBL-14146
release note: Fixed an issue where file module items we not marked completed
> Fix file module item completion notification

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/API/APIDiscussionRequestable.swift
- Core/Core/Models/QuizType.swift
- Core/CoreTests/API/APIDiscussionRequestableTests.swift
- Core/CoreUITests/Discussions/DiscussionReplyTests.swift
- Core/PactTests/API/APIPactExtensions.swift
- Core/PactTests/Pact/CanvasMockService.swift
- Core/PactTests/Pact/PactEncoder.swift
- Core/PactTests/Pact/PactSimpleEncodable.swift
- Core/PactTests/Tests/DiscussionPactTests.swift
- Core/PactTests/Tests/PactTestCase.swift
- scripts/build_automation/bitrise_workflows/tests.yml
> Add discussion tests to pact

- Core/Core.xcodeproj/project.pbxproj
- Core/Core/Modules/ModuleList/ModuleItemCell.swift
- Core/Core/Modules/ModuleList/ModuleItemSubHeaderCell.swift
- Core/Core/Modules/ModuleList/ModuleListViewController.storyboard
- Core/Core/Modules/ModuleList/ModuleListViewController.swift
- Core/Core/Modules/ModuleList/ModuleSectionHeaderView.swift
- Core/Core/Modules/ModuleList/ModuleSectionHeaderView.xib
- Core/Core/Modules/ModuleList/ModuleStore.swift
- Core/Core/Planner/CalendarViewController.swift
- Core/CoreTests/Modules/ModuleListViewControllerTests.swift
- Core/CoreTests/Modules/ModuleStoreTests.swift
- Student/Student/RootViewController.swift
- rn/Teacher/ios/Teacher.xcodeproj/project.pbxproj
- rn/Teacher/ios/Teacher/AppDelegate+Routes.swift
> Move ModuleList to Core

- package.json
- scripts/build_automation/automateVersioning.sh
- scripts/build_automation/release.sh
> Can release with `yarn release`

- CanvasCore/CanvasCore/Files/File/FileUpload/DocumentMenu/DocumentMenuController.swift
- CanvasCore/CanvasCore/Media/AudioRecorderView.swift
- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/SubmissionViewController.swift
- Core/Core/Grades/GradesViewController.swift
- Core/Core/Logger/LogEventList/LogEventListViewController.storyboard
- Core/Core/Logger/LogEventList/LogEventListViewController.swift
- Core/Core/People/PeopleListViewController.swift
- Student/Student/Submissions/SubmissionComments/SubmissionCommentsViewController.swift
refs: none
release note: Fixed a crash in uploading a file in a quiz
> Fix actionSheet crashes

- Core/Core/API/APIGradingPeriod.swift
- Core/Core/API/AssignmentListRequestable.swift
- Core/Core/Models/Database.xcdatamodeld/Database.xcdatamodel/contents
- Core/Core/Models/GradingPeriod.swift
- Core/CoreTests/API/AssignmentListRequestableTests.swift
- Core/CoreTests/Use Cases/GradingPeriodUseCaseTests.swift
- Student/Student.xcodeproj/project.pbxproj
- Student/Student/Assignments/AssignmentList/AssignmentListModel.swift
- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
- Student/StudentUITests/Assignments/IPadAssignmentsTests.swift
- Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListModelTests.swift
- Student/StudentUnitTests/Assignments/AssignmentList/AssignmentListViewControllerTests.swift
- TestsFoundation/TestsFoundation/Fixtures/API/APIGradingPeriodFixture.swift
- TestsFoundation/TestsFoundation/Fixtures/API/AssignmentListFixtures.swift
- TestsFoundation/TestsFoundation/Fixtures/Model/GradingPeriodFixture.swift
- TestsFoundation/TestsFoundation/MiniCanvas/MiniCanvasEndpoints.swift
> Refactor assignment list

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- Core/Core/Modules/ModuleList/ModuleListViewController.swift
- Core/CoreTests/Modules/ModuleListViewControllerTests.swift
- Student/Student/Routes.swift
- Student/StudentUnitTests/RoutesTests.swift
> Add new module list to student behind flag

- Core/Core/AppEnvironment/ExperimentalFeature.swift
- rn/Teacher/src/common/ExperimentalFeature.js
- rn/Teacher/src/modules/courses/CourseNavigation.js
refs: MBL-14177
Test plan:
* Student View should not show on course details by default
* Enable teacher_student_view feature flag in Dev Menu
* Student View should show on course details
> Feature flag Teacher Student View

- Core/Core/API/APIModule.swift
- Core/CoreTests/API/APIModuleTests.swift
refs: CNVS-48713
release note: Fixed an error in modules
Test plan:
* See view modules as user in ticket
> Handle null indent on module items

- Core/Core/Conferences/ConferenceListViewController.swift
- Core/Core/Courses/CourseListViewController.swift
- Core/Core/Modules/ModuleList/ModuleListViewController.swift
- Core/Core/Pages/PageList/PageListPresenter.swift
- Core/Core/People/PeopleListViewController.swift
- Core/Core/Planner/PlannerListViewController.swift
- Core/Core/Router/Router.swift
- Core/Core/Todos/TodoList/TodoListViewController.swift
- Core/CoreTests/Modules/ModuleListViewControllerTests.swift
- Core/CoreTests/Pages/PageList/PageListPresenterTests.swift
- Core/CoreTests/Planner/PlannerListViewControllerTests.swift
- Core/CoreTests/Router/RouterTests.swift
- Student/Canvas/Modules/ModuleDetailsViewController.swift
- Student/Student/Assignments/AssignmentList/AssignmentListViewController.swift
- Student/Student/Dashboard/DashboardViewController.swift
- Student/Student/Notifications/ActivityStreamViewController.swift
- Student/Student/Quizzes/QuizList/QuizListPresenter.swift
- Student/StudentUnitTests/Quizzes/QuizList/QuizListPresenterTests.swift
- rn/Teacher/ios/TeacherTests/RoutesTests.swift
> Remove the option to not embedInNav in detail

- Parent/ParentUITests/InboxTests.swift
> Disable testReplyWithAttachments

- Core/Core/Modules/ModuleList/ModuleSectionHeaderView.xib
> Reduce the size of the module headers

- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/NonNativeQuizTakingViewController.swift
- CanvasCore/CanvasCore/Quizzes/Taking a Quiz/QuizPresentingViewController.swift
- Core/Core/Extensions/NotificationCenterExtensions.swift
- Student/Student/Assignments/AssignmentDetails/AssignmentDetailsPresenter.swift
- Student/Student/Submissions/SubmissionDetails/SubmissionDetailsPresenter.swift
refs: MBL-14186
release note: Fixed an issue where Take Quiz is still shown after completing a quiz
> Notify assignment & submission when quiz needs to refresh

- Core/Core/Planner/CalendarViewController.swift
- Core/Core/Planner/PlannerViewController.swift
- Core/Core/Views/PagesViewController.swift
> Fix testSwipes in planner in student

- Student/Student/Routes.swift
- Student/StudentUnitTests/RoutesTests.swift
refs: MBl-14222
release note: Fixed a crash in Assignments
Test plan:
* Student assignments list should be the RN assignments list
> Use RN Assignments List in Student

- Core/Core/Pages/GetPage.swift
- Core/CoreTests/Pages/GetPageTests.swift
refs: MBL-14219
Testing
follow ticket https://instructure.atlassian.net/browse/MBL-14219
> Fix page links with pre-encoded url from teacher

- Core/Core/Router/Router.swift
- Core/CoreTests/Router/RouterTests.swift
> Fix links that have `support` in the path

- Student/GradesWidget/GradesWidget.entitlements
> Add needed app group to GradesWidget entitlement
